### ISSUE TITLE
Inventory#query throws NullPointerException when querying for CraftingOutput.class in Workbench inventories

### ISSUE THREAD

**Issue by Zerthick** [SpongePowered/Sponge#1082]
As the titles says, when querying a Workbench inventory for [CraftingOutput.class](http://jd.spongepowered.org/5.0.0/org/spongepowered/api/item/inventory/crafting/CraftingOutput.html) a null pointer exception is thrown.

*SpongeVanilla 1.10.2-5.1.0-BETA-366*

**Stacktrace:**
```
[17:59:09 ERROR] [Sponge]: Could not pass ClickInventoryEvent$Primary$Impl to Plugin{id=protectionperms, name=ProtectionPerms, version=0.5.0, description=A simple player protection and control plugin.}
java.lang.NullPointerException
	at org.spongepowered.common.item.inventory.query.strategy.ClassStrategy.matches(ClassStrategy.java:50) ~[ClassStrategy.class:1.10.2-5.1.0-BETA-366]
	at org.spongepowered.common.item.inventory.query.Query.execute(Query.java:126) ~[Query.class:1.10.2-5.1.0-BETA-366]
	at org.spongepowered.common.item.inventory.query.Query.execute(Query.java:122) ~[Query.class:1.10.2-5.1.0-BETA-366]
	at org.spongepowered.common.item.inventory.adapter.impl.MinecraftInventoryAdapter.query(MinecraftInventoryAdapter.java:154) ~[MinecraftInventoryAdapter.class:1.10.2-5.1.0-BETA-366]
	at io.github.zerthick.protectionperms.events.listeners.item.CraftItemListener.onItemCraft(CraftItemListener.java:23) ~[CraftItemListener.class:?]
	at org.spongepowered.common.event.listener.ClickInventoryEventListener_CraftItemListener_onItemCraft5.handle(Unknown Source) ~[?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.10.2-5.1.0-BETA-366]
	at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:305) ~[SpongeEventManager.class:1.10.2-5.1.0-BETA-366]
	at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:320) ~[SpongeEventManager.class:1.10.2-5.1.0-BETA-366]
	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:141) ~[SpongeImpl.class:1.10.2-5.1.0-BETA-366]
	at org.spongepowered.common.event.tracking.phase.packet.PacketFunction.lambda$static$31(PacketFunction.java:678) ~[PacketFunction.class:1.10.2-5.1.0-BETA-366]
	at org.spongepowered.common.event.tracking.phase.packet.PacketPhase.unwind(PacketPhase.java:320) [PacketPhase.class:1.10.2-5.1.0-BETA-366]
	at org.spongepowered.common.event.tracking.CauseTracker.completePhase(CauseTracker.java:192) [CauseTracker.class:1.10.2-5.1.0-BETA-366]
	at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:141) [PacketUtil.class:1.10.2-5.1.0-BETA-366]
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zip000(SourceFile:39) [fl$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(SourceFile:142) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(SourceFile:338) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(SourceFile:554) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(SourceFile:458) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
```

**Code:**
```Java
@Listener
public void onItemCraft(ClickInventoryEvent event, @Root Player player, @Getter("getTargetInventory") Inventory inventory) {

    if(inventory.getArchetype() == InventoryArchetypes.PLAYER || inventory.getArchetype() == InventoryArchetypes.WORKBENCH) {
        Inventory craftingOutputs = inventory.query(CraftingOutput.class); //NullPointerException here
    }
}
```

Of note however is this code works perfectly for player inventories.

**Comment by Faithcaio** [comment]
This happens because there is no fallback lens for containers when the lens is not provided.
This will be fixed with https://github.com/SpongePowered/SpongeCommon/pull/1010
