### ISSUE TITLE
Exception when creating the `FishHook` entity

### ISSUE THREAD

**Issue by Limeth** [SpongePowered/Sponge#1084]
This line of code:
```java
FishHook hook = (FishHook) world.createEntity(EntityTypes.FISHING_HOOK, hookPosition);
```

Results in this error:
```
java.lang.RuntimeException: There was an issue attempting to construct minecraft:fishinghook
	at net.minecraft.world.World.createEntity(World.java:422) ~[ajq.class:?]
	at cz.creeper.limefun.LimeFun.onHandInteract(LimeFun.java:111) ~[LimeFun.class:?]
	at org.spongepowered.common.event.listener.MainHandListener_LimeFun_onHandInteract14.handle(Unknown Source) ~[?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.11-2168-6.0.0-BETA-1924]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:357) [SpongeModEventManager.class:1.11-2168-6.0.0-BETA-1924]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:398) [SpongeModEventManager.class:1.11-2168-6.0.0-BETA-1924]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:370) [SpongeModEventManager.class:1.11-2168-6.0.0-BETA-1924]
	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:144) [SpongeImpl.class:1.11-2168-6.0.0-BETA-1924]
	at org.spongepowered.common.event.SpongeCommonEventFactory.callInteractItemEventPrimary(SpongeCommonEventFactory.java:322) [SpongeCommonEventFactory.class:1.11-2168-6.0.0-BETA-1924]
	at org.spongepowered.common.network.PacketUtil.firePreEvents(PacketUtil.java:180) [PacketUtil.class:1.11-2168-6.0.0-BETA-1924]
	at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:87) [PacketUtil.class:1.11-2168-6.0.0-BETA-1924]
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zja000(SourceFile:39) [fo$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fo$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_101]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_101]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:679) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384) [lh.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.NoSuchMethodException: No such accessible constructor on object: net.minecraft.entity.projectile.EntityFishHook
	at org.apache.commons.lang3.reflect.ConstructorUtils.invokeConstructor(ConstructorUtils.java:115) ~[minecraft_server.1.11.jar:?]
	at org.apache.commons.lang3.reflect.ConstructorUtils.invokeConstructor(ConstructorUtils.java:85) ~[minecraft_server.1.11.jar:?]
	at net.minecraft.world.World.createEntity(World.java:419) ~[ajq.class:?]
	... 20 more
```

Additionally, I don't think there's a method on `FishHook` to set the entity who casted the hook.

**Comment by JBYoshi** [comment]
All fishing hooks need to be launched by a `ProjectileSource` (typically either a dispenser or an entity). Use `ProjectileSource.launchProjectile()` instead.

**Comment by Limeth** [comment]
I see. Would it be possible to make an `ArmorStand` cast a fishing rod, even though it's not an instance of `ProjectileSource`?
Maybe this should be documented somewhere, or possibly the error could explain what to do.

**Comment by kashike** [comment]
No, this is a vanilla issue. There is no `World`-only constructor in `EntityFishHook`.

**Comment by Zidane** [comment]
@kashike 

It wouldn't be pretty but we could add an interface under Entity that would classify Entities that can be created this way (and not via launchProjectile). That way, it becomes quite clear you can't do this simply cause the projectile wouldn't be of that type.

**Comment by simon816** [comment]
In `MixinWorld#createEntity` there is the ability to use a specific constructor if the expected one doesn't work.
Note that in my PR from long ago (https://github.com/SpongePowered/SpongeCommon/pull/37) I commented that spawning a fish hook doesn't work in some cases. I think this is still an issue

**Comment by ryantheleach** [comment]
Looking for some input on whether this is wontfix, if we can come up with a better error message, or otherwise work around this.

**Comment by gabizou** [comment]
@Zidane looks like in 1.13, we won't have a choice about spawning these sorts of entities without specific types. There are certain entities that cannot be re-created and are explicitly disabled for serialization and summoning. 

For 1.12 (API 7.2+), we can expose this as a new method in `EntityType` to determine if it's possible to spawn/summon said entity, without using other means like ProjectileSource#launch, and manually detect if there's a world argument constructor available (public) when constructing `EntityType` in the implementation. This way it's auto-detected based on mod classes as well as vanilla classes.

In 1.13 (API 8), this will be a literal mapping of the methods exposed in 1.13 to say an entity is not summonable/serailizable, which would make this method have a new exception for being thrown.
