### ISSUE TITLE
Worlds do not have persisting UUIDs

### ISSUE THREAD

**Issue by codeHusky** [SpongePowered/Sponge#1181]
Saving and loading a position from a config after a restart results in a deserialization error because...
```
Caused by: org.spongepowered.api.data.persistence.InvalidDataException: Could not find world by UUID: adfdf5d4-2b6f-4431-b666-55d05a1e5bcd
	at org.spongepowered.common.data.builder.world.LocationBuilder.buildContent(LocationBuilder.java:57) ~[LocationBuilder.class:1.11.2-6.0.0-BETA-207]
	at org.spongepowered.api.data.persistence.AbstractDataBuilder.build(AbstractDataBuilder.java:87) ~[AbstractDataBuilder.class:1.11.2-6.0.0-BETA-207]
```

They don't persist, it's rather frustrating.

**Comment by codeHusky** [comment]
This is a sponge vanilla issue since there's no hard set uuid system for whatever reason.
