### ISSUE TITLE
IllegalArgumentException: Invalid input debug_all_block_states was found

### ISSUE THREAD

**Issue by vorburger** [SpongePowered/Sponge#1195]
Just this, no idea what it means, but looks like something you may want to know about?

Happened while using http://nucleuspowered.org/docs/modules/world.html on a spongevanilla 1.10.2-5.1.0-BETA-371 while typing /world create -g <TAB> in server console:

```[17:33:55 FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.RuntimeException: Error occured while tab completing 'world create -g '
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_121]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_121]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(SourceFile:1499) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(SourceFile:338) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(SourceFile:554) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(SourceFile:458) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.RuntimeException: Error occured while tab completing 'world create -g '
	at org.spongepowered.common.command.SpongeCommandManager.getSuggestions(SpongeCommandManager.java:369) ~[SpongeCommandManager.class:1.10.2-5.1.0-BETA-371]
	at net.minecraft.server.MinecraftServer.redirect$onGetTabCompletionOptions$zhh000(SourceFile:3912) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_184104_a(SourceFile:843) ~[MinecraftServer.class:?]
	at org.spongepowered.server.console.ConsoleCommandCompleter.lambda$complete$0(ConsoleCommandCompleter.java:61) ~[ConsoleCommandCompleter.class:1.10.2-5.1.0-BETA-371]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_121]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
	... 5 more
Caused by: java.lang.IllegalArgumentException: Invalid input debug_all_block_states was found
	at org.spongepowered.api.command.args.GenericArguments$CatalogedTypeCommandElement.getValue(GenericArguments.java:1405) ~[spongevanilla-1.10.2-5.1.0-BETA-371.jar:1.10.2-5.1.0-BETA-371]
	at com.google.common.collect.Iterators$8.transform(Iterators.java:794) ~[minecraft_server.1.10.2.jar:?]
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48) ~[minecraft_server.1.10.2.jar:?]
	at org.spongepowered.api.command.args.CommandElement.parse(CommandElement.java:87) ~[CommandElement.class:1.10.2-5.1.0-BETA-371]
	at io.github.nucleuspowered.nucleus.argumentparsers.ImprovedCatalogTypeArgument.parse(ImprovedCatalogTypeArgument.java:42) ~[ImprovedCatalogTypeArgument.class:0.21.1-S5.1]
	at org.spongepowered.api.command.args.GenericArguments$OnlyOneCommandElement.parse(GenericArguments.java:1431) ~[GenericArguments$OnlyOneCommandElement.class:1.10.2-5.1.0-BETA-371]
	at org.spongepowered.api.command.args.CommandFlags.parseShortFlags(CommandFlags.java:174) ~[CommandFlags.class:1.10.2-5.1.0-BETA-371]
	at org.spongepowered.api.command.args.CommandFlags.parse(CommandFlags.java:87) ~[CommandFlags.class:1.10.2-5.1.0-BETA-371]
	at org.spongepowered.api.command.args.GenericArguments$SequenceCommandElement.complete(GenericArguments.java:290) ~[GenericArguments$SequenceCommandElement.class:1.10.2-5.1.0-BETA-371]
	at org.spongepowered.api.command.args.GenericArguments$FirstParsingCommandElement.lambda$complete$0(GenericArguments.java:483) ~[GenericArguments$FirstParsingCommandElement.class:1.10.2-5.1.0-BETA-371]
	at com.google.common.collect.Iterators$8.transform(Iterators.java:794) ~[minecraft_server.1.10.2.jar:?]
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48) ~[minecraft_server.1.10.2.jar:?]
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48) ~[minecraft_server.1.10.2.jar:?]
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:543) ~[minecraft_server.1.10.2.jar:?]
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:268) ~[minecraft_server.1.10.2.jar:?]
	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:226) ~[minecraft_server.1.10.2.jar:?]
	at org.spongepowered.api.command.args.GenericArguments$FirstParsingCommandElement.complete(GenericArguments.java:476) ~[GenericArguments$FirstParsingCommandElement.class:1.10.2-5.1.0-BETA-371]
	at org.spongepowered.api.command.spec.CommandSpec.complete(CommandSpec.java:322) ~[CommandSpec.class:1.10.2-5.1.0-BETA-371]
	at org.spongepowered.api.command.args.ChildCommandElementExecutor.complete(ChildCommandElementExecutor.java:105) ~[ChildCommandElementExecutor.class:1.10.2-5.1.0-BETA-371]
	at org.spongepowered.api.command.spec.CommandSpec.complete(CommandSpec.java:322) ~[CommandSpec.class:1.10.2-5.1.0-BETA-371]
	at org.spongepowered.api.command.spec.CommandSpec.getSuggestions(CommandSpec.java:361) ~[CommandSpec.class:1.10.2-5.1.0-BETA-371]
	at org.spongepowered.api.command.dispatcher.SimpleDispatcher.getSuggestions(SimpleDispatcher.java:348) ~[SimpleDispatcher.class:1.10.2-5.1.0-BETA-371]
	at org.spongepowered.common.command.SpongeCommandManager.getSuggestions(SpongeCommandManager.java:355) ~[SpongeCommandManager.class:1.10.2-5.1.0-BETA-371]
	at net.minecraft.server.MinecraftServer.redirect$onGetTabCompletionOptions$zhh000(SourceFile:3912) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_184104_a(SourceFile:843) ~[MinecraftServer.class:?]
	at org.spongepowered.server.console.ConsoleCommandCompleter.lambda$complete$0(ConsoleCommandCompleter.java:61) ~[ConsoleCommandCompleter.class:1.10.2-5.1.0-BETA-371]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_121]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
	... 5 more
[17:33:55 ERROR] [Sponge]: Failed to tab complete

```

**Comment by gabizou** [comment]
Should be fixed with the latest builds of both SpongeForge#2262 and SpongeVanilla#235.
