### ISSUE TITLE
launchProjectile() method failing

### ISSUE THREAD

**Issue by LoganSchmalz** [SpongePowered/Sponge#1206]
Something seems to have changed between the SpongeVanilla-1.11.2-6.0.0 versions 196 and 198 where the player.launchProjectile() method is no longer working. This also affects Forge (although I'm not sure when it changed) and running the exact same plugin on 196 works whereas it does not on 198.

**Comment by Deamon5550** [comment]
Is there anything in the console when it fails to work?

**Comment by LoganSchmalz** [comment]
Only if you try to access it, it will just say that it can't find the object (NoSuchElementException). Otherwise, nothing. 196 works fine, launches the object and it can be modified, but 198 does not.

**Comment by simon816** [comment]
Can I see the whole error? Also, what plugin are you referring to/what code is failing?

**Comment by LoganSchmalz** [comment]
It's for a plugin I am writing. I marked a spot that will write to the logger.

My code:
`logger.info("This is where it fails, no arrow launched");
Projectile arrow = player.launchProjectile(Arrow.class, getNewArrowVelocity(player, 1.5)).get();`

Logger on 198:
`[21:20:15] [Server thread/INFO] [bowta]: This is where it fails, no arrow launched
[21:20:15] [Server thread/ERROR] [Sponge]: Could not pass InteractItemEvent$Secondary$MainHand$Impl to Plugin{id=bowta, name=Bowta, version=1.0, source=mods\Bowta.jar}
java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135) ~[?:1.8.0_111]
	at io.github.geotan00.bowta.PlayerInteractListener.onPlayerInteract(PlayerInteractListener.java:38) ~[PlayerInteractListener.class:?]
	at org.spongepowered.common.event.listener.SecondaryListener_PlayerInteractListener_onPlayerInteract96.handle(Unknown Source) ~[?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.11.2-6.0.0-BETA-198]
	at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:305) [SpongeEventManager.class:1.11.2-6.0.0-BETA-198]
	at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:320) [SpongeEventManager.class:1.11.2-6.0.0-BETA-198]
	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:144) [SpongeImpl.class:1.11.2-6.0.0-BETA-198]
	at org.spongepowered.common.event.SpongeCommonEventFactory.callInteractItemEventSecondary(SpongeCommonEventFactory.java:423) [SpongeCommonEventFactory.class:1.11.2-6.0.0-BETA-198]
	at org.spongepowered.common.network.PacketUtil.firePreEvents(PacketUtil.java:250) [PacketUtil.class:1.11.2-6.0.0-BETA-198]
	at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:89) [PacketUtil.class:1.11.2-6.0.0-BETA-198]
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjd000(SourceFile:539) [fo$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fo$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(SourceFile:1526) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(SourceFile:335) [lh.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(SourceFile:562) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(SourceFile:466) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]`

Logger on 196:
`[21:24:15] [Server thread/INFO] [bowta]: This is where it fails, no arrow launched
[21:24:15] [Server thread/INFO] [bowta]: This is where it fails, no arrow launched
[21:24:17] [Server thread/INFO] [bowta]: This is where it fails, no arrow launched
[21:24:18] [Server thread/INFO] [bowta]: This is where it fails, no arrow launched
[21:24:18] [Server thread/INFO] [bowta]: This is where it fails, no arrow launched
[21:24:19] [Server thread/INFO] [bowta]: This is where it fails, no arrow launched
[21:24:19] [Server thread/INFO] [bowta]: This is where it fails, no arrow launched
[21:24:19] [Server thread/INFO] [bowta]: This is where it fails, no arrow launched
[21:24:19] [Server thread/INFO] [bowta]: This is where it fails, no arrow launched
[21:24:19] [Server thread/INFO] [bowta]: This is where it fails, no arrow launched`

As you can see it just repeats the message I want to log, and actually arrows are launched as they are supposed to be on 196, so the testing log I wrote just represents where the error occurs in 198.

**Comment by simon816** [comment]
Oh I think I know why, since 1.9 there are different types of arrow, and the `Arrow` interface became a common superinterface between the types. Use `TippedArrow` for a standard arrow

**Comment by LoganSchmalz** [comment]
Interesting. That seems to have fixed it. I'm a little surprised that this change was so random just inbetween two versions, I guess that is to be expected between the experimental releases.

**Comment by JBYoshi** [comment]
Since this is pretty much an invisible change between the two versions, would it be possible to implement some default behavior for `Arrow`, or to log an information message for developers to see?

**Comment by RedNesto** [comment]
@JBYoshi I did a PR to fix this issue, we just have to determine if we let plugins launch `Arrow`s or not.

**Comment by ImMorpheus** [comment]
@RedNesto PR merged. Can this be closed ?

**Comment by parlough** [comment]
For now I will close this with https://github.com/SpongePowered/SpongeCommon/pull/1776, if more issues occur, please open a new issue.
