### ISSUE TITLE
InvalidMixinException on field_177997_b / net.minecraft.util.math.BlockPos$MutableBlockPos

### ISSUE THREAD

**Issue by LemADEC** [SpongePowered/Sponge#1275]
As of 
forge-1.10.2-12.18.3.2254-universal.jar
spongeforge-1.10.2-2254-5.2.0-BETA-2259.jar
with various packs like Invasion, Direwolf20, SkyFactory3, and Beyond,
an InvalidMixinException is reported during boot time:
```
[17:45:53] [main/DEBUG] [mixin/]: RemapperAdapterFML is remapping obfuscated field field_177997_bI for cm$a
[17:45:53] [main/INFO] [mixin/]: Instancing error handler class org.spongepowered.mod.mixin.handler.MixinErrorHandler
[17:45:53] [main/WARN] [mixin/]: Mixin apply failed mixins.common.core.optional.json:util.math.MixinMutableBlockPos -> net.minecraft.util.math.BlockPos$MutableBlockPos: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException Shadow field field_177997_b was not located in the target class
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Shadow field field_177997_b was not located in the target class
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachFields(MixinPreProcessorStandard.java:448) ~[spongeforge-1.10.2-2254-5.2.0-BETA-2259.jar:1.10.2-2254-5.2.0-BETA-2259]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:204) ~[spongeforge-1.10.2-2254-5.2.0-BETA-2259.jar:1.10.2-2254-5.2.0-BETA-2259]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:186) ~[spongeforge-1.10.2-2254-5.2.0-BETA-2259.jar:1.10.2-2254-5.2.0-BETA-2259]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1103) ~[spongeforge-1.10.2-2254-5.2.0-BETA-2259.jar:1.10.2-2254-5.2.0-BETA-2259]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:245) ~[spongeforge-1.10.2-2254-5.2.0-BETA-2259.jar:1.10.2-2254-5.2.0-BETA-2259]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:281) ~[spongeforge-1.10.2-2254-5.2.0-BETA-2259.jar:1.10.2-2254-5.2.0-BETA-2259]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:816) [spongeforge-1.10.2-2254-5.2.0-BETA-2259.jar:1.10.2-2254-5.2.0-BETA-2259]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:786) [spongeforge-1.10.2-2254-5.2.0-BETA-2259.jar:1.10.2-2254-5.2.0-BETA-2259]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transform(MixinTransformer.java:591) [spongeforge-1.10.2-2254-5.2.0-BETA-2259.jar:1.10.2-2254-5.2.0-BETA-2259]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer$Proxy.transform(MixinTransformer.java:183) [spongeforge-1.10.2-2254-5.2.0-BETA-2259.jar:1.10.2-2254-5.2.0-BETA-2259]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) [launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) [?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [?:1.8.0_121]
	at org.spongepowered.common.registry.provider.BlockPropertyIdProvider.<init>(BlockPropertyIdProvider.java:146) [BlockPropertyIdProvider.class:1.10.2-2254-5.2.0-BETA-2259]
	at org.spongepowered.common.registry.provider.BlockPropertyIdProvider$Holder.<clinit>(BlockPropertyIdProvider.java:281) [BlockPropertyIdProvider$Holder.class:1.10.2-2254-5.2.0-BETA-2259]
	at org.spongepowered.common.registry.provider.BlockPropertyIdProvider.getInstance(BlockPropertyIdProvider.java:49) [BlockPropertyIdProvider.class:1.10.2-2254-5.2.0-BETA-2259]
	at org.spongepowered.common.registry.provider.BlockPropertyIdProvider.getIdAndTryRegistration(BlockPropertyIdProvider.java:67) [BlockPropertyIdProvider.class:1.10.2-2254-5.2.0-BETA-2259]
	at org.spongepowered.common.registry.type.BlockTypeRegistryModule.registerBlockTrait(BlockTypeRegistryModule.java:128) [BlockTypeRegistryModule.class:1.10.2-2254-5.2.0-BETA-2259]
	at org.spongepowered.common.registry.type.BlockTypeRegistryModule.registerFromGameData(BlockTypeRegistryModule.java:116) [BlockTypeRegistryModule.class:1.10.2-2254-5.2.0-BETA-2259]
	at net.minecraft.block.Block.handler$onRegisterBlock$zzl000(Block.java:2618) [akf.class:?]
	at net.minecraft.block.Block.func_176215_a(Block.java:2383) [akf.class:?]
	at net.minecraft.block.Block.func_176219_a(Block.java:2387) [akf.class:?]
	at net.minecraft.block.Block.func_149671_p(Block.java:2102) [akf.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:537) [kq.class:?]
	at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1403) [MinecraftServer.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:62) [forge-1.10.2-12.18.3.2239-universal.jar:?]
	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:31) [forge-1.10.2-12.18.3.2239-universal.jar:?]
[17:45:53] [main/DEBUG] [mixin/]: Mixing block.properties.MixinPropertyInteger from mixins.common.core.json into net.minecraft.block.properties.PropertyInteger
[17:45:53] [main/DEBUG] [mixin/]: Mixing block.MixinBlockPistonExtension from mixins.common.core.json into net.minecraft.block.BlockPistonExtension
```

**Comment by Deamon5550** [comment]
Duplicate #1272 disable `optimizedBlockPos` in the config of foamfix.
