### ISSUE TITLE
Exception when run in forge.

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/Sponge#133]
I heard that sponge should now at least build (which it does) but results in a runtime exception being thrown as follows:

    [08:57:59] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
    [08:57:59] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
    [08:57:59] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
    [08:57:59] [main/INFO] [FML]: Forge Mod Loader version 8.0.16.1021 for Minecraft 1.8 loading
    [08:57:59] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_05, running on Windows 8.1:amd64:6.3, installed at C:\Program Files\Java\jre8
    [08:57:59] [main/WARN] [FML]: The coremod org.spongepowered.mod.SpongeCoremod does not have a MCVersion annotation, it may cause issues with this version of Minecraft
    [08:57:59] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.NoClassDefFoundError: org/spongepowered/asm/mixin/MixinEnvironment
    [08:57:59] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.spongepowered.mod.SpongeCoremod.<init>(SpongeCoremod.java:38)
    [08:57:59] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    [08:57:59] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
    [08:57:59] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
    [08:57:59] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
    [08:57:59] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.Class.newInstance(Unknown Source)
    [08:57:59] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:461)
    [08:57:59] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:349)
    [08:57:59] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:217)
    [08:57:59] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90)
    [08:57:59] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67)
    [08:57:59] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34)
    [08:57:59] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraftforge.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:125)
    [08:57:59] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
    [08:57:59] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    [08:57:59] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: java.lang.ClassNotFoundException: org.spongepowered.asm.mixin.MixinEnvironment
    [08:57:59] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.net.URLClassLoader$1.run(Unknown Source)
    [08:57:59] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.net.URLClassLoader$1.run(Unknown Source)
    [08:57:59] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.security.AccessController.doPrivileged(Native Method)
    [08:57:59] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.net.URLClassLoader.findClass(Unknown Source)
    [08:57:59] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
    [08:57:59] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
    [08:57:59] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
    [08:57:59] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106)
    [08:57:59] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
    [08:57:59] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
    [08:57:59] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	... 15 more
    [08:57:59] [main/ERROR] [FML]: An error occurred trying to configure the minecraft home at C:\Users\Ryan\AppData\Roaming\.minecraft for Forge Mod Loader
    java.lang.NoClassDefFoundError: org/spongepowered/asm/mixin/MixinEnvironment
    	at org.spongepowered.mod.SpongeCoremod.<init>(SpongeCoremod.java:38) ~[sponge-1.8-11.14.0.1281-SNAPSHOT-release.jar:1.8-11.14.0.1281-SNAPSHOT+unknown-b0.git-unknown]
    	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_05]
    	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_05]
    	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_05]
    	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_05]
    	at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_05]
    	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:461) ~[fml-1.8-8.0.16.1021-1.8.jar:?]
    	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:349) ~[fml-1.8-8.0.16.1021-1.8.jar:?]
    	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:217) ~[fml-1.8-8.0.16.1021-1.8.jar:?]
    	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90) [fml-1.8-8.0.16.1021-1.8.jar:?]
    	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67) [fml-1.8-8.0.16.1021-1.8.jar:?]
    	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34) [fml-1.8-8.0.16.1021-1.8.jar:?]
    	at net.minecraftforge.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:125) [fml-1.8-8.0.16.1021-1.8.jar:?]
    	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.11.jar:?]
    	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
    Caused by: java.lang.ClassNotFoundException: org.spongepowered.asm.mixin.MixinEnvironment
    	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_05]
    	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_05]
    	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_05]
    	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_05]
    	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_05]
    	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) ~[?:1.8.0_05]
    	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_05]
    	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106) ~[launchwrapper-1.11.jar:?]
    	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_05]
    	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_05]
    	... 15 more
    Exception in thread "main" [08:57:59] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.NoClassDefFoundError: org/spongepowered/asm/mixin/MixinEnvironment
    [08:57:59] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at org.spongepowered.mod.SpongeCoremod.<init>(SpongeCoremod.java:38)
    [08:57:59] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    [08:57:59] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
    [08:57:59] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
    [08:57:59] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
    [08:57:59] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.Class.newInstance(Unknown Source)
    [08:57:59] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:461)
    [08:57:59] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:349)
    [08:57:59] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:217)
    [08:57:59] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:90)
    [08:57:59] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:67)
    [08:57:59] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:34)
    [08:57:59] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraftforge.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:125)
    [08:57:59] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
    [08:57:59] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    [08:57:59] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: java.lang.ClassNotFoundException: org.spongepowered.asm.mixin.MixinEnvironment
    [08:57:59] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.net.URLClassLoader$1.run(Unknown Source)
    [08:57:59] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.net.URLClassLoader$1.run(Unknown Source)
    [08:57:59] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.security.AccessController.doPrivileged(Native Method)
    [08:57:59] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.net.URLClassLoader.findClass(Unknown Source)
    [08:57:59] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
    [08:57:59] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
    [08:57:59] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
    [08:57:59] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106)
    [08:57:59] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
    [08:57:59] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
    [08:57:59] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	... 15 more

**Comment by Mumfrey** [comment]
Yes we know, why are you trying to run something that's not finished anyway?

**Comment by ryantheleach** [comment]
Once building works the next step is getting it to work at runtime right?

**Comment by Mumfrey** [comment]
Yes, but Forge does something differently with classloading to how I do it in liteloader so I'm investigating. It's not high priority though because there's no need to run this in production right now.

**Comment by Mumfrey** [comment]
I've given it a cursory look and it seems that FML is indeed loading jars differently to how I do it. It seems FML doesn't inject coremod jars into the AppClassLoader's classpath, which is breaking the class loading for mixins which are deliberately forced to exist in the AppClassLoader, but can't because the jar is not present in the classpath. I can remove the restriction for now and think of a different way to to do the restrictions that will be compatible with FML.
