### ISSUE TITLE
Selectors are only accepting internal names like @minecraft:all_players instead of @a

### ISSUE THREAD

**Issue by BrainStone** [SpongePowered/Sponge#1339]
Currently selectors being parsed by `Selector.parse` are not accepting the vanilla names `@a`, `@p`, `@r`, `@e`.

According to @Deamon5550 it has been introduced in https://github.com/SpongePowered/SpongeCommon/commit/9d594880e16905f61784f37d0bc890da05981caf#diff-8a5cb22781e1c7adcaf6e572dd7f6710R36

Test case:
```
try {
    logger.info(Selector.parse("@a").toPlain());
} catch (Exception e) {
    e.printStackTrace();
}
```

**What is the expected result?**
`@a` or `@minecraft:all_players`

**What is the current result?**
```
[17:17:19 ERROR] [STDERR]: java.lang.IllegalArgumentException: No type known as 'a'
[17:17:19 ERROR] [STDERR]:      at com.google.common.base.Preconditions.checkArgument(Preconditions.java:148)
[17:17:19 ERROR] [STDERR]:      at org.spongepowered.common.text.selector.SpongeSelectorFactory.parseRawSelector(SpongeSelectorFactory.java:146)
[17:17:19 ERROR] [STDERR]:      at org.spongepowered.api.text.selector.Selector.parse(Selector.java:88)
[17:17:19 ERROR] [STDERR]:      at world.jnc.invsync.InventorySync.init(InventorySync.java:110)
[17:17:19 ERROR] [STDERR]:      at org.spongepowered.common.event.listener.GameInitializationEventListener_InventorySync_init8.handle(Unknown Source)
[17:17:19 ERROR] [STDERR]:      at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95)
[17:17:19 ERROR] [STDERR]:      at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:349)
[17:17:19 ERROR] [STDERR]:      at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:366)
[17:17:19 ERROR] [STDERR]:      at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:370)
[17:17:19 ERROR] [STDERR]:      at org.spongepowered.common.SpongeImpl.postState(SpongeImpl.java:198)
[17:17:19 ERROR] [STDERR]:      at org.spongepowered.server.SpongeVanilla.initialize(SpongeVanilla.java:145)
[17:17:19 ERROR] [STDERR]:      at net.minecraft.server.dedicated.DedicatedServer.handler$onServerInitialize$zob000(SourceFile:1234)
[17:17:19 ERROR] [STDERR]:      at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(SourceFile:186)
[17:17:19 ERROR] [STDERR]:      at net.minecraft.server.MinecraftServer.run(SourceFile:436)
[17:17:19 ERROR] [STDERR]:      at java.lang.Thread.run(Unknown Source)
```

**Comment by BrainStone** [comment]
Also see NucleusPowered/Nucleus#771
