### ISSUE TITLE
Overzealous PositionOutOfBoundsException

### ISSUE THREAD

**Issue by DarkArc** [SpongePowered/Sponge#1349]
Version info:
```
    Minecraft: 1.10.2
    SpongeAPI: 5.2.0-SNAPSHOT-a26c654
    SpongeForge: 1.10.2-2281-5.2.0-BETA-2322
    Minecraft Forge: 12.18.3.2254
```

When killing an entity the following exception occurs, despite the position being within the given bounds:
```
org.spongepowered.api.util.PositionOutOfBoundsException: Position is out of bounds: expected in range (-30000000, 0, -30000000) to (29999999, 0, 29999999) but got (19381, 69, 51)
        at net.minecraft.world.World.checkBiomeBounds(World.java:5066) ~[aid.class:?]
        at net.minecraft.world.World.getBiome(World.java:4854) ~[aid.class:?]
        at org.spongepowered.api.world.extent.BiomeVolume.getBiome(BiomeVolume.java:98) ~[BiomeVolume.class:1.10.2-2281-5.2.0-BETA-2322]
        at com.skelril.skree.content.world.wilderness.WildernessWorldWrapper.onEntityDeath(WildernessWorldWrapper.java:448) ~[WildernessWorldWrapper.class:?]
        at org.spongepowered.common.event.listener.DeathListener_WildernessWorldWrapper_onEntityDeath108.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.10.2-2281-5.2.0-BETA-2322]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:313) ~[SpongeModEventManager.class:1.10.2-2281-5.2.0-BETA-2322]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:297) ~[SpongeModEventManager.class:1.10.2-2281-5.2.0-BETA-2322]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:338) ~[SpongeModEventManager.class:1.10.2-2281-5.2.0-BETA-2322]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:326) ~[SpongeModEventManager.class:1.10.2-2281-5.2.0-BETA-2322]
        at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:143) ~[SpongeImpl.class:1.10.2-2281-5.2.0-BETA-2322]
        at org.spongepowered.common.event.SpongeCommonEventFactory.callDestructEntityEventDeath(SpongeCommonEventFactory.java:509) ~[SpongeCommonEventFactory.class:1.10.2-2281-5.2.0-BETA-2322]
        at net.minecraft.entity.EntityLivingBase.func_70645_a(EntityLivingBase.java:3080) ~[sf.class:?]
        at net.minecraft.entity.monster.EntityZombie.func_70645_a(EntityZombie.java:793) ~[zi.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:3337) ~[sf.class:?]
        at net.minecraft.entity.monster.EntityMob.func_70097_a(SourceFile:73) ~[yx.class:?]
        at net.minecraft.entity.monster.EntityZombie.func_70097_a(EntityZombie.java:284) ~[zi.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java:3758) ~[zs.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_71059_n(EntityPlayerMP.java:1226) ~[lu.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:2414) ~[me.class:?]
        at net.minecraft.network.play.client.CPacketUseEntity.func_148833_a(SourceFile:68) ~[iu.class:?]
        at net.minecraft.network.play.client.CPacketUseEntity.func_148833_a(SourceFile:12) ~[iu.class:?]
        at org.spongepowered.common.network.PacketUtil.lambda$onProcessPacket$0(PacketUtil.java:157) ~[PacketUtil.class:1.10.2-2281-5.2.0-BETA-2322]
        at org.spongepowered.common.event.tracking.CauseTracker.switchToPhase(CauseTracker.java:160) [CauseTracker.class:1.10.2-2281-5.2.0-BETA-2322]
        at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:156) [PacketUtil.class:1.10.2-2281-5.2.0-BETA-2322]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjh000(SourceFile:539) [fl$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
        at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:241) [SpongeImplHooks.class:1.10.2-2281-5.2.0-BETA-2322]
        at net.minecraft.server.MinecraftServer.redirect$onRun$zhn000(MinecraftServer.java:3928) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
```

**Comment by kashike** [comment]
The `y` coordinates of `org.spongepowered.common.mixin.core.world.MixinWorld#BIOME_MIN` and `org.spongepowered.common.mixin.core.world.MixinWorld#BIOME_MAX` don't use the `y` coordinates from `org.spongepowered.common.mixin.core.world.MixinWorld#BLOCK_MIN` and `org.spongepowered.common.mixin.core.world.MixinWorld#BLOCK_MAX`.
