### ISSUE TITLE
OpenComputers crash, inventory size

### ISSUE THREAD

**Issue by XakepSDK** [SpongePowered/Sponge#1373]
```
java.lang.IllegalArgumentException: Invalid size: 0
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:148)
	at org.spongepowered.common.item.inventory.lens.impl.AbstractLens.<init>(AbstractLens.java:89)
	at org.spongepowered.common.item.inventory.lens.impl.AbstractLens.<init>(AbstractLens.java:80)
	at org.spongepowered.common.item.inventory.lens.impl.MinecraftLens.<init>(MinecraftLens.java:44)
	at org.spongepowered.common.item.inventory.lens.impl.minecraft.PlayerInventoryLens.<init>(PlayerInventoryLens.java:60)
	at net.minecraft.entity.player.InventoryPlayer.handler$onConstructed$zff000(InventoryPlayer.java:1462)
	at net.minecraft.entity.player.InventoryPlayer.<init>(InventoryPlayer.java:43)
	at li.cil.oc.server.agent.Inventory.<init>(Inventory.scala:18)
	at li.cil.oc.server.agent.Player.<init>(Player.scala:106)
	at li.cil.oc.common.tileentity.Robot.li$cil$oc$common$tileentity$Robot$$player_$lzycompute(Robot.scala:190)
	at li.cil.oc.common.tileentity.Robot.li$cil$oc$common$tileentity$Robot$$player_(Robot.scala:190)
	at li.cil.oc.common.tileentity.Robot$$anonfun$updateEntity$1.apply$mcVI$sp(Robot.scala:374)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:160)
	at li.cil.oc.common.tileentity.Robot.updateEntity(Robot.scala:372)
	at li.cil.oc.common.tileentity.RobotProxy.updateEntity(RobotProxy.scala:135)
	at li.cil.oc.common.tileentity.traits.Tickable$class.update(Tickable.scala:6)
	at li.cil.oc.common.tileentity.RobotProxy.func_73660_a(RobotProxy.scala:33)
	at org.spongepowered.common.event.tracking.TrackingUtil.tickTileEntity(TrackingUtil.java:230)
	at net.minecraft.world.WorldServer.updateTileEntity(WorldServer.java:2826)
	at net.minecraft.world.WorldServer.redirect$onUpdateTileEntities$zkc000(WorldServer.java:2813)
	at net.minecraft.world.World.func_72939_s(World.java:6481)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:2175)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Thread.java:748)
```

Build: https://github.com/SpongePowered/SpongeForge/commit/3f25197b74a8fc4f489252a0915e20d78bb8ac7b

**Comment by Faithcaio** [comment]
should be fixed in latest build.
If its not please tell me how to reproduce.
