### ISSUE TITLE
IC2 EntityDynamite explosion NPE

### ISSUE THREAD

**Issue by XakepSDK** [SpongePowered/Sponge#1404]
```
[20:10:44] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:726) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384) ~[lh.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NullPointerException
	at net.minecraft.world.WorldServer.func_180495_p(WorldServer.java:3091) ~[lw.class:?]
	at net.minecraft.world.World.func_175623_d(World.java:223) ~[ajs.class:?]
	at ic2.core.block.EntityDynamite.func_70071_h_(EntityDynamite.java:140) ~[EntityDynamite.class:?]
	at org.spongepowered.common.event.tracking.TrackingUtil.tickEntity(TrackingUtil.java:158) ~[TrackingUtil.class:1.11.2-2315-6.1.0-BETA-2402]
	at net.minecraft.world.WorldServer.redirect$onCallEntityUpdate$zkc000(WorldServer.java:2843) ~[lw.class:?]
	at net.minecraft.world.World.func_72866_a(World.java:4051) ~[ajs.class:?]
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:840) ~[lw.class:?]
	at net.minecraft.world.World.func_72870_g(World.java:1934) ~[ajs.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:6464) ~[ajs.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:2180) ~[lw.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720) ~[MinecraftServer.class:?]
	... 4 more
[20:10:44] [Server thread/ERROR]: This crash report has been saved to: /home/user/Desktop/Spsrv/./crash-reports/crash-2017-06-21_20.10.44-server.txt
```
SpongeForge 1.11.2-2315-6.1.0-BETA-2402

**Comment by JBYoshi** [comment]
Does this still happen on the latest SpongeForge build? If so, could you post an updated crash report?

**Comment by XakepSDK** [comment]
Yep, build 2438. Same error..
```
net.minecraft.util.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:726) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384) ~[lh.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NullPointerException
	at net.minecraft.world.WorldServer.func_180495_p(WorldServer.java:3114) ~[lw.class:?]
	at net.minecraft.world.World.func_175623_d(World.java:223) ~[ajs.class:?]
	at ic2.core.block.EntityDynamite.func_70071_h_(EntityDynamite.java:140) ~[EntityDynamite.class:?]
	at org.spongepowered.common.event.tracking.TrackingUtil.tickEntity(TrackingUtil.java:158) ~[TrackingUtil.class:1.11.2-2315-6.1.0-BETA-2438]
	at net.minecraft.world.WorldServer.redirect$onCallEntityUpdate$zkd000(WorldServer.java:2866) ~[lw.class:?]
	at net.minecraft.world.World.func_72866_a(World.java:4051) ~[ajs.class:?]
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:840) ~[lw.class:?]
	at net.minecraft.world.World.func_72870_g(World.java:1934) ~[ajs.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:6464) ~[ajs.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:2203) ~[lw.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720) ~[MinecraftServer.class:?]
	... 4 more
```

**Comment by JBYoshi** [comment]
What were you doing when you got the crash?

**Comment by XakepSDK** [comment]
Just join server and load chunk with unknown entity(idk, what entity is this)

**Comment by JBYoshi** [comment]
Fixing the names results in this:

```
net.minecraft.util.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:726) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:384) ~[lh.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:624) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.NullPointerException
	at net.minecraft.world.WorldServer.getBlockState(WorldServer.java:3114) ~[lw.class:?]
	at net.minecraft.world.World.isAirBlock(World.java:223) ~[ajs.class:?]
	at ic2.core.block.EntityDynamite.onUpdate(EntityDynamite.java:140) ~[EntityDynamite.class:?]
	at org.spongepowered.common.event.tracking.TrackingUtil.tickEntity(TrackingUtil.java:158) ~[TrackingUtil.class:1.11.2-2315-6.1.0-BETA-2438]
	at net.minecraft.world.WorldServer.redirect$onCallEntityUpdate$zkd000(WorldServer.java:2866) ~[lw.class:?]
	at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:4051) ~[ajs.class:?]
	at net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:840) ~[lw.class:?]
	at net.minecraft.world.World.updateEntity(World.java:1934) ~[ajs.class:?]
	at net.minecraft.world.World.updateEntities(World.java:6464) ~[ajs.class:?]
	at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:2203) ~[lw.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:720) ~[MinecraftServer.class:?]
	... 4 more
```

It looks like a stick of dynamite is trying to check if there's an air block at `null`. However, I can't figure out exactly how to reproduce this, so I can't pull it up in the debugger to check for sure.

If it is the world, would you be OK posting a copy of your world and telling me where the faulty stick is?

**Comment by ryantheleach** [comment]
@JBYoshi The Explosion Code in IC2 and Sponge is ... interesting.

At the moment we have nearly no support for forge in regards to explosions of any nature, we need to both send back the explosion events to forge for our own explosions, as well as being able to handle modded explosions which as far as I can tell we can't really in a way that makes sense...

**Comment by ryantheleach** [comment]
It's my hope that the capturing system is different enough from 1.12 that this is fixed, but judging by my memory of IC2 code it's doubtful.

If IC2 has been updated for 1.12 I'm looking for someone to test this on 1.12.

@limbo-app move to sf

**Comment by phit** [comment]
~move to sf

**Comment by phit** [comment]
~move to sf

**Comment by limbo-app** [comment]
Hey @XakepSDK! I've moved your issue to [SpongePowered/SpongeForge#1979](https://github.com/SpongePowered/SpongeForge/issues/1979).

**Comment by limbo-app** [comment]
Hey @XakepSDK! I've moved your issue to [SpongePowered/SpongeForge#1980](https://github.com/SpongePowered/SpongeForge/issues/1980).
