### ISSUE TITLE
NPE on Inventory#getProperty

### ISSUE THREAD

**Issue by pie-flavor** [SpongePowered/Sponge#1423]
Code: 
```java
            ItemStack stack = ((Player) src).getItemInHand(HandTypes.MAIN_HAND).get();
            Iterable<Slot> slots = ((Player) src).getInventory().query(GridInventory.class).queryAny(stack).slots();
            String msg = StreamSupport.stream(slots.spliterator(), false)
                    .map(s -> s.getProperty(SlotIndex.class, "slotindex")).flatMap(s -> s.map(Stream::of).orElseGet(Stream::of))
                    .map(pos -> "" + pos.getValue()).collect(Collectors.joining(", "));
            src.sendMessage(Text.of(msg));
```

Trace: 
```
[01:56:37 ERROR] [Sponge]: Error occurred while executing command 'test' for source EntityPlayerMP['pie_flavor'/380, l='world', x=281.51, y=70.00, z=188.24]: null
java.lang.NullPointerException
        at org.spongepowered.common.item.inventory.adapter.impl.Adapter$Logic.lambda$getProperties$0(Adapter.java:275) ~[Adapter$Logic.class:1.11.2-6.1.0-BETA-11]
        at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:1.8.0_131]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_131]
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_131]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_131]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:1.8.0_131]
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_131]
        at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:1.8.0_131]
        at org.spongepowered.common.item.inventory.adapter.impl.Adapter$Logic.getProperties(Adapter.java:276) ~[Adapter$Logic.class:1.11.2-6.1.0-BETA-11]
        at org.spongepowered.common.item.inventory.adapter.impl.Adapter$Logic.getProperties(Adapter.java:265) ~[Adapter$Logic.class:1.11.2-6.1.0-BETA-11]
        at org.spongepowered.common.item.inventory.adapter.impl.MinecraftInventoryAdapter.getProperty(MinecraftInventoryAdapter.java:148) ~[MinecraftInventoryAdapter.class:1.11.2-6.1.0-BETA-11]
        at org.spongepowered.common.item.inventory.adapter.impl.MinecraftInventoryAdapter.getProperty(MinecraftInventoryAdapter.java:161) ~[MinecraftInventoryAdapter.class:1.11.2-6.1.0-BETA-11]
        at flavor.pie.testplugin.TestPlugin.lambda$null$0(TestPlugin.java:34) ~[TestPlugin.class:?]
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:1.8.0_131]
        at java.util.Iterator.forEachRemaining(Unknown Source) ~[?:1.8.0_131]
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_131]
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_131]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_131]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:1.8.0_131]
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_131]
        at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:1.8.0_131]
        at flavor.pie.testplugin.TestPlugin.lambda$init$4(TestPlugin.java:35) ~[TestPlugin.class:?]
        at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:359) ~[CommandSpec.class:1.11.2-6.1.0-BETA-11]
        at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:336) ~[SimpleDispatcher.class:1.11.2-6.1.0-BETA-11]
        at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:296) ~[SpongeCommandManager.class:1.11.2-6.1.0-BETA-11]
        at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083) ~[bd.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(SourceFile:818) ~[mi.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(SourceFile:805) ~[mi.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) ~[ip.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) ~[ip.class:?]
        at org.spongepowered.common.network.PacketUtil.lambda$onProcessPacket$0(PacketUtil.java:153) ~[PacketUtil.class:1.11.2-6.1.0-BETA-11]
        at org.spongepowered.common.event.tracking.CauseTracker.switchToPhase(CauseTracker.java:161) [CauseTracker.class:1.11.2-6.1.0-BETA-11]
        at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:152) [PacketUtil.class:1.11.2-6.1.0-BETA-11]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjg000(SourceFile:539) [fo$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fo$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_131]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_131]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:256) [SpongeImplHooks.class:1.11.2-6.1.0-BETA-11]
        at net.minecraft.server.MinecraftServer.redirect$onRun$zhf000(SourceFile:4172) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(SourceFile:1527) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(SourceFile:335) [lh.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(SourceFile:562) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(SourceFile:466) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
```
SpongeVanilla 1.11.2-6.1.0-BETA-11

**Comment by JBYoshi** [comment]
I can't reproduce this. What do you have in your inventory when you run this code?

**Comment by pie-flavor** [comment]
No matter what I have, it doesn't work. But for an identical case, try putting a stick in your storage inventory, another in your hotbar, and holding it.

**Comment by JBYoshi** [comment]
Is this still an issue? If so, could you post an updated stack trace?

**Comment by JBYoshi** [comment]
Is this still an issue?
