### ISSUE TITLE
DamageEntityEvent Reduncency Call

### ISSUE THREAD

**Issue by SjsolisZXA** [SpongePowered/Sponge#1447]
**Forge Build:** forge-1.10.2-12.18.3.2281-universal
**SpongeForge Build:** spongeforge-1.10.2-2281-5.2.0-BETA-2464
**Java:** 1.8.0 131-b11
**OS:** Windows 10

When a player falls off the map and dies, the DamageEntityEvent listener gets called twice. I have a listener that re-spawns a player if they fall of the map, but it's called on twice. Below is the listener and the 

**Listener:**
```java
@Listener
public void onEntityDeath(DamageEntityEvent event) {
	
    if(event.willCauseDeath()){
	
        Optional<EntityDamageSource> optDamageSource = event.getCause().first(EntityDamageSource.class);
        
        if (!optDamageSource.isPresent()) {
    	
	    	Entity entity = event.getTargetEntity();
	    	
	    	Optional<Text> userN = entity.get(Keys.DISPLAY_NAME);
	    	
	    	if(userN.isPresent()){
	    		
	    		Player player = ((Player) entity);

        		ScoreBoardUtils.addDeathScore(player);

                TDMConfigUtils.respawnContestant("A1", player);
        		
        		Sponge.getServer().getBroadcastChannel().send(Text.of("Player died of supernatural causes."));
    			
    			event.setCancelled(true);
    			
        	}
        }
    }
```

**Log:**

```
[12:01:32] [Server thread/INFO]: Player died of supernatural causes.
[12:01:32] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]: java.lang.Exception: Stack trace
[12:01:32] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]:      at java.lang.Thread.dumpStack(Unknown Source)
[12:01:32] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]:      at Listeners.GeneralArenaListeners.onEntityDeath(GeneralArenaListeners.java:445)
[12:01:32] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]:      at org.spongepowered.common.event.listener.DamageEntityEventListener_GeneralArenaListeners_onEntityDeath91.handle(Unknown Source)
[12:01:32] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]:      at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95)
[12:01:32] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]:      at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:313)
[12:01:32] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]:      at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:342)
[12:01:32] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]:      at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:326)
[12:01:32] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]:      at net.minecraft.entity.EntityLivingBase.damageEntityHook(EntityLivingBase.java:3411)
[12:01:32] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]:      at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:3259)
[12:01:32] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]:      at net.minecraft.entity.player.EntityPlayer.func_70097_a(EntityPlayer.java:1022)
[12:01:32] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]:      at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(EntityPlayerMP.java:543)
[12:01:32] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]:      at net.minecraft.entity.EntityLivingBase.func_70076_C(EntityLivingBase.java:1417)
[12:01:32] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]:      at net.minecraft.entity.Entity.func_70030_z(Entity.java:473)
[12:01:32] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]:      at net.minecraft.entity.EntityLivingBase.func_70030_z(EntityLivingBase.java:216)
[12:01:32] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]:      at net.minecraft.entity.Entity.func_70071_h_(Entity.java:359)
[12:01:32] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]:      at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1932)
[12:01:32] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]:      at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:233)
[12:01:32] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]:      at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:303)
[12:01:32] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]:      at net.minecraft.network.NetHandlerPlayServer.redirect$onPlayerTick$zhf000(NetHandlerPlayServer.java:1955)
[12:01:32] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]:      at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:162)
[12:01:32] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]:      at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:213)
[12:01:32] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]:      at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287)
[12:01:32] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]:      at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
[12:01:32] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]:      at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:732)
[12:01:32] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]:      at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
[12:01:32] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]:      at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
[12:01:32] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]:      at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
[12:01:32] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]:      at java.lang.Thread.run(Unknown Source)
[12:01:33] [Server thread/INFO]: Player died of supernatural causes.
[12:01:33] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]: java.lang.Exception: Stack trace
[12:01:33] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]:      at java.lang.Thread.dumpStack(Unknown Source)
[12:01:33] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]:      at Listeners.GeneralArenaListeners.onEntityDeath(GeneralArenaListeners.java:445)
[12:01:33] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]:      at org.spongepowered.common.event.listener.DamageEntityEventListener_GeneralArenaListeners_onEntityDeath91.handle(Unknown Source)
[12:01:33] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]:      at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95)
[12:01:33] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]:      at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:313)
[12:01:33] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]:      at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:342)
[12:01:33] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]:      at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:326)
[12:01:33] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]:      at net.minecraft.entity.EntityLivingBase.damageEntityHook(EntityLivingBase.java:3411)
[12:01:33] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]:      at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:3259)
[12:01:33] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]:      at net.minecraft.entity.player.EntityPlayer.func_70097_a(EntityPlayer.java:1022)
[12:01:33] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]:      at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(EntityPlayerMP.java:543)
[12:01:33] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]:      at net.minecraft.entity.EntityLivingBase.func_180430_e(EntityLivingBase.java:1205)
[12:01:33] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]:      at net.minecraft.entity.player.EntityPlayer.func_180430_e(EntityPlayer.java:1936)
[12:01:33] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]:      at net.minecraft.block.Block.func_180658_a(Block.java:807)
[12:01:33] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]:      at net.minecraft.entity.Entity.redirect$onBlockFallenUpon$zcp000(Entity.java:5675)
[12:01:33] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]:      at net.minecraft.entity.Entity.func_184231_a(Entity.java:1007)
[12:01:33] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]:      at net.minecraft.entity.EntityLivingBase.func_184231_a(EntityLivingBase.java:205)
[12:01:33] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]:      at net.minecraft.entity.player.EntityPlayerMP.func_71122_b(EntityPlayerMP.java:732)
[12:01:33] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]:      at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:517)
[12:01:33] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]:      at net.minecraft.network.play.client.CPacketPlayer.func_148833_a(SourceFile:126)
[12:01:33] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]:      at net.minecraft.network.play.client.CPacketPlayer.func_148833_a(SourceFile:8)
[12:01:33] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]:      at org.spongepowered.common.network.PacketUtil.lambda$onProcessPacket$0(PacketUtil.java:157)
[12:01:33] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]:      at org.spongepowered.common.event.tracking.CauseTracker.switchToPhase(CauseTracker.java:162)
[12:01:33] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]:      at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:156)
[12:01:33] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]:      at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjj000(SourceFile:539)
[12:01:33] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]:      at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
[12:01:33] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]:      at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[12:01:33] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]:      at java.util.concurrent.FutureTask.run(Unknown Source)
[12:01:33] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]:      at net.minecraft.util.Util.func_181617_a(SourceFile:45)
[12:01:33] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]:      at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:241)
[12:01:33] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]:      at net.minecraft.server.MinecraftServer.redirect$onRun$zhp000(MinecraftServer.java:3932)
[12:01:33] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]:      at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668)
[12:01:33] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]:      at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
[12:01:33] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]:      at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
[12:01:33] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]:      at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
[12:01:33] [Server thread/INFO] [STDERR]: [java.lang.Thread:dumpStack:-1]:      at java.lang.Thread.run(Unknown Source)
```

**Comment by SjsolisZXA** [comment]
Bumping up report.

**Comment by RedNesto** [comment]
I cannot reproduce on `spongeforge-1.12.2-2586-7.1.0-BETA-2865` and `spongevanilla-1.12.2-7.1.0-BETA-14`

**Comment by ryantheleach** [comment]
@RedNesto Thanks for testing I assume you used the listener in the OP.

@SjsolisZXA If you are able to still reproduce this, leave a comment describing how and I'll re-open.
