### ISSUE TITLE
Player.getName() throws an AbstractMethodError

### ISSUE THREAD

**Issue by me4502** [SpongePowered/Sponge#148]
[03:37:23] [Server thread/WARN] [SpongeAPIMod]: A handler raised an error when handling an event
java.lang.AbstractMethodError: net.minecraft.entity.player.EntityPlayerMP.getName()Ljava/lang/String;
        at com.me4502.Kingdoms.Kingdoms.onBlock(Kingdoms.java:22) ~[Kingdoms.class:?]
        at org.spongepowered.mod.event.handler.EventHandler_Kingdoms_onBlock1.handle(Unknown Source) ~[?:?]
        at org.spongepowered.mod.event.SpongeEventBus.callListener(SpongeEventBus.java:197) [SpongeEventBus.class:1.8-11.14.0.1282-SNAPSHOT+unknown-b0.git-unknown]
        at org.spongepowered.mod.event.SpongeEventBus.post(SpongeEventBus.java:250) [SpongeEventBus.class:1.8-11.14.0.1282-SNAPSHOT+unknown-b0.git-unknown]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:55) [EventBus.class:?]
        at net.minecraftforge.common.ForgeHooks.onBlockBreakEvent(ForgeHooks.java:522) [ForgeHooks.class:?]
        at net.minecraft.server.management.ItemInWorldManager.func_180237_b(ItemInWorldManager.java:280) [qx.class:?]
        at net.minecraft.server.management.ItemInWorldManager.func_180784_a(ItemInWorldManager.java:154) [qx.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:526) [rj.class:?]
        at net.minecraft.network.play.client.C07PacketPlayerDigging.func_180763_a(SourceFile:40) [ml.class:?]
        at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:10) [ml.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [ih.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_25]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_25]
        at net.minecraftforge.fml.common.FMLCommonHandler.callFuture(FMLCommonHandler.java:676) [FMLCommonHandler.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:655) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:364) [po.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:598) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:478) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]

**Comment by simon816** [comment]
Makes sense, since methods from [`User`](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/entity/player/User.java) are [not yet implemented](https://github.com/SpongePowered/Sponge/blob/master/src/main/java/org/spongepowered/mod/mixin/entity/player/MixinEntityPlayerMP.java)

**Comment by me4502** [comment]
Ah, I see.
