### ISSUE TITLE
AbstractMethodError with new TE unload mechanism

### ISSUE THREAD

**Issue by Orhideous** [SpongePowered/Sponge#1509]
**I am currently running...**

- Sponge version: **1.10.2-12.18.3.2422**
- SpongeForge version: 1.10.2-2281-5.2.0-BETA-2597
- Java version: 1.8.0_131, Oracle Corporation
- Operating System: Linux (amd64) version 3.16.0-4-amd64

 - [x] Linux (Ubuntu, Debian, Fedora, etc)
 - [ ] macOS
 - [ ] Windows

**What is the expected result?**
Server should'nt crash
**What is the current result?**
Server crashed instead.
```
java.lang.AbstractMethodError: Method net/minecraft/world/WorldServer.getProperties()Lorg/spongepowered/api/world/storage/WorldProperties; is abstract
	at net.minecraft.world.WorldServer.getProperties(WorldServer.java)
	at net.minecraft.world.WorldServer.getUniqueId(WorldServer.java:1827)
	at net.minecraft.world.chunk.Chunk.handler$onConstructed$zjm000(Chunk.java:1753)
	at net.minecraft.world.chunk.Chunk.<init>(Chunk.java:93)
	at org.spongepowered.common.world.SpongeEmptyChunk.<init>(SpongeEmptyChunk.java:50)
	at net.minecraft.world.gen.ChunkProviderServer.handler$onConstruct$zkk000(ChunkProviderServer.java:601)
	at net.minecraft.world.gen.ChunkProviderServer.<init>(ChunkProviderServer.java:45)
	at net.minecraft.world.WorldServer.func_72970_h(WorldServer.java:855)
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:115)
	at org.spongepowered.common.world.WorldManager.createWorldFromProperties(WorldManager.java:811)
	at org.spongepowered.common.world.WorldManager.loadAllWorlds(WorldManager.java:782)
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:3492)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:266)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431)
	at java.lang.Thread.run(Thread.java:748)
```

Looks like this happened after porting Forge's 1.12 TE unload patch to fix MC-117075 (MinecraftForge/MinecraftForge#4281) in 3067867e9ee373a450a36f502349525daec92db2

**Comment by Zidane** [comment]
Closing as we no longer support 1.10.
