### ISSUE TITLE
Expected to exit phase: EntityTickPhase, But instead found phase: DeathPhase

### ISSUE THREAD

**Issue by Magi1053** [SpongePowered/Sponge#1515]
```
/*****************************************************************************************************************/
/*                                          Completing incorrect phase                                           */
/*****************************************************************************************************************/
/* Sponge's tracking system is very dependent on                                                                 */
/* knowing whena change to any world takes place,                                                                */
/* however, we are attemptingto complete a "phase"                                                               */
/* other than the one we most recently entered.This                                                              */
/* is an error usually on Sponge's part, so a                                                                    */
/* reportis required on the issue tracker on GitHub.                                                             */
/*****************************************************************************************************************/
/* Expected to exit phase: EntityTickPhase                                                                       */
/* But instead found phase: org.spongepowered.common.event.tracking.phase.entity.DeathPhase@3b0a59bc             */
/* StackTrace:                                                                                                   */
/* java.lang.Exception: null                                                                                     */
/*     org.spongepowered.common.event.tracking.CauseTracker.printIncorrectPhaseCompletion(CauseTracker.java:275) */
/*     org.spongepowered.common.event.tracking.CauseTracker.completePhase(CauseTracker.java:197)                 */
/*     org.spongepowered.common.event.tracking.TrackingUtil.tickEntity(TrackingUtil.java:163)                    */
/*     net.minecraft.world.WorldServer.redirect$onCallEntityUpdate$zkc000(WorldServer.java:2843)                 */
/*     net.minecraft.world.World.func_72866_a(World.java:4072)                                                   */
/*     net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:839)                                        */
/*     net.minecraft.world.World.func_72870_g(World.java:1934)                                                   */
/*     net.minecraft.world.World.func_72939_s(World.java:6029)                                                   */
/*     net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:2185)                                       */
/*     net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)                               */
/*     net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)                     */
/*     net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)                               */
/*     net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)                                        */
/*     java.lang.Thread.run(Thread.java:748)                                                                     */
/*  Phases Remaining:                                                                                            */
/*   - Phase: org.spongepowered.common.event.tracking.phase.entity.DeathPhase@3b0a59bc                           */
/*     Context:                                                                                                  */
/*     - Name: Source                                                                                            */
/*       Object: EntityVillager['Villager'/523812, l='world', x=-429.50, y=70.00, z=373.50]                      */
/*     - Name: DamageSource                                                                                      */
/*       Object: DamageSource{Name=inWall, Type=suffocate}                                                       */
/*     - Name: CapturedBlocks                                                                                    */
/*       Object: CapturedBlocksSupplier{Captured=0}                                                              */
/*     - Name: CapturedEntities                                                                                  */
/*       Object: CapturedEntitiesSupplier{Captured=0}                                                            */
/*   - Phase: EntityTickPhase                                                                                    */
/*     Context:                                                                                                  */
/*     - Name: Source                                                                                            */
/*       Object: EntityVillager['Villager'/523812, l='world', x=-429.50, y=70.00, z=373.50]                      */
/*     - Name: CapturedEntities                                                                                  */
/*       Object: CapturedEntitiesSupplier{Captured=0}                                                            */
/*     - Name: CapturedBlocks                                                                                    */
/*       Object: CapturedBlocksSupplier{Captured=0}                                                              */
/*                                                                                                               */
/* Minecraft : 1.10.2                                                                                            */
/* SpongeAPI : 5.2.0-SNAPSHOT-c675e80                                                                            */
/* SpongeForge : 1.10.2-2281-5.2.0-BETA-2597                                                                     */
/* Minecraft Forge : 12.18.3.2422                                                                                */
/*****************************************************************************************************************/
```
```
net.minecraft.util.ReportedException: Ticking entity
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:715) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) ~[ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.IllegalArgumentException: bound must be positive
        at java.util.Random.nextInt(Random.java:388) ~[?:1.8.0_131]
        at net.minecraft.entity.passive.EntityVillager.func_175554_cu(EntityVillager.java:1859) ~[zn.class:?]
        at net.minecraft.entity.passive.EntityVillager.func_145748_c_(EntityVillager.java:675) ~[zn.class:?]
        at net.minecraft.util.DamageSource.func_151519_b(SourceFile:181) ~[rh.class:?]
        at net.minecraft.util.CombatTracker.func_151521_b(SourceFile:105) ~[rg.class:?]
        at org.spongepowered.common.event.SpongeCommonEventFactory.callDestructEntityEventDeath(SpongeCommonEventFactory.java:567) ~[SpongeCommonEventFactory.class:1.10.2-2281-5.2.0-BETA-2597]
        at net.minecraft.entity.EntityLivingBase.func_70645_a(EntityLivingBase.java:3082) ~[sf.class:?]
        at net.minecraft.entity.passive.EntityVillager.func_70645_a(EntityVillager.java:502) ~[zn.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:3339) ~[sf.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70030_z(EntityLivingBase.java:224) ~[sf.class:?]
        at net.minecraft.entity.EntityLiving.func_70030_z(EntityLiving.java:208) ~[sg.class:?]
        at net.minecraft.entity.Entity.func_70071_h_(Entity.java:359) ~[rw.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1932) ~[sf.class:?]
        at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295) ~[sg.class:?]
        at org.spongepowered.common.event.tracking.TrackingUtil.tickEntity(TrackingUtil.java:158) ~[TrackingUtil.class:1.10.2-2281-5.2.0-BETA-2597]
        at net.minecraft.world.WorldServer.redirect$onCallEntityUpdate$zkc000(WorldServer.java:2843) ~[ls.class:?]
        at net.minecraft.world.World.func_72866_a(World.java:4072) ~[aid.class:?]
        at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:839) ~[ls.class:?]
        at net.minecraft.world.World.func_72870_g(World.java:1934) ~[aid.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:6029) ~[aid.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:2185) ~[ls.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709) ~[MinecraftServer.class:?]
```

**Comment by Magi1053** [comment]
So there must be some kind of a villager in a chunk, probably underground as there is nothing on the surface. When a player walks into the chunk (and now the chunk is chunkloaded), the server instantly crashes with this message. Upon that same player reconnecting to the server after restart, it crashes again.
The only way I've been able to stop the crash is to /kill all the passive villagers on the server.

**Comment by Magi1053** [comment]
This issue is continuously crashing the server, so it would be great if someone could look into it.

**Comment by phit** [comment]
Closing this in favor of https://github.com/SpongePowered/SpongeForge/issues/1467
