### ISSUE TITLE
1.12.2 CauseTracker Error -- Dragging itemstack off inventory screens for ALL inventory screens (except 1)

### ISSUE THREAD

**Issue by theboomer** [SpongePowered/Sponge#1543]
Cause Tracker error thrown when you drag an itemstack off of the player inventory and release it outside to drop --- for either left mouse (drop everything) or right mouse (drop just one from itemstack) operations.   

The error results from that off-the-side drop behavior for the following:
Survival and creative: Workbench, Furnace, (Trapped) Chests, both singled and doubled,  Dispenser, Dropper, Hopper, Beacon, MinecartChest, MinecartHopper, EnchantmentTable, and villager-trade GUI.
Survival: Player inventory screen (key-I opened) 

CREATIVE Player key-opened inventory screen is the only exception, no error gets thrown, regardless of which tab is used as well.

Dropping the items with the drop-key from the hotbar does not generate the error.

------------------------
Spongevanilla-beta-339
Spongeforge-beta-2666
But this result is seen back to 2660 as well, and you are expecting a bunch of tracker errors to be found :)

**Comment by theboomer** [comment]
```
[04:08:35] [Server thread/ERROR] [EntityTracker]: "Silently" catching entity tracking error.
net.minecraft.util.ReportedException: Adding entity to track
	at net.minecraft.entity.EntityTracker.func_72785_a(SourceFile:178) [ol.class:?]
	at net.minecraft.entity.EntityTracker.func_72786_a(SourceFile:109) [ol.class:?]
	at net.minecraft.world.ServerWorldEventHandler.func_72703_a(SourceFile:41) [op.class:?]
	at net.minecraft.world.World.func_72923_a(SourceFile:963) [amu.class:?]
	at net.minecraft.world.WorldServer.func_72923_a(SourceFile:971) [oo.class:?]
	at net.minecraft.world.WorldServer.onSpongeEntityAdded(SourceFile:2716) [oo.class:?]
	at net.minecraft.world.WorldServer.forceSpawnEntity(SourceFile:2762) [oo.class:?]
	at net.minecraft.world.WorldServer.forceSpawnEntity(SourceFile:2745) [oo.class:?]
	at org.spongepowered.common.event.tracking.TrackingUtil.splitAndSpawnEntities(TrackingUtil.java:863) [TrackingUtil.class:1.12.2-7.0.0-BETA-338]
	at org.spongepowered.common.event.tracking.TrackingUtil.splitAndSpawnEntities(TrackingUtil.java:828) [TrackingUtil.class:1.12.2-7.0.0-BETA-338]
	at org.spongepowered.common.event.tracking.phase.general.PostState.postDispatch(PostState.java:105) [PostState.class:1.12.2-7.0.0-BETA-338]
	at org.spongepowered.common.event.tracking.phase.general.PostState.unwind(PostState.java:80) [PostState.class:1.12.2-7.0.0-BETA-338]
	at org.spongepowered.common.event.tracking.phase.general.PostState.unwind(PostState.java:41) [PostState.class:1.12.2-7.0.0-BETA-338]
	at org.spongepowered.common.event.tracking.CauseTracker.completePhase(CauseTracker.java:209) [CauseTracker.class:1.12.2-7.0.0-BETA-338]
	at org.spongepowered.common.event.tracking.PhaseContext.close(PhaseContext.java:399) [PhaseContext.class:1.12.2-7.0.0-BETA-338]
	at org.spongepowered.common.event.tracking.CauseTracker.completePhase(CauseTracker.java:215) [CauseTracker.class:1.12.2-7.0.0-BETA-338]
	at org.spongepowered.common.event.tracking.PhaseContext.close(PhaseContext.java:399) [PhaseContext.class:1.12.2-7.0.0-BETA-338]
	at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:151) [PacketUtil.class:1.12.2-7.0.0-BETA-338]
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjn000(SourceFile:539) [hv$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_111]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:271) [SpongeImplHooks.class:1.12.2-7.0.0-BETA-338]
	at net.minecraft.server.MinecraftServer.redirect$onRun$zhp000(SourceFile:4175) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(SourceFile:1523) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(SourceFile:349) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(SourceFile:560) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(SourceFile:464) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: java.lang.IllegalStateException: Entity EntityItem['item.item.bone'/172, l='world', x=95.03, y=69.32, z=101.93] is already tracked for world: world
	at net.minecraft.entity.EntityTracker.redirect$reportEntityAlreadyTrackedWithWorld$zdc000(SourceFile:561) ~[ol.class:?]
	at net.minecraft.entity.EntityTracker.func_72785_a(SourceFile:152) ~[ol.class:?]
	... 29 more
```

**Comment by bloodmc** [comment]
@theboomer This should be fixed in commit https://github.com/SpongePowered/SpongeCommon/commit/2a5b90cf1a28b6f8b965db2f604cb561c0a4949d

Please confirm and close if it is.

**Comment by theboomer** [comment]
Confirmed bug has been squished.
Time to stress-test a bunch of events tonight find some more..
