### ISSUE TITLE
Broken MessageEvent

### ISSUE THREAD

**Issue by XakepSDK** [SpongePowered/Sponge#1564]
I just made simple plugin with simple event listener.
```Java
    @Listener
    public void chat(MessageEvent event, @Root Player player) {
        System.out.println("===============");
        System.out.println(event.getMessage());
        System.out.println("===============");
        MenuManager menuManager = new SpongeMenuManager();
        Menu idsf = menuManager.createMenu(container, "idsf", InventoryArchetypes.CHEST);
        idsf.offer(...);
        idsf.open(player);
    }
```
So...
It printed this:
```
[17:10:20 INFO] [STDOUT]: ===============
[17:10:20 INFO] [STDOUT]: Text{children=[Text{children=[Text{children=[Text{children=[Text{You are not allowed to log in to this server.}], }], }], }], }
[17:10:20 INFO] [STDOUT]: ===============
```
With null player object, then this:
```
[17:10:20 INFO] [STDOUT]: ===============
[17:10:20 INFO] [STDOUT]: Text{children=[Text{children=[Text{children=[Text{children=[Text{format=TextFormat{color=yellow, style=TextStyle{}}, SpongeTranslation{id=multiplayer.player.joined}, arguments=[Text{clickAction=SuggestCommand{/msg Xakep_SDK }, hoverAction=ShowEntity{Ref{uuid=2fbd0793-7515-4d91-a143-2b257c11205d, name=Xakep_SDK, type=Optional.empty}}, shiftClickAction=InsertText{Xakep_SDK}, Xakep_SDK}]}], }], }], }], }
[17:10:20 INFO] [STDOUT]: ===============
```
Why it prints `You are not allowed to log in to this server`? Why it calls method with null arg?

**Comment by kashike** [comment]
Sorry, could you clarify what you mean? I don't understand.

**Comment by dualspiral** [comment]
@XakepSDK Next time, could you please add more information about what you're doing? It's not obvious what's going on without that extra context.

To answer your question, you would have gotten a bit of a clearer answer if you had printed out `event.getClass()`. You neglected to say that someone was logging in at the time. The two events in question are [`ClientConnectionEvent.Login`](https://jd.spongepowered.org/6.0.0/org/spongepowered/api/event/network/ClientConnectionEvent.Login.html) followed by [`ClientConnectionEvent.Join`](https://jd.spongepowered.org/6.0.0/org/spongepowered/api/event/network/ClientConnectionEvent.Join.html). The first event was giving you the message that _would_ have been sent out if the event was cancelled and the player was kicked during the login phase. It should not have called your listener as there shouldn't be a `Player` cause in it during that phase - the `Player` is yet to be constructed I think. The second is the standard join message, that's firing as expected.

@kashike I think there is a bug in here that his event handler is called with the filter even when `ClientConnectionEvent.Login` is called - is there potentially a `null` at the head of the CSM which is casting to `Player`?

**Comment by XakepSDK** [comment]
@dualspiral Its just plugin with 1 listener. There is nothing special, nothing extra.
I will send stacktrace as soon as possible.

**Comment by ryantheleach** [comment]
What are you trying to accomplish listening to the Message Event and constructing your menu anyway?

For testing things, I'd recommend creating a simple command, if that's your goal.

**Comment by XakepSDK** [comment]
Event should not be called, because there is no correct player in cause context! This is a bug.
https://puu.sh/xUnaZ/55c2237021.png

**Comment by kashike** [comment]
Stacktrace please.

**Comment by XakepSDK** [comment]
```Java
@Plugin(id = "lwma",
        name = "lwma",
        version = "1.0-SNAPSHOT",
        description = "Menu api for sponge",
        authors = "Xakep_SDK")
public class Main {

    @Inject
    private Logger logger;

    @Listener
    public void a(MessageEvent event, @Root Player player) {
        logger.warn("===========");
        logger.warn(event.getMessage().toPlain());
        logger.warn("===========");
        player.sendMessage(event.getMessage());
    }
}
```
```
[10:08:49 WARN] [lwma]: ===========
[10:08:49 WARN] [lwma]: You are not allowed to log in to this server.
[10:08:49 WARN] [lwma]: ===========
[10:08:49 ERROR] [Sponge]: Could not pass ClientConnectionEvent$Login$Impl to Plugin{id=lwma, name=lwma, version=1.0-SNAPSHOT, description=Menu api for sponge, authors=[Xakep_SDK], source=mods/lwma-1.0-SNAPSHOT.jar}
java.lang.NullPointerException: null
	at net.minecraft.entity.player.EntityPlayerMP.sendMessage(SourceFile:3781) ~[oq.class:?]
	at org.spongepowered.api.text.channel.MessageChannel.lambda$send$3(MessageChannel.java:196) ~[MessageChannel.class:1.12.2-7.0.0-BETA-346]
	at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_144]
	at org.spongepowered.api.text.channel.MessageChannel.send(MessageChannel.java:196) ~[MessageChannel.class:1.12.2-7.0.0-BETA-346]
	at org.spongepowered.common.text.chat.ChatUtil.sendMessage(ChatUtil.java:61) ~[ChatUtil.class:1.12.2-7.0.0-BETA-346]
	at net.minecraft.entity.player.EntityPlayerMP.func_145747_a(SourceFile:3795) ~[oq.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.sendMessage(SourceFile:1371) ~[oq.class:?]
	at dk.xakeps.lwma.Main.a(Main.java:44) ~[Main.class:?]
	at org.spongepowered.common.event.listener.MessageEventListener_Main_a3.handle(Unknown Source) ~[?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-7.0.0-BETA-346]
	at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:371) [SpongeEventManager.class:1.12.2-7.0.0-BETA-346]
	at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:388) [SpongeEventManager.class:1.12.2-7.0.0-BETA-346]
	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:198) [SpongeImpl.class:1.12.2-7.0.0-BETA-346]
	at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(SourceFile:1288) [pl.class:?]
	at net.minecraft.server.management.PlayerList.func_72355_a(SourceFile:1204) [pl.class:?]
	at net.minecraft.server.network.NetHandlerLoginServer.func_147326_c(SourceFile:119) [pc.class:?]
	at net.minecraft.server.network.NetHandlerLoginServer.func_73660_a(SourceFile:66) [pc.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(SourceFile:231) [gw.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(SourceFile:187) [oz.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(SourceFile:1599) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(SourceFile:349) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(SourceFile:560) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(SourceFile:464) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
[10:08:49 INFO]: Xakep_SDK[/127.0.0.1:56712] logged in with entity id 186 in world(0) at (134.1498192296801, 64.0, 257.68575270200233)
[10:08:49 WARN] [lwma]: ===========
[10:08:49 WARN] [lwma]: Xakep_SDK joined the game
[10:08:49 WARN] [lwma]: ===========

```
Oh, sorry guys, my bad, something wrong in internals of EntityPlayer. Only I slept after 48 hours of marathon without sleep.

**Comment by gabizou** [comment]
The player is not in fact `null`, what I believe is happening is that the `EntityPlayerMP.connection` which is the instance of `NetHandlerPlayServer` is not set yet, which makes sense why this will happen on `ClientConnectionEvent.Login`, since the handler is not constructed until well after.

@kashike @dualspiral the issues lie [here](https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/mixin/core/server/MixinPlayerList.java#L271-L319) and [here](https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/mixin/core/entity/player/MixinEntityPlayerMP.java#L464).

@XakepSDK in the future, stack traces help a great deal to find the bug in any code, because without it, jumping to conclusions does not tell us anything helpful.

For more disucssion however, @Zidane and I had this discussion several months ago about whether the Player should be in the cause or not so early in the connection.

**Comment by XakepSDK** [comment]
@gabizou yes, sorry, guys. This was completely my fault.

**Comment by dualspiral** [comment]
> For more disucssion however, @Zidane and I had this discussion several months ago about whether the Player should be in the cause or not so early in the connection.

To add to that discussion, I'd argue it should be the `GameProfile` or non-Player `User` instead. The `ClientConnectionEvent.Login` is a `TargetUserEvent`, not a `TargetPlayerEvent`, I suspect for this very reason. We shouldn't be pushing incomplete objects to the `Cause` stack because, well, this will happen.

That being said, is `MessageEvent` even appropriate for `ClientConnectionEvent.Login`? I know that it involves a `Text` message, but this sends a message on _cancel_, while every other event that I can think of sends the message if the event is not cancelled. Given that there are some events where a message can be set on cancel, would it make sense to add another interface, such as `Cancellable.WithMessage` that indicates that setting such a message will only take effect if the event is cancelled?

**Comment by simon816** [comment]
Two years ago we decided not to include the player in the `Login` event (https://github.com/SpongePowered/SpongeAPI/pull/944). 
The player is in an undefined state up until the `ClientConnectionEvent.Join` event is fired, and should not be included in any cause stacks. Instead `GameProfile` should be available and, once the server has fetched player data from disk, `User` should also be made available.
These don't even need to be on the cause, since there's already `getProfile()` and `getTargetUser()`

**Comment by ryantheleach** [comment]
I'll be honest, I'm not exactly following this conversation.

Can someone please come up with a summary of 

- What's wrong.
- What the proposed fix is.

So someone can potentially follow up? 

I've got somewhat of an idea, but with 0 confidence that my interpretation is correct, or that it successfully covers xakep's issue, so feel a summary of some kind would be very helpful.

@XakepSDK In the future issues with no version numbers, no contexts will be closed until follow up information is provided. Please follow the template in the future.

**Comment by ImMorpheus** [comment]
The issue started as:
`public void chat(MessageEvent event, @Root Player player)` is called even if `player` is `null` (That listener should only be called when the root cause of the MessageEvent is a Player).

However 
> The player is not in fact null, what I believe is happening is that the EntityPlayerMP.connection which is the instance of NetHandlerPlayServer is not set yet, which makes sense why this will happen on ClientConnectionEvent.Login, since the handler is not constructed until well after.

To make things clear, here's a modified example:

```
@Listener
public void onLogin(ClientConnectionEvent.Login event, @Root Player player) {
    System.out.println("===========");
    System.out.println(event.getMessage().toPlain());
    System.out.println(event.getClass());
    System.out.println(player);
    player.sendMessage(event.getMessage());
}
```
Keep in mind ClientConnectionEvent.Login is TargetUserEvent, there shouldn't be any player (and the listener should not be called) at this point (see simon and dual comments above).

Output:

```
[Server thread/INFO] [STDOUT]: [org.spongepowered.test.TestTest:a:284]: You are not allowed to log in to this server.
[Server thread/INFO] [STDOUT]: [org.spongepowered.test.TestTest:a:285]: class org.spongepowered.api.event.ClientConnectionEvent$Login$Impl
[Server thread/INFO] [STDOUT]: [org.spongepowered.test.TestTest:a:286]: EntityPlayerMP['Notch_'/345, l='world', x=94.61, y=71.00, z=-63.43]
[Server thread/ERROR] [Sponge]: Could not pass ClientConnectionEvent$Login$Impl to Plugin{id=testtest, name=TestTest, version=0.0.0}
java.lang.NullPointerException: null
	at net.minecraft.entity.player.EntityPlayerMP.sendMessage(EntityPlayerMP.java:4251) ~[EntityPlayerMP.class:?]
	at org.spongepowered.api.text.channel.MessageChannel.lambda$send$3(MessageChannel.java:196) ~[MessageChannel.class:?]
	at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_171]
	at org.spongepowered.api.text.channel.MessageChannel.send(MessageChannel.java:196) ~[MessageChannel.class:?]
	at org.spongepowered.common.text.chat.ChatUtil.sendMessage(ChatUtil.java:61) ~[ChatUtil.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.sendMessage(EntityPlayerMP.java:4269) ~[EntityPlayerMP.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.sendMessage(EntityPlayerMP.java:1725) ~[EntityPlayerMP.class:?]
	at org.spongepowered.test.TestTest.onLogin(TestTest.java:287) ~[TestTest.class:?]
	at org.spongepowered.common.event.listener.LoginListener_TestTest_a42.handle(Unknown Source) ~[?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:?]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:383) [SpongeModEventManager.class:?]
	at org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:443) [SpongeModEventManager.class:?]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:404) [SpongeModEventManager.class:?]
	at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:458) [SpongeEventManager.class:?]
	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:225) [SpongeImpl.class:?]
	at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:1621) [PlayerList.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:259) [NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.serverToClientHandshake(NetworkDispatcher.java:161) [NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.fmlServerHandshake(FMLNetworkHandler.java:73) [FMLNetworkHandler.class:?]
	at net.minecraft.server.network.NetHandlerLoginServer.tryAcceptPlayer(NetHandlerLoginServer.java:139) [NetHandlerLoginServer.class:?]
	at net.minecraft.server.network.NetHandlerLoginServer.update(NetHandlerLoginServer.java:67) [NetHandlerLoginServer.class:?]
	at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:307) [NetworkManager.class:?]
	at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:197) [NetworkSystem.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:865) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:414) [DedicatedServer.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:743) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:592) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748)

```

This was reproduced on 1.12 (stable-7 updated to https://github.com/SpongePowered/SpongeCommon/commit/9e07c8e78f9056d7cbce189b44c2a1a0d354d4d8)

**Comment by ImMorpheus** [comment]
Not able to reproduce.
This was fixed when we switched to User (the listener above won't work because the root is now a SpongeUser)
https://github.com/SpongePowered/SpongeCommon/blob/80bf2d93bbedc78d7fbf447cfa9f574ce09a4a45/src/main/java/org/spongepowered/common/util/NetworkUtil.java#L199
