### ISSUE TITLE
IllegalAccessException with @RegisterCatalog

### ISSUE THREAD

**Issue by conreptio** [SpongePowered/Sponge#1668]
An IllegalAccessException is thrown by the game registry when a **plugin provided** registry module is registered with the RegisterCatalog annotation. 

The ```final``` declaration of the "pseudo enum" fields is ignored by the [RegistryHelper](https://github.com/SpongePowered/SpongeCommon/blob/5d8ac978765dde886c022dda23dbfedd96f24107/src/main/java/org/spongepowered/common/registry/RegistryHelper.java#L75).

StackTrace:
```
[Sponge]: Error while mapping com.neolumia.quartz.arena.ArenaStates.DEAD
java.lang.IllegalAccessException: Can not set static final com.neolumia.quartz.arena.ArenaState field com.neolumia.quartz.arena.ArenaStates.DEAD to com.neolumia.quartz.core.arena.QuartzArenaState
        at sun.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(Unknown Source) ~[?:1.8.0_131]
        at sun.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(Unknown Source) ~[?:1.8.0_131]
        at sun.reflect.UnsafeQualifiedStaticObjectFieldAccessorImpl.set(Unknown Source) ~[?:1.8.0_131]
        at java.lang.reflect.Field.set(Unknown Source) ~[?:1.8.0_131]
        at org.spongepowered.common.registry.RegistryHelper.mapFields(RegistryHelper.java:75) [RegistryHelper.class:1.12.2-7.0.0-BETA-384]
        at org.spongepowered.common.registry.RegistryHelper.mapFields(RegistryHelper.java:43) [RegistryHelper.class:1.12.2-7.0.0-BETA-384]
        at org.spongepowered.common.registry.util.RegistryModuleLoader.tryModulePhaseRegistration(RegistryModuleLoader.java:69) [RegistryModuleLoader.class:1.12.2-7.0.0-BETA-384]
        at org.spongepowered.common.registry.SpongeGameRegistry.registerModulePhase(SpongeGameRegistry.java:529) [SpongeGameRegistry.class:1.12.2-7.0.0-BETA-384]
        at org.spongepowered.common.registry.SpongeGameRegistry.preInit(SpongeGameRegistry.java:553) [SpongeGameRegistry.class:1.12.2-7.0.0-BETA-384]
        at org.spongepowered.server.SpongeVanilla.preInitialize(SpongeVanilla.java:122) [SpongeVanilla.class:1.12.2-7.0.0-BETA-384]
        at net.minecraft.server.dedicated.DedicatedServer.handler$onServerLoad$zol000(SourceFile:1234) [nz.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(SourceFile:117) [nz.class:?]
        at net.minecraft.server.MinecraftServer.run(SourceFile:434) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
```

Code:
https://github.com/neolumia/quartz/tree/4f4e6e65fad5a51623889dc8107aa99291144b75

**Comment by gabizou** [comment]
This was more of a requirement for us when it camto the initial aspects of the registry and setting fields. Early on we elected to use an access transformer *at runtime* to remove the final designation on the fields we needed to set the static values to. Afterwards, what ended up sticking is that same system where we "assume" the field is no longer `final` at runtime.

I'd be open to having it perform the final removal flag operation prior to setting, though it may only be slower for plugin provided classes. Thoughts @Zidane @Minecrell @Mumfrey ?
