### ISSUE TITLE
DataSerializableTypeSerializer does not use parent serializers

### ISSUE THREAD

**Issue by ShortCircuit908** [SpongePowered/Sponge#1816]
**I am currently running**

- SpongeForge version: 1.10.2-2477-5.2.0-BETA-2731
- Java version: 1.8
- Operating System: Windows 10

- Plugins/Mods: Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, CoFH ASM, ccl-entityhook, Bazaar, TieredKits, Watchdog, CodeChicken Lib, CodeChicken Core, CoFH Core, Golden Sands, Island Limiter, YUNoMakeGoodMap, ItsBecauseUHasNoGoodSpawn, Nucleus, Redstone Clock, Thermal Foundation, Thermal Expansion, Total Economy

**Issue Description**
I am using Configurate to serialize ItemStacks to a HOCON file. This works for all vanilla items, but some items added by mods (such as Thermal Expansion) contain arrays in their NBT data, which is not supported by default. I wrote array serializers and registered them with the ConfigurationNode options, and confirm that they work. However, through testing I have found that `org.spongepowered.common.config.DataSerializableTypeSerializer` does NOT use the parent options' serializers, and therefore does not recognize the array serializers.

The serializer I wrote is [here](https://gist.github.com/Short-Circuit/8828a2e26e22301cb0f04aca7e596288) and is registered with
```java
TypeSerializerCollection serializers = configuration_node.getOptions().getSerializers();
Class<byte[]> b_class = (Class<byte[]>) Class.forName("[B");
serializers.registerType(TypeToken.of(b_class), new ByteArraySerializer());
serializers.registerType(TypeToken.of(byte[].class), new ByteArraySerializer());
configuration_node.getOptions().setSerializers(serializers);
```

However, this exception is still thrown when serializing items that contain a byte array as part of its data
```
java.lang.IllegalArgumentException: Configuration does not accept objects of type class [B
        at ninja.leaping.configurate.ScalarConfigValue.setValue(ScalarConfigValue.java:42) ~[spongeforge-1.10.2-2477-5.2.0-BETA-2731.jar:1.10.2-2477-5.2.0-BETA-2731]
        at ninja.leaping.configurate.SimpleConfigurationNode.insertNewValue(SimpleConfigurationNode.java:274) ~[spongeforge-1.10.2-2477-5.2.0-BETA-2731.jar:1.10.2-2477-5.2.0-BETA-2731]
        at ninja.leaping.configurate.SimpleConfigurationNode.setValue(SimpleConfigurationNode.java:201) ~[spongeforge-1.10.2-2477-5.2.0-BETA-2731.jar:1.10.2-2477-5.2.0-BETA-2731]
        at ninja.leaping.configurate.commented.SimpleCommentedConfigurationNode.setValue(SimpleCommentedConfigurationNode.java:74) ~[spongeforge-1.10.2-2477-5.2.0-BETA-2731.jar:1.10.2-2477-5.2.0-BETA-2731]
        at ninja.leaping.configurate.commented.SimpleCommentedConfigurationNode.setValue(SimpleCommentedConfigurationNode.java:32) ~[spongeforge-1.10.2-2477-5.2.0-BETA-2731.jar:1.10.2-2477-5.2.0-BETA-2731]
        at ninja.leaping.configurate.SimpleConfigurationNode.setValue(SimpleConfigurationNode.java:182) ~[spongeforge-1.10.2-2477-5.2.0-BETA-2731.jar:1.10.2-2477-5.2.0-BETA-2731]
        at ninja.leaping.configurate.commented.SimpleCommentedConfigurationNode.setValue(SimpleCommentedConfigurationNode.java:74) ~[spongeforge-1.10.2-2477-5.2.0-BETA-2731.jar:1.10.2-2477-5.2.0-BETA-2731]
        at ninja.leaping.configurate.commented.SimpleCommentedConfigurationNode.setValue(SimpleCommentedConfigurationNode.java:32) ~[spongeforge-1.10.2-2477-5.2.0-BETA-2731.jar:1.10.2-2477-5.2.0-BETA-2731]
        at ninja.leaping.configurate.SimpleConfigurationNode.setValue(SimpleConfigurationNode.java:182) ~[spongeforge-1.10.2-2477-5.2.0-BETA-2731.jar:1.10.2-2477-5.2.0-BETA-2731]
        at ninja.leaping.configurate.commented.SimpleCommentedConfigurationNode.setValue(SimpleCommentedConfigurationNode.java:74) ~[spongeforge-1.10.2-2477-5.2.0-BETA-2731.jar:1.10.2-2477-5.2.0-BETA-2731]
        at ninja.leaping.configurate.commented.SimpleCommentedConfigurationNode.setValue(SimpleCommentedConfigurationNode.java:32) ~[spongeforge-1.10.2-2477-5.2.0-BETA-2731.jar:1.10.2-2477-5.2.0-BETA-2731]
        at ninja.leaping.configurate.SimpleConfigurationNode.setValue(SimpleConfigurationNode.java:182) ~[spongeforge-1.10.2-2477-5.2.0-BETA-2731.jar:1.10.2-2477-5.2.0-BETA-2731]
        at ninja.leaping.configurate.commented.SimpleCommentedConfigurationNode.setValue(SimpleCommentedConfigurationNode.java:74) ~[spongeforge-1.10.2-2477-5.2.0-BETA-2731.jar:1.10.2-2477-5.2.0-BETA-2731]
        at ninja.leaping.configurate.commented.SimpleCommentedConfigurationNode.setValue(SimpleCommentedConfigurationNode.java:32) ~[spongeforge-1.10.2-2477-5.2.0-BETA-2731.jar:1.10.2-2477-5.2.0-BETA-2731]
        at org.spongepowered.common.config.DataSerializableTypeSerializer.serialize(DataSerializableTypeSerializer.java:59) ~[DataSerializableTypeSerializer.class:1.10.2-2477-5.2.0-BETA-2731]
        at org.spongepowered.common.config.DataSerializableTypeSerializer.serialize(DataSerializableTypeSerializer.java:41) ~[DataSerializableTypeSerializer.class:1.10.2-2477-5.2.0-BETA-2731]
        at ninja.leaping.configurate.objectmapping.serialize.TypeSerializers$ListSerializer.serialize(TypeSerializers.java:247) ~[spongeforge-1.10.2-2477-5.2.0-BETA-2731.jar:1.10.2-2477-5.2.0-BETA-2731]
        at ninja.leaping.configurate.objectmapping.serialize.TypeSerializers$ListSerializer.serialize(TypeSerializers.java:206) ~[spongeforge-1.10.2-2477-5.2.0-BETA-2731.jar:1.10.2-2477-5.2.0-BETA-2731]
        at ninja.leaping.configurate.objectmapping.ObjectMapper$FieldData.serializeTo(ObjectMapper.java:113) ~[spongeforge-1.10.2-2477-5.2.0-BETA-2731.jar:1.10.2-2477-5.2.0-BETA-2731]
        at ninja.leaping.configurate.objectmapping.ObjectMapper$BoundInstance.serialize(ObjectMapper.java:162) ~[spongeforge-1.10.2-2477-5.2.0-BETA-2731.jar:1.10.2-2477-5.2.0-BETA-2731]
        at ninja.leaping.configurate.objectmapping.serialize.TypeSerializers$AnnotatedObjectSerializer.serialize(TypeSerializers.java:284) ~[spongeforge-1.10.2-2477-5.2.0-BETA-2731.jar:1.10.2-2477-5.2.0-BETA-2731]
        at ninja.leaping.configurate.objectmapping.serialize.TypeSerializers$ListSerializer.serialize(TypeSerializers.java:247) ~[spongeforge-1.10.2-2477-5.2.0-BETA-2731.jar:1.10.2-2477-5.2.0-BETA-2731]
        at ninja.leaping.configurate.objectmapping.serialize.TypeSerializers$ListSerializer.serialize(TypeSerializers.java:206) ~[spongeforge-1.10.2-2477-5.2.0-BETA-2731.jar:1.10.2-2477-5.2.0-BETA-2731]
        at ninja.leaping.configurate.objectmapping.ObjectMapper$FieldData.serializeTo(ObjectMapper.java:113) ~[spongeforge-1.10.2-2477-5.2.0-BETA-2731.jar:1.10.2-2477-5.2.0-BETA-2731]
        at ninja.leaping.configurate.objectmapping.ObjectMapper$BoundInstance.serialize(ObjectMapper.java:162) ~[spongeforge-1.10.2-2477-5.2.0-BETA-2731.jar:1.10.2-2477-5.2.0-BETA-2731]
        at ninja.leaping.configurate.objectmapping.serialize.TypeSerializers$AnnotatedObjectSerializer.serialize(TypeSerializers.java:284) ~[spongeforge-1.10.2-2477-5.2.0-BETA-2731.jar:1.10.2-2477-5.2.0-BETA-2731]
        at ninja.leaping.configurate.objectmapping.serialize.TypeSerializers$ListSerializer.serialize(TypeSerializers.java:247) ~[spongeforge-1.10.2-2477-5.2.0-BETA-2731.jar:1.10.2-2477-5.2.0-BETA-2731]
        at ninja.leaping.configurate.objectmapping.serialize.TypeSerializers$ListSerializer.serialize(TypeSerializers.java:206) ~[spongeforge-1.10.2-2477-5.2.0-BETA-2731.jar:1.10.2-2477-5.2.0-BETA-2731]
        at ninja.leaping.configurate.objectmapping.ObjectMapper$FieldData.serializeTo(ObjectMapper.java:113) ~[spongeforge-1.10.2-2477-5.2.0-BETA-2731.jar:1.10.2-2477-5.2.0-BETA-2731]
        at ninja.leaping.configurate.objectmapping.ObjectMapper$BoundInstance.serialize(ObjectMapper.java:162) ~[spongeforge-1.10.2-2477-5.2.0-BETA-2731.jar:1.10.2-2477-5.2.0-BETA-2731]
        at ninja.leaping.configurate.objectmapping.serialize.TypeSerializers$AnnotatedObjectSerializer.serialize(TypeSerializers.java:284) ~[spongeforge-1.10.2-2477-5.2.0-BETA-2731.jar:1.10.2-2477-5.2.0-BETA-2731]
        at ninja.leaping.configurate.objectmapping.serialize.TypeSerializers$MapSerializer.serialize(TypeSerializers.java:200) ~[spongeforge-1.10.2-2477-5.2.0-BETA-2731.jar:1.10.2-2477-5.2.0-BETA-2731]
        at ninja.leaping.configurate.objectmapping.serialize.TypeSerializers$MapSerializer.serialize(TypeSerializers.java:143) ~[spongeforge-1.10.2-2477-5.2.0-BETA-2731.jar:1.10.2-2477-5.2.0-BETA-2731]
        at ninja.leaping.configurate.ConfigurationNode.setValue(ConfigurationNode.java:402) ~[spongeforge-1.10.2-2477-5.2.0-BETA-2731.jar:1.10.2-2477-5.2.0-BETA-2731]
        at com.goldensandsmc.tieredkits.sponge.TieredKits.saveConfig(TieredKits.java:116) ~[TieredKits.class:?]
        at com.goldensandsmc.tieredkits.sponge.commands.EditKitCommand.execute(EditKitCommand.java:215) ~[EditKitCommand.class:?]
        at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:359) ~[CommandSpec.class:1.10.2-2477-5.2.0-BETA-2731]
        at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:336) ~[SimpleDispatcher.class:1.10.2-2477-5.2.0-BETA-2731]
        at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:291) ~[SpongeCommandManager.class:1.10.2-2477-5.2.0-BETA-2731]
        at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083) ~[bd.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:913) ~[me.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:892) ~[me.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) ~[im.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) ~[im.class:?]
        at org.spongepowered.common.network.PacketUtil.lambda$onProcessPacket$0(PacketUtil.java:157) ~[PacketUtil.class:1.10.2-2477-5.2.0-BETA-2731]
        at org.spongepowered.common.event.tracking.CauseTracker.switchToPhase(CauseTracker.java:163) [CauseTracker.class:1.10.2-2477-5.2.0-BETA-2731]
        at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:156) [PacketUtil.class:1.10.2-2477-5.2.0-BETA-2731]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjj000(SourceFile:539) [fl$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_152]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_152]
        at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:239) [SpongeImplHooks.class:1.10.2-2477-5.2.0-BETA-2731]
        at net.minecraft.server.MinecraftServer.redirect$onRun$zhp000(MinecraftServer.java:3948) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
```

**Comment by clienthax** [comment]
Why aren't you just using ItemStackSnapshot?

**Comment by gabizou** [comment]
> contain arrays in their NBT data, which is not supported by default.

DataContainers always support arrays, what makes you think it's not supporting arrays? Do you have some sort of debugging screenshot to show us where the problem is about to happen?

**Comment by ShortCircuit908** [comment]
> DataContainers always support arrays, what makes you think it's not supporting arrays?

The container itself supports the array, but the Configurate serializers do not accept array types by default

The issue is that I registered serializers necessary for arrays, but they are not being used from within `org.spongepowered.common.config.DataSerializableTypeSerializer`

**Comment by gabizou** [comment]
Maybe we should provide support in Configurate core? @kashike @zml2008 ?

**Comment by ImMorpheus** [comment]
This sounds like https://github.com/SpongePowered/SpongeCommon/issues/1334

So something that should be handled by https://github.com/SpongePowered/configurate/issues/95

**Comment by ryantheleach** [comment]
@ImMorpheus That would solve the issue they are having, but what about the expected behavior of the work around?

@dualspiral @ImMorpheus 
Is 

"However, through testing I have found that org.spongepowered.common.config.DataSerializableTypeSerializer does NOT use the parent options' serializers, and therefore does not recognize the array serializers."

Works as Intended as far as Configurate goes?

**Edit:** Additionally, is this still how it works on 1.12

**Comment by Zidane** [comment]
1.10 is a version that has not been supported for a long time.
