### ISSUE TITLE
TimingHistory assumes EntityType is an instance of SpongeEntityType

### ISSUE THREAD

**Issue by clienthax** [SpongePowered/Sponge#1828]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2611-7.1.0-BETA-2937
- SpongeVanilla version: 
- Java version: 1.8
- Operating System: N/A

- Plugins/Mods: N/A

**Issue Description**
I have a custom EntityType named PixelmonType which extends EntityType (mixined using the enum and cataloged up), all is well until timings run.

```
[23:35:01] [Server thread/INFO] [STDOUT]: [moe.clienthax.tests.commands.PartyTestCommand:execute:29]: Mudkip
[23:35:41] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.ClassCastException: com.pixelmonmod.pixelmon.enums.EnumPokemon cannot be cast to org.spongepowered.common.entity.SpongeEntityType
        at co.aikar.timings.TimingHistory.lambda$null$1(TimingHistory.java:128) ~[TimingHistory.class:1.12.2-2611-7.1.0-BETA-2937]
        at co.aikar.util.JSONUtil.mapArrayToObject(JSONUtil.java:109) ~[JSONUtil.class:1.12.2-2611-7.1.0-BETA-2937]
        at co.aikar.timings.TimingHistory.lambda$null$3(TimingHistory.java:123) ~[TimingHistory.class:1.12.2-2611-7.1.0-BETA-2937]
        at co.aikar.util.JSONUtil.mapArray(JSONUtil.java:94) ~[JSONUtil.class:1.12.2-2611-7.1.0-BETA-2937]
        at co.aikar.timings.TimingHistory.lambda$new$4(TimingHistory.java:101) ~[TimingHistory.class:1.12.2-2611-7.1.0-BETA-2937]
        at co.aikar.util.JSONUtil.mapArrayToObject(JSONUtil.java:109) ~[JSONUtil.class:1.12.2-2611-7.1.0-BETA-2937]
        at co.aikar.timings.TimingHistory.<init>(TimingHistory.java:100) ~[TimingHistory.class:1.12.2-2611-7.1.0-BETA-2937]
        at co.aikar.timings.FullServerTickHandler.stopTiming(FullServerTickHandler.java:101) ~[FullServerTickHandler.class:1.12.2-2611-7.1.0-BETA-2937]
        at net.minecraft.server.MinecraftServer.handler$onServerTickEnd$zjf000(MinecraftServer.java:3870) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:711) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_152]
```

**Comment by kashike** [comment]
https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/co/aikar/timings/TimingsExport.java#L167
https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/co/aikar/timings/TimingHistory.java#L128

Timings really needs to stop needing int ids and start using namespaced keys.
