### ISSUE TITLE
Firework effects NoSuchElement

### ISSUE THREAD

**Issue by XakepSDK** [SpongePowered/Sponge#1853]
`firework.getFireworkData()` / `firework.effects()` throws `NoSuchElementException`.
`firework.getOrCreate(FireworkEffectData.class).get();`
Returns `FireworkEffectData`, offering back returns this:
```
DataTransactionResult{resultType=SUCCESS, rejectedData=[], replacedData=[], successfulData=[ImmutableSpongeListValue{key=SpongeKey{name=Firework Effects, id=sponge:firework_effects, valueToken=org.spongepowered.api.data.value.mutable.ListValue<org.spongepowered.api.item.FireworkEffect>, elementToken=java.util.List<org.spongepowered.api.item.FireworkEffect>, query=FireworkEffects}, defaultValue=[], actualValue=[]}]}

```

Tested on: `spongevanilla-1.12.2-7.1.0-BETA-33`

**Comment by XakepSDK** [comment]
`FireworkRocketData` not present too.

**Comment by XakepSDK** [comment]
Fireworks completely broken
```java
Firework fwEntity = (Firework) player.getLocation().createEntity(EntityTypes.FIREWORK);
FireworkEffectData fireworkData = fwEntity.getOrCreate(FireworkEffectData.class).get();
FireworkEffect effect = FireworkEffect.builder()
        .colors(Color.BLACK, Color.RED, Color.GRAY)
        .fades(Color.YELLOW, Color.WHITE, Color.LIME)
        .shape(FireworkShapes.STAR)
        .trail(true)
        .flicker(true)
        .build();
fireworkData.effects().set(Collections.singletonList(effect));
fwEntity.offer(fireworkData);
FireworkRocketData rocketData = fwEntity.getOrCreate(FireworkRocketData.class).get();
rocketData.flightModifier().set(1);
fwEntity.offer(rocketData);
player.getLocation().spawnEntity(fwEntity);
```
This code just launches firework, no effects applied. If i don't create `FireworkRocketData`, just little sparks at my legs appears.

**Comment by Aaron1011** [comment]
@XakepSDK: This seems to be a problem with how you're using the Data API

Calling `fireworkData.effects()` gives you back a completely fresh value, which isn't linked to the `FireworkEffectData`. To actually apply it, you'd need to `offer` back the value you called `set` on.

Alternatively, you can call `fireworkData.set(Keys.FIREWORK_EFFECTS, Collections.singletonList(effect))`

**Comment by XakepSDK** [comment]
> `firework.getFireworkData()` / `firework.effects()` throws `NoSuchElementException`.
  
Also, it shouldn't return fresh value, it should return current value, but because there is no current value - it throws this exception. 

I tried to do this in your way. It has same problems.

**Comment by Aaron1011** [comment]
Are you running the latest SpongeVanilla? It was recently updated to the latest SpongeCommon changes.

**Comment by XakepSDK** [comment]
Beta-33 was latest at test time. I'll try it later.

**Comment by XakepSDK** [comment]
beta 41
```
[02:06:08 ERROR] [Sponge]: Could not pass MessageChannelEvent$Chat$Impl to Plugin{id=spongetests, name=spongetests, source=/media/data/Development/IdeaProjects/spongetests/build/classes/java/main}
java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135) ~[?:1.8.0_162]
	at org.spongepowered.api.entity.projectile.Firework.effects(Firework.java:57) ~[Firework.class:1.12.2-7.1.0-BETA-41]
	at dk.xakeps.spongetests.SpongeTests.a(SpongeTests.java:22) ~[SpongeTests.class:?]
	at org.spongepowered.common.event.listener.ChatListener_SpongeTests_a3.handle(Unknown Source) ~[?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-7.1.0-BETA-41]
	at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:417) [SpongeEventManager.class:1.12.2-7.1.0-BETA-41]
	at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:444) [SpongeEventManager.class:1.12.2-7.1.0-BETA-41]
	at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:436) [SpongeEventManager.class:1.12.2-7.1.0-BETA-41]
	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:207) [SpongeImpl.class:1.12.2-7.1.0-BETA-41]
	at net.minecraft.network.NetHandlerPlayServer.handler$onProcessChatMessage$zpm000(SourceFile:2522) [pa.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(SourceFile:845) [pa.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
	at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:149) [PacketUtil.class:1.12.2-7.1.0-BETA-41]
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zkn000(SourceFile:539) [hv$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_162]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_162]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:277) [SpongeImplHooks.class:1.12.2-7.1.0-BETA-41]
	at net.minecraft.server.MinecraftServer.redirect$onRun$zjc000(SourceFile:4149) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(SourceFile:1580) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(SourceFile:349) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(SourceFile:560) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(SourceFile:464) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
```
This happens with `createEntity` and `createEntityNaturally`.
Test code:
```java
package dk.xakeps.spongetests;

import org.spongepowered.api.entity.EntityTypes;
import org.spongepowered.api.entity.living.player.Player;
import org.spongepowered.api.entity.projectile.Firework;
import org.spongepowered.api.event.Listener;
import org.spongepowered.api.event.filter.cause.Root;
import org.spongepowered.api.event.message.MessageChannelEvent;
import org.spongepowered.api.plugin.Plugin;
import org.spongepowered.api.scoreboard.Scoreboard;
import org.spongepowered.api.scoreboard.Team;
import org.spongepowered.api.text.Text;

@Plugin(id = "spongetests")
public class SpongeTests {

    @Listener
    public void a(MessageChannelEvent.Chat event, @Root Player player) {
        if (event.getRawMessage().toPlain().startsWith("f")) {
            Firework firework = (Firework) player.getWorld().createEntityNaturally(EntityTypes.FIREWORK, player.getPosition());
            System.out.println(firework.effects());
            System.out.println(firework.getFireworkData());
        } else if (event.getRawMessage().toPlain().startsWith("t")) {
            Team team = Team.builder()
                    .name("12345678901234567")
                    .displayName(Text.of("12345678901234567890123456789012"))
                    .build();
            Scoreboard scoreboard = Scoreboard.builder().build();
            scoreboard.registerTeam(team);
            player.setScoreboard(scoreboard);
        }
    }
}

```

**Comment by Aaron1011** [comment]
It appears that the implementation currently makes a distinction between a firework that has an empty list of effects (an empty `Explosions` NBT tag), and a firework with no `Explosion` tag at all. A newly created firework falls into the second case, which is why the getter method is throwing an exception.

@gabizou: Is this a meaningful distinction to maintain, or should we treat firewoks as always having `FireworkEffectData` set?

**Comment by gabizou** [comment]
We should treat the distinction to where if data is requested, we should create it. Only on application will it really set either an empty compound, or set an actual compound.

**Comment by XakepSDK** [comment]
Fireworks doesn't contain RocketData too, also, if i fill these(fireworkdata + rocketdata) data
manually, nothing happens. Like there is no data.

**Comment by randombyte-developer** [comment]
`1.12.2-7.1.0-BETA-98`

As xakep reported, the fireworks particle builder doesn't do anything, no color, no shape, no flicker is applied.

**Comment by XakepSDK** [comment]
@Zidane i think, this can be closed?

**Comment by randombyte-developer** [comment]
When was this fixed?

**Comment by XakepSDK** [comment]
https://github.com/SpongePowered/SpongeCommon/commit/75f2f1fec0171ca6a559a753b8e5541c6b2acd14, i haven't tested this.

**Comment by ryantheleach** [comment]
Assuming fixed for now, based on issue feedback. Happy to reopen should it not be fixed.
