### ISSUE TITLE
Data ID must be formatted incorrectly

### ISSUE THREAD

**Issue by mosemister** [SpongePowered/Sponge#1854]
Running:
1.12.2-7.1.0-BETA-33 (Currently latest recommended)
- Java version: 
jre1.8.0_162
- Operating System:
Windows 10

- Plugins/Mods:
 1 Mod I am working on

**Issue Description**

While creating the Data half of my custom plugin I followed the CookBook:MyHomes example ( https://github.com/SpongePowered/Cookbook/blob/master/Plugin/MyHomes/src/main/java/org/spongepowered/cookbook/myhomes/MyHomes.java ) exactly. When it came to test my plugin it came up with this error
`[21:29:29 ERROR] [Sponge]: Could not pass SpongeGameRegistryRegisterEvent to Plugin{id=entitydisguiseplugin, name=Entity DisguiseSettings, version=SNAPSHOT-01, description=DisguiseSettings into any mob, source=mods\EntityDisguise-1.0-SNAPSHOT.jar}
java.lang.IllegalArgumentException: Data ID must be formatted correctly!
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[minecraft_server.1.12.2.jar:?]
        at org.spongepowered.common.data.SpongeDataRegistrationBuilder.manipulatorId(SpongeDataRegistrationBuilder.java:77) ~[SpongeDataRegistrationBuilder.class:1.12.2-7.1.0-BETA-33]
        at org.spongepowered.common.data.SpongeDataRegistrationBuilder.manipulatorId(SpongeDataRegistrationBuilder.java:45) ~[SpongeDataRegistrationBuilder.class:1.12.2-7.1.0-BETA-33]
        at org.entitydisguise.entitydisguiseplugin.EntityDisguisePlugin.onDataRegistration(EntityDisguisePlugin.java:88) ~[EntityDisguisePlugin.class:?]
        at org.spongepowered.common.event.listener.RegisterListener_EntityDisguisePlugin_onDataRegistration3.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-7.1.0-BETA-33]
        at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:408) [SpongeEventManager.class:1.12.2-7.1.0-BETA-33]
        at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:435) [SpongeEventManager.class:1.12.2-7.1.0-BETA-33]
        at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:427) [SpongeEventManager.class:1.12.2-7.1.0-BETA-33]
        at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:207) [SpongeImpl.class:1.12.2-7.1.0-BETA-33]
        at org.spongepowered.common.registry.SpongeGameRegistry.throwRegistryEvent(SpongeGameRegistry.java:608) [SpongeGameRegistry.class:1.12.2-7.1.0-BETA-33]
        at org.spongepowered.common.registry.SpongeGameRegistry.registerModulePhase(SpongeGameRegistry.java:534) [SpongeGameRegistry.class:1.12.2-7.1.0-BETA-33]
        at org.spongepowered.common.registry.SpongeGameRegistry.init(SpongeGameRegistry.java:563) [SpongeGameRegistry.class:1.12.2-7.1.0-BETA-33]
        at org.spongepowered.server.SpongeVanilla.initialize(SpongeVanilla.java:136) [SpongeVanilla.class:1.12.2-7.1.0-BETA-33]
        at net.minecraft.server.dedicated.DedicatedServer.handler$onServerInitialize$zpp000(SourceFile:1243) [nz.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(SourceFile:191) [nz.class:?]
        at net.minecraft.server.MinecraftServer.run(SourceFile:434) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_162]`

So I double checked my formatting, and it was fine, here is the example I used
    
    'entitydisguiseplugin:entity_settings'

So I went to check the SpongeCommon code on the error line it was specifying, line 77 on this class ( https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/data/SpongeDataRegistrationBuilder.java )

After changing my ID's onDataReg event to not include the ':', sponge managed to get passed that part but failed on another part.

**Comment by XakepSDK** [comment]
> but failed on another part
What part?

**Comment by mosemister** [comment]
Sorry, didnt think that part was important. This is the crash report if the ':' is not included.

edit: removed raw error in code form to Gist: https://gist.github.com/mosemister/c22f48ec8df58d6fe6acf1afe8748390

**Comment by XakepSDK** [comment]
``` 
Your error is completely unreadable.
Use gist, pastebin or triple ` at start and end of error, instean of single `.
```

**Comment by mosemister** [comment]
Sorry, Here is the Gist.github version of the same error.
https://gist.github.com/mosemister/c22f48ec8df58d6fe6acf1afe8748390

**Comment by XakepSDK** [comment]
`ManipulatorBuilder cannot be null!`
You must create and set your manipulator builder. Also, cookbook is very old, use this as example: https://github.com/pie-flavor/ExampleDataPlugin/

**Comment by mosemister** [comment]
I realise the ManipulatorBuilder could not be null, I can read. 

Thanks for the example, I saw commits on CookBook saying API 7, so I didn't think it was that out of date. What I was doing wrong was that I had the ManipulatorId as the full ID aka
'entitydisguise:something'
and I didn't realise your supposed to chop of the pluginid on the manipulatorid.
