### ISSUE TITLE
Add team name length check

### ISSUE THREAD

**Issue by XakepSDK** [SpongePowered/Sponge#1857]
Currently minecraft team impl. thrown exception about team name length.
Exception says about `display name`, this can be confusing.
Add name length check in builder. [here](https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/scoreboard/builder/SpongeTeamBuilder.java#L64)
Max name length is 32 chars.

**Comment by kashike** [comment]
Stacktrace?

I'm not sure where you got `32` from, but the maximum length of a team name is `16`.

**Comment by XakepSDK** [comment]
I got this error somewhere from TeamScorePlayer.class or similar. I'll give stacktrace bit later.

**Comment by parlough** [comment]
@XakepSDK Any update on that front?

**Comment by XakepSDK** [comment]
I'll add stacktrace tomorrow.

**Comment by XakepSDK** [comment]
```
[02:01:19 ERROR] [Sponge]: Could not pass MessageChannelEvent$Chat$Impl to Plugin{id=spongetests, name=spongetests, source=/media/data/Development/IdeaProjects/spongetests/build/classes/java/main}
java.lang.IllegalArgumentException: Display name is 33 characters long! It must be at most 32.
	at net.minecraft.scoreboard.ScorePlayerTeam.setDisplayName(SourceFile:610) ~[bhh.class:?]
	at org.spongepowered.common.scoreboard.builder.SpongeTeamBuilder.build(SpongeTeamBuilder.java:170) ~[SpongeTeamBuilder.class:1.12.2-7.1.0-BETA-41]
	at dk.xakeps.spongetests.SpongeTests.a(SpongeTests.java:28) ~[SpongeTests.class:?]
	at org.spongepowered.common.event.listener.ChatListener_SpongeTests_a3.handle(Unknown Source) ~[?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-7.1.0-BETA-41]
	at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:417) [SpongeEventManager.class:1.12.2-7.1.0-BETA-41]
	at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:444) [SpongeEventManager.class:1.12.2-7.1.0-BETA-41]
	at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:436) [SpongeEventManager.class:1.12.2-7.1.0-BETA-41]
	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:207) [SpongeImpl.class:1.12.2-7.1.0-BETA-41]
	at net.minecraft.network.NetHandlerPlayServer.handler$onProcessChatMessage$zpm000(SourceFile:2522) [pa.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(SourceFile:845) [pa.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
	at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:149) [PacketUtil.class:1.12.2-7.1.0-BETA-41]
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zkn000(SourceFile:539) [hv$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_162]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_162]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:277) [SpongeImplHooks.class:1.12.2-7.1.0-BETA-41]
	at net.minecraft.server.MinecraftServer.redirect$onRun$zjc000(SourceFile:4149) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(SourceFile:1580) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(SourceFile:349) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(SourceFile:560) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(SourceFile:464) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
```
`name` max lenght is 16 chars, player will be kicked with error, if name > 16 chars.
https://puu.sh/AakfY/bb0592070c.png
There is no stacktrace at server.
Test code:
```java
package dk.xakeps.spongetests;

import org.spongepowered.api.entity.EntityTypes;
import org.spongepowered.api.entity.living.player.Player;
import org.spongepowered.api.entity.projectile.Firework;
import org.spongepowered.api.event.Listener;
import org.spongepowered.api.event.filter.cause.Root;
import org.spongepowered.api.event.message.MessageChannelEvent;
import org.spongepowered.api.plugin.Plugin;
import org.spongepowered.api.scoreboard.Scoreboard;
import org.spongepowered.api.scoreboard.Team;
import org.spongepowered.api.text.Text;

@Plugin(id = "spongetests")
public class SpongeTests {

    @Listener
    public void a(MessageChannelEvent.Chat event, @Root Player player) {
        if (event.getRawMessage().toPlain().startsWith("f")) {
            Firework firework = (Firework) player.getWorld().createEntityNaturally(EntityTypes.FIREWORK, player.getPosition());
            System.out.println(firework.effects());
            System.out.println(firework.getFireworkData());
        } else if (event.getRawMessage().toPlain().startsWith("t")) {
            Team team = Team.builder()
                    .name("12345678901234567")
                    .displayName(Text.of("12345678901234567890123456789012"))
                    .build();
            Scoreboard scoreboard = Scoreboard.builder().build();
            scoreboard.registerTeam(team);
            player.setScoreboard(scoreboard);
        }
    }
}
```

**Comment by XakepSDK** [comment]
Fix labels

**Comment by XakepSDK** [comment]
Is this fixed?

**Comment by ImMorpheus** [comment]
From the wiki: `name must be at most 16 characters. display name must be at most 32 characters. `

Fixed by https://github.com/SpongePowered/SpongeCommon/commit/92c5aad6fbfad1fc20da6fb4516efd321d8257e4
