### ISSUE TITLE
SOE breaking a door

### ISSUE THREAD

**Issue by kashike** [SpongePowered/Sponge#1873]
via @Inscrutable
`spongeforge-1.12.2-2655-7.1.0-BETA-3024`
```
[09:09:34] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:771) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.StackOverflowError
	at net.minecraft.entity.ai.EntityAIBreakDoor.redirect$spongeShouldExecuteForGriefer$zen000(EntityAIBreakDoor.java:559) ~[wu.class:?]
	at net.minecraft.entity.ai.EntityAIBreakDoor.func_75250_a(EntityAIBreakDoor.java:20) ~[wu.class:?]
	at net.minecraft.entity.ai.EntityAIBreakDoor.redirect$spongeShouldExecuteForGriefer$zen000(EntityAIBreakDoor.java:559) ~[wu.class:?]
	at net.minecraft.entity.ai.EntityAIBreakDoor.func_75250_a(EntityAIBreakDoor.java:20) ~[wu.class:?]
	at net.minecraft.entity.ai.EntityAIBreakDoor.redirect$spongeShouldExecuteForGriefer$zen000(EntityAIBreakDoor.java:559) ~[wu.class:?]
	at net.minecraft.entity.ai.EntityAIBreakDoor.func_75250_a(EntityAIBreakDoor.java:20) ~[wu.class:?]
	at net.minecraft.entity.ai.EntityAIBreakDoor.redirect$spongeShouldExecuteForGriefer$zen000(EntityAIBreakDoor.java:559) ~[wu.class:?]
	at net.minecraft.entity.ai.EntityAIBreakDoor.func_75250_a(EntityAIBreakDoor.java:20) ~[wu.class:?]
	at net.minecraft.entity.ai.EntityAIBreakDoor.redirect$spongeShouldExecuteForGriefer$zen000(EntityAIBreakDoor.java:559) ~[wu.class:?]
	at net.minecraft.entity.ai.EntityAIBreakDoor.func_75250_a(EntityAIBreakDoor.java:20) ~[wu.class:?]
	at net.minecraft.entity.ai.EntityAIBreakDoor.redirect$spongeShouldExecuteForGriefer$zen000(EntityAIBreakDoor.java:559) ~[wu.class:?]
	at net.minecraft.entity.ai.EntityAIBreakDoor.func_75250_a(EntityAIBreakDoor.java:20) ~[wu.class:?]
	at net.minecraft.entity.ai.EntityAIBreakDoor.redirect$spongeShouldExecuteForGriefer$zen000(EntityAIBreakDoor.java:559) ~[wu.class:?]
	at net.minecraft.entity.ai.EntityAIBreakDoor.func_75250_a(EntityAIBreakDoor.java:20) ~[wu.class:?]
```

**Comment by ghost** [comment]
Same
