### ISSUE TITLE
NoSuchElementException thrown by Inventory#getProperty during inventory close event

### ISSUE THREAD

**Issue by caseif** [SpongePowered/Sponge#1875]
**I am currently running**
- SpongeForge version: 2990 (latest RB for stability purposes)

_Other environment information is irrelevant_

**Issue Description** `Inventory#getProperty` will sometimes throw a `NoSuchElementException` when called. I'm not sure of the exact circumstances (just grabbed it from a log file), but it seems like it's happening when the inventory is a childless parent (not entirely familiar with Sponge's inventory implementation so not sure what this scenario means practically speaking).

Minified problem code:
```java
InteractInventoryEvent.Close event = ...;
Optional<Identifiable> idPropOpt = interest.getProperty(Identifiable.class, "uuid");
// NoSuchElementException thrown
```

Minified stack trace:
```
[22:15:06] [Server thread/ERROR] [Sponge]: Could not pass InteractInventoryEvent$Close$Impl to Plugin{id=redacted, name=redacted, version=3.0.0-SNAPSHOT, source=redacted.jar}
java.util.NoSuchElementException: null
	at com.google.common.collect.Iterators$1.next(Iterators.java:81) ~[minecraft_server.1.12.2.jar:?]
	at org.spongepowered.common.item.inventory.adapter.impl.AdapterLogic.inventoryRoot(AdapterLogic.java:300) ~[AdapterLogic.class:1.12.2-2611-7.1.0-BETA-2990]
	at org.spongepowered.common.item.inventory.adapter.impl.AdapterLogic.getRootProperty(AdapterLogic.java:276) ~[AdapterLogic.class:1.12.2-2611-7.1.0-BETA-2990]
	at org.spongepowered.common.item.inventory.adapter.impl.MinecraftInventoryAdapter.getProperty(MinecraftInventoryAdapter.java:175) ~[MinecraftInventoryAdapter.class:1.12.2-2611-7.1.0-BETA-2990]
	at redacted.onCloseInventory(redacted.java:99) ~[redacted.class:3.0.0-SNAPSHOT]
```

[Problem line in SpongeCommon for convenience](https://github.com/SpongePowered/SpongeCommon/blob/ccbd879e979c6163b42ceaf54ea892a81e726f91/src/main/java/org/spongepowered/common/item/inventory/adapter/impl/AdapterLogic.java#L300)

**Comment by Faithcaio** [comment]
Very weird. It would be good to know what Container was opened there.

**Comment by caseif** [comment]
I encountered it personally yesterday when opening a Pixelmon PC, but didn't look too deep into it. (Obviously, this is a little problematic in that it's from a 3rd-party mod.) Perhaps it doesn't adhere exactly to the model Sponge expects?

**Comment by hsyyid** [comment]
Related: #2045

**Comment by Faithcaio** [comment]
https://github.com/SpongePowered/SpongeCommon/compare/7702de741c87...e7d7978abd03
