### ISSUE TITLE
Slot's id is not consistant

### ISSUE THREAD

**Issue by NeumimTo** [SpongePowered/Sponge#1912]
**I am currently running**

- SpongeVanilla version: 1.12.2-7.1.0-BETA-42
- Java version: 1.8
- Operating System: ubuntu 17

I want to be able to identify any slot from player inventory by its id.
In a nutshell: i want to create "special slots" in player's inventory. These slots will accept only specific type of items/specific items with metadata etc.. 
eg.:
In vanilla mc - i want to cancell any slottransaction which occurs in the first top-left slot.
With baubles mod - i want to cancell any slottransaction which occurs in specific slot from baubles mod.
These slots are configurable via slotId. 
What i was expecting: 
 - `getInventoryProperty(SlotIndex.class)` will always return a same id.

What is actually happening:
- The slotId shifts depending on opened container

Use the listener below. 
 - Open player inventory and click with item in any slot
 - Open a chest click into the same slot again
You will get two different ids. 

```
         @Listener(order = Order.FIRST)
	 public void onClick(ClickInventoryEvent event, @Root Player player) {
		List<SlotTransaction> transactions = event.getTransactions();
		for (SlotTransaction transaction : transactions) {
			Optional<SlotIndex> inventoryProperty = transaction.getSlot().getInventoryProperty(SlotIndex.class);
			inventoryProperty.ifPresent(slotIndex -> player.sendMessage(Text.of("[Debug] Clicked slot index:" + slotIndex.getValue())));
		}
		
	}
```

Is this intended or is this a bug?
Is there another way how can i uniquely identity specific inventory slot, a value which wont shift when a player opens a chest/hopper/any other container?

**Comment by Faithcaio** [comment]
Inventory Properties like SlotIndex are always based on the parent inventory.
As the size of the Container changes you'll obiously get a different slot id.

You can query a SubInventory like MainPlayerInventory and go from there.

Keep in mind that Slots you get from an opened Container belong directly to the Container and not to the subinventories.
`Slot#transform` returns the slot in the viewed inventory.

**Comment by NeumimTo** [comment]
@Faithcaio What do you mean with the term "viewed inventory"? 

So `slot.transform.getslotid ` always return same slot id relevant to the parent inventory (eg.: transformed top left slot in MainPlayerInventory will always have id 0, no matter if the player has opened a chest?

Also I would like to know if a container which has the clicked slot comes from a mod (and mod's id/name/whatever), or if it is actually vanilla container such as MainPlayerInventory. 
Is that possible?

**Comment by Faithcaio** [comment]
In MC when you open an Inventory you always get a Container.
That Container is a view onto the opened inventory and usually a part of the player inventory (MainPlayerInventory) 

Yes the topleft slot in a MainPlayerInventory has SlotIndex 0.
It doesnt matter whether the inventory is open or not what matters is that the parent of the slot is the same.
Keep in mind that a query for SlotIndex will check for all hierachies below.
Grids, Rows, Columns all have their own SlotIndex 0.
That ofc. does not apply to getInventoryProperty because it only checks in relation to the parent.

MainPlayerInventory is not a Vanilla Inventory in fact its not a real Inventory.
Sponge just provides that inventory ( main player grid + hotbar ) as a view onto the real inventory.
Which could be either the PlayerInventory or a Container.

I don't think we have a straigthforward way of checking where a Container comes from.
You could check its class.

**Comment by NeumimTo** [comment]
Tested the getClass and it should be enough for what i need. 
but im not sure how i am supposed to get slot index from transformed slot  `transaction.getSlot().transform().getInventoryProperty(SlotIndex.class);` returns an empty optional.
Same result if i try to use SlotPos instead.

**Comment by Faithcaio** [comment]
My bad. Should work with my latest commit now.
The transformed Slot was not reusing existing Lenses when possible.

SlotPos not working is to be expected. 
SlotPos only applies to grids and the PlayerInventory (the parent of the slot) is not a Grid.

**Comment by NeumimTo** [comment]
Thanks but i found some issues using latest build

It seems like you accidentally broke something related to `player#openInventory(Inventory)`

```
 org.spongepowered.common.item.inventory.lens.impl.comp.GridInventoryLensImpl cannot be cast to org.spongepowered.common.item.inventory.lens.slots.SlotLens
java.lang.ClassCastException: org.spongepowered.common.item.inventory.lens.impl.comp.GridInventoryLensImpl cannot be cast to org.spongepowered.common.item.inventory.lens.slots.SlotLens
        at net.minecraft.inventory.Slot.handler$onConstructed$zih004(Slot.java:1067) ~[agr.class:?]
        at net.minecraft.inventory.Slot.<init>(Slot.java:23) ~[agr.class:?]
        at net.minecraft.inventory.ContainerChest.<init>(SourceFile:20) ~[afv.class:?]
        at org.spongepowered.common.registry.type.item.InventoryArchetypeRegistryModule.lambda$registerDefaults$1(InventoryArchetypeRegistryModule.java:177) ~[InventoryArchetypeRegistryModule.class:1.12.2-2655-7.1.0-BETA-3075]
        at org.spongepowered.common.item.inventory.custom.CustomInventory.func_174876_a(CustomInventory.java:151) ~[CustomInventory.class:1.12.2-2655-7.1.0-BETA-3075]
        at net.minecraft.entity.player.EntityPlayerMP.func_71007_a(EntityPlayerMP.java:899) ~[oq.class:?]
        at org.spongepowered.common.event.SpongeCommonEventFactory.displayContainer(SpongeCommonEventFactory.java:1095) ~[SpongeCommonEventFactory.class:1.12.2-2655-7.1.0-BETA-3075]
        at net.minecraft.entity.player.EntityPlayerMP.openInventory(EntityPlayerMP.java:4202) ~[oq.class:?]
        at cz.neumimto.rpg.gui.VanillaMessaging.displayCommonMenu(VanillaMessaging.java:399) ~[VanillaMessaging.class:1.0.11-SNAPSHOT]
        at cz.neumimto.rpg.gui.VanillaMessaging.sendListOfRaces(VanillaMessaging.java:382) ~[VanillaMessaging.class:1.0.11-SNAPSHOT]
        at cz.neumimto.rpg.gui.Gui.sendRaceList(Gui.java:136) ~[Gui.class:1.0.11-SNAPSHOT]
        at cz.neumimto.rpg.NtRpgPlugin.lambda$registerCharacterCommands$41(NtRpgPlugin.java:1256) ~[NtRpgPlugin.class:1.0.11-SNAPSHOT]
        at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:388) ~[CommandSpec.class:1.12.2-2655-7.1.0-BETA-3075]
        at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:341) ~[SimpleDispatcher.class:1.12.2-2655-7.1.0-BETA-3075]
        at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:328) [SpongeCommandManager.class:1.12.2-2655-7.1.0-BETA-3075]
        at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083) [dh.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:958) [pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:937) [pa.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
        at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:148) [PacketUtil.class:1.12.2-2655-7.1.0-BETA-3075]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zlb000(SourceFile:539) [hv$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_152]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_152]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:284) [SpongeImplHooks.class:1.12.2-2655-7.1.0-BETA-3075]
        at net.minecraft.server.MinecraftServer.redirect$onRun$zjg000(MinecraftServer.java:3975) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_152]
```

My code which caused this exception: 
https://github.com/NeumimTo/NT-RPG/blob/fix-inventory-system/Plugin/src/main/java/cz/neumimto/rpg/gui/VanillaMessaging.java#L399


I can now get SlotIdex from transformed slot but its acting a little weird. 

My code which i use to debug this: 


```
@Listener(order = Order.FIRST)
	public void onClick(ClickInventoryEvent event, @Root Player player) {
		List<SlotTransaction> transactions = event.getTransactions();
		for (SlotTransaction transaction : transactions) {
			Optional<SlotIndex> inventoryProperty = transaction.getSlot().transform().getInventoryProperty(SlotIndex.class);
			inventoryProperty.ifPresent(slotIndex -> player.sendMessage(TextHelper.parse("[Debug] ID:" + slotIndex.getValue()
					+ ", Container: " + transaction.getSlot().parent().getClass().getName())));
		}
	}
```

Scenario 1: 
I drop something from my hotbar by pressing Q key. inventory is not opened - It prints correct id which happens to be in range from 0-8 and the container class is HotbarAdapter from sponge package
Scenario 2:
I open inventory and interact with item in top left corner. It has id 9 and the class is  InventoryPlayer from nms package
Scenario 3: 
I switch myself to creative mode. then i put any helmet on. then leave the server and reconnect. 
The listener catches event ClickInventoryEvent.Creative 3 times in row. ID:39, Class: InventoryPlayer
Scenario 4: 
Again in creative with empty inventory i give myself items via /give command (the item is assigned to hotbar), then open inventory. The event is fired right after the inventory is opened. It has correct ID, class: InventoryPlayer. This works fine in survival mode.
Scenario 5: 
While in creative mode open inventory and move one item to another slot.  When you interact with the slot for the first time it prints correct id, when you place the item to another slot it prints the same id again. This works fine in survival mode.
Scenario 6: 
Open inventory and move items from player inventory/or player hotbar to the chest. 
Slot Id seems to be correct but class is always nms ContainerChest. 
For example if you interact with first hotbar slot (from left side) it prints exactly same value as if you interact with top-left slot in the chest.

**Comment by NeumimTo** [comment]
Tested 3076 build - the error which was happening during player#openInvenotry is fixed, but other problems are still present.

**Comment by NeumimTo** [comment]
@Faithcaio I encountered another problem with 3076 Build

I have installed Baubles mod - https://minecraft.curseforge.com/projects/baubles
When i try to open the baubles inventory i get this error:
```
[14:40:19] [Server thread/FATAL] [net.minecraft.server.MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException: Index: 0
        at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_152]
        at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_152]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:284) [SpongeImplHooks.class:1.12.2-2655-7.1.0-BETA-3076]
        at net.minecraft.server.MinecraftServer.redirect$onRun$zjg000(MinecraftServer.java:3975) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_152]
Caused by: java.lang.IndexOutOfBoundsException: Index: 0
        at java.util.Collections$EmptyList.get(Unknown Source) ~[?:1.8.0_152]
        at net.minecraft.inventory.Slot.handler$onConstructed$zih004(Slot.java:1067) ~[agr.class:?]
        at net.minecraft.inventory.Slot.<init>(Slot.java:23) ~[agr.class:?]
        at net.minecraftforge.items.SlotItemHandler.<init>(SlotItemHandler.java:38) ~[SlotItemHandler.class:?]
        at baubles.common.container.SlotBauble.<init>(SlotBauble.java:17) ~[SlotBauble.class:?]
        at baubles.common.container.ContainerPlayerExpanded.<init>(ContainerPlayerExpanded.java:80) ~[ContainerPlayerExpanded.class:?]
        at baubles.common.CommonProxy.getServerGuiElement(CommonProxy.java:22) ~[CommonProxy.class:?]
        at net.minecraftforge.fml.common.network.NetworkRegistry.redirect$setRemoteContainerPlugin$bag000(NetworkRegistry.java:547) ~[NetworkRegistry.class:?]
        at net.minecraftforge.fml.common.network.NetworkRegistry.getRemoteGuiContainer(NetworkRegistry.java:256) ~[NetworkRegistry.class:?]
        at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:88) ~[FMLNetworkHandler.class:?]
        at net.minecraft.entity.player.EntityPlayer.openGui(EntityPlayer.java:2550) ~[aed.class:?]
        at baubles.common.network.PacketOpenBaublesInventory$1.run(PacketOpenBaublesInventory.java:26) ~[PacketOpenBaublesInventory$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_152]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_152]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 7 more
```
It worked in the build 3074.

**Comment by Faithcaio** [comment]
I guess try again with the next one...

**Comment by Faithcaio** [comment]
> Scenario 2:
I open inventory and interact with item in top left corner. It has id 9 and the class is InventoryPlayer from nms package

Because Minecraft is weird like that in InventoryPlayer Hotbar is before the Grid.
Hotbar 0-8 Grid 9-35 Armor 36-39 OffHand 40
In all Containers the order is Viewed -> Grid -> Hotbar.
And in ContainerPlayer the armor slots are reversed as well.

> creative mode

is weird and proably broken :/

> Scenario 6:
Open inventory and move items from player inventory/or player hotbar to the chest.
Slot Id seems to be correct but class is always nms ContainerChest.
For example if you interact with first hotbar slot (from left side) it prints exactly same value as if you interact with top-left slot in the chest.

Slots in events from open Containers always have the Container as parent. Only after `Slot#transform` it the parent is the viewed inventory.

**Comment by NeumimTo** [comment]
Thanks for fast fix, unfortunately i cannot test it because ci did not build sponge forge

 I do not really care right now about the creative inventory issues, i just reported what i found, my current blocker is the scenario 6. 

>Slots in events from open Containers always have the Container as parent. Only after Slot#transform it the parent is the viewed inventory.

I'm already doing Slot#transform but still getting ContainerChest as the slot's parent inventory

**Comment by Faithcaio** [comment]
Your code above does not use transform.
> `+ ", Container: " + transaction.getSlot().parent().getClass().getName())));`

Also with if next build decides to deploy creative events should be a bit better.

**Comment by NeumimTo** [comment]
@Faithcaio I posted updated version later with transform. 
it got lost in the stacktraces :)
```
@Listener(order = Order.FIRST)
	public void onClick(ClickInventoryEvent event, @Root Player player) {
		List<SlotTransaction> transactions = event.getTransactions();
		for (SlotTransaction transaction : transactions) {
			Optional<SlotIndex> inventoryProperty = transaction.getSlot().transform().getInventoryProperty(SlotIndex.class);
			inventoryProperty.ifPresent(slotIndex -> player.sendMessage(TextHelper.parse("[Debug] ID:" + slotIndex.getValue()
					+ ", Container: " + transaction.getSlot().parent().getClass().getName())));
		}
	}
```

**Comment by Faithcaio** [comment]
^ still the same without transform ...

transaction.getSlot().parent()**.transform()**.getClass().getName())));

**Comment by NeumimTo** [comment]
Oh.. i'm an idiot :D sorry

**Comment by NeumimTo** [comment]
I tested stuff again. Almost everything seems to be fixed expect this one 

>Scenario 4:
Again in creative with empty inventory i give myself items via /give command (the item is assigned to hotbar), then open inventory. The event is fired right after the inventory is opened. It has correct ID, class: InventoryPlayer. This works fine in survival mode.
