### ISSUE TITLE
WorldProvider.getSaveFolder NPE

### ISSUE THREAD

**Issue by clienthax** [SpongePowered/Sponge#1944]
**I am currently running**

- SpongeForge version:  spongeforge-1.12.2-2705-7.1.0-BETA-3184.jar 
- Java version: 8
- Operating System: Docker / Ubuntu 18

- Plugins/Mods:  
```
Mods (206): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, /dank/null, Actually Additions, Actually Baubles, Akashic Tome, AppleSkin, Applied Energistics 2, ArchitectureCraft, Aroma1997's Dimensional World, Aroma1997Core, Astral Sorcery, AutoRegLib, B.A.S.E, BD Lib, Bad Wither No Cookie! Reloaded, Baubles, Bed Patch, Better Advancements, Better Builder's Wands, BiblioCraft, Binnie Core, Binnie's Botany, Binnie's Design, Binnie's Extra Bees, Binnie's Extra Trees, Binnie's Genetics, Blockcraftery, Blood Magic: Alchemical Wizardry, Bookshelf, Botania, Brandon's Core, Chameleon, Chest Transporter, Chisel, Chisels & Bits, Clumps, CoFH Core, CoFH World, CodeChicken Lib, Compact Machines 3, Compact Solar Arrays, Compacter, Construct's Armory, Cooking for Blockheads, CraftTweaker JEI Support, CraftTweaker2, Dark Utilities, DeepResonance, Diet Hopper, Dirt2Path, Draconic Evolution, ET Lunar, ElecCore, EluCore, EluLib, Embers, Ender IO, Ender IO Applied Energistics Conduits, Ender IO Base, Ender IO Conduits, Ender IO Integration with Forestry, Ender IO Integration with Tinkers' Construct, Ender IO Integration with Tinkers' Construct, Ender IO Machines, Ender IO Open Computers Conduits, Ender IO Powertools, Ender IO Refined Storage Conduits, EnderCore, EnderStorage, Engineer's Doors, Engineer's Workshop Reborn, Environmental Tech, Exchangers, Extra Cells 2, Extra Rails, Extra Utilities 2, Extreme Reactors, FTB Guides, FTB Utilities, FTBLib, FastWorkbench, Fence Jumper, Flat Colored Blocks, Flux Networks, FoamFix, FoamFixCore, Forestry, Forge Microblocks, Forge Multipart CBE, Gadgetry: Core, Gadgetry: Machines, GenDustry, Guide-API, Harvest, Immersive Engineering, Immersive Petroleum, Industrial Foregoing, Industrial Wires, IndustrialCraft 2, Inventory Tweaks, Iron Backpacks, Iron Chest, JEI Bees, JourneyMap, Just Enough Items, KleeSlabs, Long Fall Boots, MCMultiPart, MTLib, MagicBees, Mantle, McJtyLib, MineTogether, MineTogetherServer, Minecraft Multipart Plugin, Mod Tweaker, Morph-o-Tool, Morpheus, MrTJPCore, Natura, Nature's Compass, NetherPortalFix, Nice, Not Enough Wands, NotEnoughIDs, OpenBlocks, OpenComputers, OpenComputers (Core), OpenModsLib, OpenModsLib Core, Pam's HarvestCraft, Placebo, Platforms, ProjectRed Core, ProjectRed Exploration, ProjectRed Fabrication, ProjectRed Illumination, ProjectRed Transmission, ProjectRed integration, Quark, Quick Leaf Decay, RFTools, RFTools Control, RFToolsPower, Ranged Pumps, Reborn Core, Redstone Arsenal, Redstone Flux, Reliquary, Roots 2, Rustic, Secret Rooms 5, SecretRooms Hooks, ShadowMC, Shadowfacts' Forgelin, ShetiPhian-Core, Signals, SimpleVoidWorld, Simply Jetpacks 2, Snad, SonarCore, Soul Shards - The Old Ways, Steve's Carts 2, Storage Drawers, Storage Drawers Extras, TOP Addons, Tesla Core Lib, Tesla Core Lib Registries, Thaumcrafft Inventory Scanning, Thaumcraft, The Lost Cities, The One Probe, The Twilight Forest, Thermal Cultivation, Thermal Dynamics, Thermal Expansion, Thermal Foundation, Thermal Innovation, Thut Core, Thut's Tech, ThutCore Compat, Tinkers Tool Leveling, Tinkers' Construct, TorchMaster, Translocators, Traverse, UniDict, Universal Modifiers, Valkyrie Lib, WanionLib, Waystones, Wireless Crafting Terminal 2, XNet, Xtones, YABBA, Zero CORE, careerbees, p455w0rd's Library, projectred-expansion, projectred-relocation, projectred-transportation
```

**Issue Description**
Load up FTB Revelations
```
[03:38:09] [Server thread/INFO] [STDERR]: [org.spongepowered.common.world.WorldManager:getWorldFolder:1438]: java.lang.NullPointerException
[03:38:09] [Server thread/INFO] [STDERR]: [org.spongepowered.common.world.WorldManager:getWorldFolder:1438]: 	at mcjty.lostcities.dimensions.world.LostWorldProvider.getSaveFolder(LostWorldProvider.java:28)
[03:38:09] [Server thread/INFO] [STDERR]: [org.spongepowered.common.world.WorldManager:getWorldFolder:1438]: 	at org.spongepowered.common.world.WorldManager.getWorldFolder(WorldManager.java:1434)
[03:38:09] [Server thread/INFO] [STDERR]: [org.spongepowered.common.world.WorldManager:getWorldFolder:1438]: 	at org.spongepowered.common.world.WorldManager.loadAllWorlds(WorldManager.java:674)
[03:38:09] [Server thread/INFO] [STDERR]: [org.spongepowered.common.world.WorldManager:getWorldFolder:1438]: 	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:3541)
[03:38:09] [Server thread/INFO] [STDERR]: [org.spongepowered.common.world.WorldManager:getWorldFolder:1438]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:270)
[03:38:09] [Server thread/INFO] [STDERR]: [org.spongepowered.common.world.WorldManager:getWorldFolder:1438]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
[03:38:09] [Server thread/INFO] [STDERR]: [org.spongepowered.common.world.WorldManager:getWorldFolder:1438]: 	at java.lang.Thread.run(Thread.java:748)
```

https://github.com/McJtyMods/LostCities/blob/1.12/src/main/java/mcjty/lostcities/dimensions/world/LostWorldProvider.java#L28

https://github.com/McJtyMods/LostCities/issues/142

**Comment by gabizou** [comment]
Considering [WorldManager is relying on `DimensionType` to create the provider](https://github.com/SpongePowered/SpongeForge/blob/bleeding/src/main/java/org/spongepowered/mod/mixin/core/common/world/MixinWorldManager.java#L135), there's no reason to expect that the world provider is neither:
- Singular
- Initialized with a valid world reference with itself set yet

I don't think Sponge is really responsible for the issue, but it is responsible for exposing the issue. 

Ultimately I'll leave the decision to @Zidane to make.

**Comment by LemADEC** [comment]
Any update on this issue?

**Comment by ImMorpheus** [comment]
https://github.com/McJtyMods/LostCities/pull/183
