### ISSUE TITLE
Cannot construct BlockSnapshot without world and position

### ISSUE THREAD

**Issue by pie-flavor** [SpongePowered/Sponge#1960]
```java
BlockSnapshot snapshot = BlockSnapshot.builder()
        .blockState(BlockState.builder()
                .blockType(BlockTypes.COMMAND_BLOCK)
                .build())
        .build();
```

```
[20:19:10 ERROR] [Sponge]: Could not pass ClickInventoryEvent$Primary$Impl to Plugin{id=armorstandtools, name=flavor.pie.armorstandtools.ArmorStandTools, version=1.0-SNAPSHOT, description=Tools for manipulating armor stands., authors=[pie_flavor], source=mods\ArmorStandTools-1.0-SNAPSHOT.jar}
java.lang.NullPointerException: null
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770) ~[minecraft_server.1.12.2.jar:?]
        at org.spongepowered.common.block.SpongeBlockSnapshot.<init>(SpongeBlockSnapshot.java:114) ~[SpongeBlockSnapshot.class:1.12.2-7.1.0-BETA-74]
        at org.spongepowered.common.block.SpongeBlockSnapshotBuilder.build(SpongeBlockSnapshotBuilder.java:226) ~[SpongeBlockSnapshotBuilder.class:1.12.2-7.1.0-BETA-74]
        at org.spongepowered.common.block.SpongeBlockSnapshotBuilder.build(SpongeBlockSnapshotBuilder.java:66) ~[SpongeBlockSnapshotBuilder.class:1.12.2-7.1.0-BETA-74]
        at flavor.pie.armorstandtools.GuiListener.onClick(GuiListener.kt:137) ~[GuiListener.class:?]
        at org.spongepowered.common.event.listener.ClickInventoryEventListener_GuiListener_onClick13.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-7.1.0-BETA-74]
        at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:423) [SpongeEventManager.class:1.12.2-7.1.0-BETA-74]
        at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:459) [SpongeEventManager.class:1.12.2-7.1.0-BETA-74]
        at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:446) [SpongeEventManager.class:1.12.2-7.1.0-BETA-74]
        at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:217) [SpongeImpl.class:1.12.2-7.1.0-BETA-74]
        at org.spongepowered.common.event.tracking.phase.packet.BasicInventoryPacketState.unwind(BasicInventoryPacketState.java:205) [BasicInventoryPacketState.class:1.12.2-7.1.0-BETA-74]
        at org.spongepowered.common.event.tracking.phase.packet.BasicInventoryPacketState.unwind(BasicInventoryPacketState.java:58) [BasicInventoryPacketState.class:1.12.2-7.1.0-BETA-74]
        at org.spongepowered.common.event.tracking.PhaseTracker.completePhase(PhaseTracker.java:213) [PhaseTracker.class:1.12.2-7.1.0-BETA-74]
        at org.spongepowered.common.event.tracking.PhaseContext.close(PhaseContext.java:439) [PhaseContext.class:1.12.2-7.1.0-BETA-74]
        at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:150) [PacketUtil.class:1.12.2-7.1.0-BETA-74]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zkm000(SourceFile:539) [hv$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_144]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_144]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:288) [SpongeImplHooks.class:1.12.2-7.1.0-BETA-74]
        at net.minecraft.server.MinecraftServer.redirect$onRun$zjb000(SourceFile:4147) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(SourceFile:1581) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(SourceFile:349) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(SourceFile:560) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(SourceFile:464) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
```

**Comment by simon816** [comment]
This is intended. A block snapshot is a representation of a block in the world at some position (think of it as a clone of a `Location` object). Methods such as `restore()` can't work without a world and position.
