### ISSUE TITLE
EntityArchetype serialization broken

### ISSUE THREAD

**Issue by XakepSDK** [SpongePowered/Sponge#1964]
- SpongeVanilla version: spongevanilla-1.12.2-7.1.0-BETA-74

Test code:
```java
        StringWriter stringWriter = new StringWriter();
        YAMLConfigurationLoader build = YAMLConfigurationLoader.builder()
                .setSink(() -> new BufferedWriter(stringWriter))
                .setSource(() -> new BufferedReader(new StringReader("")))
                .build();
        ConfigurationNode load1 = build.load();
        load1.getNode("key").setValue(TypeToken.of(EntityArchetype.class), EntityArchetype.of(EntityTypes.VILLAGER));
        build.save(load1);
        BufferedReader reader = new BufferedReader(new StringReader(stringWriter.toString()));
        YAMLConfigurationLoader build2 = YAMLConfigurationLoader.builder()
                .setSink(() -> new BufferedWriter(new StringWriter()))
                .setSource(() -> reader)
                .build();
        ConfigurationNode load2 = build2.load();
        System.out.println(load2.getNode("key").getValue(TypeToken.of(EntityArchetype.class)));
        System.out.println("==================");
```
This error happens with any of config loader types.

**Comment by XakepSDK** [comment]
@gabizou

**Comment by XakepSDK** [comment]
Error:
```
Caused by: ninja.leaping.configurate.objectmapping.ObjectMappingException: Could not translate DataSerializable of type: org.spongepowered.api.entity.EntityArchetype
	at org.spongepowered.common.config.DataSerializableTypeSerializer.lambda$deserialize$0(DataSerializableTypeSerializer.java:51) ~[DataSerializableTypeSerializer.class:1.12.2-7.1.0-BETA-74]
	at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_172]
	at org.spongepowered.common.config.DataSerializableTypeSerializer.deserialize(DataSerializableTypeSerializer.java:51) ~[DataSerializableTypeSerializer.class:1.12.2-7.1.0-BETA-74]
	at org.spongepowered.common.config.DataSerializableTypeSerializer.deserialize(DataSerializableTypeSerializer.java:41) ~[DataSerializableTypeSerializer.class:1.12.2-7.1.0-BETA-74]
	at ninja.leaping.configurate.SimpleConfigurationNode.getValue(SimpleConfigurationNode.java:211) ~[spongevanilla-1.12.2-7.1.0-BETA-74.jar:1.12.2-7.1.0-BETA-74]
	at ninja.leaping.configurate.ConfigurationNode.getValue(ConfigurationNode.java:491) ~[spongevanilla-1.12.2-7.1.0-BETA-74.jar:1.12.2-7.1.0-BETA-74]
	at dk.xakeps.uniblocker.UniBlocker.<init>(UniBlocker.java:109) ~[UniBlocker.class:?]
	at dk.xakeps.uniblocker.UniBlocker$$FastClassByGuice$$1fa97bcd.newInstance(<generated>) ~[UniBlocker.class:?]
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89) ~[spongevanilla-1.12.2-7.1.0-BETA-74.jar:1.12.2-7.1.0-BETA-74]
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:111) ~[spongevanilla-1.12.2-7.1.0-BETA-74.jar:1.12.2-7.1.0-BETA-74]
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90) ~[spongevanilla-1.12.2-7.1.0-BETA-74.jar:1.12.2-7.1.0-BETA-74]
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268) ~[spongevanilla-1.12.2-7.1.0-BETA-74.jar:1.12.2-7.1.0-BETA-74]
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46) ~[spongevanilla-1.12.2-7.1.0-BETA-74.jar:1.12.2-7.1.0-BETA-74]
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092) ~[spongevanilla-1.12.2-7.1.0-BETA-74.jar:1.12.2-7.1.0-BETA-74]
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40) ~[spongevanilla-1.12.2-7.1.0-BETA-74.jar:1.12.2-7.1.0-BETA-74]
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194) ~[spongevanilla-1.12.2-7.1.0-BETA-74.jar:1.12.2-7.1.0-BETA-74]
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41) ~[spongevanilla-1.12.2-7.1.0-BETA-74.jar:1.12.2-7.1.0-BETA-74]
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:205) ~[spongevanilla-1.12.2-7.1.0-BETA-74.jar:1.12.2-7.1.0-BETA-74]
	at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:199) ~[spongevanilla-1.12.2-7.1.0-BETA-74.jar:1.12.2-7.1.0-BETA-74]
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085) ~[spongevanilla-1.12.2-7.1.0-BETA-74.jar:1.12.2-7.1.0-BETA-74]
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:199) ~[spongevanilla-1.12.2-7.1.0-BETA-74.jar:1.12.2-7.1.0-BETA-74]
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:180) ~[spongevanilla-1.12.2-7.1.0-BETA-74.jar:1.12.2-7.1.0-BETA-74]
	... 12 more
```

**Comment by XakepSDK** [comment]
`DataRegistrar` doesn't contain this: `dataManager.registerBuilder(EntityArchetype.class, new SpongeEntityArchetypeBuilder());`
