### ISSUE TITLE
Can't implement a custom BanService

### ISSUE THREAD

**Issue by supertassu** [SpongePowered/Sponge#1990]
**I am currently running**

- Minecraft: 1.12.2
- SpongeAPI: 7.1.0-SNAPSHOT-9cb5cb8c
- SpongeVanilla: 1.12.2-7.1.0-BETA-59

- Plugins/Mods: 
```
Plugins (8): Minecraft, Mod Coder Pack, SpongeAPI, SpongeVanilla,  FastAsyncWorldEdit, LuckPerms, Pumpkin (mod i'm working on), WorldEdit
```

**Issue Description**

I'm trying to implement a custom BanService, however SpongeCommon [assumes](https://github.com/SpongePowered/SpongeCommon/blob/2fc061810045369dbf1bae69f2fc3a972fe1cc49/src/main/java/org/spongepowered/common/service/ban/SpongeUserListBans.java#L58-L61) that `BanService#getBanFor(GameProfile)` returns a Minecraft ban (`UserListBansEntry`) instead of a custom one.

**Stack Trace**
```
[10:36:43 WARN]: Failed to handle packet for /1.2.3.4:5
java.lang.ClassCastException: me.tassu.myban.ban.MyBan$Uuid cannot be cast to net.minecraft.server.management.UserListBansEntry
        at org.spongepowered.common.service.ban.SpongeUserListBans.getEntry(SpongeUserListBans.java:60) ~[SpongeUserListBans.class:1.12.2-7.1.0-BETA-59]
        at org.spongepowered.common.service.ban.SpongeUserListBans.func_152683_b(SpongeUserListBans.java:43) ~[SpongeUserListBans.class:1.12.2-7.1.0-BETA-59]
        at net.minecraft.server.management.PlayerList.func_148542_a(SourceFile:377) ~[pl.class:?]
        at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(SourceFile:1274) ~[pl.class:?]
        at net.minecraft.server.management.PlayerList.func_72355_a(SourceFile:1211) ~[pl.class:?]
        at net.minecraft.server.network.NetHandlerLoginServer.func_147326_c(SourceFile:119) ~[pc.class:?]
        at net.minecraft.server.network.NetHandlerLoginServer.func_73660_a(SourceFile:66) ~[pc.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(SourceFile:231) ~[gw.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(SourceFile:187) [oz.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(SourceFile:1657) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(SourceFile:349) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(SourceFile:560) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(SourceFile:464) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
```

**SSCCE**
https://gist.github.com/supertassu/a4b6853f2a0dac30f237f312e439fd1d

**Comment by gabizou** [comment]
Because, you're not supposed to implement the Ban, use the [Ban.builder()](https://github.com/SpongePowered/SpongeAPI/blob/bleeding/src/main/java/org/spongepowered/api/util/ban/Ban.java#L50) to make a ban that you can then use in your service.

**Comment by ryantheleach** [comment]
@gabizou Is it worth somehow documenting the classes that are expected to be able to be extended by plugin classes?
