### ISSUE TITLE
ConstructEntityEvent.toString() throws NPE

### ISSUE THREAD

**Issue by Lignium** [SpongePowered/Sponge#2029]
**I am currently running**

- SpongeVanilla version: spongevanilla-1.12.2-7.1.0-BETA-93
- Java version: OpenJDK Version "1.8.0_171"
- Operating System: Linux Mint 18.3 Sylvia (Kernel: x86_64 Linux 4.13.0-45-generic)
- Plugins/Mods: Empty (Only one my experimental plugin)

**Issue Description**

My listener:
```
package net.lignium.spongeriment;

@Listener
public final void onConstructEntity(ConstructEntityEvent event) {
	Objects.requireNonNull(event, "event");
	
	System.out.println(event.getClass().getName());
	System.out.println(event.toString()); // Line 68
}
```

When a player connect to the server, NPE is thrown:

```
[22:11:36 INFO] [STDOUT]: org.spongepowered.api.event.ConstructEntityEvent$Post$Impl
[22:11:36 ERROR] [Sponge]: Could not pass ConstructEntityEvent$Post$Impl to Plugin{id=spongeriment, name=Spongeriment, version=1.0.0-SNAPSHOT, source=mods/spongeriment-1.0.0-SNAPSHOT.jar}
java.lang.NullPointerException: null
	at net.minecraft.entity.player.EntityPlayer.func_70005_c_(SourceFile:1804) ~[aed.class:?]
	at net.minecraft.entity.Entity.toString(SourceFile:2035) ~[vg.class:?]
	at java.lang.String.valueOf(String.java:2994) ~[?:1.8.0_171]
	at java.lang.StringBuilder.append(StringBuilder.java:131) ~[?:1.8.0_171]
	at org.spongepowered.api.event.ConstructEntityEvent$Post$Impl.toString(Unknown Source) ~[ConstructEntityEvent$Post$Impl.class:1.12.2-7.1.0-BETA-93]
	at net.lignium.spongeriment.Spongeriment.onConstructEntity(Spongeriment.java:68) ~[Spongeriment.class:?]
	at org.spongepowered.common.event.listener.ConstructEntityEventListener_Spongeriment_onConstructEntity15.handle(Unknown Source) ~[?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-7.1.0-BETA-93]
	at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:423) ~[SpongeEventManager.class:1.12.2-7.1.0-BETA-93]
	at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:459) ~[SpongeEventManager.class:1.12.2-7.1.0-BETA-93]
	at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:446) ~[SpongeEventManager.class:1.12.2-7.1.0-BETA-93]
	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:225) ~[SpongeImpl.class:1.12.2-7.1.0-BETA-93]
	at net.minecraft.entity.Entity.handler$onConstructed$zph000(SourceFile:5673) ~[vg.class:?]
	at net.minecraft.entity.Entity.<init>(SourceFile:213) ~[vg.class:?]
	at net.minecraft.entity.EntityLivingBase.<init>(SourceFile:171) ~[vp.class:?]
	at net.minecraft.entity.player.EntityPlayer.<init>(SourceFile:207) ~[aed.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.<init>(SourceFile:156) ~[oq.class:?]
	at net.minecraft.server.management.PlayerList.func_148545_a(SourceFile:434) ~[pl.class:?]
	at net.minecraft.server.network.NetHandlerLoginServer.func_147326_c(SourceFile:119) ~[pc.class:?]
	at net.minecraft.server.network.NetHandlerLoginServer.func_73660_a(SourceFile:66) ~[pc.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(SourceFile:231) ~[gw.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(SourceFile:187) ~[oz.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(SourceFile:1657) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(SourceFile:349) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(SourceFile:560) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(SourceFile:464) ~[MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
```

Remapped: (ryan)
```
[22:11:36 INFO] [STDOUT]: org.spongepowered.api.event.ConstructEntityEvent$Post$Impl
[22:11:36 ERROR] [Sponge]: Could not pass ConstructEntityEvent$Post$Impl to Plugin{id=spongeriment, name=Spongeriment, version=1.0.0-SNAPSHOT, source=mods/spongeriment-1.0.0-SNAPSHOT.jar}
java.lang.NullPointerException: null
	at net.minecraft.entity.player.EntityPlayer.getName(SourceFile:1804) ~[aed.class:?]
	at net.minecraft.entity.Entity.toString(SourceFile:2035) ~[vg.class:?]
	at java.lang.String.valueOf(String.java:2994) ~[?:1.8.0_171]
	at java.lang.StringBuilder.append(StringBuilder.java:131) ~[?:1.8.0_171]
	at org.spongepowered.api.event.ConstructEntityEvent$Post$Impl.toString(Unknown Source) ~[ConstructEntityEvent$Post$Impl.class:1.12.2-7.1.0-BETA-93]
	at net.lignium.spongeriment.Spongeriment.onConstructEntity(Spongeriment.java:68) ~[Spongeriment.class:?]
	at org.spongepowered.common.event.listener.ConstructEntityEventListener_Spongeriment_onConstructEntity15.handle(Unknown Source) ~[?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-7.1.0-BETA-93]
	at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:423) ~[SpongeEventManager.class:1.12.2-7.1.0-BETA-93]
	at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:459) ~[SpongeEventManager.class:1.12.2-7.1.0-BETA-93]
	at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:446) ~[SpongeEventManager.class:1.12.2-7.1.0-BETA-93]
	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:225) ~[SpongeImpl.class:1.12.2-7.1.0-BETA-93]
	at net.minecraft.entity.Entity.handler$onConstructed$zph000(SourceFile:5673) ~[vg.class:?]
	at net.minecraft.entity.Entity.<init>(SourceFile:213) ~[vg.class:?]
	at net.minecraft.entity.EntityLivingBase.<init>(SourceFile:171) ~[vp.class:?]
	at net.minecraft.entity.player.EntityPlayer.<init>(SourceFile:207) ~[aed.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.<init>(SourceFile:156) ~[oq.class:?]
	at net.minecraft.server.management.PlayerList.createPlayerForUser(SourceFile:434) ~[pl.class:?]
	at net.minecraft.server.network.NetHandlerLoginServer.tryAcceptPlayer(SourceFile:119) ~[pc.class:?]
	at net.minecraft.server.network.NetHandlerLoginServer.update(SourceFile:66) ~[pc.class:?]
	at net.minecraft.network.NetworkManager.processReceivedPackets(SourceFile:231) ~[gw.class:?]
	at net.minecraft.network.NetworkSystem.networkTick(SourceFile:187) ~[oz.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(SourceFile:1657) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(SourceFile:349) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.tick(SourceFile:560) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(SourceFile:464) ~[MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
```

**Comment by ryantheleach** [comment]
Proposed fix, have a null check in the to String, and use `name != null ? "\"" + name +"\"" : "null"` as a substitute for the name method.

But the chances of it being that simple with the event generator are slim.

It's likely a symptom of a larger problem, in that Player's (and maybe other entities) arn't fully constructed when this event is called.

Changing the order that stuff is initialized would probably be bad, maybe this event needs to be thrown later? Changing what player.name returns also seems like a hack.

I'm torn to whether this is even an issue, (considering it's a construct event, called extremely early on) But I'm open to being convinced otherwise.

**Comment by ImMorpheus** [comment]
> 	at net.lignium.spongeriment.Spongeriment.onConstructEntity(Spongeriment.java:68) ~[Spongeriment.class:?]

Did you forget to mention your `experimental plugin` is the one firing the event ?

Not able to reproduce (surprisingly) with SF (SC updated to https://github.com/SpongePowered/SpongeCommon/commit/fd4ff92c3ae5062b1368f01e50541832915bedd5).
