### ISSUE TITLE
NoSuchElementException on getInventoryProperty

### ISSUE THREAD

**Issue by hsyyid** [SpongePowered/Sponge#2045]
**I am currently running**
- SpongeForge version: `1.12.2-2705-7.1.0-BETA-3361`

**Issue Description**

Stacktrace:

```
java.util.NoSuchElementException: null
    at com.google.common.collect.Iterators$1.next(Iterators.java:81) ~[minecraft_server.1.12.2.jar:?]
    at org.spongepowered.common.item.inventory.adapter.impl.AdapterLogic.inventoryRoot(AdapterLogic.java:303) ~[AdapterLogic.class:1.12.2-2705-7.1.0-BETA-3361]
    at org.spongepowered.common.item.inventory.adapter.impl.AdapterLogic.getRootProperty(AdapterLogic.java:277) ~[AdapterLogic.class:1.12.2-2705-7.1.0-BETA-3361]
    at org.spongepowered.common.item.inventory.adapter.impl.MinecraftInventoryAdapter.getProperty(MinecraftInventoryAdapter.java:174) ~[MinecraftInventoryAdapter.class:1.12.2-2705-7.1.0-BETA-3361]
    at org.spongepowered.common.item.inventory.adapter.impl.MinecraftInventoryAdapter.getInventoryProperty(MinecraftInventoryAdapter.java:188) ~[MinecraftInventoryAdapter.class:1.12.2-2705-7.1.0-BETA-3361]
```

Looks like it's being thrown from the following code, when I try to get the `InventoryTitle` property.

Yes, I realize I do not check if the property is present, but if you look at the stacktrace it's erroring before I call `get()`

Note this code worked without issue prior to updating.

```java
        @Listener
	public void click(ClickInventoryEvent event, @First Player p)
	{
		Container c = p.getOpenInventory().orElse(null);

		if (c != null)
		{
			String name = TextSerializers.FORMATTING_CODE.serialize(c.getInventoryProperty(InventoryTitle.class).get().getValue());
                }
        }
```

**Comment by hsyyid** [comment]
Seems like there should be a `hasNext` call on this line before it calls `next` here:

https://github.com/SpongePowered/SpongeCommon/blob/2b340b7d4fe878428525183e69aaf99f89460c7c/src/main/java/org/spongepowered/common/item/inventory/adapter/impl/AdapterLogic.java#L303

**Comment by ryantheleach** [comment]
~qa

**Comment by randombyte-developer** [comment]
https://github.com/SpongePowered/SpongeCommon/issues/2057#issuecomment-412365898

**Comment by hsyyid** [comment]
Commit e7d7978 by @Faithcaio did not resolve the issue.

Updated stacktrace:

```
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[?:1.8.0_121]
	at java.util.ArrayList.get(ArrayList.java:429) ~[?:1.8.0_121]
	at net.minecraft.inventory.Container.func_75139_a(Container.java:120) ~[afr.class:?]
	at org.spongepowered.common.item.inventory.lens.impl.fabric.ContainerFabric.get(ContainerFabric.java:74) ~[ContainerFabric.class:1.12.2-2705-7.1.0-BETA-3406]
	at org.spongepowered.common.item.inventory.lens.impl.fabric.ContainerFabric.get(ContainerFabric.java:42) ~[ContainerFabric.class:1.12.2-2705-7.1.0-BETA-3406]
	at org.spongepowered.common.item.inventory.adapter.impl.AdapterLogic.inventoryRoot(AdapterLogic.java:303) ~[AdapterLogic.class:1.12.2-2705-7.1.0-BETA-3406]
	at org.spongepowered.common.item.inventory.adapter.impl.AdapterLogic.getRootProperty(AdapterLogic.java:277) ~[AdapterLogic.class:1.12.2-2705-7.1.0-BETA-3406]
	at org.spongepowered.common.item.inventory.adapter.impl.MinecraftInventoryAdapter.getProperty(MinecraftInventoryAdapter.java:174) ~[MinecraftInventoryAdapter.class:1.12.2-2705-7.1.0-BETA-3406]
	at org.spongepowered.common.item.inventory.adapter.impl.MinecraftInventoryAdapter.getInventoryProperty(MinecraftInventoryAdapter.java:188) ~[MinecraftInventoryAdapter.class:1.12.2-2705-7.1.0-BETA-3406]
```

**Comment by hsyyid** [comment]
https://github.com/SpongePowered/SpongeCommon/blob/e7d7978abd03fac83a02d3a4884962292dc4cd89/src/main/java/org/spongepowered/common/item/inventory/adapter/impl/AdapterLogic.java#L303

Still no check if the list is empty.

**Comment by Faithcaio** [comment]
Because that list should never be empty. 
What Container is that without any slots in it?
You literally cannot view it.

Fabric should abstract away that list.

I guess i'll put the check in there. But I still don't get how its possible to get a Container without slots

**Comment by hsyyid** [comment]
@Faithcaio reproducible using a Pixelmon PC

Move Pokemon around in the GUI

**Comment by Faithcaio** [comment]
Would not help me to understand how this happens. I would need the code for that.
Anyways I just return null in the fabric when the container has no slots.
Works fine for now as I only check the container slots for inventories built with sponge anyways.
