### ISSUE TITLE
Can't serialize ItemStackSnapshot in a ConfigurationNode

### ISSUE THREAD

**Issue by Yeregorix** [SpongePowered/Sponge#2058]
**I am currently running**
- SpongeForge version: 1.12.2-2705-8.0.0-BETA-3394:dev
- Java version: 1.8.0_162
- Operating System: Windows 10 x64

**Issue Description**
I was used to serialize and to deserialize `ItemStackSnapshot`s and now I'm getting an exception.

**How to reproduce**
```java
	public static void test() throws ObjectMappingException {
		ConfigurationNode root = HoconConfigurationLoader.builder().build().createEmptyNode();
		root.setValue(TypeToken.of(ItemStack.class), ItemStack.of(ItemTypes.STONE, 1));
	}
```
This example use `ItemStack` but the problem is exactly the same with `ItemStackSnapshot`.

**Result**
```
java.lang.IllegalArgumentException: Configuration does not accept objects of type class net.minecraft.util.ResourceLocation
	at ninja.leaping.configurate.ScalarConfigValue.setValue(ScalarConfigValue.java:51) ~[configurate-core-3.6.jar:?]
	at ninja.leaping.configurate.SimpleConfigurationNode.insertNewValue(SimpleConfigurationNode.java:318) ~[configurate-core-3.6.jar:?]
	at ninja.leaping.configurate.SimpleConfigurationNode.setValue(SimpleConfigurationNode.java:283) ~[configurate-core-3.6.jar:?]
	at ninja.leaping.configurate.commented.SimpleCommentedConfigurationNode.setValue(SimpleCommentedConfigurationNode.java:87) ~[configurate-core-3.6.jar:?]
	at ninja.leaping.configurate.commented.SimpleCommentedConfigurationNode.setValue(SimpleCommentedConfigurationNode.java:33) ~[configurate-core-3.6.jar:?]
	at ninja.leaping.configurate.MapConfigValue.setValue(MapConfigValue.java:68) ~[configurate-core-3.6.jar:?]
	at ninja.leaping.configurate.SimpleConfigurationNode.setValue(SimpleConfigurationNode.java:262) ~[configurate-core-3.6.jar:?]
	at ninja.leaping.configurate.commented.SimpleCommentedConfigurationNode.setValue(SimpleCommentedConfigurationNode.java:87) ~[configurate-core-3.6.jar:?]
	at ninja.leaping.configurate.commented.SimpleCommentedConfigurationNode.setValue(SimpleCommentedConfigurationNode.java:33) ~[configurate-core-3.6.jar:?]
	at org.spongepowered.common.config.DataSerializableTypeSerializer.serialize(DataSerializableTypeSerializer.java:59) ~[DataSerializableTypeSerializer.class:1.12.2-2705-8.0.0-BETA-3394]
	at org.spongepowered.common.config.DataSerializableTypeSerializer.serialize(DataSerializableTypeSerializer.java:41) ~[DataSerializableTypeSerializer.class:1.12.2-2705-8.0.0-BETA-3394]
	at ninja.leaping.configurate.ConfigurationNode.setValue(ConfigurationNode.java:562) ~[configurate-core-3.6.jar:?]
	at net.smoofyuniverse.core.SmoofyCorePlugin.test(SmoofyCorePlugin.java:191) ~[SmoofyCorePlugin.class:?]
```

**Comment by XakepSDK** [comment]
Issue with CatalogKeys, not text.
Merged PR that (95%) introduced this regression:
https://github.com/SpongePowered/SpongeCommon/pull/1554
