### ISSUE TITLE
map-optimization causing ConcurrentModificationException crash

### ISSUE THREAD

**Issue by Sir-Will** [SpongePowered/Sponge#2108]
I was updating sponge and unfortunately discovered that `map-optimization` which was added in build 3392 causes the server to crash once a player joins. Disabling this got rid of the issue. I also wasn't able to reproduce this with a fresh world.

Not sure if it is possible to fix this without finding which mod causes this incompatibility with this sponge optimization tweak.

spongeforge-1.12.2-2705-7.1.0-BETA-3392 to spongeforge-1.12.2-2705-7.1.0-BETA-3458

```
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at net.minecraft.server.MinecraftServer.handler$onEndTick$zph000(MinecraftServer.java:4096)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:713)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)

-- Sponge PhaseTracker --
Details:
	Phase Stack: [Empty stack]
Stacktrace:
	at net.minecraft.server.MinecraftServer.handler$onCrashReport$zjj000(MinecraftServer.java:3982)
	at net.minecraft.server.MinecraftServer.func_71230_b(MinecraftServer.java:889)
	at net.minecraft.server.dedicated.DedicatedServer.func_71230_b(DedicatedServer.java:370)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:558)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by phit** [comment]
it's caused by twilight forest https://github.com/SpongePowered/SpongeForge/issues/2398
