### ISSUE TITLE
CaptureInventory of IMixinContainer does not set to false after switch hotbar

### ISSUE THREAD

**Issue by ginyai** [SpongePowered/Sponge#2112]
**I am currently running**

- SpongeForge version: spongeforge-1.12.2-2705-7.1.0-BETA-3477
- Java version: 1.8.0_162
- Operating System: Windows10

**Issue Description**
In survival mode.
Put an itemstack in the hotbar, select that slot, press F to swap the itemstack in mainhand and offhand, and click the inventory.
`ClickInventoryEvent#getTransactions` contains the transactions made by swaphand.

https://github.com/SpongePowered/SpongeCommon/blob/cd7c8e87f2e1902f940a6121167a8739de3f1a8a/src/main/java/org/spongepowered/common/event/tracking/phase/packet/inventory/BasicInventoryPacketState.java#L155
https://github.com/SpongePowered/SpongeCommon/blob/cd7c8e87f2e1902f940a6121167a8739de3f1a8a/src/main/java/org/spongepowered/common/event/tracking/phase/packet/inventory/SwapHandItemsState.java#L61

**Comment by ginyai** [comment]
Code:
```java
@Mixin(ContainerPlayer.class)
public abstract class MixinContainerPlayer extends MixinContainer {
    @Override
    public void setCaptureInventory(boolean flag) {
        super.setCaptureInventory(flag);
        Plugin.getLogger().info("Capture:{}",capturingInventory());
        StackTraceElement[] trace = Thread.currentThread().getStackTrace();
        for (StackTraceElement traceElement : trace)
            Plugin.getLogger().info("\tat {}",traceElement);
    }
}
```
When I switch hotbar slots:
```
Capture:true
        at java.lang.Thread.getStackTrace(Thread.java:1559)
        at net.minecraft.inventory.ContainerPlayer.setCaptureInventory(ContainerPlayer.java:1515)
        at org.spongepowered.common.event.tracking.phase.packet.inventory.BasicInventoryPacketState.populateContext(BasicInventoryPacketState.java:117)
        at org.spongepowered.common.event.tracking.phase.packet.inventory.SwitchHotbarScrollState.populateContext(SwitchHotbarScrollState.java:59)
        at org.spongepowered.common.event.tracking.phase.packet.inventory.SwitchHotbarScrollState.populateContext(SwitchHotbarScrollState.java:52)
        at org.spongepowered.common.event.tracking.phase.packet.PacketPhase.populateContext(PacketPhase.java:230)
        at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:187)
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zlg000(SourceFile:539)
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at net.minecraft.util.Util.func_181617_a(SourceFile:46)
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:294)
        at net.minecraft.server.MinecraftServer.redirect$onRun$zjk000(MinecraftServer.java:3970)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
        at java.lang.Thread.run(Thread.java:748)
Capture:false
        at java.lang.Thread.getStackTrace(Thread.java:1559)
        at net.minecraft.inventory.ContainerPlayer.setCaptureInventory(ContainerPlayer.java:1515)
        at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.handleSlotRestore(PacketPhaseUtil.java:85)
        at org.spongepowered.common.event.tracking.phase.packet.inventory.SwitchHotbarScrollState.unwind(SwitchHotbarScrollState.java:100)
        at org.spongepowered.common.event.tracking.phase.packet.inventory.SwitchHotbarScrollState.unwind(SwitchHotbarScrollState.java:52)
        at org.spongepowered.common.event.tracking.PhaseTracker.completePhase(PhaseTracker.java:268)
        at org.spongepowered.common.event.tracking.PhaseContext.close(PhaseContext.java:565)
        at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:195)
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zlg000(SourceFile:539)
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at net.minecraft.util.Util.func_181617_a(SourceFile:46)
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:294)
        at net.minecraft.server.MinecraftServer.redirect$onRun$zjk000(MinecraftServer.java:3970)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
        at java.lang.Thread.run(Thread.java:748)
Capture:true
        at java.lang.Thread.getStackTrace(Thread.java:1559)
        at net.minecraft.inventory.ContainerPlayer.setCaptureInventory(ContainerPlayer.java:1515)
        at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.handleSlotRestore(PacketPhaseUtil.java:87)
        at org.spongepowered.common.event.tracking.phase.packet.inventory.SwitchHotbarScrollState.unwind(SwitchHotbarScrollState.java:100)
        at org.spongepowered.common.event.tracking.phase.packet.inventory.SwitchHotbarScrollState.unwind(SwitchHotbarScrollState.java:52)
        at org.spongepowered.common.event.tracking.PhaseTracker.completePhase(PhaseTracker.java:268)
        at org.spongepowered.common.event.tracking.PhaseContext.close(PhaseContext.java:565)
        at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:195)
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zlg000(SourceFile:539)
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at net.minecraft.util.Util.func_181617_a(SourceFile:46)
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:294)
        at net.minecraft.server.MinecraftServer.redirect$onRun$zjk000(MinecraftServer.java:3970)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
        at java.lang.Thread.run(Thread.java:748)
```
Tested with spongeforge-1.12.2-2705-7.1.0-BETA-3481

**Comment by ginyai** [comment]
It seems that `SwitchHotbarScrollState` does not use the data IMixinContainer captured.

**Comment by Faithcaio** [comment]
Fixed in latest.
Thanks for the investigation really saved a lot of time.
