### ISSUE TITLE
Encountered an unexpected exception

### ISSUE THREAD

**Issue by nikosgram13** [SpongePowered/Sponge#229]
```log
[20:52:50] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NullPointerException: color
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:229) ~[guava-17.0.jar:?]
	at org.spongepowered.api.text.TextBuilder.color(TextBuilder.java:101) ~[TextBuilder.class:?]
	at org.spongepowered.api.text.TextBuilder$Translatable.color(TextBuilder.java:696) ~[TextBuilder$Translatable.class:?]
	at net.minecraft.command.ServerCommandManager.executeCommand(ServerCommandManager.java:92) ~[ServerCommandManager.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.executePendingCommands(DedicatedServer.java:424) ~[DedicatedServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.finalTick(DedicatedServer.java:336) ~[DedicatedServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:553) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_40]
```

**Comment by Xemiru** [comment]
Related to #216 ?

**Comment by nikosgram13** [comment]
Soz, I had not seen this.
