### ISSUE TITLE
WorldServer cannot be cast to WorldServerBridge

### ISSUE THREAD

**Issue by Magi1053** [SpongePowered/Sponge#2344]
**I am currently running**

- SpongeForge version: 1.12.2-2838-7.1.7-RC3885
- Forge version: 1.12.2-14.23.5.2838
- Java version: 1.8.0_222
- Operating System: Alpine

- Plugins (9): 
```
Minecraft, Minecraft Coder Pack, SpongeAPI, Sponge, LuckPerms, Nucleus, Plan, Sledgehammer, spark
```
- Mods (153): 
```
Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, Sponge, Advanced Chimneys, Adventurer's Amulets, Animania,AppleCore, Applied Energistics 2, Arcane Archives, Aroma1997Core, AromaBackup, AromaBackuprecovery, Astral Sorcery, Attribute Fix, AutoPackager, AutoRegLib, Avaritia, Bad Wither No Cookie! Reloaded, Baubles, Better Diving, Better Questing, Better Questing Quest Book, Better Records, BiblioCraft, Binnie Core, Binnie's Botany, Binnie's Design, Binnie's Extra Bees, Binnie's Extra Trees, Binnie's Genetics, Blockcraftery, Blood Arsenal, Blood Magic: Alchemical Wizardry, Botania, Brandon's Core, Building Gadgets, Calculator, Carry On, Chameleon, Chisel, CoFH Core, CoFH World, CodeChicken Lib, Computronics, Console Filter, Cooking for Blockheads, CoroUtil Library, CraftStudio API, CraftTweaker JEI Support, CraftTweaker2, Crafting Tweaks, CreativeCore, CreativeCoreDummy, CustomNPCs, Deep Mob Learning, Draconic Evolution, Dude! Where's my Horse?, Dynamic Trees, Dynamic Trees PHC, Dynmap, EnderStorage, Engineer's Doors, Extended Mod Config, Extended Renderer, FTB Library, FoamFix, FoamFixCore, Forestry, Forge Endertech, Forge Microblocks, Forge Multipart CBE, Garden Stuff, Guide-API, Guidebook, Hammer Core, Ice and Fire, Immersive Engineering, Immersive Petroleum, Immersive Posts, Immersive Tech, Improved Backpacks, Industrial Foregoing, Infernal Mobs, InfinityLib, Integration Foregoing, Inventory Tweaks, Iron Chest, JourneyMap, Just Enough Items, JustEnoughIDs, LLibrary, LT Photo Converter, LagGoggles, LibrarianLib, LibrarianLib Stage 2, LittleTiles, LittleTilesCore, Localized Weather & Storms, MCMultiPart, McJtyLib, Mekanism, Mekanism: Generators, Minecraft Chromium Embedded Framework, Minecraft Multipart Plugin, MrTJPCore, Mystical Lib, NPC Integration, NetherendingOres, NuclearCraft, OpenComputers, OpenComputers (Core), OpenGlasses, Pam's HarvestCraft, Patchouli, Platforms, Pollution of the Realms, Practical Logistics 2, ProjectRed Core, ProjectRed Exploration, ProjectRed Illumination, ProjectRed Integration, ProjectRed Transmission, Quark, RFTools, RFTools Control, Rats, Realistic Item Drops, Reborn Core, Redstone Flux, Shadowfacts' Forgelin, ShetiPhian-Core, SonarCore, SpongeForge, Standard Expansion, Storage Drawers, TOP Addons, Tech Reborn, Tech Reborn Mod Compatibility, Tesla Core Lib, Tesla Core Lib Registries, The One Probe, Visuals, WebDisplays, World Control, WorldEdit, YABBA, asielib, guiToolkit, iChunUtil, renderToolkit
```

**Issue Description**
```
java.lang.ClassCastException: net.minecraft.world.WorldServer cannot be cast to org.spongepowered.common.bridge.world.WorldServerBridge
	at org.spongepowered.common.world.WorldManager.reorderWorldsVanillaFirst(WorldManager.java:929)
	at net.minecraftforge.common.DimensionManager.setWorld(DimensionManager.java:756)
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:124)
	at org.spongepowered.common.world.WorldManager.createWorldFromProperties(WorldManager.java:846)
	at org.spongepowered.common.world.WorldManager.loadAllWorlds(WorldManager.java:813)
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:4396)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:270)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:748)
```
- Crash Report: https://gist.github.com/a70cdf1d4bdc302490ad8ba4c5a6a5bc

**Comment by Addalyn** [comment]
Having similar issue with anything above RC3878 breaks, due slightly different issue but still related to WorldServerBridge (but named ServerWorldBridge ?)

```[09:09:54] [main/WARN] [mixin]: Error loading class: org/spongepowered/common/bridge/world/ServerWorldBridge (java.lang.ClassNotFoundException: The specified class 'org.spongepowered.common.bridge.world.ServerWorldBridge' was not found)
[09:09:54] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: java.lang.RuntimeException: java.lang.ClassNotFoundException: org.spongepowered.common.bridge.world.ServerWorldBridge
[09:09:54] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMethod(MixinPreProcessorStandard.java:682)
[09:09:54] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transform(MixinPreProcessorStandard.java:670)
[09:09:54] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:267)
[09:09:54] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:241)
[09:09:54] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1144)
[09:09:54] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:267)
[09:09:54] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353)
[09:09:54] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724)
[09:09:54] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703)
[09:09:54] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509)
[09:09:54] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72)
[09:09:54] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
[09:09:54] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
[09:09:54] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[09:09:54] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[09:09:54] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at java.lang.Class.getDeclaredMethods0(Native Method)
[09:09:54] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
[09:09:54] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
[09:09:54] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at java.lang.Class.getMethod0(Class.java:3018)
[09:09:54] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at java.lang.Class.getMethod(Class.java:1784)
[09:09:54] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:132)
[09:09:54] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[09:09:54] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[09:09:54] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[09:09:54] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[09:09:54] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[09:09:54] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70)
[09:09:54] [main/INFO] [STDERR]: [org.spongepowered.asm.mixin.transformer.MixinTransformer:transformClassBytes:519]: 	at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34)```

**Comment by Zidane** [comment]
We need to see a whole log. You have mixins not applying.

@Alexandrea Update to latest SpongeForge, you are out of date.

**Comment by Addalyn** [comment]
@Zidane using spongeforge-1.12.2-2838-7.1.7-RC3885.jar

anything above spongeforge-1.12.2-2838-7.1.7-RC3878.jar breaks

https://gist.github.com/Alexandrea/d630a17b02d373de63b62afab9ad17e4

**Comment by Zidane** [comment]
@Alexandrea LagGoggles needs an update.

**Comment by Addalyn** [comment]
@Zidane good catch started up now so not related to this issue in first place, sorry about this

**Comment by Zidane** [comment]
@Alexandrea It is, he has it installed too. @Magi1053 update LagGoggles.

**Comment by Addalyn** [comment]
just to note, LagGoggles needs another update for it to work with RC3886 i guess way sponge changes WorldServerBridge and mods wont work and needs updating if they use that

**Comment by Zidane** [comment]
@Alexandrea LagGoggles builds against our implementation and not our API. Anytime you do so, you take the chance of your product dying at any time. This will be the last time in 1.12 our bridge names radically change so the developer of that mod shouldn't have many more issues.

**Comment by LeonPhilips** [comment]
Use the latest version of LagGoggles, folks. It should already be up to date since `1.12.2-4.8` :wink:
