### ISSUE TITLE
Unable to use DataFormats.NBT.readFrom as per the documented example

### ISSUE THREAD

**Issue by BenJuan26** [SpongePowered/Sponge#2368]
**I am currently running**
- SpongeVanilla version: 1.12.2-7.1.6
- Java version: 1.8.0_222
- Operating System: Windows 10
- IDE: IntelliJ

- Plugins/Mods: None

**Issue Description**
When I try to read a `.schem` file using `DataFormats.NBT.readFrom()`, I get the following error:

```
Exception in thread "main" java.lang.UnsupportedOperationException: A method was invoked on a dummy class, due to the static field NBT not being initialized (most likely in a CatalogType-related class).
Method: public abstract org.spongepowered.api.data.DataContainer org.spongepowered.api.data.persistence.DataFormat.readFrom(java.io.InputStream) throws org.spongepowered.api.data.persistence.InvalidDataFormatException,java.io.IOException
	at org.spongepowered.api.util.dummy.DataFormat$DummyClass.readFrom(Unknown Source)
	at SampleProject.main(Schem2Blueprint.java:18)
```

This is the complete code: 

`SampleProject.java`

```java
import org.spongepowered.api.data.DataContainer;
import org.spongepowered.api.data.persistence.DataFormats;
import org.spongepowered.api.world.schematic.Schematic;
import org.spongepowered.common.data.persistence.SchematicTranslator;

import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

public class SampleProject {
    public static void main(String[] args) {
        Path path = Paths.get("C:\\Users\\UserName\\AppData\\Roaming\\.minecraft\\config\\worldedit\\schematics\\my_schematic.schem");

        try {
            InputStream inputStream = Files.newInputStream(path);
            DataContainer container = DataFormats.NBT.readFrom(inputStream);
            SchematicTranslator translator = SchematicTranslator.get();
            Schematic schem = translator.translate(container);
            System.out.println(schem.getBlock(0, 0, 0).getName());
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
```

`build.gradle`

```
plugins {
    id 'java'
}

version '1.0-SNAPSHOT'

sourceCompatibility = 1.8

repositories {
    mavenCentral()
    maven {
        name = 'sponge-repo'
        url = 'https://repo.spongepowered.org/maven'
    }
}

dependencies {
    compile 'org.spongepowered:spongeapi:7.1.0'
    compile 'org.spongepowered:spongevanilla:1.12.2-7.1.6'
}
```

Am I missing an initialization somewhere? I also tried this by building SpongeCommon and adding the JAR directly to the project, and got the exact same error.

**Comment by gabizou** [comment]
As the spec says, the file is not just a file, but a GZip'ed file. Just like [the copypasta plugin](https://github.com/SpongePowered/SpongeCommon/blob/26f40e53d20641504a5ba0b4f2630313d70e4589/testplugins/src/main/java/org/spongepowered/test/CopyPasta.java#L175-L177) you need to be using the input stream and pipe that to a GZip so the NBT data can be read by the translator.

Also, your bigger issue is that you're not actually running the game or initializing the GameRegistry, as indicated that the catalog type `DataFormats.NBT` being a `DummyObject`.
