### ISSUE TITLE
World/NBT error in console every 45 seconds

### ISSUE THREAD

**Issue by Voltasalt** [SpongePowered/Sponge#241]
Every 45 seconds this gets spammed in the server console:

    [22:05:25] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.NullPointerException
    [22:05:25] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.world.storage.WorldInfo.updateSpongeNbt(WorldInfo.java:245)
    [22:05:25] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.world.storage.WorldInfo.getSpongeRootLevelNbt(WorldInfo.java:568)
    [22:05:25] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.world.storage.SaveHandler.saveWorldInfoWithPlayer(SaveHandler.java:169)
    [22:05:25] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.world.chunk.storage.AnvilSaveHandler.saveWorldInfoWithPlayer(AnvilSaveHandler.java:47)
    [22:05:25] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.world.WorldServer.saveLevel(WorldServer.java:1019)
    [22:05:25] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.world.WorldServer.saveAllChunks(WorldServer.java:969)
    [22:05:25] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.server.MinecraftServer.saveAllWorlds(MinecraftServer.java:419)
    [22:05:25] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:691)
    [22:05:25] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:540)
    [22:05:25] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.Thread.run(Thread.java:745)

Offending method (in MixinWorldInfo) (>>> is line 245):

    private void updateSpongeNbt() {
        if (this.levelName != null) {
            this.spongeNbt.setString("LevelName", this.levelName); // for reference
        }
        this.spongeNbt.setInteger("dimensionId", this.dimension);
        if (this.dimensionType != null) {
            this.spongeNbt.setString("dimensionType", this.dimensionType.getDimensionClass().getName());
        }
        if (this.uuid != null) {
            this.spongeNbt.setLong("uuid_most", this.uuid.getMostSignificantBits());
            this.spongeNbt.setLong("uuid_least", this.uuid.getLeastSignificantBits());
        }
        this.spongeNbt.setBoolean("enabled", this.worldEnabled);
        this.spongeNbt.setBoolean("keepSpawnLoaded", this.keepSpawnLoaded);
        this.spongeNbt.setBoolean("loadOnStartup", this.loadOnStartup);

        NBTTagList generatorModifierNbt = new NBTTagList();
        >>> for (String generatorModifierId : this.generatorModifiers) {
            generatorModifierNbt.appendTag(new NBTTagString(generatorModifierId));
        }
        this.spongeNbt.setTag("generatorModifiers", generatorModifierNbt);
    }

Ping @bloodmc, git says you added that part

**Comment by Zidane** [comment]
Was this with existing worlds? Latest master? More details please.

**Comment by Deamon5550** [comment]
@Zidane its from @rutgerkok changes looks like he missed adding the initializer for that field in 2 of the 3 constructor injections.

[see here](https://github.com/SpongePowered/Sponge/blob/master/src/main/java/org/spongepowered/mod/mixin/core/world/storage/MixinWorldInfo.java#L217)

**Comment by Voltasalt** [comment]
@Zidane Latest master (as of a few hours ago). Fresh install completely, booted up Sponge, and instantly this error started spamming.

**Comment by Zidane** [comment]
Thats odd that I haven't hit it whatsoever

@Voltasalt 
Add the line of code that @Deamon5550 linked to the other constructors and see if your issue goes away. If so, PR it.
