### ISSUE TITLE
SpongeForge RC3976 crash: net.minecraft.util.ReportedException: Ticking entity

### ISSUE THREAD

**Issue by electron93** [SpongePowered/Sponge#2457]
**I am currently running**

- SpongeForge version: **7.1.9-RC3976**
- Java version: 1.8.0_232
- Operating System: Linux (amd64)
- Mods: **none** (spongeforge)
- Plugins: **none**

**Issue Description**

Crash.

[crash-2020-01-03_14.39.57-server.txt + latest.log + debug.log](https://gist.github.com/electron93/ee14c44b23c2f344d617e0174c9f56b2)

RC**3973** works fine.

Logs from the server with a freshly generated map:
```
[14:47:41] [Server thread/INFO] [minecraft/MinecraftServer]: Preparing spawn area: 25%
[14:47:42] [Server thread/INFO] [minecraft/MinecraftServer]: Preparing spawn area: 47%
[14:47:43] [Server thread/INFO] [minecraft/MinecraftServer]: Preparing spawn area: 67%
[14:47:44] [Server thread/INFO] [minecraft/MinecraftServer]: Preparing spawn area: 88%
[14:47:44] [Server thread/INFO] [Sponge]: Loading world [galactech] (minecraft:overworld/0)
[14:47:45] [Server thread/INFO] [minecraft/AdvancementList]: Loaded 488 advancements
[14:47:45] [Server thread/INFO] [minecraft/AdvancementList]: Loaded 6 advancement trees
[14:47:45] [Server thread/INFO] [Sponge]: Loading world [DIM-1] (minecraft:nether/-1)
[14:47:45] [Server thread/INFO] [minecraft/AdvancementList]: Loaded 488 advancements
[14:47:45] [Server thread/INFO] [minecraft/AdvancementList]: Loaded 6 advancement trees
[14:47:45] [Server thread/INFO] [Sponge]: Loading world [DIM1] (minecraft:the_end/1)
[14:47:45] [Server thread/INFO] [minecraft/DedicatedServer]: Done (9,796s)! For help, type "help" or "?"
[14:47:46] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking entity
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:773) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) ~[nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
Caused by: java.lang.NoSuchFieldError: world
        at net.minecraft.entity.item.EntityItem.activation$inactiveTick(EntityItem.java:2613) ~[acl.class:?]
        at net.minecraft.world.World.handler$bbl000$forgeActivationImpl$checkIfCanUpdate(World.java:6338) ~[amu.class:?]
        at net.minecraft.world.World.func_72866_a(World.java) ~[amu.class:?]
        at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832) ~[oo.class:?]
        at net.minecraft.world.World.func_72870_g(World.java:1955) ~[amu.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:1759) ~[amu.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:3928) ~[oo.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767) ~[MinecraftServer.class:?]
        ... 4 more
[14:47:46] [Server thread/ERROR] [minecraft/MinecraftServer]: This crash report has been saved to: /path/to/crash.txt
[14:47:46] [Server thread/INFO] [minecraft/MinecraftServer]: Stopping server
[14:47:46] [Server thread/INFO] [minecraft/MinecraftServer]: Saving players
[14:47:46] [Server thread/INFO] [minecraft/MinecraftServer]: Saving worlds
[14:47:46] [Server thread/INFO] [Sponge]: Unloading world [galactech] (minecraft:overworld/0)
[14:47:46] [Server thread/INFO] [Sponge]: Unloading world [DIM-1] (minecraft:nether/-1)
[14:47:46] [Server thread/INFO] [Sponge]: Unloading world [DIM1] (minecraft:the_end/1)
[14:47:46] [Server thread/INFO] [FML]: The state engine was in incorrect state SERVER_STOPPING and forced into state SERVER_STOPPED. Errors may have been discarded.
[14:47:46] [Server Shutdown Thread/INFO] [minecraft/MinecraftServer]: Stopping server
[14:47:46] [Server Shutdown Thread/INFO] [minecraft/MinecraftServer]: Saving players
[14:47:46] [Server Shutdown Thread/INFO] [minecraft/MinecraftServer]: Saving worlds
```

**Comment by dualspiral** [comment]
Relevant mixin: https://github.com/SpongePowered/SpongeCommon/blob/stable-7/src/main/java/org/spongepowered/common/mixin/entityactivation/entity/item/EntityItemMixin_Activation.java

The field `world` is from the superclass `Entity`, this mixin targets `EntityItem`. The world field was not remapped to the SRG name during build. I ran the server in production and got Mixin to dump the class and this is how the method in question came out - note that `world` is not the SRG field name.

https://gist.github.com/dualspiral/b4a72d81f270ee48b0978f7a0946a6ff#file-entityitemmixin-java-L11

I have no idea where the bug could be here, I'm sorry to say, but we are currently in the process of moving to mixin 0.8 so iffyness can be expected for the moment.

**Comment by dualspiral** [comment]
I only hid the error and did the wrong thing to "fix" it. I will need to revert the commit I made to "fix" this as I'm hiding Forge specific behaviour. I'm reopening this to remind me to deal with this when I get chance.

**Comment by gabizou** [comment]
Please re-test on latest (SF 1.12.2-2838-7.1.9-RC3980)

**Comment by dualspiral** [comment]
Tested it, it's fine.
