### ISSUE TITLE
Exception ticking world

### ISSUE THREAD

**Issue by Regrad** [SpongePowered/Sponge#2553]
https://pastebin.com/3DSX5PLZ
Crash on world generation. Ho to: Travel.

Description: Exception ticking world

java.lang.NullPointerException: Exception ticking world
	at net.minecraft.world.WorldEntitySpawner.func_77191_a(WorldEntitySpawner.java:297)
	at biomesoplenty.common.world.ChunkGeneratorOverworldBOP.func_185931_b(ChunkGeneratorOverworldBOP.java:570)
	at org.spongepowered.mod.world.gen.SpongeChunkGeneratorForge.func_185931_b(SpongeChunkGeneratorForge.java:308)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1019)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:990)

**Comment by Regrad** [comment]
Deleted RandomPatches, foamfix, BetterFPS... No effect.

**Comment by Regrad** [comment]
i think ElectroblobsWizardry craches server. fastWorldgen=false stop chashing

**Comment by Regrad** [comment]
Hmm. Crash again on another chunk

**Comment by Regrad** [comment]
i think problem with flowers from ElectroblobsWizardry.

**Comment by ImMorpheus** [comment]
Please follow the issue template, it's actually rather important if you want to get dev attention to fix your issue.

Edit this issue with the required details / template, and I'll reopen and hide this comment.
