### ISSUE TITLE
LinkageError calling getMethods on BlockBreakEvent (possibly others)

### ISSUE THREAD

**Issue by UnwrittenFun** [SpongePowered/Sponge#266]
When calling getMethods on the class of BlockBreakEvent the error shown occurs.

This doesn't happen with CommandEvent but I have not tested other events/classes.

```
java.lang.LinkageError: loader constraint violation: loader (instance of sun/misc/Launcher$AppClassLoader) previously initiated loading for a different type with name "com/google/common/base/Optional"
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0_71]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800) ~[?:1.7.0_71]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.7.0_71]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449) ~[?:1.7.0_71]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71) ~[?:1.7.0_71]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[?:1.7.0_71]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[?:1.7.0_71]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_71]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[?:1.7.0_71]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_71]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308) ~[?:1.7.0_71]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_71]
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.7.0_71]
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2615) ~[?:1.7.0_71]
	at java.lang.Class.privateGetPublicMethods(Class.java:2733) ~[?:1.7.0_71]
	at java.lang.Class.privateGetPublicMethods(Class.java:2743) ~[?:1.7.0_71]
	at java.lang.Class.privateGetPublicMethods(Class.java:2743) ~[?:1.7.0_71]
	at java.lang.Class.privateGetPublicMethods(Class.java:2743) ~[?:1.7.0_71]
	at java.lang.Class.privateGetPublicMethods(Class.java:2743) ~[?:1.7.0_71]
	at java.lang.Class.privateGetPublicMethods(Class.java:2743) ~[?:1.7.0_71]
	at java.lang.Class.privateGetPublicMethods(Class.java:2743) ~[?:1.7.0_71]
	at java.lang.Class.privateGetPublicMethods(Class.java:2743) ~[?:1.7.0_71]
	at java.lang.Class.privateGetPublicMethods(Class.java:2743) ~[?:1.7.0_71]
	at java.lang.Class.getMethods(Class.java:1472) ~[?:1.7.0_71]
	at unwrittenfun.sponge.lunge.lua.tables.LuaJavaObject.<init>(LuaJavaObject.java:17) ~[LuaJavaObject.class:?]
	at unwrittenfun.sponge.lunge.events.LuaEventHandler.onEvent(LuaEventHandler.java:46) ~[LuaEventHandler.class:?]
	at org.spongepowered.mod.event.handler.EventHandler_LuaEventHandler_onEvent3.handle(Unknown Source) ~[?:?]
	at org.spongepowered.mod.event.SpongeEventBus.callListener(SpongeEventBus.java:234) [SpongeEventBus.class:1.8-1371-2.1DEV-437+unknown-b437.git-unknown]
	at org.spongepowered.mod.event.SpongeEventBus.post(SpongeEventBus.java:268) [SpongeEventBus.class:1.8-1371-2.1DEV-437+unknown-b437.git-unknown]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:56) [EventBus.class:?]
	at net.minecraftforge.common.ForgeHooks.onBlockBreakEvent(ForgeHooks.java:530) [ForgeHooks.class:?]
	at net.minecraft.server.management.ItemInWorldManager.func_180237_b(ItemInWorldManager.java:280) [qx.class:?]
	at net.minecraft.server.management.ItemInWorldManager.func_180785_a(ItemInWorldManager.java:241) [qx.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:537) [rj.class:?]
	at net.minecraft.network.play.client.C07PacketPlayerDigging.func_180763_a(SourceFile:40) [ml.class:?]
	at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:10) [ml.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [ih.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [?:1.7.0_71]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_71]
	at net.minecraftforge.fml.common.FMLCommonHandler.callFuture(FMLCommonHandler.java:709) [FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:655) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:364) [po.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:598) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:478) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_71]
```

**Comment by Mumfrey** [comment]
And this is the part where you mention what other mods you're running,

**Comment by unwrittenfun** [comment]
None? The plugin I'm currently developing is the only thing I have

**Comment by Mumfrey** [comment]
What's the forge version?

**Comment by unwrittenfun** [comment]
1.8-11.14.1.1371

**Comment by Mumfrey** [comment]
Okay that's really weird, it shouldn't be possible for this to happen without a misbehaving coremod. Are you shading any libraries in your mod?

**Comment by unwrittenfun** [comment]
I would not be at all surprise if this is to do with LuaJ which I'm including (http://www.luaj.org/luaj/3.0/README.html)

**Comment by Mumfrey** [comment]
Are you shading the library into your plugin jar or placing the LuaJ jar directly in the "mods" folder?

**Comment by unwrittenfun** [comment]
I'm including the classes in my plugin jar

**Comment by Mumfrey** [comment]
Can you post the source for `LuaJavaObject` please.

**Comment by unwrittenfun** [comment]
https://gist.github.com/unwrittenfun/76d4e367ac527e5e161f

**Comment by Mumfrey** [comment]
This looks like a hitherto undiscovered problem with `getMethods`'s recursive behaviour causing a class load across the classloader boundary. There isn't a simple solution for this as it shouldn't even be possible so it will need some investigation.

**Comment by Buuz135** [comment]
I get another Linkage Error when placing a sign: http://pastebin.com/fwDKVmq3

**Comment by UnwrittenFun** [comment]
probably best create a new issue and reference this one if you think its related (if you don't know how reference it by putting #id, where id is the number of this issue, somewhere in the issue)

**Comment by Aaron1011** [comment]
@Mumfrey: I'd previously discovered this issue - it appears to be a problem with `CauseTracked` being implemented by several mixins.

**Comment by Mumfrey** [comment]
@Aaron1011 that shouldn't make any difference though. What I think is happening is that somehow a Klass (for Class `Optional`) is being defined in the active classloader somehow, but I have no idea how.

**Comment by Aaron1011** [comment]
@Mumfrey: When I was debugging this, I managed to track it down to it down to `CauseTracked`. Calling `getDeclaredMethods` on it (or `getMethods` on any subinterface, presumably because of the inherited method) caused the link error with Optional. I wasn't able to reproduce this for any interface which did not extend `CauseTracked` - this includes `Cause` itself.

Removing all the uses of `CauseTracked` in event mixins caused me to get a link error in the constructor of the event (I'll post the stack trace later).

Curiously, I was able to call `getDeclaredMethods` on `CauseTracked` with no errors from the beginning of `SpongeMod`.

I'll be back later today, and I'll be looking into this more then.

**Comment by Mumfrey** [comment]
Yes, but you're missing the point. [`CauseTracked`'s Klass should be in the AppClassLoader](https://github.com/SpongePowered/Sponge/blob/master/src/main/java/org/spongepowered/mod/SpongeCoremod.java#L60), which is fine and intentional, this is **required** because of the mixin to FML's `Event` class which must be loaded in the ACL because it has to exist before the game starts. The Klass in LCL should thus match, and should match all the way up the parent hierarchy.

What I suspect is happening is that a Klass for Optional is being created in the LCL (probably via `defineClass` but it's possible it's some internal reflection mojo) which does not match the Klass in the ACL. The other possibility is that someone has fucked up the classloader relationship somewhere else, and that things are not being created with the correct parent classloader setup required by the environment. [This for example](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/util/event/factory/ClassGeneratorProvider.java#L100-L109) has me worried.

**Comment by Aaron1011** [comment]
https://github.com/SpongePowered/Sponge/commit/6836a463bd42923935e9383682528c40ffa76174Fixed in
