### ISSUE TITLE
AbstractMethodError at EntityPlayerMP.getGameModeData()

### ISSUE THREAD

**Issue by nikosgram13** [SpongePowered/Sponge#275]
```prolog
[01:01:26] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 3974ms behind, skipping 79 tick(s)
[01:01:26] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.AbstractMethodError: net.minecraft.entity.player.EntityPlayerMP.getGameModeData()Lorg/spongepowered/api/data/manipulator/entity/GameModeData;
[01:01:26] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at me.nikosgram.oglofus.sponge.OglofusGamemode.execute(OglofusGamemode.java:111)
[01:01:26] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at org.spongepowered.api.util.command.spec.CommandSpec.process(CommandSpec.java:330)
[01:01:26] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at org.spongepowered.api.util.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:342)
[01:01:26] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at org.spongepowered.api.service.command.SimpleCommandService.process(SimpleCommandService.java:231)
[01:01:26] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:85)
[01:01:26] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:812)
[01:01:26] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:791)
[01:01:26] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.network.play.client.C01PacketChatMessage.func_180757_a(SourceFile:37)
[01:01:26] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9)
[01:01:26] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
[01:01:26] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[01:01:26] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at java.util.concurrent.FutureTask.run(Unknown Source)
[01:01:26] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraftforge.fml.common.FMLCommonHandler.callFuture(FMLCommonHandler.java:709)
[01:01:26] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:655)
[01:01:26] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:364)
[01:01:26] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:598)
[01:01:26] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:478)
[01:01:26] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at java.lang.Thread.run(Unknown Source)
```

Java Version: `1.8`
Minecraft Version: `1.8.4`
Sponge Version: `1.8-1371-2.1DEV-449`
Forge Version: `1.8-11.14.1.1404-universal`

My code in line 111:
```java
player.getGameModeData().setGameMode( GameModes.CREATIVE );
```

**Comment by gabizou** [comment]
Can you re-open this issue in SpongeCommon as it's most relevant there.

**Comment by nikosgram13** [comment]
Done: https://github.com/SpongePowered/SpongeCommon/issues/39

**Comment by LOLDERP** [comment]
hey
Nikos Grammatikos

On Mon, May 18, 2015 at 6:10 PM, Nikos Grammatikos <notifications@github.com
