### ISSUE TITLE
NoSuchMethod Exception

### ISSUE THREAD

**Issue by randombyte-developer** [SpongePowered/Sponge#279]
Hello! I hope I post this issue in the right repository.

When I want to test a plugin regardless whether the server is installed with Forge manually or via "install" argument I get every time when an event is fired(only these the plugin subscribed to) a NoSuchMethod exception.
The "bug" was created between DEV442 and DEV449. So 442 works, 449 doesn't. I want to help but I don't know how to find the commits that were committed in that time span.

When I have time I will test all builds up to 449 beginning from 442.

Edit1: 445 doesn't work
Edit2: 447 doesn't work
Edit3: 446 doesn't work.

**Comment by ST-DDT** [comment]
Could you please post the stacktrace of that exception?

**Comment by randombyte-developer** [comment]
Stacktrace while writing something in the chat with only Spongy installed(https://forums.spongepowered.org/t/spongy-a-very-spongy-essential-plugin-v0-4-dev-extrachat-compatability-fix/6975):

``[18:32:55] [Server thread/ERROR] [Sponge]: Could not pass ServerChatEvent to Spo
ngePlugin:Spongy{0.2}
java.lang.NoSuchMethodError: org.spongepowered.api.event.message.MessageEvent.se
tMessage(Lorg/spongepowered/api/text/Text;)V
        at com.terminalbit.spongy.Main.onMessage(Main.java:112) ~[Main.class:?]
        at org.spongepowered.common.event.handler.MessageEventHandler_Main_onMes
sage4.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredHandler.handle(RegisteredHan
dler.java:86) ~[RegisteredHandler.class:1.8-1371-2.1DEV-447+unknown-b447.git-unk
nown]
        at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventMan
ager.java:248) [SpongeEventManager.class:1.8-1371-2.1DEV-447+unknown-b447.git-un
known]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEvent
Manager.java:82) [SpongeModEventManager.class:1.8-1371-2.1DEV-447+unknown-b447.g
it-unknown]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.jav
a:56) [EventBus.class:?]
        at net.minecraftforge.common.ForgeHooks.onServerChatEvent(ForgeHooks.jav
a:431) [ForgeHooks.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPl
ayServer.java:796) [rj.class:?]
        at net.minecraft.network.play.client.C01PacketChatMessage.func_180757_a(
SourceFile:37) [lu.class:?]
        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(
SourceFile:9) [lu.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [ih.class
:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [
?:1.8.0_31]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_31]
        at net.minecraftforge.fml.common.FMLCommonHandler.callFuture(FMLCommonHa
ndler.java:709) [FMLCommonHandler.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.jav
a:655) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(Dedicated
Server.java:364) [po.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.jav
a:598) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:478) [M
inecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_31]
[18:32:55] [Server thread/INFO]: <KitCrafty> Test``

**Comment by ST-DDT** [comment]
IMO This looks like a bug in SpongyPlugin. 
See the first line is located in that plugin.
com.terminalbit.spongy.Main.onMessage(Main.java:112) ~[Main.class:?]
Afaik the API has changed an the plugin needs an update.

**Comment by randombyte-developer** [comment]
I coded myself just now a test plugin. While looking which API version to use I saw that API 2.1 is there but I didn't saw an announcement(so maybe the developer didn't see that too).
My plugin works.

So sorry for opening an issue. I should have "tested" the bug more. :smile:
