### ISSUE TITLE
Problem loading javassist because of FML

### ISSUE THREAD

**Issue by greatman** [SpongePowered/Sponge#281]
Having javassist (http://www.csg.ci.i.u-tokyo.ac.jp/~chiba/javassist/) in a plugin cause this stacktrace to happen. 
This library is required by Hikari-CP, a JDBC connection pool library (https://github.com/brettwooldridge/HikariCP). It prevents the ClassPool class to be loaded.

How to reproduce:
1. Get this plugin
https://www.dropbox.com/s/ulld11xnuj4ut7f/craftconomy3-3.2.2-SNAPSHOT.jar?dl=0
2. Put it in the mods folder then launch the server, the stacktrace will be during startup. 

```java
[22:58:50] [Server thread/ERROR] [FML/]: There was a problem reading the entry com/greatmancode/javassist/ClassPool.class in the jar C:\Users\William\Desktop\forgeserver\mods\craftconomy3-3.2.2-SNAPSHOT.jar - probably a corrupt zip
net.minecraftforge.fml.common.LoaderException: java.lang.ArrayIndexOutOfBoundsException: 113

	at net.minecraftforge.fml.common.discovery.asm.ASMModParser.<init>(ASMModParser.java:58) ~[ASMModParser.class:?]
	at net.minecraftforge.fml.common.discovery.JarDiscoverer.discover(JarDiscoverer.java:74) [JarDiscoverer.class:?]
	at net.minecraftforge.fml.common.discovery.ContainerType.findMods(ContainerType.java:42) [ContainerType.class:?]
	at net.minecraftforge.fml.common.discovery.ModCandidate.explore(ModCandidate.java:71) [ModCandidate.class:?]
	at net.minecraftforge.fml.common.discovery.ModDiscoverer.identifyMods(ModDiscoverer.java:131) [ModDiscoverer.class:?]
	at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:348) [Loader.class:?]
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:469) [Loader.class:?]
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:87) [FMLServerHandler.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:355) [FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117) [po.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:438) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_45]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 113
	at org.objectweb.asm.ClassReader.a(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
	at org.objectweb.asm.ClassReader.readUTF8(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
	at org.objectweb.asm.ClassReader.b(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
	at org.objectweb.asm.ClassReader.accept(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
	at org.objectweb.asm.ClassReader.accept(Unknown Source) ~[asm-all-5.0.3.jar:5.0.3]
	at net.minecraftforge.fml.common.discovery.asm.ASMModParser.<init>(ASMModParser.java:53) ~[ASMModParser.class:?]
	... 11 more
```

**Comment by zml2008** [comment]
HikariCP is already included in Sponge -- this seems like a classloading issue that is legitimate, but any particular reason you aren't using Sponge's SqlService?

**Comment by greatman** [comment]
@zml2008 Multi-server support in the same .jar basicly. Hikari isn't in Bukkit/Canary

**Comment by zml2008** [comment]
ah, makes sense

**Comment by Aaron1011** [comment]
@greatman: This appears to be a problem with the format of the class file, or possibly a bug in ASM.

Can you try rebuilding the plugin?

**Comment by greatman** [comment]
the javap output of ClassPool.class (put here for record purposes)

https://gist.github.com/greatman/a6dc235adfc842f94c0c

**Comment by greatman** [comment]
Looks like relocate of the gradle shadow plugin played with the library compilation. Once I commented my relocate line, it started to work fine.

**Comment by Zidane** [comment]
@greatman 

Is this still an issue?

**Comment by greatman** [comment]
@Zidane, didn't retry yet with the relocate again. Aaron said it was working for him, i'll need to check it out.

**Comment by Aaron1011** [comment]
Closing, as this was a issue with shading javassist
