### ISSUE TITLE
Locally, user address is not InetSocketAddress

### ISSUE THREAD

**Issue by jb-aero** [SpongePowered/Sponge#308]
```
java.lang.ClassCastException: io.netty.channel.local.LocalAddress cannot be cast to java.net.InetSocketAddress
	at net.minecraft.network.NetworkManager.getAddress(NetworkManager.java:50)
	at net.minecraft.network.NetHandlerPlayServer.getAddress(NetHandlerPlayServer.java:92)
	at com.laytonsmith.abstraction.sponge.entities.SpongeMCPlayer.getAddress(SpongeMCPlayer.java:92)
	at com.laytonsmith.core.functions.PlayerManagement$pinfo.exec(PlayerManagement.java:907)
	at com.laytonsmith.core.Script.eval(Script.java:352)
	at com.laytonsmith.core.Script.seval(Script.java:239)
	at com.laytonsmith.core.functions.DataHandling$eval.execs(DataHandling.java:3746)
```
Occurred when calling
```
player.getConnection().getAddress();
```
with the Forge version of Sponge running on the client in a single-player world.

**Comment by loganspeck** [comment]
Mind doing a version dump of Forge and Sponge?

**Comment by jb-aero** [comment]
Sponge was 1.8-1446-2.1DEV-490
Forge was 11.14.3.1450

**Comment by JBYoshi** [comment]
Netty doesn't use an actual socket to communicate if the channel is a local channel. It would be possible to simply return `127.0.0.1`, except for the fact that there is no port.

**Comment by Cactose** [comment]
Was about to report this myself, really annoying. Need that port! D:

Still does it in the newest version of Sponge (sponge-1.8-1487-2.1DEV-525), and with the game 'Opened to LAN'.
