### ISSUE TITLE
ObjectMappingException when loading an ItemStack from config

### ISSUE THREAD

**Issue by Yeregorix** [SpongePowered/Sponge#3103]
**I am currently running**
- SpongeVanilla version: 1.12.2-7.2.4-RC380
- Java version: 1.8.0_232
- Operating System: Windows 10

**Issue description**
It's no longer possible to load an `ItemStack` nor an `ItemStackSnapshot` from a `ConfigurationNode`.

**Test code**
```java
@Listener
public void onServerStarted(GameStartedServerEvent e) throws IOException, ObjectMappingException {
	LOGGER.info(this.configLoader.load().getNode("test").getValue(TypeToken.of(ItemStack.class)).getType().getId());
}
```

**Config file**
```
test {
    Count=1
    ItemType="minecraft:leather"
    UnsafeDamage=0
}
```

**Expected result** (SV 1.12.2-7.2.4-RC379)
```
[12:20:38 INFO] [TestPlugin]: minecraft:leather
```

**Current result** (SV 1.12.2-7.2.4-RC380)
```
[12:19:00 ERROR] [Sponge]: Could not pass GameStartedServerEvent$Impl to Plugin{id=testplugin, name=TestPlugin, version=1.0.0, description=A test plugin, authors=[Yeregorix], source=mods\TestPlugin.jar}
ninja.leaping.configurate.objectmapping.ObjectMappingException: Could not translate DataSerializable of type: org.spongepowered.api.item.inventory.ItemStack
	at org.spongepowered.common.config.DataSerializableTypeSerializer.lambda$deserialize$1(DataSerializableTypeSerializer.java:64) ~[DataSerializableTypeSerializer.class:1.12.2-7.2.4-RC380]
	at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_162]
	at org.spongepowered.common.config.DataSerializableTypeSerializer.deserialize(DataSerializableTypeSerializer.java:64) ~[DataSerializableTypeSerializer.class:1.12.2-7.2.4-RC380]
	at org.spongepowered.common.config.DataSerializableTypeSerializer.deserialize(DataSerializableTypeSerializer.java:44) ~[DataSerializableTypeSerializer.class:1.12.2-7.2.4-RC380]
	at ninja.leaping.configurate.SimpleConfigurationNode.getValue(SimpleConfigurationNode.java:232) ~[spongevanilla.jar:1.12.2-7.2.4-RC380]
	at ninja.leaping.configurate.ConfigurationNode.getValue(ConfigurationNode.java:595) ~[spongevanilla.jar:1.12.2-7.2.4-RC380]
	at net.smoofyuniverse.test.TestPlugin.onServerStarted(TestPlugin.java:81) ~[TestPlugin.class:?]
	at org.spongepowered.common.event.listener.GameStartedServerEventListener_TestPlugin_onServerStarted4.handle(Unknown Source) ~[?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:97) ~[RegisteredListener.class:1.12.2-7.2.4-RC380]
	at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:435) ~[SpongeEventManager.class:1.12.2-7.2.4-RC380]
	at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:480) ~[SpongeEventManager.class:1.12.2-7.2.4-RC380]
	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:255) ~[SpongeImpl.class:1.12.2-7.2.4-RC380]
	at org.spongepowered.common.SpongeImpl.postState(SpongeImpl.java:263) ~[SpongeImpl.class:1.12.2-7.2.4-RC380]
	at org.spongepowered.server.SpongeVanilla.onServerStarting(SpongeVanilla.java:177) ~[SpongeVanilla.class:1.12.2-7.2.4-RC380]
	at net.minecraft.server.dedicated.DedicatedServer.handler$zpb000$vanilla$callServerStarting(SourceFile:2272) ~[nz.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(SourceFile:233) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.run(SourceFile:434) ~[MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
```

**Comment by zml2008** [comment]
Reproduced & figured out what the issue is, I'll have a fix ready soon.

seems like i incorrectly assumed that only root nodes would be converted to DataViews, whoops.
