### ISSUE TITLE
Fishing rods crash MC clients

### ISSUE THREAD

**Issue by DarkArc** [SpongePowered/Sponge#311]
Using a fishing rod will crash the MC client if Sponge is installed client side.
````java
java.lang.ClassCastException: net.minecraft.client.entity.EntityPlayerSP cannot be cast to org.spongepowered.api.entity.player.Player
	at net.minecraft.item.ItemFishingRod.func_77659_a(SourceFile:58)
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:150)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78769_a(PlayerControllerMP.java:437)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1519)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2041)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1028)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:345)
	at net.minecraft.client.main.Main.main(SourceFile:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
````

**Comment by Aaron1011** [comment]
This issue, as well as https://github.com/SpongePowered/Sponge/issues/311, are symptoms of a broader problem: 

The implementation of Sponge on the client isn't well defined.

We haven't really addressed how Sponge interfaces should be implemented on the client. Th above issue is specifically a problem with `Player`. While just implementing `Player` brings its own problems (how do we deal with `PlayerConnection` from a client-side context), many other issues are going to need to be considered.
