### ISSUE TITLE
Leads crash MC clients

### ISSUE THREAD

**Issue by DarkArc** [SpongePowered/Sponge#312]
Using a lead on any entity will crash the MC client if Sponge is installed client side.
````java
java.lang.ClassCastException: net.minecraft.client.entity.EntityPlayerSP cannot be cast to org.spongepowered.api.entity.player.Player
	at net.minecraft.entity.EntityLiving.callLeashEvent(EntityLiving.java:97)
	at net.minecraft.entity.EntityLiving.func_130002_c(EntityLiving.java:966)
	at net.minecraft.entity.player.EntityPlayer.func_70998_m(EntityPlayer.java:1174)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78768_b(PlayerControllerMP.java:478)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1474)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2041)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1028)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:345)
	at net.minecraft.client.main.Main.main(SourceFile:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
````

**Comment by JBYoshi** [comment]
Explanation: `EntityPlayerMP` (server-side player) implements `Player` via a mixin. `EntityPlayerSP` (client-side, active player) does not. Forge fores a leash event, and Sponge tries to cast the `EntityPlayerSP` to a `Player` (as only `Player`s can leash entities), but that fails as there is no mixin for `EntityPlayerSP`.

**Comment by JBYoshi** [comment]
See #311
