### ISSUE TITLE
Problem with HotSwapping

### ISSUE THREAD

**Issue by DerTiedemann** [SpongePowered/Sponge#313]
Useing a command in any way, when debugging a plugin results in a crash. Server with no plugin added works fine.

```
---- Minecraft Crash Report ----
// But it works on my machine.

Time: 21.07.15 13:47
Description: Exception in server tick loop

java.lang.NoSuchMethodError: org.spongepowered.api.service.command.CommandService.process(Lorg/spongepowered/api/util/command/CommandSource;Ljava/lang/String;)Lcom/google/common/base/Optional;
	at net.minecraft.command.ServerCommandManager.executeCommand(ServerCommandManager.java:85)
	at net.minecraft.server.dedicated.DedicatedServer.executePendingCommands(DedicatedServer.java:424)
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:386)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:669)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:540)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_45, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 452984304 bytes (431 MB) / 788004864 bytes (751 MB) up to 1894252544 bytes (1806 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.3.1487 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forgeSrc-1.8-11.14.3.1487.jar) 
	UCHIJAAAA	Forge{11.14.3.1487} [Minecraft Forge] (forgeSrc-1.8-11.14.3.1487.jar) 
	UCHIJAAAA	Sponge{@VERSION@} [SpongePowered Sponge] (minecraft.jar) 
	UCHIJAAAA	VaroOnRails{${version}} [VaroOnRails] (main) 
	Loaded coremods (and transformers): 
SpongeCoremod (unknown)
  
	Profiler Position: N/A (disabled)
	Player Count: 0 / 20; []
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

```

**Comment by JBYoshi** [comment]
From what I can tell, you aren't using the latest version. (I know it isn't the latest version because I changed the return type of that method in my commands PR.) Grab the latest API and implementation, then let me know if it's working.

**Comment by JBYoshi** [comment]
Actually, you probably need to wait until Sponge/SpongeVanilla update their common refs.

**Comment by DerTiedemann** [comment]
Updated my whole envoirement, but still the server crashes when a plugin is loaded with HotSwapping
I could imagine something is wrong with my setup, but everything was done as described in to doc

```
---- Minecraft Crash Report ----
// I'm sorry, Dave.

Time: 21.07.15 19:34
Description: Exception in server tick loop

java.lang.NoSuchMethodError: org.spongepowered.api.service.command.CommandService.process(Lorg/spongepowered/api/util/command/CommandSource;Ljava/lang/String;)Lcom/google/common/base/Optional;
	at net.minecraft.command.ServerCommandManager.executeCommand(ServerCommandManager.java:85)
	at net.minecraft.server.dedicated.DedicatedServer.executePendingCommands(DedicatedServer.java:424)
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:386)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:669)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:540)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_45, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 345436544 bytes (329 MB) / 801112064 bytes (764 MB) up to 1894252544 bytes (1806 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 11, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.3.1487 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forgeSrc-1.8-11.14.3.1487.jar) 
	UCHIJAAAA	Forge{11.14.3.1487} [Minecraft Forge] (forgeSrc-1.8-11.14.3.1487.jar) 
	UCHIJAAAA	Sponge{1.8-1487-2.1DEV-0} [SpongePowered Sponge] (minecraft.jar) 
	UCHIJAAAA	varoonrails{${version}} [VaroOnRais] (main) 
	Loaded coremods (and transformers): 
SpongeCoremod (unknown)
  
	Profiler Position: N/A (disabled)
	Player Count: 0 / 20; []
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)
```

**Comment by Zidane** [comment]
@DerTiedemann 

Looks like you don't have all the dependencies. You are missing Guava. I recommend re-reading the README from top to bottom and try again.

**Comment by JBYoshi** [comment]
No, that's not it. I think Sponge's common ref needs to be updated - that ought to fix it.

**Comment by ST-DDT** [comment]
@Zidane Where did you read that / How did you get that impression?
From my experience i would exclude that possibility based on the given log message.

@DerTiedemann 
Try following these instructions:
https://github.com/SpongePowered/Sponge#updating-your-clone

Isn't there a build server out there with pre-build artifacts?

**Comment by Zidane** [comment]
Ignore my post, I clearly misread.

@JBYoshi is correct. The refs simply need to be bumped.

**Comment by DerTiedemann** [comment]
Updating refs fixed it
