### ISSUE TITLE
MC Crash, tried make a fresh server, still crash.

### ISSUE THREAD

**Issue by gogasos** [SpongePowered/Sponge#314]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  SpongeCoremod (sponge-1.8-1487-2.1DEV-524.jar)
Contact their authors BEFORE contacting forge

// There are four lights!

Time: 2015-07-25 13:34
Description: Exception in server tick loop

java.lang.IllegalStateException: No subject present for user net.minecraft.server.dedicated.DedicatedServer@596ba78a
	at net.minecraft.server.MinecraftServer.getContainingCollection(MinecraftServer.java:98)
	at org.spongepowered.common.SpongeBootstrap$1.apply(SpongeBootstrap.java:101)
	at org.spongepowered.common.SpongeBootstrap$1.apply(SpongeBootstrap.java:98)
	at org.spongepowered.api.service.SimpleServiceManager$SimpleServiceReference.registered(SimpleServiceManager.java:191)
	at org.spongepowered.api.service.SimpleServiceManager.setProvider(SimpleServiceManager.java:90)
	at org.spongepowered.mod.SpongeMod.onInitialization(SpongeMod.java:189)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:731)
	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:360)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:210)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:438)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 898904584 bytes (857 MB) / 1001914368 bytes (955 MB) up to 1001914368 bytes (955 MB)
	JVM Flags: 2 total; -Xmx1024M -Xms1024M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.10 FML v8.0.99.99 Minecraft Forge 11.14.3.1498 4 mods loaded, 4 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHI	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHI	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8-11.14.3.1498-universal.jar) 
	UCHI	Forge{11.14.3.1498} [Minecraft Forge] (forge-1.8-11.14.3.1498-universal.jar) 
	UCHE	Sponge{1.8-1487-2.1DEV-524} [SpongePowered Sponge] (minecraft.jar) 
	Loaded coremods (and transformers): 
SpongeCoremod (sponge-1.8-1487-2.1DEV-524.jar)
  
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by modwizcode** [comment]
I'm not sure how this is possible. Are you using any plugins? Also can we get the full log, not just a crash log? It's hard to debug a situation without a full description and logs.

**Comment by JBYoshi** [comment]
I know what this means, I just need to pull up the code.

**Comment by modwizcode** [comment]
I figured someone might have the solution already. I'm just trying to get
people to post useful information when they have a crash.

**Comment by Mumfrey** [comment]
First thing to check is whether it works when using the correct version of Forge.

**Comment by JBYoshi** [comment]
This seems to be purely a Sponge problem - probably a bug in the service registry. I'm on my phone right now, I'll pull up my laptop so I can debug this.

**Comment by JBYoshi** [comment]
See https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/org/spongepowered/common/service/permission/DataFactoryCollection.java#L63. `putIfAbsent()` does not return the new value; it returns the existing value.
