### ISSUE TITLE
NoSuchMethodError when calling server.getBoundAddress() in 'Open To LAN' game

### ISSUE THREAD

**Issue by Cactose** [SpongePowered/Sponge#317]
Forge version: v11.14.3.1491
Sponge version: sponge-1.8-1487-2.1DEV-525

Attempting to call a Server instance's getBoundAddress() (to get the port the server is bound to) results in a NoSuchMethodError when called from a singleplayer-server with the game Opened to LAN.

````
java.lang.NoSuchMethodError: net.minecraft.server.MinecraftServer.func_71211_k()Ljava/lang/String;
	at net.minecraft.server.MinecraftServer.getBoundAddress(MinecraftServer.java:170) ~[MinecraftServer.class:?]
	at io.grappl.calcarea.GrapplCommand.process(GrapplCommand.java:85) ~[GrapplCommand.class:?]
	at org.spongepowered.api.util.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:344) ~[SimpleDispatcher.class:1.8-1487-2.1DEV-525+unknown-b525.git-unknown]
	at org.spongepowered.api.service.command.SimpleCommandService.process(SimpleCommandService.java:243) [SimpleCommandService.class:1.8-1487-2.1DEV-525+unknown-b525.git-unknown]
	at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:80) [cl.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:812) [rj.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:791) [rj.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_180757_a(SourceFile:37) [lu.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9) [lu.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [ih.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_31]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_31]
	at net.minecraftforge.fml.common.FMLCommonHandler.callFuture(FMLCommonHandler.java:714) [FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:656) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:598) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:164) [cyk.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:478) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_31]
````

**Comment by JBYoshi** [comment]
Apparently `MixinMinecraftServer.getBoundAddress()` is calling `MinecraftServer.getBoundAddress()` and `MinecraftServer.getPort()`, which are only on the dedicated server (i.e. they have `@SideOnly(Side.SERVER)`.

**Comment by Cactose** [comment]
I don't have much experience with Sponge's mixins, but I haven't had any luck trying to solve this myself. Minecraft doesn't store the port of the LAN server anywhere accessible to the Sponge as far as I can see.

The only two solutions I've found are overwriting the openToLAN() method and remembering the port, or creating a chat listener and extracting the port from the chat. Both seem clunky.

**Comment by clienthax** [comment]
Could you not get it from networksystem.endpoints?

**Comment by JBYoshi** [comment]
One thing to think about: what should `getBoundAddress()` return on the client if the user hasn't selected "Open to LAN" and, therefore, the `IntegratedServer` is not bound to a port?

**Comment by Zidane** [comment]
@JBYoshi 

I can just make it return an Optional in the API.

**Comment by JBYoshi** [comment]
@Zidane Sounds good.

**Comment by Zidane** [comment]
@JBYoshi 

Its actually already an Optional. In SinglePlayer, we can just return empty.

**Comment by simon816** [comment]
Was fixed in https://github.com/SpongePowered/SpongeCommon/commit/eeddcb1bb9faa6d188560ea9b26a95c8842bf7a7
