### ISSUE TITLE
Forge Essentials 1.8-1.8.0.21 results in "Unable to Launch"

### ISSUE THREAD

**Issue by ThornsOfire** [SpongePowered/Sponge#324]
Sponge 1.8-1499-2.1DEV-549 as main server build, using sponge compiler to generate fresh server structure.

Running:
Windows 7:amd64
Java 64-Bit Server VM, version 1.8.0_51
Minecraft 1.8
Forge Mod Loader version 8.99.196.1499
Forge Essentials - 1.8-1.8.0.21
WorldEdit - 6.1.1-SNAPSHOT

Results in a "Unable to Launch"

Here is the failed launch:
[19:39:52] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLServerTweaker
[19:39:52] [main/INFO]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLServerTweaker
[19:39:52] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLServerTweaker
[19:39:52] [main/INFO]: Forge Mod Loader version 8.99.196.1499 for Minecraft 1.8 loading
[19:39:52] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_51, running on Windows 7:amd64:6.1, installed at C:\Program Files\Java\jre1.8.0_51
[19:39:52] [main/INFO]: Found a command line coremod : org.spongepowered.mod.SpongeCoremod
[19:39:54] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.4.4 Source=file:/C:/Users/Peav/Desktop/Minecraft%20Server/sponge.jar Env=SERVER
[19:39:54] [main/INFO]: Adding new token provider org.spongepowered.mod.SpongeCoremod$TokenProvider to MixinEnvironment[PREINIT]
[19:39:54] [main/INFO]: Adding new token provider org.spongepowered.mod.SpongeCoremod$TokenProvider to MixinEnvironment[DEFAULT]
[19:39:54] [main/INFO]: Loading tweaker com.forgeessentials.core.preloader.FELaunchHandler from forgeessentials-1.8-1.8.0.21-server.jar
[19:39:54] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[19:39:54] [main/INFO]: Loading tweak class name org.spongepowered.asm.mixin.MixinEnvironment$EnvironmentStateTweaker
[19:39:54] [main/INFO]: Loading tweak class name com.forgeessentials.core.preloader.FELaunchHandler
[19:39:54] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[19:39:54] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[19:39:54] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[19:39:54] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:39:55] [main/INFO]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[19:39:55] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:39:55] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:39:55] [main/INFO]: Calling tweak class org.spongepowered.asm.mixin.MixinEnvironment$EnvironmentStateTweaker
[19:39:55] [main/INFO]: Calling tweak class com.forgeessentials.core.preloader.FELaunchHandler
[19:39:55] [main/ERROR]: Unable to launch
java.lang.IllegalStateException: MixinBootstrap.register() called before MixinBootstrap.preInit()
at org.spongepowered.asm.launch.MixinBootstrap.register(MixinBootstrap.java:156) ~[sponge.jar:1.8-1499-2.1DEV-544+unknown-b544.git-unknown]
at org.spongepowered.asm.launch.MixinTweaker.acceptOptions(MixinTweaker.java:103) ~[sponge.jar:1.8-1499-2.1DEV-544+unknown-b544.git-unknown]
at com.forgeessentials.core.preloader.FELaunchHandler.acceptOptions(FELaunchHandler.java:76) ~[forgeessentials-1.8-1.8.0.21-server.jar:?]
at net.minecraft.launchwrapper.Launch.launch(Launch.java:113) [launchwrapper-1.9.jar:?]
at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.9.jar:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_51]
at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43) [forge-1.8-11.14.3.1499.jar:?]
at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12) [forge-1.8-11.14.3.1499.jar:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_51]
at org.spongepowered.launch.handlers.RunHandler.run(RunHandler.java:85) [sponge.jar:1.8-1499-2.1DEV-544+unknown-b544.git-unknown]
at org.spongepowered.launch.Main.dispatch(Main.java:134) [sponge.jar:1.8-1499-2.1DEV-544+unknown-b544.git-unknown]
at org.spongepowered.launch.Main.main(Main.java:82) [sponge.jar:1.8-1499-2.1DEV-544+unknown-b544.git-unknown]

**Comment by luacs1998** [comment]
Close this, I'll re-file on my end. Thanks.

**Comment by ThornsOfire** [comment]
Excellent thanks lucas you're on the game!
