### ISSUE TITLE
Error SpongeCoremod Ticking world

### ISSUE THREAD

**Issue by Okinakuso** [SpongePowered/Sponge#3254]
Hi ! I have this problem on my server. Someone can help me ? Thanks

---- Minecraft Crash Report ----

WARNING: coremods are present:
  SpongeCoremod (spongeforge-1.12.2-2838-7.2.2.jar)
  PixelmoneyCoreMod (PixelMoney-1.12.2-3.0.5.jar)
Contact their authors BEFORE contacting forge

// Uh... Did I do that?

Time: 10/01/21 21:27
Description: Exception ticking world

java.lang.NullPointerException: Exception ticking world
	at net.minecraft.world.storage.loot.LootPool.func_186452_a(LootPool.java:46)
	at net.minecraft.world.storage.loot.LootPool.func_186449_b(LootPool.java:83)
	at net.minecraft.world.storage.loot.LootTable.func_186462_a(LootTable.java:42)
	at net.minecraft.world.storage.loot.LootTable.func_186460_a(LootTable.java:57)
	at net.minecraft.tileentity.TileEntityLockableLoot.func_184281_d(TileEntityLockableLoot.java:79)
	at net.minecraft.tileentity.TileEntityLockableLoot.func_70301_a(TileEntityLockableLoot.java:106)
	at org.spongepowered.common.item.inventory.util.ContainerUtil.performBlockInventoryDrops(ContainerUtil.java:190)
	at net.minecraft.inventory.InventoryHelper.redirect$zhn000$impl$dropItemsAndThrowEvents(SourceFile:555)
	at net.minecraft.inventory.InventoryHelper.func_180175_a(SourceFile:15)
	at net.minecraft.block.BlockChest.func_180663_b(BlockChest.java:406)
	at net.minecraft.world.chunk.Chunk.bridge$setBlockState(Chunk.java:3752)
	at org.spongepowered.common.event.tracking.PhaseTracker.setBlockState(PhaseTracker.java:892)
	at net.minecraft.world.WorldServer.func_180501_a(WorldServer.java:4517)
	at net.minecraft.world.gen.structure.StructureComponent.func_175811_a(StructureComponent.java:236)
	at net.minecraft.world.gen.structure.StructureComponent.func_175804_a(StructureComponent.java:288)
	at net.minecraft.world.gen.structure.StructureMineshaftPieces$Corridor.func_74875_a(SourceFile:452)
	at net.minecraft.world.gen.structure.StructureStart.func_75068_a(StructureStart.java:47)
	at net.minecraft.world.gen.structure.MapGenStructure.func_175794_a(MapGenStructure.java:1081)
	at net.minecraft.world.gen.structure.MapGenStructure.populate(MapGenStructure.java:565)
	at org.spongepowered.api.world.gen.Populator.populate(Populator.java:97)
	at org.spongepowered.mod.world.gen.SpongeChunkGeneratorForge.func_185931_b(SpongeChunkGeneratorForge.java:281)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1019)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:990)
	at net.minecraft.world.gen.ChunkProviderServer.redirect$bal000$impl$populateChunkThroughSponge(ChunkProviderServer.java:2082)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
	at net.minecraft.server.management.PlayerChunkMapEntry.redirect$bae000$forgeImpl$UpdateLoadedChunk(PlayerChunkMapEntry.java:1576)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.world.storage.loot.LootPool.func_186452_a(LootPool.java:46)
	at net.minecraft.world.storage.loot.LootPool.func_186449_b(LootPool.java:83)
	at net.minecraft.world.storage.loot.LootTable.func_186462_a(LootTable.java:42)
	at net.minecraft.world.storage.loot.LootTable.func_186460_a(LootTable.java:57)
	at net.minecraft.tileentity.TileEntityLockableLoot.func_184281_d(TileEntityLockableLoot.java:79)
	at net.minecraft.tileentity.TileEntityLockableLoot.func_70301_a(TileEntityLockableLoot.java:106)
	at org.spongepowered.common.item.inventory.util.ContainerUtil.performBlockInventoryDrops(ContainerUtil.java:190)
	at net.minecraft.inventory.InventoryHelper.redirect$zhn000$impl$dropItemsAndThrowEvents(SourceFile:555)
	at net.minecraft.inventory.InventoryHelper.func_180175_a(SourceFile:15)
	at net.minecraft.block.BlockChest.func_180663_b(BlockChest.java:406)
	at net.minecraft.world.chunk.Chunk.bridge$setBlockState(Chunk.java:3752)
	at org.spongepowered.common.event.tracking.PhaseTracker.setBlockState(PhaseTracker.java:892)
	at net.minecraft.world.WorldServer.func_180501_a(WorldServer.java:4517)
	at net.minecraft.world.gen.structure.StructureComponent.func_175811_a(StructureComponent.java:236)
	at net.minecraft.world.gen.structure.StructureComponent.func_175804_a(StructureComponent.java:288)
	at net.minecraft.world.gen.structure.StructureMineshaftPieces$Corridor.func_74875_a(SourceFile:452)
	at net.minecraft.world.gen.structure.StructureStart.func_75068_a(StructureStart.java:47)
	at net.minecraft.world.gen.structure.MapGenStructure.func_175794_a(MapGenStructure.java:1081)
	at net.minecraft.world.gen.structure.MapGenStructure.populate(MapGenStructure.java:565)
	at org.spongepowered.api.world.gen.Populator.populate(Populator.java:97)
	at org.spongepowered.mod.world.gen.SpongeChunkGeneratorForge.func_185931_b(SpongeChunkGeneratorForge.java:281)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1019)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:990)
	at net.minecraft.world.gen.ChunkProviderServer.redirect$bal000$impl$populateChunkThroughSponge(ChunkProviderServer.java:2082)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
	at net.minecraft.server.management.PlayerChunkMapEntry.redirect$bae000$forgeImpl$UpdateLoadedChunk(PlayerChunkMapEntry.java:1576)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)

-- Affected level --
Details:
	Level name: pixelsurvie
	All players: 1 total; [EntityPlayerMP['YamiKurai'/63, l='pixelsurvie', x=13532,01, y=105,00, z=20053,74]]
	Chunk stats: ServerChunkCache: 823 Drop: 0
	Level seed: -661457691060111737
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (280,70,-27), Chunk: (at 8,4,5 in 17,-2; contains blocks 272,0,-32 to 287,255,-17), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 211482916 game time, 5957954 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 17812 (now: true), thunder time: 13746 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false

-- Sponge PhaseTracker --
Details:
	Phase Stack: /************************************************************************************************/
/*   - Phase: Generation{Terrain:TERRAIN_GENERATION}                                            */
/*     Context:                                                                                 */
/*     - World: WorldServer{Name=pixelsurvie, DimensionId=0, DimensionType=minecraft:overworld} */
/*   - Phase: Generation{Terrain:TERRAIN_GENERATION}                                            */
/*     Context:                                                                                 */
/*     - World: WorldServer{Name=pixelsurvie, DimensionId=0, DimensionType=minecraft:overworld} */
/************************************************************************************************/

Stacktrace:
	at net.minecraft.server.MinecraftServer.handler$zje000$onCrashReport(MinecraftServer.java:4687)
	at net.minecraft.server.MinecraftServer.func_71230_b(MinecraftServer.java:889)
	at net.minecraft.server.dedicated.DedicatedServer.func_71230_b(DedicatedServer.java:371)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:554)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 4.19.0-10-amd64
	Java Version: 1.8.0_251, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1635711792 bytes (1559 MB) / 4039602176 bytes (3852 MB) up to 31136546816 bytes (29694 MB)
	JVM Flags: 22 total; -Xms512M -XX:PermSize=384M -XX:MaxPermSize=768M -XX:-UseConcMarkSweepGC -XX:+UseParNewGC -XX:+UseNUMA -XX:+CMSParallelRemarkEnabled -XX:+UseAdaptiveGCBoundary -XX:-UseGCOverheadLimit -XX:+UseBiasedLocking -XX:SurvivorRatio=8 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=15 -XX:UseSSE=3 -XX:+UseLargePages -XX:+UseFastAccessorMethods -XX:+UseStringCache -XX:+UseCompressedOops -XX:+OptimizeStringConcat -XX:+AggressiveOpts -XX:MaxGCPauseMillis=50 -XX:ParallelGCThreads=2
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 46 mods loaded, 46 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

**Comment by ImMorpheus** [comment]
Please follow the issue template, it's actually rather important if you want to get dev attention to fix your issue.

Edit this issue with the required details / template, and I'll reopen and hide this comment.
