### ISSUE TITLE
Brigadier parsing error with Selector.Builder#score

### ISSUE THREAD

**Issue by thibaulthenry** [SpongePowered/Sponge#3287]
```
SpongeVanilla version: 1.16.4-8.0.0 (commit 38e815d4c54333e045fcf10685d5eed989de0b91)
Java version: 8
Operating System: Windows 10
Plugins: Cosmos
```

Hey, 

Yesterday I was dealing with selectors and I got a stack when using `Selector.Builder#score`. 
It seems to be related with how Sponge build the selector filters String which brigadier cannot parse.

```
java.lang.IllegalArgumentException: Could not create selector criteria based on input
	at net.minecraft.commands.arguments.selector.EntitySelectorParser.api$handle(SourceFile:1612) ~[?:?]
	at net.minecraft.commands.arguments.selector.EntitySelectorParser.api$handle(SourceFile:1605) ~[?:?]
	at net.minecraft.commands.arguments.selector.EntitySelectorParser.build(SourceFile:1537) ~[?:?]
	at cosmos.registries.listener.impl.perworld.ChatsListener.onPlayerChatEvent(ChatsListener.java:34) ~[ChatsListener.class:?]
	at org.spongepowered.common.event.listener.PlayerChatEventListener_ChatsListener_onPlayerChatEvent14.handle(Unknown Source) ~[?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:97) ~[?:?]
	at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:432) ~[?:?]
	at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:463) ~[?:?]
	at org.spongepowered.common.SpongeCommon.postEvent(SpongeCommon.java:160) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handler$zmc000$vanilla$onProcessChatMessage(SourceFile:2197) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(SourceFile:1201) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$filterTextPacket$1(SourceFile:314) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$filterTextPacket$3(SourceFile:324) ~[?:?]
	at net.minecraft.server.TickTask.run(SourceFile:18) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(SourceFile:144) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(SourceFile:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.redirect$zld000$tracker$wrapAndPerformContextSwitch(SourceFile:4316) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(SourceFile:761) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(SourceFile:155) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(SourceFile:118) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(SourceFile:743) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTask(SourceFile:737) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(SourceFile:127) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(SourceFile:722) ~[?:?]
	at net.minecraft.server.MinecraftServer.runServer(SourceFile:674) ~[?:?]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(SourceFile:257) ~[?:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
Caused by: com.mojang.brigadier.exceptions.CommandSyntaxException: Expected '=' at position 18: ...ponentImpl<--[HERE]
Caused by: com.mojang.brigadier.exceptions.CommandSyntaxException: Expected '=' at position 18: ...ponentImpl<--[HERE]
```

Thanks for reading this issue

**Comment by dualspiral** [comment]
This is something that is incorrect in the API, it should be `addObjective` and adding objectives, not scores. Oversight on my part - correcting this in the API.

`addScore(Score, Range<Integer>)` -> `addObjective(Objective, Range<Integer>)`
