### ISSUE TITLE
Help command broken 

### ISSUE THREAD

**Issue by vlee489** [SpongePowered/Sponge#329]
Forge Version : forge-1.8-11.14.3.1499-universal
Sponge Version : sponge-1.8-1499-2.1DEV-584
OS : Windows 10
Mods/plugins: Total economy, Permissions ex, Adminshop, World Edit (Forge mod)
Java Version: 1.8.1_25

when do /help sponge gives me this error 

    [18:24:04] [Server thread/INFO]: Error occurred while executing command: Could not initialize class ninja.leaping.permissionsex.sponge.SpongeMessageFormatter
    [18:24:04] [Server thread/ERROR] [Sponge]: Error occurred while executing command 'help' for source net.minecraft.server.dedicated.DedicatedServer@eb7c3ed: Could not initialize class ninja.leaping.permissionsex.sponge.SpongeMessageFormatter
    java.lang.NoClassDefFoundError: Could not initialize class ninja.leaping.permissionsex.sponge.SpongeMessageFormatter
        at ninja.leaping.permissionsex.sponge.SpongeCommander.<init>(SpongeCommander.java:50) ~[SpongeCommander.class:?]
        at ninja.leaping.permissionsex.sponge.PEXSpongeCommand.testPermission(PEXSpongeCommand.java:50) ~[PEXSpongeCommand.class:?]
        at org.spongepowered.common.command.SpongeHelpCommand$2$1.apply(SpongeHelpCommand.java:103) ~[sponge-1.8-1499-2.1DEV-584.jar:1.8-1499-2.1DEV-584+unknown-b584.git-unknown]
        at org.spongepowered.common.command.SpongeHelpCommand$2$1.apply(SpongeHelpCommand.java:99) ~[sponge-1.8-1499-2.1DEV-584.jar:1.8-1499-2.1DEV-584+unknown-b584.git-unknown]
        at com.google.common.collect.Iterators$7.computeNext(Iterators.java:647) ~[minecraft_server.1.8.jar:?]
        at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143) ~[minecraft_server.1.8.jar:?]
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138) ~[minecraft_server.1.8.jar:?]
        at com.google.common.collect.Iterators.size(Iterators.java:186) ~[minecraft_server.1.8.jar:?]
        at com.google.common.collect.Collections2$FilteredCollection.size(Collections2.java:211) ~[minecraft_server.1.8.jar:?]
        at java.util.TreeSet.addAll(Unknown Source) ~[?:1.8.0_25]
        at org.spongepowered.common.command.SpongeHelpCommand$2.execute(SpongeHelpCommand.java:98) ~[SpongeHelpCommand$2.class:1.8-1499-2.1DEV-584+unknown-b584.git-unknown]
        at org.spongepowered.api.util.command.spec.CommandSpec.process(CommandSpec.java:334) ~[CommandSpec.class:1.8-1499-2.1DEV-584+unknown-b584.git-unknown]
        at org.spongepowered.api.util.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:345) ~[SimpleDispatcher.class:1.8-1499-2.1DEV-584+unknown-b584.git-unknown]
        at org.spongepowered.api.service.command.SimpleCommandService.process(SimpleCommandService.java:250) [SimpleCommandService.class:1.8-1499-2.1DEV-584+unknown-b584.git-unknown]
        at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:80) [cl.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:400) [po.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:365) [po.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:598) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:478) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_25]

**Comment by vlee489** [comment]
Permission Ex Problem
