### ISSUE TITLE
ParticleEffect can not be serialized

### ISSUE THREAD

**Issue by thibaulthenry** [SpongePowered/Sponge#3311]
```
SpongeVanilla version: 1.16.4-8.0.0 (commit 5a0778bc25a66ea96b6799e6c347b65aa4473592)
Java version: 8
Operating System: Windows 10
Plugins: Cosmos
```

Hey, 

The `toContainer` method of the `ParticleEffect` is putting the minecraft object `SimpleParticleType` (`ParticleType` in Sponge), which leads to an error when trying to write a `ParticleEffect` in an NBT file.

```java
dataContainer.set(Constants.Particles.PARTICLE_TYPE, this.type);
```

![tocontainer](https://user-images.githubusercontent.com/25883318/110225024-7a540480-7ee1-11eb-846c-e87908218d6d.png)

The stack when writing to NBT with the api : 

```
java.lang.IllegalArgumentException: Unable to translate object to NBTBase: net.minecraft.core.particles.SimpleParticleType@56351c02
	at org.spongepowered.common.data.persistence.NBTTranslator.getBaseFromObject(NBTTranslator.java:168) ~[main/:?]
	at org.spongepowered.common.data.persistence.NBTTranslator.containerToCompound(NBTTranslator.java:86) ~[main/:?]
	at org.spongepowered.common.data.persistence.NBTTranslator.containerToCompound(NBTTranslator.java:67) ~[main/:?]
	at org.spongepowered.common.data.persistence.NBTTranslator.translate(NBTTranslator.java:302) ~[main/:?]
	at org.spongepowered.common.data.persistence.NBTDataFormat.writeTo(NBTDataFormat.java:62) ~[main/:?]
	at cosmos.services.io.impl.FinderServiceImpl.writeToFile(FinderServiceImpl.java:203) ~[?:?]
```

Thanks for reading this issue

**Comment by thibaulthenry** [comment]
Hi, I can confirm that the exception is still raised while I'm trying to serialize `ParticleEffect`
