### ISSUE TITLE
API8 SpV: The Dedicated Server is Not Available error-spam loading datapack

### ISSUE THREAD

**Issue by theboomer** [SpongePowered/Sponge#3322]
API-8  Win7, Java 8_281, spongevanilla-universal jar built with tyhdefu fix commit https://github.com/SpongePowered/Sponge/commit/8c84a888258402e4d541bea25b1675f9694c40ab march 9  (Previous many days of builds prevented making a new server, and slowed producing a reproducible way to generate error to post here)
==
Problem: The spongevanilla 1.16.5 server is unable to load files from my datapacks, due to the dedicated server not available.   Conversation with gabizou in discord #plugins channel march 7 PST/march 8 EST 

To reproduce, and simplify one of my datapacks to a few files only, I stripped my mob-death-rewards datapack down to include just two mob kill triggers and execution, and the appropriate load/tick based files.  The datapack is here to download: [www.prennet.com/mobrewards.zip](http://www.prennet.com/mobrewards.zip)

To reproduce the error:
Create a brand new server with universal jar file /bat file, and run/fix eula/rerun etc to get a working baseline spongevanilla server, and stop.  Then move the mobrewards datapack folder/file structures from the zip file into the world datapack folder, and then run.

![image](https://user-images.githubusercontent.com/3393225/110474125-4b8a8980-80ad-11eb-853d-82e00961b412.png)

Errors generated will be spewn for each file like so
![image](https://user-images.githubusercontent.com/3393225/110474339-8d1b3480-80ad-11eb-9bae-322a9b58425b.png)

**Comment by tyhdefu** [comment]
I can reproduce this.
Appears to be an issue with commands being registered too early (before the server is available).
[Here is a full log](https://gist.github.com/tyhdefu/515fdd0c4b57255918994a7006171fcd)

**Comment by zml2008** [comment]
This will be a bit of a fun balancing act for us. With 1.16, Mojang loads data packs before a server instance even exists, and does all command parsing at that point. To accommodate this, we have to load commands before the server is available.

We'll need to figure out a few things to make this play nicely with our commands system:

1. Do we want to ignore permissions checks altogether for datapack loads? Or shift permissions checks to execution time? To make this work, we would have to represent function execution in command context somehow -- either as a context on an existing subject, or as a subject of its own.
2. Are there issues with the server holding on to the CommandContext from parse time onwards? We should make sure any information that could become stale is not held. I think trying to copy Brigadier's parse-time vs execution-time split will cause more problem than it solves. Instead, we'll have to make sure that any Sponge-specific parsing is only performed at execution time (though I think this is already mostly the case).

**Comment by gabizou** [comment]
> 1. Do we want to ignore permissions checks altogether for datapack loads?

We can wrap data pack loads with a PhaseState and check there (Intermediary PermissionService by way of PhaseTracker being the bootstrapped permission service?)

**Comment by dualspiral** [comment]
> We can wrap data pack loads with a PhaseState and check there (Intermediary PermissionService by way of PhaseTracker being the bootstrapped permission service?)

No, because the permission service is server scoped so there'd be nothing to bootstrap on to.

**Comment by theboomer** [comment]
Its been a while before I could test this out, but the recent builds (spongevanilla-1.17-9.0.0-RC659-universal) still throw these errors.  
Is the temp fix not incorporated into the server project , or has it rebroken since?

**Comment by Faithcaio** [comment]
I think the issue is coming from `CommandSourceStackMixin_API` then.
There is no `Subject` in the cause and it then picks the system subject
instead of forwarding `CommandSource.NULL` from `ServerFunctionLibrary`

**Comment by dualspiral** [comment]
> I think the issue is coming from CommandSourceStackMixin_API then.

Uhhh, no? It's doing everything it's meant to be doing. `ServerFunctionLibrary` perhaps should be adding the null source to the cause, which itself may need some mixing into. Even there, there are other considerations - and it's really a pain because of how early it wants to parse the nodes...

There are a lot of nuances to this issue, of which that is only one part. It's not a quick fix. If it was, it would have been done already.

**Comment by MarGar12** [comment]
Bringing this up again, I am also having this issue, but this time on SpongeNeo `1.21.1-21.1.35-12.0.2-RC2149-universal`, hopefully this can be fixed because theres some game changing datapacks in my server like Enhanced Allays, Dynamic Lights, Custom Portals, etc.

**Comment by aromaa** [comment]
@MarGar12 Could you post the full logs?

**Comment by SawFowl** [comment]
This problem also exists on SpongeVanilla.
```yaml
    Minecraft: 1.21.1
    SpongeAPI: 12.1.0-SNAPSHOT
    Sponge: 1.21.1-12.1.0-SNAPSHOT
    SpongeVanilla: 1.21.1-12.0.2-RC2149
    JVM: 21.0.4/64-bit (Eclipse Adoptium)
    OS: Linux/6.1.0-26-amd64 (amd64)
```

[latest.log](https://github.com/user-attachments/files/19568570/latest.log)

**Comment by MarGar12** [comment]
> [@MarGar12](https://github.com/MarGar12) Could you post the full logs?

[debug.log](https://github.com/user-attachments/files/19568752/debug.log)
[latest.log](https://github.com/user-attachments/files/19568753/latest.log)

**Comment by aromaa** [comment]
Thank you, just confirming the underlying cause is still the same.

I think we can provide hotfix for this in 12 and then do the proper fix in 14 and decouple the service layer from the actual engine instance.

**Comment by Faithcaio** [comment]
Underlying Exception which we are loosing here: https://github.com/SpongePowered/Sponge/blob/881a506b2b276621a402f5e5457b89259f86b2dd/src/main/java/org/spongepowered/common/command/brigadier/dispatcher/SpongeCommandDispatcher.java#L382

This is checking Permissions via Permission Plugin (but its not available yet)

```
java.lang.IllegalStateException: The dedicated server is not available!
	at TRANSFORMER/spongevanilla@1.21.4-14.0.0-RC0/org.spongepowered.common.util.Preconditions.checkState(Preconditions.java:33)
	at TRANSFORMER/spongevanilla@1.21.4-14.0.0-RC0/org.spongepowered.common.SpongeGame.server(SpongeGame.java:184)
	at TRANSFORMER/spongevanilla@1.21.4-14.0.0-RC0/org.spongepowered.api.Sponge.server(Sponge.java:138)
	at TRANSFORMER/spongevanilla@1.21.4-14.0.0-RC0/org.spongepowered.common.service.server.permission.SubjectHelper.applySubject(SubjectHelper.java:47)
	at TRANSFORMER/spongevanilla@1.21.4-14.0.0-RC0/org.spongepowered.common.service.server.permission.SpongeSystemSubject.bridge$resolveReferenceOptional(SpongeSystemSubject.java:49)
	at TRANSFORMER/spongevanilla@1.21.4-14.0.0-RC0/org.spongepowered.common.service.server.permission.SpongeSystemSubject.bridge$resolveOptional(SpongeSystemSubject.java:56)
	at TRANSFORMER/spongevanilla@1.21.4-14.0.0-RC0/org.spongepowered.common.service.server.permission.BridgeSubject.hasPermission(BridgeSubject.java:103)
	at TRANSFORMER/spongevanilla@1.21.4-14.0.0-RC0/org.spongepowered.api.service.permission.SubjectProxy.hasPermission(SubjectProxy.java:169)
	at TRANSFORMER/minecraft@1.21.4/net.minecraft.commands.arguments.selector.EntitySelectorParser.handler$zfg000$impl$onAllowSelectors(EntitySelectorParser.java:1866)
	at TRANSFORMER/minecraft@1.21.4/net.minecraft.commands.arguments.selector.EntitySelectorParser.allowSelectors(EntitySelectorParser.java)
	at TRANSFORMER/minecraft@1.21.4/net.minecraft.commands.arguments.EntityArgument.parse(EntityArgument.java:102)
	at TRANSFORMER/minecraft@1.21.4/net.minecraft.commands.arguments.EntityArgument.parse(EntityArgument.java:43)
	at SECURE-BOOTSTRAP/brigadier@1.3.10/com.mojang.brigadier.tree.ArgumentCommandNode.parse(ArgumentCommandNode.java:59)
	at TRANSFORMER/spongevanilla@1.21.4-14.0.0-RC0/org.spongepowered.common.command.brigadier.dispatcher.SpongeCommandDispatcher.parseNodes0(SpongeCommandDispatcher.java:380)
	at TRANSFORMER/spongevanilla@1.21.4-14.0.0-RC0/org.spongepowered.common.command.brigadier.dispatcher.SpongeCommandDispatcher.parseNodes0(SpongeCommandDispatcher.java:484)
	at TRANSFORMER/spongevanilla@1.21.4-14.0.0-RC0/org.spongepowered.common.command.brigadier.dispatcher.SpongeCommandDispatcher.parseNodes0(SpongeCommandDispatcher.java:466)
	at TRANSFORMER/spongevanilla@1.21.4-14.0.0-RC0/org.spongepowered.common.command.brigadier.dispatcher.SpongeCommandDispatcher.parseNodes(SpongeCommandDispatcher.java:339)
	at TRANSFORMER/spongevanilla@1.21.4-14.0.0-RC0/org.spongepowered.common.command.brigadier.dispatcher.SpongeCommandDispatcher.parse(SpongeCommandDispatcher.java:125)
	at TRANSFORMER/spongevanilla@1.21.4-14.0.0-RC0/org.spongepowered.common.command.brigadier.dispatcher.SpongeCommandDispatcher.parse(SpongeCommandDispatcher.java:119)
	at TRANSFORMER/spongevanilla@1.21.4-14.0.0-RC0/org.spongepowered.common.command.brigadier.dispatcher.DelegatingCommandDispatcher.parse(DelegatingCommandDispatcher.java:85)
	at TRANSFORMER/spongevanilla@1.21.4-14.0.0-RC0/org.spongepowered.common.command.brigadier.dispatcher.DelegatingCommandDispatcher.parse(DelegatingCommandDispatcher.java:45)
	at TRANSFORMER/minecraft@1.21.4/net.minecraft.commands.functions.CommandFunction.parseCommand(CommandFunction.java:95)
	at TRANSFORMER/minecraft@1.21.4/net.minecraft.commands.functions.CommandFunction.fromLines(CommandFunction.java:76)
```

**Comment by aromaa** [comment]
This should be addressed by a29d2fd. The fix is not perfect for 12 but hopefully its enough until we get a proper fix in 14.

**Comment by aromaa** [comment]
All relevant work here is now done. We have decoupled the permission system from the `MinecraftServer` instance in 3d13ecb.

As added bonus, permission plugins can now have fine grained control over each functions permissions with 58d7427.
