### ISSUE TITLE
Error when breaking stone

### ISSUE THREAD

**Issue by DarkArc** [SpongePowered/Sponge#335]
````java
[FML]: Exception caught executing FutureTask: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=variant, clazz=class net.minecraft.block.BlockStone$EnumType, values=[stone, granite, smooth_granite, diorite, smooth_diorite, andesite, smooth_andesite]} as it does not exist in BlockState{block=minecraft:air, properties=[]}
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=variant, clazz=class net.minecraft.block.BlockStone$EnumType, values=[stone, granite, smooth_granite, diorite, smooth_diorite, andesite, smooth_andesite]} as it does not exist in BlockState{block=minecraft:air, properties=[]}
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_51]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_51]
        at net.minecraftforge.fml.common.FMLCommonHandler.callFuture(FMLCommonHandler.java:715) [FMLCommonHandler.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:656) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:364) [po.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:598) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:478) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=variant, clazz=class net.minecraft.block.BlockStone$EnumType, values=[stone, granite, smooth_granite, diorite, smooth_diorite, andesite, smooth_andesite]} as it does not exist in BlockState{block=minecraft:air, properties=[]}
        at net.minecraft.block.state.BlockState$StateImplementation.func_177229_b(BlockState.java:165) ~[beg.class:?]
        at net.minecraft.block.BlockStone.func_176201_c(SourceFile:54) ~[bba.class:?]
        at net.minecraft.block.Block.getHarvestTool(Block.java:1951) ~[atr.class:?]
        at net.minecraftforge.common.ForgeHooks.canHarvestBlock(ForgeHooks.java:130) ~[ForgeHooks.class:?]
        at net.minecraftforge.event.world.BlockEvent$HarvestDropsEvent.onConstructed(BlockEvent.java:76) ~[BlockEvent$HarvestDropsEvent.class:?]
        at net.minecraftforge.event.world.BlockEvent$HarvestDropsEvent.<init>(BlockEvent.java:63) ~[BlockEvent$HarvestDropsEvent.class:?]
        at net.minecraftforge.event.ForgeEventFactory.fireBlockHarvesting(ForgeEventFactory.java:184) ~[ForgeEventFactory.class:?]
        at net.minecraft.block.Block.func_180653_a(Block.java:480) ~[atr.class:?]
        at net.minecraft.block.Block.func_176226_b(Block.java:472) ~[atr.class:?]
        at net.minecraft.block.Block.func_180657_a(Block.java:807) ~[atr.class:?]
        at net.minecraft.server.management.ItemInWorldManager.func_180237_b(ItemInWorldManager.java:319) ~[qx.class:?]
        at net.minecraft.server.management.ItemInWorldManager.func_180785_a(ItemInWorldManager.java:241) ~[qx.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:537) ~[rj.class:?]
        at net.minecraft.network.play.client.C07PacketPlayerDigging.func_180763_a(SourceFile:40) ~[ml.class:?]
        at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:10) ~[ml.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[ih.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_51]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_51]
        at net.minecraftforge.fml.common.FMLCommonHandler.callFuture(FMLCommonHandler.java:714) ~[FMLCommonHandler.class:?]
        ... 5 more
````

**Comment by Zidane** [comment]
@DarkArc 

Is your plugin using any Property of the Stone? Paste your Listener.

**Comment by DarkArc** [comment]
So there are two listeners in this plugin which listen to block break.
https://github.com/Skelril/Skree/blob/master/src/main/java/com/skelril/skree/content/world/wilderness/WildernessWorldWrapper.java#L212
https://github.com/Skelril/Skree/blob/master/src/main/java/com/skelril/skree/content/world/build/BuildWorldWrapper.java#L96

These two listeners are constrained to a world via 
````java
if (!optLoc.isPresent() || !isApplicable(optLoc.get().getExtent())) {
...
````

I tried breaking a stone block in a completely unrelated world (so no modification logic should be being processed), and the above error is still reproducible.

**Comment by DarkArc** [comment]
This also eventually leads to the following error which crashes the server (and continues to crash the server when the chunk is loaded):
````java
net.minecraft.util.ReportedException: Ticking entity
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:710) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:364) ~[po.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:598) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:478) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=variant, clazz=class net.minecraft.block.BlockStone$EnumType, values=[stone, granite, smooth_granite, diorite, smooth_diorite, andesite, smooth_andesite]} as it does not exist in BlockState{block=minecraft:air, properties=[]}
        at net.minecraft.block.state.BlockState$StateImplementation.func_177229_b(BlockState.java:165) ~[beg.class:?]
        at net.minecraft.block.BlockStone.func_176201_c(SourceFile:54) ~[bba.class:?]
        at net.minecraft.block.Block.getHarvestTool(Block.java:1951) ~[atr.class:?]
        at net.minecraftforge.common.ForgeHooks.canHarvestBlock(ForgeHooks.java:130) ~[ForgeHooks.class:?]
        at net.minecraftforge.event.world.BlockEvent$HarvestDropsEvent.onConstructed(BlockEvent.java:76) ~[BlockEvent$HarvestDropsEvent.class:?]
        at net.minecraftforge.event.world.BlockEvent$HarvestDropsEvent.<init>(BlockEvent.java:63) ~[BlockEvent$HarvestDropsEvent.class:?]
        at net.minecraftforge.event.ForgeEventFactory.fireBlockHarvesting(ForgeEventFactory.java:184) ~[ForgeEventFactory.class:?]
        at net.minecraft.block.Block.func_180653_a(Block.java:480) ~[atr.class:?]
        at net.minecraft.block.Block.func_176226_b(Block.java:472) ~[atr.class:?]
        at net.minecraft.block.Block.func_180657_a(Block.java:807) ~[atr.class:?]
        at net.minecraft.server.management.ItemInWorldManager.func_180237_b(ItemInWorldManager.java:319) ~[qx.class:?]
        at net.minecraft.server.management.ItemInWorldManager.func_73075_a(ItemInWorldManager.java:111) ~[qx.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:221) ~[qw.class:?]
        at net.minecraft.world.World.func_72866_a(World.java:98) ~[aqu.class:?]
        at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:732) ~[qt.class:?]
        at net.minecraft.world.World.func_72870_g(World.java:1850) ~[aqu.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:1679) ~[aqu.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:571) ~[qt.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:704) ~[MinecraftServer.class:?]
        ... 4 more
````
