### ISSUE TITLE
Permissions checks fail in single player

### ISSUE THREAD

**Issue by DarkArc** [SpongePowered/Sponge#336]
````java
[20:45:22] [Server thread/FATAL] [FML]: Exception caught executing FutureTask: java.util.concurrent.ExecutionException: java.lang.NullPointerException
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_51]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_51]
	at net.minecraftforge.fml.common.FMLCommonHandler.callFuture(FMLCommonHandler.java:715) [FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:656) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:598) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:164) [cyk.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:478) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.NullPointerException
	at net.minecraft.server.management.UserListOps.func_152699_b(SourceFile:39) ~[sp.class:?]
	at net.minecraft.server.management.UserListOps.func_152681_a(SourceFile:9) ~[sp.class:?]
	at net.minecraft.server.management.UserList.func_152683_b(SourceFile:56) ~[ss.class:?]
	at org.spongepowered.common.service.permission.UserSubject.getOpLevel(UserSubject.java:93) ~[UserSubject.class:1.8-1499-2.1DEV-0+unknown-b0.git-unknown]
	at org.spongepowered.common.service.permission.UserSubject$1.getParent(UserSubject.java:55) ~[UserSubject$1.class:1.8-1499-2.1DEV-0+unknown-b0.git-unknown]
	at org.spongepowered.common.service.permission.base.SingleParentMemorySubjectData.getParents(SingleParentMemorySubjectData.java:51) ~[SingleParentMemorySubjectData.class:1.8-1499-2.1DEV-0+unknown-b0.git-unknown]
	at org.spongepowered.common.service.permission.base.SpongeSubject.getDataPermissionValue(SpongeSubject.java:65) ~[SpongeSubject.class:1.8-1499-2.1DEV-0+unknown-b0.git-unknown]
	at org.spongepowered.common.service.permission.base.SpongeSubject.getPermissionValue(SpongeSubject.java:58) ~[SpongeSubject.class:1.8-1499-2.1DEV-0+unknown-b0.git-unknown]
	at org.spongepowered.common.service.permission.UserSubject.getPermissionValue(UserSubject.java:115) ~[UserSubject.class:1.8-1499-2.1DEV-0+unknown-b0.git-unknown]
	at net.minecraft.entity.player.EntityPlayerMP.getPermissionValue(EntityPlayerMP.java:146) ~[qw.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.hasPermission(EntityPlayerMP.java:128) ~[qw.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.hasPermission(EntityPlayerMP.java:140) ~[qw.class:?]
	at org.spongepowered.api.service.command.SimpleCommandService.process(SimpleCommandService.java:280) ~[SimpleCommandService.class:1.8-1499-2.1DEV-0+unknown-b0.git-unknown]
	at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:80) ~[cl.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:812) ~[rj.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:791) ~[rj.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_180757_a(SourceFile:37) ~[lu.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9) ~[lu.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[ih.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_51]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_51]
	at net.minecraftforge.fml.common.FMLCommonHandler.callFuture(FMLCommonHandler.java:714) ~[FMLCommonHandler.class:?]
	... 5 more
````
Edit: In this particular stack trace, it's the help command triggering this.

**Comment by JBYoshi** [comment]
For developers: the MCP remapped stack trace is:
```java
Exception caught executing FutureTask: java.util.concurrent.ExecutionException: java.lang.NullPointerException
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_60]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_60]
	at net.minecraftforge.fml.common.FMLCommonHandler.callFuture(FMLCommonHandler.java:715) [FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:727) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:669) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:171) [IntegratedServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:540) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
Caused by: java.lang.NullPointerException
	at net.minecraft.server.management.UserListOps.getUUIDString(UserListOps.java:43) ~[UserListOps.class:?]
	at net.minecraft.server.management.UserListOps.getObjectKey(UserListOps.java:75) ~[UserListOps.class:?]
	at net.minecraft.server.management.UserList.getEntry(UserList.java:95) ~[UserList.class:?]
	at org.spongepowered.common.service.permission.UserSubject.getOpLevel(UserSubject.java:93) ~[UserSubject.class:?]
	at org.spongepowered.common.service.permission.UserSubject$1.getParent(UserSubject.java:55) ~[UserSubject$1.class:?]
	at org.spongepowered.common.service.permission.base.SingleParentMemorySubjectData.getParents(SingleParentMemorySubjectData.java:51) ~[SingleParentMemorySubjectData.class:?]
	at org.spongepowered.common.service.permission.base.SpongeSubject.getDataPermissionValue(SpongeSubject.java:65) ~[SpongeSubject.class:?]
	at org.spongepowered.common.service.permission.base.SpongeSubject.getPermissionValue(SpongeSubject.java:58) ~[SpongeSubject.class:?]
	at org.spongepowered.common.service.permission.UserSubject.getPermissionValue(UserSubject.java:115) ~[UserSubject.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.getPermissionValue(EntityPlayerMP.java:146) ~[EntityPlayerMP.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.hasPermission(EntityPlayerMP.java:128) ~[EntityPlayerMP.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.hasPermission(EntityPlayerMP.java:140) ~[EntityPlayerMP.class:?]
	at org.spongepowered.api.service.command.SimpleCommandService.process(SimpleCommandService.java:280) ~[SimpleCommandService.class:?]
	at net.minecraft.command.ServerCommandManager.executeCommand(ServerCommandManager.java:80) ~[ServerCommandManager.class:?]
	at net.minecraft.network.NetHandlerPlayServer.handleSlashCommand(NetHandlerPlayServer.java:853) ~[NetHandlerPlayServer.class:?]
	at net.minecraft.network.NetHandlerPlayServer.processChatMessage(NetHandlerPlayServer.java:829) ~[NetHandlerPlayServer.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.processPacket(C01PacketChatMessage.java:44) ~[C01PacketChatMessage.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.processPacket(C01PacketChatMessage.java:57) ~[C01PacketChatMessage.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:24) ~[PacketThreadUtil$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_60]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_60]
	at net.minecraftforge.fml.common.FMLCommonHandler.callFuture(FMLCommonHandler.java:714) ~[FMLCommonHandler.class:?]
	... 5 more
```

**Comment by bloodmc** [comment]
Dupe SpongePowered/SpongeCommon#117
