### ISSUE TITLE
Furnace Duping Bug

### ISSUE THREAD

**Issue by Cannash** [SpongePowered/Sponge#339]
When I place a furnace and then right-click on it, I receive another furnace in my inventory. (This also happens with chests, enchantment tables, and ender chests)

Sponge build: 1.8-1499-2.1DEV-613
Forge Version: 11.14.3.1512
Running a Dedicated Server

Installed plugins:
- Core-2.1.0a
- PermissionsEx build#91

OS: Windows 10 x64
Java: 8u60 x64

**Comment by gabizou** [comment]
> Forge Version: 11.14.3.1512

Please use the recommended forge build: 1499 and report whether the issue still exists.

**Comment by bloodmc** [comment]
It isn't a Sponge problem. The issue is being caused by either a mod or plugin that you are using.

**Comment by Cannash** [comment]
The problem still exists with Forge build 1499.

**Comment by Cannash** [comment]
Also, it is a Sponge problem, unless it's a Forge problem. I just tried running it with no other mods/plugins besides Forge and Sponge, and the problem still exists. So, could someone reopen this?

**Comment by Cannash** [comment]
I just noticed that this in the console when I right-click a furnace:

Exception caught executing FutureTask: java.util.concurrent.ExecutionException: java.lang.NullPointerException: extent
java.util.concurrent.ExecutionException: java.lang.NullPointerException: extent
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_60]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_60]
	at net.minecraftforge.fml.common.FMLCommonHandler.callFuture(FMLCommonHandler.java:715) [FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:656) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:364) [po.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:598) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:478) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_60]
Caused by: java.lang.NullPointerException: extent
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:229) ~[minecraft_server.1.8.jar:?]
	at org.spongepowered.api.world.Location.<init>(Location.java:123) ~[Location.class:1.8-1499-2.1DEV-613+spongeproject-ci-b613.git-da462d3e6170f88a265f46a7e6354b5f594ce91f]
	at net.minecraft.tileentity.TileEntity.getLocation(TileEntity.java:62) ~[bcm.class:?]
	at org.spongepowered.common.block.SpongeBlockSnapshot.<init>(SpongeBlockSnapshot.java:119) ~[SpongeBlockSnapshot.class:1.8-1499-2.1DEV-613+spongeproject-ci-b613.git-da462d3e6170f88a265f46a7e6354b5f594ce91f]
	at org.spongepowered.common.block.SpongeBlockSnapshot.<init>(SpongeBlockSnapshot.java:84) ~[SpongeBlockSnapshot.class:1.8-1499-2.1DEV-613+spongeproject-ci-b613.git-da462d3e6170f88a265f46a7e6354b5f594ce91f]
	at net.minecraftforge.common.util.BlockSnapshot.createSpongeBlockSnapshot(BlockSnapshot.java:59) ~[BlockSnapshot.class:?]
	at net.minecraftforge.event.world.BlockEvent$PlaceEvent.onConstructed(BlockEvent.java:57) ~[BlockEvent$PlaceEvent.class:?]
	at net.minecraftforge.event.world.BlockEvent$PlaceEvent.<init>(BlockEvent.java:146) ~[BlockEvent$PlaceEvent.class:?]
	at net.minecraftforge.event.ForgeEventFactory.onPlayerBlockPlace(ForgeEventFactory.java:92) ~[ForgeEventFactory.class:?]
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:598) ~[ForgeHooks.class:?]
	at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:132) ~[amj.class:?]
	at net.minecraft.server.management.ItemInWorldManager.func_180236_a(ItemInWorldManager.java:446) ~[qx.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:595) ~[rj.class:?]
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_180769_a(SourceFile:59) ~[mx.class:?]
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:10) ~[mx.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[ih.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_60]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_60]
	at net.minecraftforge.fml.common.FMLCommonHandler.callFuture(FMLCommonHandler.java:714) ~[FMLCommonHandler.class:?]
	... 5 more

**Comment by bloodmc** [comment]
That is another issue, fixed in latest Sponge build.

**Comment by Cannash** [comment]
I have the latest dev build (1.8-1499-2.1DEV-613).

**Comment by Cannash** [comment]
How do I fix this then?

**Comment by RobertHerhold** [comment]
This happens with signs too... possibly something to do with placing `TileEntity`s?

**Comment by bloodmc** [comment]
Wait for our build server to be fixed. Nothing has built since build 613.

**Comment by bloodmc** [comment]
Build server is still down but apparently 2 more builds were built, just not showing up on download page.

Try build 615

https://repo.spongepowered.org/maven/org/spongepowered/sponge/1.8-1499-2.1DEV-615/sponge-1.8-1499-2.1DEV-615.jar

**Comment by Cannash** [comment]
It works fine now. No more duping. Thank you.
