### ISSUE TITLE
java.lang.NoClassDefFoundError when building

### ISSUE THREAD

**Issue by ghost** [SpongePowered/Sponge#3403]
```
FAILURE: Build failed with an exception.

* What went wrong:
com/github/jengelman/gradle/plugins/shadow/tasks/ShadowJar

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
java.lang.NoClassDefFoundError: com/github/jengelman/gradle/plugins/shadow/tasks/ShadowJar
	at org.spongepowered.gradle.vanilla.ShadowConfigurationApplier.applyShadowConfiguration(ShadowConfigurationApplier.java:45)
	at org.spongepowered.gradle.vanilla.VanillaGradle.lambda$applyToProject$5(VanillaGradle.java:96)
	at org.spongepowered.gradle.vanilla.VanillaGradle.applyToProject(VanillaGradle.java:95)
	at org.spongepowered.gradle.vanilla.VanillaGradle.apply(VanillaGradle.java:66)
	at Program.execute(Unknown Source)

* Get more help at https://help.gradle.org

BUILD FAILED in 321ms

**Comment by gabizou** [comment]
We don’t support build issues on GitHub. We have forums and discord for that. Plus, we’re not supporting build issues for the snapshot branch.
