### ISSUE TITLE
[1.16.5] Error when launching

### ISSUE THREAD

**Issue by MrSlimeDiamond** [SpongePowered/Sponge#3429]
**I am currently running**

- SpongeVanilla version: spongevanilla-1.16.5-8.0.0-RC644-universal.jar
 Not using 1.17 because I wanted 1.16.5 :frog:
- Java version: openjdk version "1.8.0_292"
- Operating System: Ubuntu 20.04.2 LTS aarch64 

- Plugins/Mods: None

**Issue Description**
When I launch spongevanilla-1.16.5-8.0.0-RC644-universal.jar, I get the following error:
```
Exception in thread "main" java.lang.ExceptionInInitializerError
        at org.fusesource.jansi.AnsiConsole.ansiStream(AnsiConsole.java:239)
        at org.fusesource.jansi.AnsiConsole.initStreams(AnsiConsole.java:542)
        at org.fusesource.jansi.AnsiConsole.systemInstall(AnsiConsole.java:496)
        at org.spongepowered.vanilla.applaunch.Main.<clinit>(Main.java:46)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at org.spongepowered.vanilla.installer.InstallerMain.invokeMain(InstallerMain.java:148)
        at org.spongepowered.vanilla.installer.InstallerMain.downloadAndRun(InstallerMain.java:133)
        at org.spongepowered.vanilla.installer.InstallerMain.run(InstallerMain.java:75)
        at org.spongepowered.vanilla.installer.InstallerMain.main(InstallerMain.java:70)
Caused by: java.lang.RuntimeException: Unable to load jansi native library
        at org.fusesource.jansi.internal.JansiLoader.initialize(JansiLoader.java:62)
        at org.fusesource.jansi.internal.CLibrary.<clinit>(CLibrary.java:30)
        ... 10 more
Caused by: java.lang.Exception: No native library found for os.name=Linux, os.arch=aarch64, paths=[/usr/java/packages/lib/aarch64:/usr/lib/aarch64-linux-gnu/jni:/lib/aarch64-linux-gnu:/usr/lib/aarch64-linux-gnu:/usr/lib/jni:/lib:/usr/lib]
        at org.fusesource.jansi.internal.JansiLoader.loadJansiNativeLibrary(JansiLoader.java:333)
        at org.fusesource.jansi.internal.JansiLoader.initialize(JansiLoader.java:60)
        ... 11 more

```

Full log: https://paste.md-5.net/akozuwibav.sql
I was told to make an issue about this a little while ago but I forgot to so here I am

**Comment by dualspiral** [comment]
I notice you're using an ARM64 machine there. With that in mind, having a look around, I suspect https://github.com/fusesource/jansi/commit/e4d58d94eab5ecbc2f466978a5006835cf728da7 may fix the issue, so it would involve us updating jansi to v2.3.3 if possible.

**Comment by dualspiral** [comment]
https://github.com/SpongePowered/Sponge/pull/3431 - if you get a chance to test the build I attached to that PR that would be helpful.

**Comment by MrSlimeDiamond** [comment]
Since this is fixed, I'll close it now.
