### ISSUE TITLE
Mixin apply failed 1.16.5 spongeforge

### ISSUE THREAD

**Issue by Xplodin** [SpongePowered/Sponge#3531]
**I am currently running**

- SpongeForge version: 896
- SpongeVanilla version: NA
- Java version: 11
- Operating System: ubuntu 18.04

- Plugins/Mods:
TNP Limitless 3 1.11

**Issue Description**
I get a mixin error that crashes the server
heres the crash from the log.txt since it never got put into crashlogs oddly.

```
 [main/FATAL] [mixin/]: Mixin apply failed mixins.sponge.api.json:minecraft.server.MinecraftServerMixin_API -> net.minecraft.server.MinecraftServer: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException Conflicting type cast at offset 4 in synthetic bridge method func_212871_a_(Ljava/lang/Object;)V
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Conflicting type cast at offset 4 in synthetic bridge method func_212871_a_(Ljava/lang/Object;)V
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachUniqueMethod(MixinPreProcessorStandard.java:557) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachMethods(MixinPreProcessorStandard.java:341) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:289) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:267) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1271) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:287) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:223) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformationHandler.processClass(MixinTransformationHandler.java:121) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at org.spongepowered.asm.launch.MixinLaunchPlugin.processClass(MixinLaunchPlugin.java:131) ~[mixin-0.8.2.jar:0.8.2+unknown-b0.git-unknown]
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154) ~[modlauncher-8.0.9.jar:8.0.9+86+master.3cf110c]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	at net.minecraft.server.Main.main(Main.java:116) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[server.jar:36.2]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?]
	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [server.jar:?]
	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [server.jar:?]
	at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [server.jar:?]
[11Sep2021 09:14:33.039] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[11Sep2021 09:14:33.039] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
[11Sep2021 09:14:33.039] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[11Sep2021 09:14:33.039] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[11Sep2021 09:14:33.040] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[11Sep2021 09:14:33.040] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[11Sep2021 09:14:33.040] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]: 	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63)
[11Sep2021 09:14:33.040] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]: 	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60)
[11Sep2021 09:14:33.040] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]: 	at net.minecraftforge.server.ServerMain.main(ServerMain.java:57)
[11Sep2021 09:14:33.041] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1059]: Caused by: java.lang.reflect.InvocationTargetException
[11Sep2021 09:14:33.041] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1059]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[11Sep2021 09:14:33.041] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1059]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[11Sep2021 09:14:33.041] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1059]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[11Sep2021 09:14:33.041] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1059]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[11Sep2021 09:14:33.041] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1059]: 	at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51)
[11Sep2021 09:14:33.041] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1059]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[11Sep2021 09:14:33.041] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1059]: 	... 7 more
[11Sep2021 09:14:33.042] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]: Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[11Sep2021 09:14:33.042] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
[11Sep2021 09:14:33.042] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:223)
[11Sep2021 09:14:33.042] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformationHandler.processClass(MixinTransformationHandler.java:121)
[11Sep2021 09:14:33.042] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]: 	at org.spongepowered.asm.launch.MixinLaunchPlugin.processClass(MixinLaunchPlugin.java:131)
[11Sep2021 09:14:33.042] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]: 	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154)
[11Sep2021 09:14:33.042] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]: 	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85)
[11Sep2021 09:14:33.042] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]: 	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
[11Sep2021 09:14:33.043] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]: 	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265)
[11Sep2021 09:14:33.043] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
[11Sep2021 09:14:33.043] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[11Sep2021 09:14:33.043] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
[11Sep2021 09:14:33.043] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]: 	at net.minecraft.server.Main.main(Main.java:116)
[11Sep2021 09:14:33.043] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:648]: 	... 13 more
[11Sep2021 09:14:33.043] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:671]: Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [mixins.sponge.api.json:minecraft.server.MinecraftServerMixin_API] from phase [DEFAULT] in config [mixins.sponge.api.json] FAILED during APPLY
[11Sep2021 09:14:33.044] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:671]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:642)
[11Sep2021 09:14:33.044] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:671]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:594)
[11Sep2021 09:14:33.044] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:671]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:356)
[11Sep2021 09:14:33.044] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:671]: 	... 24 more
[11Sep2021 09:14:33.044] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:713]: Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Conflicting type cast at offset 4 in synthetic bridge method func_212871_a_(Ljava/lang/Object;)V
[11Sep2021 09:14:33.044] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:713]: 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachUniqueMethod(MixinPreProcessorStandard.java:557)
[11Sep2021 09:14:33.044] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:713]: 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachMethods(MixinPreProcessorStandard.java:341)
[11Sep2021 09:14:33.044] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:713]: 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:289)
[11Sep2021 09:14:33.045] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:713]: 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:267)
[11Sep2021 09:14:33.045] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:713]: 	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1271)
[11Sep2021 09:14:33.045] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:713]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:287)
[11Sep2021 09:14:33.045] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:713]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
[11Sep2021 09:14:33.045] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:713]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
[11Sep2021 09:14:33.045] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:713]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
[11Sep2021 09:14:33.045] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:713]: 	... 24 more

```

**Comment by Zidane** [comment]
Cannot reproduce. Try with the latest builds and report back otherwise.
