### ISSUE TITLE
RuntimeException when starting the server: attempted to load client class 

### ISSUE THREAD

**Issue by ImMorpheus** [SpongePowered/Sponge#3548]
**I am currently running**

- SpongeForge version: 1.16.5 (https://github.com/SpongePowered/Sponge/commit/a06a32ef0ddb489ac79364ab3befcf010b480194)

- Plugins/Mods: 
- architectury-1.23.33-forge.jar
- SteveKunG's-Lib-mc1.16.5-v4.1.6-forge.jar

**Issue Description**
The issue affects other mods, but this is a minimal test case.
We're routing mods to our own event manager: https://github.com/SpongePowered/Sponge/blob/a06a32ef0ddb489ac79364ab3befcf010b480194/forge/src/mixins/java/org/spongepowered/forge/mixin/core/minecraftforge/fml/FMLModContainerMixin_Forge.java#L56 which is scanning the class hierarchy for event listeners: https://github.com/SpongePowered/Sponge/blob/a06a32ef0ddb489ac79364ab3befcf010b480194/src/main/java/org/spongepowered/common/event/manager/SpongeEventManager.java#L255

Note that forge is also filtering out listeners based on the `Dist` annotation so this might be triggered in other ways.

https://github.com/MinecraftForge/MinecraftForge/blob/9ef34a9f1a17ad102be1566206f384fbb471823c/src/main/java/net/minecraftforge/fml/AutomaticEventSubscriber.java#L71
____

Log:

```
[main/FATAL] [ne.mi.fm.ModLoader/]: Encountered non-modloading exceptions!
java.util.concurrent.CompletionException: java.lang.RuntimeException
        at java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:367) ~[?:?] {}
        at java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:376) ~[?:?] {}
        at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1074) ~[?:?] {}
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?] {}
        at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610) ~[?:?] {}
        at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1085) ~[?:?] {}
        at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479) ~[?:?] {}
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[?:?] {}
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[?:?] {}
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[?:?] {}
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[?:?] {}
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?] {}
Caused by: java.lang.RuntimeException
        at net.minecraftforge.fml.ModList.completableFutureFromExceptionList(ModList.java:139) ~[forge:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.spongeforge.accessors.json:fml.ModListAccessor,pl:mixin:A}
        at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072) ~[?:?] {}
        ... 9 more
        Suppressed: java.lang.RuntimeException: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
                at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71) ~[forge-1.16.5-36.2.8.jar:36.2] {}
                at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-8.0.9.jar:?] {}
                at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-8.0.9.jar:?] {}
                at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.0.9.jar:?] {}
                at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.9.jar:?] {re:classloading}
                at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?] {re:classloading}
                at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?] {}
                at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?] {}
                at java.lang.Class.privateGetDeclaredMethods(Class.java:3166) ~[?:?] {}
                at java.lang.Class.getDeclaredMethods(Class.java:2309) ~[?:?] {}
                at org.spongepowered.common.event.manager.SpongeEventManager.registerListener(SpongeEventManager.java:285) ~[spongeforge:1.16.5-36.2.5-8.0.0-RC0] {re:mixin,re:classloading}
                at org.spongepowered.common.event.manager.SpongeEventManager.registerListeners(SpongeEventManager.java:315) ~[spongeforge:1.16.5-36.2.5-8.0.0-RC0] {re:mixin,re:classloading}
                at net.minecraftforge.fml.javafmlmod.FMLModContainer.handler$zoi000$forge$registerModForSpongeListeners(FMLModContainer.java:1059) ~[forge:36.2] {re:mixin,re:classloading,pl:mixin:APP:mixins.spongeforge.accessors.json:fml.javafmlmod.FMLModContainerAccessor,pl:mixin:APP:mixins.spongeforge.core.json:minecraftforge.fml.FMLModContainerMixin_Forge,pl:mixin:A}
                at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:97) ~[forge:36.2] {re:mixin,re:classloading,pl:mixin:APP:mixins.spongeforge.accessors.json:fml.javafmlmod.FMLModContainerAccessor,pl:mixin:APP:mixins.spongeforge.core.json:minecraftforge.fml.FMLModContainerMixin_Forge,pl:mixin:A}
                at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.spongeforge.core.json:minecraftforge.fml.ModContainerMixin_Forge,pl:mixin:A}
                at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736) ~[?:?] {}
                at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728) ~[?:?] {}
                at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[?:?] {}
                at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[?:?] {}
                at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[?:?] {}
                at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[?:?] {}
                at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?] {}
[main/FATAL] [minecraft/Main]: Failed to start the minecraft server
java.util.concurrent.CompletionException: java.lang.RuntimeException
        at java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:367) ~[?:?] {}
        at java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:376) ~[?:?] {}
        at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1074) ~[?:?] {}
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?] {}
        at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610) ~[?:?] {}
        at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1085) ~[?:?] {}
        at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479) ~[?:?] {}
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[?:?] {}
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[?:?] {}
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[?:?] {}
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[?:?] {}
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?] {}
Caused by: java.lang.RuntimeException
        at net.minecraftforge.fml.ModList.completableFutureFromExceptionList(ModList.java:139) ~[forge:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.spongeforge.accessors.json:fml.ModListAccessor,pl:mixin:A}
        at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072) ~[?:?] {}
        ... 9 more
        Suppressed: java.lang.RuntimeException: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
                at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71) ~[forge-1.16.5-36.2.8.jar:36.2] {}
                at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-8.0.9.jar:?] {}
                at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-8.0.9.jar:?] {}
                at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.0.9.jar:?] {}
                at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.9.jar:?] {re:classloading}
                at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?] {re:classloading}
                at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?] {}
                at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?] {}
                at java.lang.Class.privateGetDeclaredMethods(Class.java:3166) ~[?:?] {}
                at java.lang.Class.getDeclaredMethods(Class.java:2309) ~[?:?] {}
                at org.spongepowered.common.event.manager.SpongeEventManager.registerListener(SpongeEventManager.java:285) ~[spongeforge:1.16.5-36.2.5-8.0.0-RC0] {re:mixin,re:classloading}
                at org.spongepowered.common.event.manager.SpongeEventManager.registerListeners(SpongeEventManager.java:315) ~[spongeforge:1.16.5-36.2.5-8.0.0-RC0] {re:mixin,re:classloading}
                at net.minecraftforge.fml.javafmlmod.FMLModContainer.handler$zoi000$forge$registerModForSpongeListeners(FMLModContainer.java:1059) ~[forge:36.2] {re:mixin,re:classloading,pl:mixin:APP:mixins.spongeforge.accessors.json:fml.javafmlmod.FMLModContainerAccessor,pl:mixin:APP:mixins.spongeforge.core.json:minecraftforge.fml.FMLModContainerMixin_Forge,pl:mixin:A}
                at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:97) ~[forge:36.2] {re:mixin,re:classloading,pl:mixin:APP:mixins.spongeforge.accessors.json:fml.javafmlmod.FMLModContainerAccessor,pl:mixin:APP:mixins.spongeforge.core.json:minecraftforge.fml.FMLModContainerMixin_Forge,pl:mixin:A}
                at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.spongeforge.core.json:minecraftforge.fml.ModContainerMixin_Forge,pl:mixin:A}
                at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736) ~[?:?] {}
                at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728) ~[?:?] {}
                at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[?:?] {}
                at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[?:?] {}
                at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[?:?] {}
                at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[?:?] {}
                at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?] {}

```

**Comment by gabizou** [comment]
Care to try this [special build](https://github.com/SpongePowered/Sponge/suites/5163966667/artifacts/156362790) built from [this PR](https://github.com/SpongePowered/Sponge/pull/3619)? I believe it'll solve this problem (and the 4 other tickets related to this one).

**Comment by gabizou** [comment]
Fixed with https://github.com/SpongePowered/Sponge/pull/3619
