### ISSUE TITLE
Crash from Inventory NPE with SpongeVanilla 1.17.1

### ISSUE THREAD

**Issue by Inscrutable** [SpongePowered/Sponge#3554]
- **I am currently running**
    Sponge: 1.17.1-9.0.0-SNAPSHOT
    SpongeVanilla: 1.17.1-9.0.0-RC929
    JVM: 16.0.1/64-bit (Private Build)
    OS: Linux/5.4.0-66-generic (amd64)

- Plugins/Mods:
    CubeEngine - LibCube v2.0.0-SNAPSHOT
    CubeEngine - Zoned v1.1.0-SNAPSHOT
    CubeEngine - ItemDuct v1.2.0-SNAPSHOT
    CubeEngine - Roles v1.1.0-SNAPSHOT
    CubeEngine - Chat v1.0.1-SNAPSHOT
    CubeEngine - Portals v1.1.0-SNAPSHOT
    CubeEngine - Locker v1.1.0-SNAPSHOT
    CubeEngine - tablist v1.0.0-SNAPSHOT
    CubeEngine - Squelch v1.0.0-SNAPSHOT
    CubeEngine - VanillaPlus v1.1.0-SNAPSHOT
    CubeEngine - Teleport v1.1.0-SNAPSHOT
    CubeEngine - Writer v1.0.0-SNAPSHOT
    CubeEngine - KickBan v1.1.0-SNAPSHOT
    CubeEngine - Protector v1.2.0-SNAPSHOT
    CubeEngine - Spawn v1.1.0-SNAPSHOT
    CubeEngine - Terra v1.2.0-SNAPSHOT
    CubeEngine - Travel v1.1.0-SNAPSHOT
    CubeEngine - Multiverse v1.1.0-SNAPSHOT
    CubeEngine - Spawner v1.0.1-SNAPSHOT
    CubeEngine - Powertools v1.1.0-SNAPSHOT
    CubeEngine - Elevator v1.1.0-SNAPSHOT
    CubeEngine - Mechanism v1.0.0-SNAPSHOT
    CubeEngine - Kits v1.1.0-SNAPSHOT

- **Issue Description**
The server crashed after a player logged in. They were online earlier with no problems.
`[Server thread/FATAL]: Error executing task on Server
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.player.Player.getInventory()" because "player" is null`

Here's the log file that captures the above, and then the phase tracker convulsing in all it's glory:
[latest.log](https://github.com/SpongePowered/Sponge/files/7482305/latest.log)

**Comment by Faithcaio** [comment]
```
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.player.Player.getInventory()" because "player" is null
	at org.spongepowered.common.event.tracking.context.transaction.inventory.PlayerInventoryTransaction.<init>(PlayerInventoryTransaction.java:49) ~[PlayerInventoryTransaction.class:1.17.1-9.0.0-RC929]
	at org.spongepowered.common.event.tracking.context.transaction.TransactionSink.logPlayerInventoryChange(TransactionSink.java:322) ~[TransactionSink.class:1.17.1-9.0.0-RC929]
	at org.spongepowered.common.event.tracking.phase.packet.PacketContext.close(PacketContext.java:133) ~[PacketContext.class:1.17.1-9.0.0-RC929]
```
`PacketContext.packetPlayer` is missing.

```
Suppressed: java.lang.NullPointerException: value
at java.util.Objects.requireNonNull(Objects.java:233) ~[?:?]
		at org.spongepowered.common.event.tracking.SpongeCauseStackFrame.addContext(SpongeCauseStackFrame.java:122) ~[SpongeCauseStackFrame.class:1.17.1-9.0.0-RC929]
		at org.spongepowered.common.event.tracking.phase.packet.player.AttackEntityPacketState.lambda$new$0(AttackEntityPacketState.java:56) ~[AttackEntityPacketState.class:1.17.1-9.0.0-RC929]
```

**Comment by ImMorpheus** [comment]
Fixed by https://github.com/SpongePowered/Sponge/commit/5d0c1eeb169af323c55c3b88f924b58f13d899fe  

Merged into api-9
