### ISSUE TITLE
net.minecraft.ReportedException: Exception generating new chunk while generating a new world (1.18)

### ISSUE THREAD

**Issue by masagameplay** [SpongePowered/Sponge#3571]
**I am currently running**

- SpongeVanilla version:  1.18.1-9.0.0-RC982
- Java version: 17.0.1/64-bit (Oracle Corporation)
- Operating System: Windows 10

- Plugins/Mods:
No mods
 
**Issue Description**
I created a new 1.18 server with the given jar from https://www.spongepowered.org/downloads/spongevanilla?minecraft=1.18.1&offset=0 and when the world generation started the server started throwing this.

```
[21:38:59] [Server thread/FATAL]: Error executing task on Chunk source main thread executor for minecraft:overworld
net.minecraft.ReportedException: Exception generating new chunk
        at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$19(ChunkMap.java:619) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[?:?]
        at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.doRunTask(ServerChunkCache.java:552) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[?:?]
        at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.pollTask(ServerChunkCache.java:561) ~[?:?]
        at net.minecraft.server.level.ServerChunkCache.pollTask(ServerChunkCache.java:282) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:768) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:756) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:134) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:741) ~[?:?]
        at net.minecraft.server.MinecraftServer.accessor$waitUntilNextTick(MinecraftServer.java) ~[?:?]
        at org.spongepowered.common.world.server.SpongeWorldManager.loadSpawnChunks(SpongeWorldManager.java:1152) ~[SpongeWorldManager.class:1.18.1-9.0.0-RC982]
        at org.spongepowered.common.world.server.SpongeWorldManager.postWorldLoad(SpongeWorldManager.java:1092) ~[SpongeWorldManager.class:1.18.1-9.0.0-RC982]
        at org.spongepowered.common.world.server.SpongeWorldManager.loadLevel(SpongeWorldManager.java:1013) ~[SpongeWorldManager.class:1.18.1-9.0.0-RC982]
        at net.minecraft.server.dedicated.DedicatedServer.loadLevel(DedicatedServer.java:2242) ~[?:?]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:182) ~[?:?]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:657) ~[?:?]
        at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:270) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.IllegalStateException: Unregistered biome: net.minecraft.world.level.biome.Biome@48565172
        at net.minecraft.world.level.levelgen.SurfaceSystem.lambda$buildSurface$2(SurfaceSystem.java:139) ~[?:?]
        at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
        at net.minecraft.world.level.levelgen.SurfaceSystem.buildSurface(SurfaceSystem.java:139) ~[?:?]
        at net.minecraft.world.level.levelgen.NoiseBasedChunkGenerator.buildSurface(NoiseBasedChunkGenerator.java:261) ~[?:?]
        at net.minecraft.world.level.chunk.ChunkStatus.lambda$static$9(ChunkStatus.java:123) ~[?:?]
        at net.minecraft.world.level.chunk.ChunkStatus$SimpleGenerationTask.doWork(ChunkStatus.java:338) ~[?:?]
        at net.minecraft.world.level.chunk.ChunkStatus.generate(ChunkStatus.java:289) ~[?:?]
        at net.minecraft.server.level.ChunkMap.redirect$zgc000$impl$attachEventToCompletedGeneration(ChunkMap.java:2473) ~[?:?]
        at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$20(ChunkMap.java:605) ~[?:?]
        at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[?:?]
        at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$22(ChunkMap.java:599) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.lambda$message$1(ChunkTaskPriorityQueueSorter.java:58) ~[?:?]
        at net.minecraft.util.thread.ProcessorMailbox.pollTask(ProcessorMailbox.java:91) ~[?:?]
        at net.minecraft.util.thread.ProcessorMailbox.pollUntil(ProcessorMailbox.java:146) ~[?:?]
        at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102) ~[?:?]
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
````

**Comment by masagameplay** [comment]
I solved this issue by deleting the world folder and started the server again.
