### ISSUE TITLE
Leads Crash Server

### ISSUE THREAD

**Issue by TBlueF** [SpongePowered/Sponge#358]
This is a little different than [this Issue](https://github.com/SpongePowered/Sponge/issues/312).
Here is the Exception: http://pastebin.com/1JeDXSmc
I don't know why an `UnleashEntityEvent` needs a `Rider` or a `Vehicle` but for me it seems like they being `null` is causing the crash.
Loading the Server without Sponge fixes the Problem just temporarily.

`Entity's Rider: ~~ERROR~~ NullPointerException: null`
`Entity's Vehicle: ~~ERROR~~ NullPointerException: null`

`java.lang.NullPointerException: Ticking entity`
 `at net.minecraft.entity.EntityLiving.callUnleashEvent(EntityLiving.java:110)`
 `  at net.minecraft.entity.EntityLiving.func_110160_i(EntityLiving.java:1013)`
 `  at net.minecraft.entity.EntityLiving.func_110159_bB(EntityLiving.java:1004)`
 `  at net.minecraft.entity.EntityCreature.func_110159_bB(SourceFile:75)`
 `  at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:233)`
 `  at net.minecraft.entity.passive.EntityHorse.func_70071_h_(EntityHorse.java:1034)`

**Comment by TBlueF** [comment]
Actually i just realized this is a SpongeCommon Issue, isn't it? ... Sorry, ill reopen it there.
