### ISSUE TITLE
Eventbus error spam with Applied Energistics 2

### ISSUE THREAD

**Issue by kencinder** [SpongePowered/Sponge#3588]
**I am currently running**

- SpongeForge version: 1.16.5-36.2.5-8.0.0-RC1036
- SpongeVanilla version: N/A
- Java version: 11.0.13
- Operating System: Windows 10

- Plugins/Mods:
Applied Energistics 2 v8.4.6

**Issue Description**
Continuous spam of the following error, full log also attached.
```
[14Jan.2022 13:37:25.116] [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: null
	Index: 1
	Listeners:
		0: NORMAL
		1: net.minecraftforge.eventbus.EventBus$$Lambda$3095/0x0000000800fbfc40@36ab2d93
java.lang.NullPointerException
	at appeng.hooks.ticking.TickHandler.readyTiles(TickHandler.java:370)
	at appeng.hooks.ticking.TickHandler.onWorldTick(TickHandler.java:293)
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
	at org.spongepowered.forge.launch.event.SpongeEventBus.post(SpongeEventBus.java:120)
	at org.spongepowered.forge.launch.event.ForgeEventManager.post(ForgeEventManager.java:125)
	at org.spongepowered.forge.launch.event.ForgeEventManager.post(ForgeEventManager.java:111)
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPostWorldTick(BasicEventHooks.java:100)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:857)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291)
	at net.minecraft.server.MinecraftServer.redirect$zca000$tracker$wrapUpdateTimeLightAndEntities(MinecraftServer.java:4308)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787)
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642)
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232)
	at java.base/java.lang.Thread.run(Thread.java:829)
```
[debug.log](https://github.com/SpongePowered/Sponge/files/7872228/debug.log)

**Comment by Zidane** [comment]
Sponge is only in the stacktrace since we wrap the Forge eventbus.

That is a null from that mod.

**Comment by kencinder** [comment]
It doesn't happen without Spongeforge

**Comment by Zidane** [comment]
It doesn't? Hmmm.
