### ISSUE TITLE
Server crash with Randompatches

### ISSUE THREAD

**Issue by kencinder** [SpongePowered/Sponge#3589]
**I am currently running**

- SpongeForge version: 1.16.5-36.2.5-8.0.0-RC1036
- SpongeVanilla version: N/A
- Java version: 11.0.13
- Operating System: Windows 10

- Plugins/Mods:

Randompatches 2.4.4

**Issue Description**

Crash on startup, full log also attached. This error doesn't occur without Spongeforge present, despite the reference to a client class.
```
[14Jan.2022 18:07:14.469] [main/FATAL] [net.minecraftforge.fml.ModLoader/]: Encountered non-modloading exceptions!
java.util.concurrent.CompletionException: java.lang.RuntimeException
	at java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:367) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:376) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1074) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1085) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?]
Caused by: java.lang.RuntimeException
	at net.minecraftforge.fml.ModList.completableFutureFromExceptionList(ModList.java:139) ~[forge:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072) ~[?:?]
	... 9 more
	Suppressed: java.lang.RuntimeException: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
		at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71) ~[forge-1.16.5-36.2.21.jar:36.2]
		at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-8.0.9.jar:?]
		at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-8.0.9.jar:?]
		at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.0.9.jar:?]
		at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.9.jar:?]
		at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?]
		at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
		at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?]
		at java.lang.Class.privateGetDeclaredMethods(Class.java:3166) ~[?:?]
		at java.lang.Class.getDeclaredMethods(Class.java:2309) ~[?:?]
		at org.spongepowered.common.event.manager.SpongeEventManager.registerListener(SpongeEventManager.java:280) ~[spongeforge:1.16.5-36.2.5-8.0.0-RC1036]
		at org.spongepowered.common.event.manager.SpongeEventManager.registerListeners(SpongeEventManager.java:310) ~[spongeforge:1.16.5-36.2.5-8.0.0-RC1036]
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.handler$zpa000$forge$registerModForSpongeListeners(FMLModContainer.java:1056) ~[forge:36.2]
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:97) ~[forge:36.2]
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?]
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736) ~[?:?]
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728) ~[?:?]
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[?:?]
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[?:?]
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[?:?]
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[?:?]
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?]
[14Jan.2022 18:07:14.475] [main/FATAL] [net.minecraft.server.Main/]: Failed to start the minecraft server
java.util.concurrent.CompletionException: java.lang.RuntimeException
	at java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:367) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:376) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1074) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:610) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1085) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?]
Caused by: java.lang.RuntimeException
	at net.minecraftforge.fml.ModList.completableFutureFromExceptionList(ModList.java:139) ~[forge:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072) ~[?:?]
	... 9 more
	Suppressed: java.lang.RuntimeException: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
		at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71) ~[forge-1.16.5-36.2.21.jar:36.2]
		at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-8.0.9.jar:?]
		at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-8.0.9.jar:?]
		at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.0.9.jar:?]
		at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.9.jar:?]
		at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?]
		at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
		at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?]
		at java.lang.Class.privateGetDeclaredMethods(Class.java:3166) ~[?:?]
		at java.lang.Class.getDeclaredMethods(Class.java:2309) ~[?:?]
		at org.spongepowered.common.event.manager.SpongeEventManager.registerListener(SpongeEventManager.java:280) ~[spongeforge:1.16.5-36.2.5-8.0.0-RC1036]
		at org.spongepowered.common.event.manager.SpongeEventManager.registerListeners(SpongeEventManager.java:310) ~[spongeforge:1.16.5-36.2.5-8.0.0-RC1036]
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.handler$zpa000$forge$registerModForSpongeListeners(FMLModContainer.java:1056) ~[forge:36.2]
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:97) ~[forge:36.2]
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?]
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736) ~[?:?]
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728) ~[?:?]
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[?:?]
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[?:?]
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[?:?]
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[?:?]
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?]
```

[debug.log](https://github.com/SpongePowered/Sponge/files/7873545/debug.log)

**Comment by gabizou** [comment]
Care to try this [special build](https://github.com/SpongePowered/Sponge/suites/5163966667/artifacts/156362790) built from [this PR](https://github.com/SpongePowered/Sponge/pull/3619)? I believe it'll solve this problem (and the 4 other tickets related to this one).

**Comment by kencinder** [comment]
Same result as https://github.com/SpongePowered/Sponge/issues/3532#issuecomment-1030759693

**Comment by gabizou** [comment]
Try with [this build](https://github.com/SpongePowered/Sponge/suites/5195843733/artifacts/158428511) built from the same PR.

**Comment by kencinder** [comment]
No errors on server startup or after player joining server, appears to have fixed it.
