### ISSUE TITLE
Client code on server crash

### ISSUE THREAD

**Issue by BronzeS8** [SpongePowered/Sponge#3597]
**I am currently running**

- SpongeForge version: 1.16.5-36.2.5-8.0.0-RC1039
- SpongeVanilla version: 
- Java version: 11
- Operating System: MacOS

- Plugins/Mods:

MarbleGate's Exotic Enchantment: Flowing Agony
flowingagony-1.16.5-1.0.4.jar

AIOT Botania
aiotbotania-1.16.5-1.8.4.jar

Alex's Mobs
alexsmobs-1.12.1.jar

Aquaculture 2
Aquaculture-1.16.5-2.1.21.jar

Architectury API (Forge)
architectury-1.28.48.jar

Ars Nouveau
ars_nouveau-1.16.5-1.24.14.jar

Astral Sorcery
astralsorcery-1.16-1.16.5-1.13.12.jar

AttributeFix
AttributeFix-1.16.5-10.1.3.jar

AutoRegLib
AutoRegLib-1.6-49.jar

Baubles - Reborn?
baubles-1.8.7.1-1.16.5.jar

Biomes O' Plenty
BiomesOPlenty-1.16.5-13.1.0.477-universal.jar

Blood Magic
BloodMagic-1.16.4-3.1.7-27.jar

Blue Skies
blue_skies-1.16.5-1.1.3.jar

Bookshelf
Bookshelf-Forge-1.16.5-10.4.31.jar

Botania
Botania-1.16.5-420.1.jar

Botany Pots
BotanyPots-1.16.5-7.0.17.jar

Botany Trees
BotanyTrees-1.16.5-3.0.5.jar

Chipped
chipped-1.16.5-1.2.1-forge.jar

Chunky Pregenerator (Forge)
Chunky-1.2.123.jar

Citadel
citadel-1.8.1-1.16.5.jar

Cosmetic Armor Reworked
CosmeticArmorReworked-1.16.5-v4a.jar

Create
create-mc1.16.5_v0.3.2g.jar

Create Crafts & Additions
createaddition-1.16.5-20211215b.jar

Curios API (Forge)
curios-forge-1.16.5-4.0.5.3.jar

Decorative Blocks
decorative_blocks-1.16.4-1.7.2.jar

Decorative Blocks modded compat
decorative_blocks_abnormals-1.2.jar

Druidcraft
Druidcraft-1.16.5-0.4.54.jar

Dungeon Crawl
DungeonCrawl-1.16.5-2.3.5.jar

Dungeons Enhanced
dungeons_enhanced-1.16.5-1.4.jar

Dungeons Mobs
dungeons_mobs-1.16.5-1.0.10.jar

Dungeons Plus
dungeons_plus-1.16.5-1.1.5.jar

Dynamic Surroundings
DynamicSurroundings-1.16.5-4.0.5.0.jar

Eidolon
eidolon-0.2.7.jar

Eidolon's Hexblades
hexblades-1.16.5-0.0.9.2.jar

Esencia
Esencia_public_beta_0.1.1.jar

Exotic Birds
exoticbirds-1.16.4-1.4.0.jar

Fairy Lights
fairylights-4.0.5-1.16.5.jar

Farmer's Delight
FarmersDelight-1.16.5-0.5.4.jar

Farmer's Delight Compats
farmersdelightintegrations-1.16.5-1.2.jar

Farmer's Delight Integration
farmersdelightintegration-1.16.5-1.0.3.jar

Flywheel
flywheel-1.16-0.2.5.jar

Frikinzi's Fauna
frikinzis-fauna-1.2.1-1.16.5.jar.jar

FTB Chunks (Forge)
ftb-chunks-forge-1605.3.2-build.115.jar

FTB Library (Forge)
ftb-library-forge-1605.3.4-build.90.jar

FTB Ranks (Forge)
ftb-ranks-forge-1605.1.5-build.16.jar

FTB Teams (Forge)
ftb-teams-forge-1605.2.3-build.40.jar

GeckoLib
geckolib-forge-1.16.5-3.0.59.jar

Goblin Traders
goblintraders-1.6.0-1.16.3.jar

Guide-API Village and Pillage
Guide-API-VP-1.16.5-2.2.2.jar

Hals Exploration Mod
H.E.M V0.4.1M.jar

Hexerei
hexerei-0.1.4.jar

Ice and Fire: Dragons
iceandfire-2.1.9-1.16.5.jar

JourneyMap
journeymap-1.16.5-5.7.3.jar

Just Enough Items (JEI)
jei-1.16.5-7.7.1.145.jar

Kobolds!
Kobolds-1.5.1.2.jar

LibX
LibX-1.16.3-1.0.76.jar

Ma Essentials
Ma-Essentials-1.16.5-3.5.0.jar

Magnesium
magnesium-1.5.jar

Mowzie's Mobs
mowziesmobs-1.5.19.jar

Mushroom Quest
MushroomQuest_1.16.5_v3.2.jar

MythicBotany
MythicBotany-1.16.5-1.4.19.jar

Nature's Aura
NaturesAura-34.3.jar

Nether's Exoticism
nether-s-exoticism-1.16.5-1.1.4.jar

NoCube's Sea Dwellers
NoCube's_Sea_Dwellers_1.0.2.jar

Obfuscate
obfuscate-0.6.2-1.16.3.jar

ObserverLib
observerlib-1.16.5-1.5.3.jar

Occultism
occultism-1.16.5-1.24.0.jar

Odd Water Mobs
OddWaterMobs[1.16.5]_1.5.0.jar

Patchouli
Patchouli-1.16.4-53.2.jar

Property Modifier
propertymodifier-1.16.5-0.6.3.jar

Quark
Quark-r2.4-321.jar

Sea And Prehistory
Sea and preshitory V6 1.16.5.jar

Selene Lib
selene-1.16.5-1.9.0.jar

Serene Seasons
SereneSeasons-1.16.5-4.0.1.123-universal.jar

Serene Shrubbery
SereneShrubbery-1.16.5-1.1.0.jar

Skin Swapper
skin-swapper-forge-2.0.1.jar

Sky Villages [Forge]
SkyVillage_1.0.0_1.16.5.jar

Sophisticated Backpacks
sophisticatedbackpacks-1.16.5-3.15.1.503.jar

Structure Gel API
structure_gel-1.16.5-1.7.8.jar

Supplementaries
supplementaries-1.16.5-0.18.0.jar

The Twilight Forest
twilightforest-1.16.5-4.0.870-universal.jar

Tome of Blood
tomeofblood-1.16.5-1.2.3.jar

Vampirism - Become a vampire!
Vampirism-1.16.5-1.8.6.jar

Vampirism Integrations
VampirismIntegrations-1.16.5-1.6.1.jar

Waystones
Waystones_1.16.5-7.6.4.jar

Whisperwoods
whisperwoods-1.16.5-2.0.2.jar

Xenoclus 2
Xenoclus2V2.0.jar

YUNG's API (Forge)
YungsApi-1.16.4-Forge-13.jar

YUNG's Better Caves (Forge)
BetterCaves-Forge-1.16.4-1.1.2.jar

YUNG's Better Mineshafts
BetterMineshafts-Forge-1.16.4-2.0.4.jar

**Issue Description** 

-Im not 100% sure on what this means, however speaking to Botania peeps they've said "this seems more like someone's using client classes without checking" and "client code that shouldnt be used on server". Server crashes on start up as a result.
See log below

[message.txt](https://github.com/SpongePowered/Sponge/files/7877726/message.txt)

**Comment by zml2008** [comment]
This seems to be unavoidable from our use of reflection here. I'm wondering if Forge is [throwing the wrong exception](https://github.com/MinecraftForge/MinecraftForge/blob/ed1f83047c1aedee3e9728add5808ef02518262f/src/fmllauncher/java/net/minecraftforge/fml/loading/RuntimeDistCleaner.java#L71), and should be throwing a `ClassNotFoundException` instead.

Alternately, we might have to add something to the transformer pipeline or interact with the FML scan data to be able to discover method overrides without triggering classloads.

**Comment by BronzeS8** [comment]
Whatever works mon friend, appreciate bugs like this are a pain in the ass and I legit know nothing about mods and java and all that

**Comment by gabizou** [comment]
Care to try this [special build](https://github.com/SpongePowered/Sponge/suites/5163966667/artifacts/156362790) built from [this PR](https://github.com/SpongePowered/Sponge/pull/3619)? I believe it'll solve this problem (and the 4 other tickets related to this one).

**Comment by BronzeS8** [comment]
Ill try it now, sorry for late response

**Comment by BronzeS8** [comment]
Looks to have fixed issue, though I now get this error
[Error.txt](https://github.com/SpongePowered/Sponge/files/8008917/Error.txt)
:

**Comment by gabizou** [comment]
Thanks, will update with a new build soon to re-test.

**Comment by BronzeS8** [comment]
👍 thank you!!!

**Comment by gabizou** [comment]
Try with [this build](https://github.com/SpongePowered/Sponge/suites/5195843733/artifacts/158428511) built from the same PR.

**Comment by BronzeS8** [comment]
Got me another crash I'm afraid:
[Error.txt](https://github.com/SpongePowered/Sponge/files/8010735/Error.txt)
 
 I wouldn't worry too much about it any more tbh, I've recently decided that I'll be updating to 1.18.1 in July time so if problem is a pain in the ass I don't want you to stress

**Comment by gabizou** [comment]
That appears to be a separate issue then. The client code crash itself is solved for this issue. 

The crash in question appears to be something as a `toString` instead of using ResourceKeys (like `minecraft:overworld`).
```
18:33:47] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
java.lang.IllegalStateException: No key was found for 'net.minecraft.world.DimensionType@235a8bf4'!
        at net.minecraft.util.registry.Registry.valueKey(Registry.java:590) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:computing_frames,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:mixins.sponge.api.json:minecraft.core.RegistryMixin_API,pl:mixin:APP:mixins.sponge.core.json:core.RegistryMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at org.spongepowered.common.world.server.SpongeWorldManager.loadLevel(SpongeWorldManager.java:922) ~[spongeforge:1.16.5-36.2.5-8.0.0-RC0] {re:mixin,re:classloading}
        at net.minecraft.server.dedicated.DedicatedServer.func_240800_l__(DedicatedServer.java:1656) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.sponge.accessors.json:server.dedicated.DedicatedServerAccessor,pl:mixin:APP:mixins.sponge.api.json:minecraft.server.dedicated.DedicatedServerMixin_API,pl:mixin:APP:mixins.sponge.core.json:server.dedicated.DedicatedServerMixin,pl:mixin:APP:mixins.sponge.tracker.json:server.dedicated.DedicatedServerMixin_Tracker,pl:mixin:A}
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:168) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.sponge.accessors.json:server.dedicated.DedicatedServerAccessor,pl:mixin:APP:mixins.sponge.api.json:minecraft.server.dedicated.DedicatedServerMixin_API,pl:mixin:APP:mixins.sponge.core.json:server.dedicated.DedicatedServerMixin,pl:mixin:APP:mixins.sponge.tracker.json:server.dedicated.DedicatedServerMixin_Tracker,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:621) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:mixins.sponge.accessors.json:server.MinecraftServerAccessor,pl:mixin:APP:mixins.spongeforge.api.json:minecraft.server.MinecraftServerMixin_Forge_API,pl:mixin:APP:mixins.spongeforge.core.json:server.MinecraftServerMixin_Forge,pl:mixin:APP:mixins.sponge.api.json:minecraft.server.MinecraftServerMixin_API,pl:mixin:APP:mixins.sponge.core.json:server.MinecraftServerMixin,pl:mixin:APP:mixins.sponge.tracker.json:server.MinecraftServerMixin_Tracker,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:mixins.sponge.accessors.json:server.MinecraftServerAccessor,pl:mixin:APP:mixins.spongeforge.api.json:minecraft.server.MinecraftServerMixin_Forge_API,pl:mixin:APP:mixins.spongeforge.core.json:server.MinecraftServerMixin_Forge,pl:mixin:APP:mixins.sponge.api.json:minecraft.server.MinecraftServerMixin_API,pl:mixin:APP:mixins.sponge.core.json:server.MinecraftServerMixin,pl:mixin:APP:mixins.sponge.tracker.json:server.MinecraftServerMixin_Tracker,pl:mixin:A,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:829) [?:?] {}
```
Once this issue is closed, I'll post the build number to re-try and we can open a new issue, but as you said, it's not likely you'll be using 1.16.5 anymore.

**Comment by gabizou** [comment]
SpongeForge 1.16.5-36.2.5-8.0.0-RC1064 and newer has the original issue fixed.

I don't know enough of these mods in the list to be able to debug the problem that you started experiencing.
