### ISSUE TITLE
Sporadic classloading issues

### ISSUE THREAD

**Issue by lucko** [SpongePowered/Sponge#3632]
### Affected Product(s)

SpongeForge, SpongeVanilla

### Version

1.18.1-9.0.0-RC1063

### Operating System

macos

### Java Version

Temurin-17+35

### Plugins/Mods

```shell
* luckperms
```

### Describe the bug

It seems that occasionally there are classloading issues running newer versions of Sponge (I've only started noticing this on API 8 builds, it never happened before)

I can reproduce locally, and others have reported similar problems to me.

e.g.
* https://github.com/LuckPerms/LuckPerms/issues/3308 (spongevanilla-1.16.5-8.0.0-RC1055-universal)
* https://github.com/LuckPerms/LuckPerms/issues/3312 (spongeforge-1.16.5-36.2.5-8.0.0-RC1073-universal)

example here of a LuckPerms class failing to load: https://gist.github.com/pietelite/86f5a0142fe24669f95cf084b89f8134

and of a SpongeAPI class: https://gist.github.com/Eric-liucn/2550f5fa24fde4ed1f32b8fe58cf88d1

The classloading behaviour of LuckPerms hasn't changed relative to the builds that ran on SpongeAPI 7, so I wonder if something has changed in Sponge? Perhaps a race condition with parallel classloading??

**Comment by Zidane** [comment]
Hum this is interesting.

With SpongeForge, I could see if due to mods loading asynchronously (maybe some oddities there?). With SpongeVanilla, I don't do this at all. I've also not seen this reported with other plugins either (not to say you are at fault, you are very likely not). Got to be some unusual unique combination here....

Catch me up to speed, does Luckperms download and classload any dependencies? If not download, does it at least cache them on the filesystem and then classload them?

**Comment by lucko** [comment]
> Catch me up to speed, does Luckperms download and classload any dependencies? If not download, does it at least cache them on the filesystem and then classload them?

It does - could definitely be contributing to the problem.

It uses this code to get a `URLClassLoader`:
https://github.com/LuckPerms/LuckPerms/blob/master/sponge/src/main/java/me/lucko/luckperms/sponge/SpongeClassPathAppender.java#L36-L58

then calls the addURL method to add jars to it at runtime. (by the way I would love to switch this to use an API method or something less hacky if one was ever made available)

I probably wouldn't have reported it & would have assumed it was my fault if it wasn't for the similar error with a Sponge API class.

**Comment by Zidane** [comment]
Even more mysterious....you're putting it on the TCL. Is this reproducible 100%?

It is like, one side is on the wrong classloader. I would not assume Sponge would be cause all hell would break loose already if so (I would imagine...)

**Comment by lucko** [comment]
Not exactly.. the reflection mess in that class obtains the URLClassLoader that the TCL delegates to. Is there a better place to put it?

The odd part is that when running LuckPerms on an API7 sponge build (I've only recently changed master to only target API 8) the problem never occurred - but the code used to add dependency jars hasn't changed.

It might be that Sponge now depends on a newer version of modlauncher, which has different behaviour? It's also weird that it happens sporadically.

**Comment by Zidane** [comment]
Ah yes, I do see you append right onto it's delegated "wrapped" classloader...

So Sponge uses this version in api-8: https://github.com/SpongePowered/Sponge/blob/api-8/gradle.properties#L20

This could be the case of modlauncher, despite the classes contained in the delegated classloader, somehow thinking they are already known to the TCL yet when the class is asked for, CNFE.... Not the easiest thing to debug due to modlauncher being somewhat complicated and complex in its design (as I'm sure you have already noticed).

Probably the easiest thing to do would be to give you some way to do this, sanely. As you're not the only one to benefit. A way to ask the Sponge bootstrap to supply your libraries onto the classpath before it even gets passed up to modlauncher. Just trying to think of a sane way to do this...

**Comment by lucko** [comment]
> Probably the easiest thing to do would be to give you some way to do this, sanely. As you're not the only one to benefit. A way to ask the Sponge bootstrap to supply your libraries onto the classpath before it even gets passed up to modlauncher.

That would be fantastic 😄

**Comment by Zidane** [comment]
@lucko 

How does a first run go? Do you have an installer that server owners run or does the plugin booting up pull down libraries or?

**Comment by lucko** [comment]
Dependencies are currently downloaded (if they aren't already cached) in the ConstructPluginEvent.

The full set of libraries isn't known until the LP configuration file is loaded + parsed. For example, it conditionally downloads the required storage drivers based on the current config instead of just loading everything.

I suppose this makes things challenging if Sponge needs to submit the URLs to modlauncher before plugin init and isn't able to append extras after..

**Comment by Zidane** [comment]
@lucko 

That will be a problem. Initial thought was to have you bundle library metadata and that gets downloaded and baked into the full classpath before hand off to ModLauncher but that would involve 0 plugin code being invoked.

Hmmm

**Comment by lucko** [comment]
So.. I have another way around this issue that I use in Bukkit land, basically the LuckPerms.jar that Sponge loads is a minimal bootstrap, that creates a URLClassLoader of its own and then adds the main plugin code, bundled as a jar-in-jar, and all of its dependencies at runtime.

It means that none of the classloading / reflection inject stuff is necessary.

I've implemented it on a branch here: https://github.com/LuckPerms/LuckPerms/compare/feature/sponge-jar-in-jar
As you can see, the code that does the injection into modlauncher is gone.

The plugin loads up fine on the latest API 8 build for 1.16.5, but throws this error:

```
java.lang.ClassNotFoundException: Lorg/spongepowered/api/util/Tristate;
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at org.spongepowered.common.event.manager.ListenerClassVisitor$DiscoveredMethod.classByLoader(ListenerClassVisitor.java:324)
	at org.spongepowered.common.event.manager.ListenerClassVisitor$ListenerAnnotationVisitor.visitEnum(ListenerClassVisitor.java:229)
	at org.objectweb.asm.ClassReader.readElementValue(ClassReader.java:3074)
	at org.objectweb.asm.ClassReader.readElementValues(ClassReader.java:2993)
	at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1413)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:744)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:424)
	at org.spongepowered.common.event.manager.ListenerClassVisitor.getEventListenerMethods(ListenerClassVisitor.java:77)
	at org.spongepowered.common.event.manager.SpongeEventManager.registerListener(SpongeEventManager.java:256)
	at org.spongepowered.common.event.manager.SpongeEventManager.registerListeners(SpongeEventManager.java:328)
	at org.spongepowered.common.event.manager.SpongeEventManager.registerListeners(SpongeEventManager.java:78)
	at me.lucko.luckperms.sponge.LPSpongeBootstrap.registerListeners(LPSpongeBootstrap.java:203)
	at me.lucko.luckperms.sponge.LPSpongePlugin.registerPlatformListeners(LPSpongePlugin.java:134)
	at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:154)
	at me.lucko.luckperms.sponge.LPSpongeBootstrap.onEnable(LPSpongeBootstrap.java:168)
	at me.lucko.luckperms.sponge.loader.SpongeLoaderPlugin.onEnable(SpongeLoaderPlugin.java:67)
	at org.spongepowered.common.event.listener.ConstructPluginEventListener_SpongeLoaderPlugin_onEnable1.handle(Unknown Source)
	at org.spongepowered.common.event.manager.RegisteredListener.handle(RegisteredListener.java:88)
	at org.spongepowered.common.event.manager.SpongeEventManager.post(SpongeEventManager.java:390)
	at org.spongepowered.common.event.manager.SpongeEventManager.postToPlugin(SpongeEventManager.java:426)
	at org.spongepowered.common.SpongeLifecycle.callConstructEvent(SpongeLifecycle.java:174)
	at org.spongepowered.vanilla.launch.VanillaBootstrap.perform(VanillaBootstrap.java:51)
	at org.spongepowered.vanilla.launch.DedicatedServerLaunch.performBootstrap(DedicatedServerLaunch.java:52)
	at org.spongepowered.vanilla.launch.VanillaLaunch.launchPlatform(VanillaLaunch.java:119)
	at org.spongepowered.vanilla.launch.DedicatedServerLaunch.launch(DedicatedServerLaunch.java:42)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.spongepowered.vanilla.applaunch.handler.prod.ServerProdLaunchHandler.launchService0(ServerProdLaunchHandler.java:45)
	at org.spongepowered.vanilla.applaunch.handler.AbstractVanillaLaunchHandler.lambda$launchService$2(AbstractVanillaLaunchHandler.java:197)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
	at org.spongepowered.vanilla.applaunch.Main.run(Main.java:95)
	at org.spongepowered.vanilla.applaunch.Main.main(Main.java:65)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.spongepowered.vanilla.installer.InstallerMain.invokeMain(InstallerMain.java:156)
	at org.spongepowered.vanilla.installer.InstallerMain.downloadAndRun(InstallerMain.java:139)
	at org.spongepowered.vanilla.installer.InstallerMain.run(InstallerMain.java:75)
	at org.spongepowered.vanilla.installer.InstallerMain.main(InstallerMain.java:70)
```

It's similar to the second reported error shown above, I initially grouped them together but I actually don't think they're the same. This one doesn't seem to be a race condition, rather a bug introduced by 5506503ca30eef0e9667766b2436b73a67e37376

I don't think it likes event handler methods annotated with `@IsCancelled(Tristate.UNDEFINED)` - if that can be fixed I think we're sorted?!

(it would still be awesome if you could provide API for adding to the classpath, but I appreciate it's a hard problem to solve and only serves a niche usecase!)

edit: yep, can confirm that commenting out the `@IsCancelled` annotation fixes the problem and the plugin loads fine 😄
