### ISSUE TITLE
Keep inventory. Errors after respawn.

### ISSUE THREAD

**Issue by SawFowl** [SpongePowered/Sponge#3653]
### Affected Product(s)

SpongeVanilla

### Version

SpongeVanilla: 1.16.5-8.0.0-RC1095

### Operating System

OS: Linux/5.16.15-arch1-1 (amd64)

### Java Version

JVM: 11.0.15/64-bit (Oracle Corporation)

### Plugins/Mods

```shell
LocaleAPI v2.1.0, LuckPerms v5.3.0, CraftEco v1.0, MyPlugin(See code below)
```

### Describe the bug

Save inventory code:
```java
	@Listener
	public void onDeath(DestructEntityEvent.Death event) {
		event.setKeepInventory(true);
	}
```
Error after respawn:
```clojure
[Server thread/WARN] [sponge]: Logged slot transactions without event! 1 net.minecraft.world.inventory.InventoryMenu
java.lang.Exception: 
        at org.spongepowered.common.event.tracking.context.transaction.inventory.ContainerBasedTransaction.generateEvent(ContainerBasedTransaction.java:167) ~[ContainerBasedTransaction.class:1.16.5-8.0.0-RC1095]
        at org.spongepowered.common.event.tracking.context.transaction.inventory.ContainerSlotTransaction.generateEvent(ContainerSlotTransaction.java:34) ~[ContainerSlotTransaction.class:1.16.5-8.0.0-RC1095]
        at org.spongepowered.common.event.tracking.context.transaction.TransactionalCaptureSupplier.generateEventForTransaction(TransactionalCaptureSupplier.java:298) ~[TransactionalCaptureSupplier.class:1.16.5-8.0.0-RC1095]
        at org.spongepowered.common.event.tracking.context.transaction.TransactionalCaptureSupplier.batchTransactions(TransactionalCaptureSupplier.java:235) ~[TransactionalCaptureSupplier.class:1.16.5-8.0.0-RC1095]
        at org.spongepowered.common.event.tracking.context.transaction.TransactionalCaptureSupplier.processTransactions(TransactionalCaptureSupplier.java:172) ~[TransactionalCaptureSupplier.class:1.16.5-8.0.0-RC1095]
        at org.spongepowered.common.event.tracking.TrackingUtil.processBlockCaptures(TrackingUtil.java:450) ~[TrackingUtil.class:1.16.5-8.0.0-RC1095]
        at org.spongepowered.common.event.tracking.phase.packet.PacketState.unwind(PacketState.java:69) ~[PacketState.class:1.16.5-8.0.0-RC1095]
        at org.spongepowered.common.event.tracking.phase.packet.PacketState.unwind(PacketState.java:48) ~[PacketState.class:1.16.5-8.0.0-RC1095]
        at org.spongepowered.common.event.tracking.PhaseTracker.completePhase(PhaseTracker.java:403) ~[PhaseTracker.class:1.16.5-8.0.0-RC1095]
        at org.spongepowered.common.event.tracking.PhaseContext.close(PhaseContext.java:325) ~[PhaseContext.class:1.16.5-8.0.0-RC1095]
        at org.spongepowered.common.event.tracking.phase.packet.PacketContext.close(PacketContext.java:139) ~[PacketContext.class:1.16.5-8.0.0-RC1095]
        at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:263) ~[PacketPhaseUtil.class:1.16.5-8.0.0-RC1095]
        at net.minecraft.network.protocol.PacketUtils.mde5f064$lambda$tracker$redirectProcessPacket$0$0(SourceFile:552) ~[?:?]
        at net.minecraft.server.TickTask.run(SourceFile:18) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(SourceFile:144) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(SourceFile:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.redirect$zca000$tracker$wrapAndPerformContextSwitch(SourceFile:4325) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(SourceFile:761) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(SourceFile:155) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(SourceFile:118) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(SourceFile:743) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTask(SourceFile:737) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(SourceFile:127) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(SourceFile:722) ~[?:?]
        at net.minecraft.server.MinecraftServer.runServer(SourceFile:674) ~[?:?]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(SourceFile:257) ~[?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]

[Server thread/WARN] [sponge]: SlotTransaction{slot=SlotAdapter[ordinal=36], original=SpongeItemStackSnapshot{itemType=minecraft:air, quantity=0}, default=SpongeItemStackSnapshot{itemType=minecraft:rotten_flesh, quantity=1}, custom=Optional.empty, valid=true}
```

**Comment by Faithcaio** [comment]
see https://github.com/SpongePowered/Sponge/issues/3680
