### ISSUE TITLE
Crash Following SpongeCauseStackFrame.addContext()

### ISSUE THREAD

**Issue by whimxiqal** [SpongePowered/Sponge#3666]
### Affected Product(s)

SpongeForge

### Version

1.16.5-36.2.5-8.0.0-RC1105

### Operating System

Linux

### Java Version

Unknown

### Plugins/Mods

```shell
LuckPerms-Sponge-5.4.18
Nope-Sponge-BETA-1.1.5
```

### Describe the bug

I was fighting a Ghast two separate times and this error crashed the server both times when the ghast fireballs exploded.

### [Link to logs](https://gist.github.com/pietelite/9e54b3d11442ca1550228d732bbaa1e4)

**Comment by Zidane** [comment]
This cannot be the error that crashed the server unless when you were fighting the Ghast, your server was in the process of already shutting down.

Will need a full complete server log.

**Comment by whimxiqal** [comment]
Sorry, [this should be more helpful](https://gist.github.com/pietelite/9e54b3d11442ca1550228d732bbaa1e4)

**Comment by Zidane** [comment]
Hmm no luck. There is one other way though...

Are you able to always reproduce this? Attacking Ghasts in the Nether? Moreso, with just SF itself?

**Comment by whimxiqal** [comment]
Yep, [I got it to happen again](https://gist.github.com/pietelite/2d6af2382362a734ce01fa973a2f1436) on a local server, using:

- OS: Windows 10
- java version "1.8.0_202"
- forge-1.16.5-36.2.20
- spongeforge-1.16.5-36.2.5-8.0.0-RC1105-universal

It didn't happen right away that time, I had to fight a few ghasts, but it eventually happened right when a fireball exploded on me.

**Comment by Zidane** [comment]
How did you make it to the nether? By command or portal?

**Comment by pietelite** [comment]
```
java.lang.NullPointerException: value
	at java.util.Objects.requireNonNull(Unknown Source) ~[?:1.8.0_202]
	at org.spongepowered.common.event.tracking.SpongeCauseStackFrame.addContext(SpongeCauseStackFrame.java:122) ~[spongeforge:1.16.5-36.2.5-8.0.0-RC1105]
	at org.spongepowered.common.event.tracking.phase.packet.player.AttackEntityPacketState.lambda$new$0(AttackEntityPacketState.java:55) ~[spongeforge:1.16.5-36.2.5-8.0.0-RC1105]
	at java.util.function.BiConsumer.lambda$andThen$0(Unknown Source) ~[?:1.8.0_202]
	at org.spongepowered.common.event.tracking.PhaseStateProxy.lambda$getFrameModifier$0(PhaseStateProxy.java:85) ~[spongeforge:1.16.5-36.2.5-8.0.0-RC1105]
	at org.spongepowered.common.event.tracking.PhaseTracker.checkProviders(PhaseTracker.java:765) ~[spongeforge:1.16.5-36.2.5-8.0.0-RC1105]
	at org.spongepowered.common.event.tracking.PhaseTracker.enforceMainThread(PhaseTracker.java:749) ~[spongeforge:1.16.5-36.2.5-8.0.0-RC1105]
	at org.spongepowered.common.event.tracking.PhaseTracker.pushCauseFrame(PhaseTracker.java:572) ~[spongeforge:1.16.5-36.2.5-8.0.0-RC1105]
	at net.minecraft.network.play.ServerPlayNetHandler.redirect$zgn000$impl$handlePlayerDisconnect(ServerPlayNetHandler.java:3501) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_147231_a(ServerPlayNetHandler.java:1019) ~[?:?]
	at net.minecraft.network.NetworkManager.func_179293_l(NetworkManager.java:366) ~[?:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:149) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:865) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?]
	at net.minecraft.server.MinecraftServer.redirect$zca000$tracker$wrapUpdateTimeLightAndEntities(MinecraftServer.java:4268) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_202]
```

**Comment by whimxiqal** [comment]
> How did you make it to the nether? By command or portal?

Portal

**Comment by whimxiqal** [comment]
Here's just the [Crash log](https://gist.github.com/pietelite/62654a9f8b3c00d027d8152f5d7d6e1f) `.log` file

**Comment by Zidane** [comment]
@pietelite 

Can you give me any more specifics? I am running the dead latest code for SpongeForge for 1.16.5 and I cannot reproduce this. I have killed several ghasts, been hit by explosions, etc in both creative and survival. No crashes.

**Comment by whimxiqal** [comment]
Try redirecting the fireballs, that's what I was doing

**Comment by Zidane** [comment]
I was doing exactly that :). Accidentally speaking, aiming with a touchpad is a *chore*.

Ahem, anyways, yes I did that too and no issue.

**Comment by whimxiqal** [comment]
I am running Optifine and a shaders... Do you think that's relevant?

**Comment by Zidane** [comment]
Nope, this is happening in server code.

**Comment by whimxiqal** [comment]
I tried it a few more times and it happens on the first or second explosion. Here's the stack trace again, from one of the more recent occasions:
```
[23:30:19] [Server thread/ERROR] [sponge/]:  Something happened when trying to unwind Packet{AttackEntity}
[23:30:19] [Server thread/ERROR] [sponge/]:  PhaseContext :
[23:30:19] [Server thread/ERROR] [sponge/]:      - Source: ServerPlayerEntity['PietElite'/313, l='ServerWorld[key=ResourceKey[minecraft:dimension / minecraft:the_nether],worldType=minecraft:the_nether]', x=31.66, y=80.00, z=-11.65]
[23:30:19] [Server thread/ERROR] [sponge/]:      - CapturedTransactions: TransactionalCaptureSupplier[tail=GameTransaction[], head=GameTransaction[], effect=null]
[23:30:19] [Server thread/ERROR] [sponge/]:      - PacketPlayer: ServerPlayerEntity['PietElite'/313, l='ServerWorld[key=ResourceKey[minecraft:dimension / minecraft:the_nether],worldType=minecraft:the_nether]', x=31.66, y=80.00, z=-11.65]
[23:30:19] [Server thread/ERROR] [sponge/]:      - Packet: net.minecraft.network.play.client.CUseEntityPacket@69efdf48
[23:30:19] [Server thread/ERROR] [sponge/]:      - ItemStackUsed: 1 AirItem[name=null]
[23:30:19] [Server thread/ERROR] [sponge/]:  Phases remaining :
[23:30:19] [Server thread/ERROR] [sponge/]:    - Phase: General{Unwinding}
[23:30:19] [Server thread/ERROR] [sponge/]:      Context:
[23:30:19] [Server thread/ERROR] [sponge/]:      - Source: ServerPlayerEntity['PietElite'/313, l='ServerWorld[key=ResourceKey[minecraft:dimension / minecraft:the_nether],worldType=minecraft:the_nether]', x=31.66, y=80.00, z=-11.65]
[23:30:19] [Server thread/ERROR] [sponge/]:      - UnwindingState: Packet{AttackEntity}
[23:30:19] [Server thread/ERROR] [sponge/]:      - UnwindingContext: BasicPacketContext{isCompleted=true}
[23:30:19] [Server thread/ERROR] [sponge/]:          - Source: ServerPlayerEntity['PietElite'/313, l='ServerWorld[key=ResourceKey[minecraft:dimension / minecraft:the_nether],worldType=minecraft:the_nether]', x=31.66, y=80.00, z=-11.65]
[23:30:19] [Server thread/ERROR] [sponge/]:          - CapturedTransactions: TransactionalCaptureSupplier[tail=GameTransaction[], head=GameTransaction[], effect=null]
[23:30:19] [Server thread/ERROR] [sponge/]:          - PacketPlayer: ServerPlayerEntity['PietElite'/313, l='ServerWorld[key=ResourceKey[minecraft:dimension / minecraft:the_nether],worldType=minecraft:the_nether]', x=31.66, y=80.00, z=-11.65]
[23:30:19] [Server thread/ERROR] [sponge/]:          - Packet: net.minecraft.network.play.client.CUseEntityPacket@69efdf48
[23:30:19] [Server thread/ERROR] [sponge/]:          - ItemStackUsed: 1 AirItem[name=null]
[23:30:19] [Server thread/ERROR] [sponge/]:    - Phase: Packet{AttackEntity}
[23:30:19] [Server thread/ERROR] [sponge/]:      Context:
[23:30:19] [Server thread/ERROR] [sponge/]:      - Source: ServerPlayerEntity['PietElite'/313, l='ServerWorld[key=ResourceKey[minecraft:dimension / minecraft:the_nether],worldType=minecraft:the_nether]', x=31.66, y=80.00, z=-11.65]
[23:30:19] [Server thread/ERROR] [sponge/]:      - CapturedTransactions: TransactionalCaptureSupplier[tail=GameTransaction[], head=GameTransaction[], effect=null]
[23:30:19] [Server thread/ERROR] [sponge/]:      - PacketPlayer: ServerPlayerEntity['PietElite'/313, l='ServerWorld[key=ResourceKey[minecraft:dimension / minecraft:the_nether],worldType=minecraft:the_nether]', x=31.66, y=80.00, z=-11.65]
[23:30:19] [Server thread/ERROR] [sponge/]:      - Packet: net.minecraft.network.play.client.CUseEntityPacket@69efdf48
[23:30:19] [Server thread/ERROR] [sponge/]:      - ItemStackUsed: 1 AirItem[name=null]
[23:30:19] [Server thread/ERROR] [sponge/]:    - Phase: Plugin{DelayedTask}
[23:30:19] [Server thread/ERROR] [sponge/]:      Context:
[23:30:19] [Server thread/ERROR] [sponge/]:      - Source: net.minecraft.util.concurrent.TickDelayedTask@1543c8c6
[23:30:19] [Server thread/ERROR] [sponge/]:  Stacktrace:
[23:30:19] [Server thread/ERROR] [sponge/]:      java.lang.NullPointerException: value
[23:30:19] [Server thread/ERROR] [sponge/]:      java.util.Objects.requireNonNull(Unknown Source)
[23:30:19] [Server thread/ERROR] [sponge/]:      org.spongepowered.common.event.tracking.SpongeCauseStackFrame.addContext(SpongeCauseStackFrame.java:122)
[23:30:19] [Server thread/ERROR] [sponge/]:      org.spongepowered.common.event.tracking.phase.packet.player.AttackEntityPacketState.lambda$new$0(AttackEntityPacketState.java:55)
[23:30:19] [Server thread/ERROR] [sponge/]:      java.util.function.BiConsumer.lambda$andThen$0(Unknown Source)
[23:30:19] [Server thread/ERROR] [sponge/]:      org.spongepowered.common.event.tracking.PhaseStateProxy.lambda$getFrameModifier$0(PhaseStateProxy.java:85)
[23:30:19] [Server thread/ERROR] [sponge/]:      org.spongepowered.common.event.tracking.PhaseTracker.checkProviders(PhaseTracker.java:765)
[23:30:19] [Server thread/ERROR] [sponge/]:      org.spongepowered.common.event.tracking.PhaseTracker.enforceMainThread(PhaseTracker.java:749)
[23:30:19] [Server thread/ERROR] [sponge/]:      org.spongepowered.common.event.tracking.PhaseTracker.pushCauseFrame(PhaseTracker.java:572)
[23:30:19] [Server thread/ERROR] [sponge/]:      org.spongepowered.common.event.tracking.context.transaction.TransactionalCaptureSupplier.lambda$generateEventForTransaction$2(TransactionalCaptureSupplier.java:292)
[23:30:19] [Server thread/ERROR] [sponge/]:      java.util.Optional.map(Unknown Source)
[23:30:19] [Server thread/ERROR] [sponge/]:      org.spongepowered.common.event.tracking.context.transaction.TransactionalCaptureSupplier.generateEventForTransaction(TransactionalCaptureSupplier.java:291)
[23:30:19] [Server thread/ERROR] [sponge/]:      org.spongepowered.common.event.tracking.context.transaction.TransactionalCaptureSupplier.batchTransactions(TransactionalCaptureSupplier.java:251)
[23:30:19] [Server thread/ERROR] [sponge/]:      org.spongepowered.common.event.tracking.context.transaction.TransactionalCaptureSupplier.processTransactions(TransactionalCaptureSupplier.java:172)
[23:30:19] [Server thread/ERROR] [sponge/]:      org.spongepowered.common.event.tracking.TrackingUtil.processBlockCaptures(TrackingUtil.java:450)
[23:30:19] [Server thread/ERROR] [sponge/]:      org.spongepowered.common.event.tracking.phase.packet.player.AttackEntityPacketState.unwind(AttackEntityPacketState.java:103)
[23:30:19] [Server thread/ERROR] [sponge/]:      org.spongepowered.common.event.tracking.phase.packet.player.AttackEntityPacketState.unwind(AttackEntityPacketState.java:50)
[23:30:19] [Server thread/ERROR] [sponge/]:      org.spongepowered.common.event.tracking.PhaseTracker.completePhase(PhaseTracker.java:403)
[23:30:19] [Server thread/ERROR] [sponge/]:      org.spongepowered.common.event.tracking.PhaseContext.close(PhaseContext.java:325)
[23:30:19] [Server thread/ERROR] [sponge/]:      org.spongepowered.common.event.tracking.phase.packet.PacketContext.close(PacketContext.java:139)
[23:30:19] [Server thread/ERROR] [sponge/]:      org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:263)
[23:30:19] [Server thread/ERROR] [sponge/]:      net.minecraft.network.PacketThreadUtil.mdcca467$lambda$tracker$redirectProcessPacket$0$0(SourceFile:552)
[23:30:19] [Server thread/ERROR] [sponge/]:      net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18)
[23:30:19] [Server thread/ERROR] [sponge/]:      net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144)
[23:30:19] [Server thread/ERROR] [sponge/]:      net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
[23:30:19] [Server thread/ERROR] [sponge/]:      net.minecraft.server.MinecraftServer.redirect$zca000$tracker$wrapAndPerformContextSwitch(MinecraftServer.java:4315)
[23:30:19] [Server thread/ERROR] [sponge/]:      net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:734)
[23:30:19] [Server thread/ERROR] [sponge/]:      net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:159)
[23:30:19] [Server thread/ERROR] [sponge/]:      net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118)
[23:30:19] [Server thread/ERROR] [sponge/]:      net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:717)
[23:30:19] [Server thread/ERROR] [sponge/]:      net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:711)
[23:30:19] [Server thread/ERROR] [sponge/]:      net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127)
[23:30:19] [Server thread/ERROR] [sponge/]:      net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:697)
[23:30:19] [Server thread/ERROR] [sponge/]:      net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:646)
[23:30:19] [Server thread/ERROR] [sponge/]:      net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232)
[23:30:19] [Server thread/ERROR] [sponge/]:      java.lang.Thread.run(Unknown Source)
[23:30:19] [Server thread/ERROR] [sponge/]:
[23:30:19] [Server thread/ERROR] [sponge/]:  Minecraft : 1.16.5
[23:30:19] [Server thread/ERROR] [sponge/]:  SpongeAPI : 8.0.0
[23:30:19] [Server thread/ERROR] [sponge/]:  Sponge : 8.0.0
[23:30:19] [Server thread/ERROR] [sponge/]:  SpongeForge : 1.16.5-36.2.5-8.0.0-RC1105
```

**Comment by whimxiqal** [comment]
Video: https://streamable.com/2jsyzo

**Comment by whimxiqal** [comment]
Update: My server has crashed multiple more times on this same place (5 times total in the past 4 days) just doing normal stuff. One of them was right after I was fighting drowners in the ocean, I think it happened as I was hitting my boat (the source of the AttackEntityPacket?) Of course, some of them were during fighting the Ghast.

**Comment by Faithcaio** [comment]
https://github.com/SpongePowered/Sponge/blob/api-8/src/main/java/org/spongepowered/common/event/tracking/phase/packet/player/AttackEntityPacketState.java#L55
expects to have a USED_HAND via PacketContext
https://github.com/SpongePowered/Sponge/blob/api-8/src/main/java/org/spongepowered/common/event/tracking/phase/packet/PacketContext.java#L101
which would have been set by
https://github.com/SpongePowered/Sponge/blob/api-8/src/main/java/org/spongepowered/common/event/tracking/phase/packet/player/AttackEntityPacketState.java#L82

maybe the context changed or got reset? @gabizou

**Comment by avaruus1** [comment]
I found a way to reproduce the crash with a 100% success rate:

1. Summon fireball right next to some blocks.
2. Hit the fireball into those blocks using an autoclicker (or just by clicking rapidly), so that it explodes immediately.


(No plugins installed)
```
Minecraft: 1.16.5
SpongeAPI: 8.1.0-SNAPSHOT
Sponge: 1.16.5-8.1.0-SNAPSHOT
SpongeVanilla: 1.16.5-8.0.0-RC1111
JVM: 18.0.1/64-bit (Oracle Corporation)
OS: Linux/5.15.32-xanmod1-tt-1 (amd64)
```

Also, I think this is related to #3669.

**Comment by dualspiral** [comment]
The two are the same issue as far as I can tell.

> maybe the context changed or got reset?

It never got set. If the `ServerboundInteractPacket` has an invalid entityId (say zero, or the ID of an entity that has since been removed from the server), then `isPacketIgnored` returns `true` and the context just isn't populated.

The modifier already accounts for this for the entity itself, so we'll just account for the hand not being available too.
