### ISSUE TITLE
Startup crash

### ISSUE THREAD

**Issue by avescarelo** [SpongePowered/Sponge#3695]
### Affected Product(s)

SpongeForge

### Version

spongeforge-1.16.5-36.2.5-8.1.0-RC1137-universal.jar

### Operating System

Linux

### Java Version

11.0.15

### Plugins/Mods

```shell
Mod List: 
		BetterDungeons-1.16.4-1.2.1.jar                   |YUNG's Better Dungeons        |betterdungeons                |1.16.4-1.2.1        |DONE      |Manifest: NOSIGNATURE
		Guide-API-VP-1.16.5-2.2.2.jar                     |Guide-API VP                  |guideapi-vp                   |2.2.2               |DONE      |Manifest: NOSIGNATURE
		BetterCaves-Forge-1.16.4-1.1.2.jar                |YUNG's Better Caves           |bettercaves                   |1.16.4-1.1.2        |DONE      |Manifest: NOSIGNATURE
		citadel-1.8.1-1.16.5.jar                          |Citadel                       |citadel                       |1.8.1               |DONE      |Manifest: NOSIGNATURE
		alexsmobs-1.12.1.jar                              |Alex's Mobs                   |alexsmobs                     |1.12.1              |DONE      |Manifest: NOSIGNATURE
		YungsApi-1.16.4-Forge-13.jar                      |YUNG's API                    |yungsapi                      |1.16.4-Forge-13     |DONE      |Manifest: NOSIGNATURE
		LibX-1.16.3-1.0.76.jar                            |LibX                          |libx                          |1.16.3-1.0.76       |DONE      |Manifest: NOSIGNATURE
		null                                              |SpongeAPI                     |spongeapi                     |8.0.0               |DONE      |Manifest: NOSIGNATURE
		vending-2.1-1.16.4.jar                            |Vending Machines              |vending                       |2.1-1.16.4          |DONE      |Manifest: NOSIGNATURE
		EventHelper-1.16.5-3.0.0.jar                      |EventHelper                   |eventhelper                   |1.16.5-3.0.0        |DONE      |Manifest: NOSIGNATURE
		mahoutsukai-1.16.5-v1.34.15.jar                   |Mahou Tsukai                  |mahoutsukai                   |1.16.5-v1.34.15     |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.35-universal.jar                |Forge                         |forge                         |36.2.35             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		TravelersTitles-1.16.4-1.5.jar                    |Traveler's Titles             |travelerstitles               |1.16.4-1.5          |DONE      |Manifest: NOSIGNATURE
		twilightforest-1.16.5-4.0.870-universal.jar       |The Twilight Forest           |twilightforest                |NONE                |DONE      |Manifest: NOSIGNATURE
		betterendforge-1.16.5-1.6.3.jar                   |BetterEnd Forge               |betterendforge                |1.16.5-1.6.3        |DONE      |Manifest: NOSIGNATURE
		antiqueatlas-6.0.1-forge-mc1.16.5.jar             |Antique Atlas                 |antiqueatlas                  |6.0.1-forge-mc1.16.5|DONE      |Manifest: NOSIGNATURE
		MythicBotany-1.16.5-1.4.19.jar                    |MythicBotany                  |mythicbotany                  |1.16.5-1.4.19       |DONE      |Manifest: NOSIGNATURE
		DungeonsArise-1.16.5-2.1.49-beta.jar              |When Dungeons Arise           |dungeons_arise                |2.1.49              |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.35-server.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		FarmersDelight-1.16.5-0.6.0.jar                   |Farmer's Delight              |farmersdelight                |1.16.5-0.6.0        |DONE      |Manifest: NOSIGNATURE
		null                                              |Sponge                        |sponge                        |8.0.0               |DONE      |Manifest: NOSIGNATURE
		Alex's+Delight+1.1.3+-+Forge+1.16.5.jar           |Alex's Delight                |amfd                          |1.1.3               |DONE      |Manifest: NOSIGNATURE
		Botania-1.16.5-420.2.jar                          |Botania                       |botania                       |1.16.5-420.2        |DONE      |Manifest: NOSIGNATURE
		spongeforge-1.16.5-36.2.5-8.1.0-RC1137-universal.j|SpongeForge                   |spongeforge                   |1.16.5-36.2.5-8.1.0-|DONE      |Manifest: NOSIGNATURE
		touhoulittlemaid-1.16.5-1.0.2.jar                 |Touhou Little Maid            |touhou_little_maid            |NONE                |DONE      |Manifest: NOSIGNATURE
		curios-forge-1.16.5-4.0.5.3.jar                   |Curios API                    |curios                        |1.16.5-4.0.5.3      |DONE      |Manifest: NOSIGNATURE
		Patchouli-1.16.4-53.2.jar                         |Patchouli                     |patchouli                     |1.16.4-53.2         |DONE      |Manifest: NOSIGNATURE
		diet-forge-1.16.5-1.0.4.0.jar                     |Diet                          |diet                          |1.16.5-1.0.4.0      |DONE      |Manifest: NOSIGNATURE
		arsomega-1.4.0.jar                                |Ars Omega                     |arsomega                      |1.16.5-1.3          |DONE      |Manifest: NOSIGNATURE
		AutoRegLib-1.6-49.jar                             |AutoRegLib                    |autoreglib                    |1.6-49              |DONE      |Manifest: NOSIGNATURE
		Quark-r2.4-322.jar                                |Quark                         |quark                         |r2.4-322            |DONE      |Manifest: NOSIGNATURE
		StorageDrawers-1.16.3-8.5.2.jar                   |Storage Drawers               |storagedrawers                |8.5.2               |DONE      |Manifest: NOSIGNATURE
		YungsExtras-Forge-1.16.4-1.0.jar                  |YUNG's Extras                 |yungsextras                   |Forge-1.16.4-1.0    |DONE      |Manifest: NOSIGNATURE
		BetterStrongholds-1.16.4-1.2.1.jar                |YUNG's Better Strongholds     |betterstrongholds             |1.16.4-1.2.1        |DONE      |Manifest: NOSIGNATURE
		Vampirism-1.16.5-1.8.8.jar                        |Vampirism                     |vampirism                     |1.8.8               |DONE      |Manifest: NOSIGNATURE
		VampirismIntegrations-1.16.5-1.6.1.jar            |Vampirism Integrations        |vampirism_integrations        |1.6.1               |DONE      |Manifest: NOSIGNATURE
		VampiresNeedUmbrellas-1.16.5-1.1.5.jar            |Vampires Need Umbrellas       |vampiresneedumbrellas         |1.1.5               |DONE      |Manifest: NOSIGNATURE
		Werewolves-1.16.5-1.8-0.6.3.jar                   |Werewolves                    |werewolves                    |0.6.3               |DONE      |Manifest: NOSIGNATURE
		ExtraBotany-r1.2-68.jar                           |ExtraBotany                   |extrabotany                   |1.0                 |DONE      |Manifest: NOSIGNATURE
		occultism-1.16.5-1.28.0.jar                       |Occultism                     |occultism                     |1.16.5-1.28.0       |DONE      |Manifest: NOSIGNATURE
		cloth-config-4.14.64-forge.jar                    |Cloth Config v4 API           |cloth-config                  |4.14.64             |DONE      |Manifest: NOSIGNATURE
		The_Undergarden-1.16.5-0.5.5.jar                  |The Undergarden               |undergarden                   |0.5.5               |DONE      |Manifest: NOSIGNATURE
		CosmeticArmorReworked-1.16.5-v5.jar               |CosmeticArmorReworked         |cosmeticarmorreworked         |1.16.5-v5           |DONE      |Manifest: 5e:ed:25:99:e4:44:14:c0:dd:89:c1:a9:4c:10:b5:0d:e4:b1:52:50:45:82:13:d8:d0:32:89:67:56:57:01:53
		BetterMineshafts-Forge-1.16.4-2.0.4.jar           |YUNG's Better Mineshafts      |bettermineshafts              |1.16.4-2.0.4        |DONE      |Manifest: NOSIGNATURE
		geckolib-forge-1.16.5-3.0.71.jar                  |GeckoLib                      |geckolib3                     |3.0.71              |DONE      |Manifest: NOSIGNATURE
		Feywild-1.16.5-2.1.2.jar                          |Feywild                       |feywild                       |1.16.5-2.1.2        |DONE      |Manifest: NOSIGNATURE
		ars_nouveau-1.16.5-1.25.1.jar                     |Ars Nouveau                   |ars_nouveau                   |1.25.1              |DONE      |Manifest: NOSIGNATURE
		ars_elemental-1.16.5-0.1.6.3.jar                  |Ars Elemental - Elemental Spel|ars_elemental                 |1.16.5-0.1.6.3      |DONE      |Manifest: NOSIGNATURE
		toomanyglyphs-snapshot-20220223.jar               |Too Many Glyphs               |toomanyglyphs                 |0.1.0               |DONE      |Manifest: NOSIGNATURE
		thebaneoftrees-1.1.jar                            |The bane of trees             |thebaneoftrees                |1.1                 |DONE      |Manifest: NOSIGNATURE
```

### Describe the bug

I started the server and got a crash

### Link to logs

https://gist.github.com/avescarelo/83e843b28fcfb20bbef0efe04508fe09

**Comment by avescarelo** [comment]
I used forge-1.16.5-36.2.5, and get this error at startup:

`avescarelo@asus:~/modding/server-1.16.5$ java -jar forge-1.16.5-36.2.5.jar 
[21:19:45] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--gameDir, ., --launchTarget, fmlserver, --fml.forgeVersion, 36.2.5, --fml.mcpVersion, 20210115.111550, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge]
[21:19:45] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 8.0.9+86+master.3cf110c starting: java version 11.0.15 by Private Build
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by cpw.mods.modlauncher.SecureJarHandler (file:/home/avescarelo/modding/server-1.16.5/libraries/cpw/mods/modlauncher/8.0.9/modlauncher-8.0.9.jar) to field java.util.jar.Manifest.jv
WARNING: Please consider reporting this to the maintainers of cpw.mods.modlauncher.SecureJarHandler
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[21:19:45] [main/INFO] [ne.mi.fm.lo.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[21:19:45] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/home/avescarelo/modding/server-1.16.5/libraries/org/spongepowered/mixin/0.8.4/mixin-0.8.4.jar Service=ModLauncher Env=SERVER
[21:19:46] [main/INFO] [or.sp.fo.ap.lo.mo.li.LibraryManager/]: Scanning and verifying libraries in './sponge-libraries'. Please wait, this may take a moment...
[21:19:47] [main/INFO] [STDERR/]: [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release
[21:19:47] [main/INFO] [STDERR/]: [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release
[21:19:47] [main/INFO] [STDERR/]: [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release
[21:19:48] [main/INFO] [cp.mo.mo.LaunchServiceHandler/MODLAUNCHER]: Launching target 'fmlserver' with arguments [--gameDir, .]
Exception in thread "main" [21:19:48] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]: java.lang.NoSuchMethodError: 'void sun.security.util.ManifestEntryVerifier.<init>(java.util.jar.Manifest)'
[21:19:48] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]: 	at cpw.mods.modlauncher.SecureJarHandler.createCodeSource(SecureJarHandler.java:66)
[21:19:48] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]: 	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:275)
[21:19:48] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
[21:19:48] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[21:19:48] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
[21:19:48] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]: 	at java.base/java.lang.Class.forName0(Native Method)
[21:19:48] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]: 	at java.base/java.lang.Class.forName(Class.java:398)
[21:19:48] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]: 	at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51)
[21:19:48] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[21:19:48] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[21:19:48] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[21:19:48] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[21:19:48] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[21:19:48] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]: 	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63)
[21:19:48] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]: 	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60)
[21:19:48] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]: 	at net.minecraftforge.server.ServerMain.main(ServerMain.java:57)
avescarelo@asus:~/modding/server-1.16.5$ 

`

**Comment by avescarelo** [comment]
I used forge-1.16.5-36.2.5, and get this error at startup:

[https://gist.github.com/avescarelo/9f23daea94da27bd8cfebdaadbab60d7](https://gist.github.com/avescarelo/9f23daea94da27bd8cfebdaadbab60d7)

**Comment by dualspiral** [comment]
`java version 11.0.15 by Private Build`

Where exactly did you get the Java build from? It's possible that the version you have doesn't include the methods ModLauncher uses to... well, launch. Try using vanilla OpenJDK or something like Temurin.

Otherwise, I think this is probably more somewhere towards Forge, but see where you get to first.

**Comment by avescarelo** [comment]
It's defaullt java

I get from here:
sudo apt-get install openjdk-11-jre

**Comment by dualspiral** [comment]
Oh, I see - update Forge to at least 36.2.26

**Comment by avescarelo** [comment]
I got new crash at stratup:
[https://gist.github.com/avescarelo/1d7a4532cd09f9970d5b95666c1e0c08](https://gist.github.com/avescarelo/1d7a4532cd09f9970d5b95666c1e0c08)

**Comment by Zidane** [comment]
Incompatibility with the diet mod and Sponge (their injection is failing here).

Not a Sponge issue but we're willing to make a change if you consult with the mod developers and they provide what their mixin that is failing is doing. Until such a time occurs, closing this issue. We'll reopen if we get a reply back to that effect.

**Comment by avescarelo** [comment]
I removed Diet mod, and updated spongeforge to latest

[https://gist.github.com/avescarelo/77190164a5a1912ee532580dcaaac3a3](https://gist.github.com/avescarelo/77190164a5a1912ee532580dcaaac3a3)

P.s. I try now to remove other mods

**Comment by avescarelo** [comment]
Also i removed Abnormals core

log: [https://gist.github.com/avescarelo/46a70c324c2152cc085b86533e3c6884](https://gist.github.com/avescarelo/46a70c324c2152cc085b86533e3c6884)

And server working now
