### ISSUE TITLE
Stuck on 'Loading Minecraft Server' on new 1.18.2 experimental builds

### ISSUE THREAD

**Issue by pop4959** [SpongePowered/Sponge#3696]
### Affected Product(s)

SpongeVanilla

### Version

1.18.2-9.0.0-RC1135

### Operating System

Linux, Windows

### Java Version

openjdk version "17.0.3" 2022-04-19, openjdk version "17.0.1" 2021-10-19

### Plugins/Mods

```shell
N/A
```

### Describe the bug

SpongeVanilla loads until it reaches this point, after which it seems to get stuck and must be shut down manually:
```
[16:09:54] [main/INFO] [launch]: Loading Minecraft Server, please wait...
[16:10:05] [Server thread/INFO] [sponge]: Registered service [BanService] to plugin 'sponge'.
[16:10:05] [Server thread/INFO] [sponge]: Registered service [ContextService] to plugin 'sponge'.
[16:10:05] [Server thread/INFO] [sponge]: Registered service [PermissionService] to plugin 'sponge'.
[16:10:05] [Server thread/INFO] [sponge]: Registered service [WhitelistService] to plugin 'sponge'.
```

The EULA has been accepted, but no other configuration has been changed, and no additional plugins/mods are installed.

Worth noting that the latest build of 1.18.1 (1.18.1-9.0.0-RC1119) works just fine as of writing.

### Link to logs

https://paste.gg/p/anonymous/2259982ed6ba488eb3d0ad33656ed882

**Comment by dualspiral** [comment]
I am seeing this on my Linux (WSL) system, gonna see if I can see where it's freezing.

**Comment by dualspiral** [comment]
```
"Server thread" #92 prio=8 os_prio=0 cpu=3204.22ms elapsed=13.51s tid=0x00007fefc5364a90 nid=0x52a runnable  [0x00007fef892eb000]
   java.lang.Thread.State: TIMED_WAITING (parking)
        at jdk.internal.misc.Unsafe.park(java.base@17.0.2/Native Method)
        - parking to wait for  <0x0000000727a00148> (a java.lang.String)
        at java.util.concurrent.locks.LockSupport.parkNanos(java.base@17.0.2/LockSupport.java:252)
        at net.minecraft.util.thread.BlockableEventLoop.waitForTasks(BlockableEventLoop.java:152)
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:142)
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:769)
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:701)
        at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:273)
        at net.minecraft.server.MinecraftServer$$Lambda$6961/0x0000000801c5b7b8.run(Unknown Source)
        at java.lang.Thread.run(java.base@17.0.2/Thread.java:833)
```

Just the start of my investigation, but it seems to be deadlocked on something - see if we can find it.

**Comment by dualspiral** [comment]
Okay, it's just a logging issue. You can actually use the server as normal, you just don't see what's going on - I'll look into it.
