### ISSUE TITLE
Minecraft 1.18.1 server error

### ISSUE THREAD

**Issue by Jaiseii** [SpongePowered/Sponge#3794]
### Is this request specific to one implementation of Sponge?

Yes, only SpongeForge

### Sponge Version

spongeforge-1.16.5-36.2.5-8.1.0-RC1235-universal

### What are you requesting?

I have a minecraft forge 1.18.1 server for about 1 year, I haven't played for 3 months (in that time I kept it saved on a flash drive) and now when I try to open it I get these errors:

C:\Users\olive\Desktop\Server 2>REM Forge requires a configured set of both JVM and program arguments.

C:\Users\olive\Desktop\Server 2>REM Add custom JVM arguments to the user_jvm_args.txt

C:\Users\olive\Desktop\Server 2>REM Add custom program arguments {such as nogui} to this file in the next line before the  or

C:\Users\olive\Desktop\Server 2>REM  pass them to this script directly

C:\Users\olive\Desktop\Server 2>java @user_jvm_args.txt @libraries/net/minecraftforge/forge/1.18.1-39.1.0/win_args.txt
[23:22:45] [main/INFO]: ModLauncher running: args [--launchTarget, forgeserver, --fml.forgeVersion, 39.1.0, --fml.mcVersion, 1.18.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20211210.034407]
[23:22:45] [main/INFO]: ModLauncher 9.1.0+9.1.0+main.6690ee51 starting: java version 19.0.1 by Oracle Corporation
[23:22:45] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/olive/Desktop/Server%202/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2319!/ Service=ModLauncher Env=SERVER
[23:22:45] [main/INFO]: Found mod file alexsmobs-1.18.4.jar of type MOD with locator {mods folder locator at C:\Users\olive\Desktop\Server 2\mods}
[23:22:45] [main/INFO]: Found mod file allthemodium-1.7.0rc6-1.18.1-39.0.10.jar of type MOD with locator {mods folder locator at C:\Users\olive\Desktop\Server 2\mods}
[23:22:45] [main/INFO]: Found mod file AmbientSounds_v5.0.9_mc1.18.1.jar of type MOD with locator {mods folder locator at C:\Users\olive\Desktop\Server 2\mods}
[23:22:45] [main/INFO]: Found mod file architectury-3.9.66.jar of type MOD with locator {mods folder locator at C:\Users\olive\Desktop\Server 2\mods}
[23:22:45] [main/INFO]: Found mod file artifacts-1.18.1-4.0.3.jar of type MOD with locator {mods folder locator at C:\Users\olive\Desktop\Server 2\mods}
[23:22:45] [main/INFO]: Found mod file awesomedungeonocean-forge-1.18.1-3.0.1.jar of type MOD with locator {mods folder locator at C:\Users\olive\Desktop\Server 2\mods}
[23:22:45] [main/INFO]: Found mod file balm-2.4.3+0.jar of type MOD with locator {mods folder locator at C:\Users\olive\Desktop\Server 2\mods}
[23:22:45] [main/INFO]: Found mod file BiomesOPlenty-1.18.1-15.0.0.105-universal.jar of type MOD with locator {mods folder locator at C:\Users\olive\Desktop\Server 2\mods}
[23:22:45] [main/INFO]: Found mod file blue_skies-1.18.1-1.3.4.jar of type MOD with locator {mods folder locator at C:\Users\olive\Desktop\Server 2\mods}
[23:22:45] [main/INFO]: Found mod file blueprint-1.18.1-5.1.1.jar of type MOD with locator {mods folder locator at C:\Users\olive\Desktop\Server 2\mods}
[23:22:45] [main/INFO]: Found mod file caelus-forge-1.18.1-3.0.0.2.jar of type MOD with locator {mods folder locator at C:\Users\olive\Desktop\Server 2\mods}
[23:22:45] [main/INFO]: Found mod file camera-1.18.1-1.0.2.jar of type MOD with locator {mods folder locator at C:\Users\olive\Desktop\Server 2\mods}
[23:22:45] [main/INFO]: Found mod file carryon-1.18.1-1.17.0.7.jar of type MOD with locator {mods folder locator at C:\Users\olive\Desktop\Server 2\mods}
[23:22:45] [main/INFO]: Found mod file citadel-1.10.10-1.18.jar of type MOD with locator {mods folder locator at C:\Users\olive\Desktop\Server 2\mods}
[23:22:45] [main/INFO]: Found mod file cookingforblockheads-forge-1.18.1-11.1.0.jar of type MOD with locator {mods folder locator at C:\Users\olive\Desktop\Server 2\mods}
[23:22:45] [main/INFO]: Found mod file corpse-1.18.1-1.0.5.jar of type MOD with locator {mods folder locator at C:\Users\olive\Desktop\Server 2\mods}
[23:22:45] [main/INFO]: Found mod file CreativeCore_v2.5.0_mc1.18.1.jar of type MOD with locator {mods folder locator at C:\Users\olive\Desktop\Server 2\mods}
[23:22:45] [main/INFO]: Found mod file curios-forge-1.18.1-5.0.6.2.jar of type MOD with locator {mods folder locator at C:\Users\olive\Desktop\Server 2\mods}
[23:22:45] [main/INFO]: Found mod file DungeonCrawl-1.18.1-2.3.7.jar of type MOD with locator {mods folder locator at C:\Users\olive\Desktop\Server 2\mods}
[23:22:45] [main/INFO]: Found mod file DungeonsArise-1.18.1-2.1.49d-beta.jar of type MOD with locator {mods folder locator at C:\Users\olive\Desktop\Server 2\mods}
[23:22:45] [main/INFO]: Found mod file exlinefurniture-forge-1.18.2-v2.05.jar of type MOD with locator {mods folder locator at C:\Users\olive\Desktop\Server 2\mods}
[23:22:45] [main/INFO]: Found mod file expandability-5.0.0-forge.jar of type MOD with locator {mods folder locator at C:\Users\olive\Desktop\Server 2\mods}
[23:22:45] [main/INFO]: Found mod file FarmersDelight-1.18.1-1.0.4.jar of type MOD with locator {mods folder locator at C:\Users\olive\Desktop\Server 2\mods}
[23:22:45] [main/INFO]: Found mod file ForgeEndertech-1.18.1-8.0.1.0-build.0059.jar of type MOD with locator {mods folder locator at C:\Users\olive\Desktop\Server 2\mods}
[23:22:45] [main/INFO]: Found mod file furniture-7.0.0-pre28-1.18.1.jar of type MOD with locator {mods folder locator at C:\Users\olive\Desktop\Server 2\mods}
[23:22:45] [main/INFO]: Found mod file GemCrabs+Gobber+v.1.0.2.jar of type MOD with locator {mods folder locator at C:\Users\olive\Desktop\Server 2\mods}
[23:22:45] [main/INFO]: Found mod file Gobber2-Forge-1.18.1-2.6.20.jar of type MOD with locator {mods folder locator at C:\Users\olive\Desktop\Server 2\mods}
[23:22:45] [main/INFO]: Found mod file Gobber_Delight_1.0.3_Forge_1.18.2.jar of type MOD with locator {mods folder locator at C:\Users\olive\Desktop\Server 2\mods}
[23:22:45] [main/INFO]: Found mod file goblintraders-1.7.0-1.18.1.jar of type MOD with locator {mods folder locator at C:\Users\olive\Desktop\Server 2\mods}
[23:22:45] [main/INFO]: Found mod file ironchest-1.18.2-13.2.11.jar of type MOD with locator {mods folder locator at C:\Users\olive\Desktop\Server 2\mods}
[23:22:45] [main/INFO]: Found mod file ironfurnaces-1.18.1-3.1.4.jar of type MOD with locator {mods folder locator at C:\Users\olive\Desktop\Server 2\mods}
[23:22:45] [main/INFO]: Found mod file jei-1.18.1-9.4.1.276.jar of type MOD with locator {mods folder locator at C:\Users\olive\Desktop\Server 2\mods}
[23:22:45] [main/INFO]: Found mod file JustEnoughResources-1.18.1-0.14.0.157.jar of type MOD with locator {mods folder locator at C:\Users\olive\Desktop\Server 2\mods}
[23:22:45] [main/INFO]: Found mod file libraryferret-forge-1.18.1-3.0.0.jar of type MOD with locator {mods folder locator at C:\Users\olive\Desktop\Server 2\mods}
[23:22:45] [main/INFO]: Found mod file mcw-bridges-2.0.5-mc1.18.1forge.jar of type MOD with locator {mods folder locator at C:\Users\olive\Desktop\Server 2\mods}
[23:22:45] [main/INFO]: Found mod file mcw-doors-1.0.7-mc1.18.1.jar of type MOD with locator {mods folder locator at C:\Users\olive\Desktop\Server 2\mods}
[23:22:45] [main/INFO]: Found mod file mcw-fences-1.0.6-mc1.18.1.jar of type MOD with locator {mods folder locator at C:\Users\olive\Desktop\Server 2\mods}
[23:22:45] [main/INFO]: Found mod file mcw-lights-1.0.4-mc1.18.1.jar of type MOD with locator {mods folder locator at C:\Users\olive\Desktop\Server 2\mods}
[23:22:45] [main/INFO]: Found mod file mcw-trapdoors-1.0.7-mc1.18.1.jar of type MOD with locator {mods folder locator at C:\Users\olive\Desktop\Server 2\mods}
[23:22:45] [main/INFO]: Found mod file mcw-windows-2.0.3-mc1.18.1.jar of type MOD with locator {mods folder locator at C:\Users\olive\Desktop\Server 2\mods}
[23:22:45] [main/INFO]: Found mod file minecraft-comes-alive-7.2.1+1.18.1-forge.jar of type MOD with locator {mods folder locator at C:\Users\olive\Desktop\Server 2\mods}
[23:22:45] [main/INFO]: Found mod file Oh+The+Biomes+You'll+Go-forge-1.18.1-1.3.5.13.jar of type MOD with locator {mods folder locator at C:\Users\olive\Desktop\Server 2\mods}
[23:22:45] [main/INFO]: Found mod file PlayerRevive_v2.0.0-pre08_mc1.18.1.jar of type MOD with locator {mods folder locator at C:\Users\olive\Desktop\Server 2\mods}
[23:22:45] [main/INFO]: Found mod file structure_gel-1.18.1-2.1.3.jar of type MOD with locator {mods folder locator at C:\Users\olive\Desktop\Server 2\mods}
[23:22:45] [main/INFO]: Found mod file supplementaries-1.18.2-1.5.13.jar of type MOD with locator {mods folder locator at C:\Users\olive\Desktop\Server 2\mods}
[23:22:45] [main/INFO]: Found mod file TerraBlender-forge-1.18.1-1.1.0.77.jar of type MOD with locator {mods folder locator at C:\Users\olive\Desktop\Server 2\mods}
[23:22:45] [main/INFO]: Found mod file the_bumblezone_forge-4.3.6+1.18.1.jar of type MOD with locator {mods folder locator at C:\Users\olive\Desktop\Server 2\mods}
[23:22:45] [main/INFO]: Found mod file trashslot-forge-1.18.1-11.0.2.jar of type MOD with locator {mods folder locator at C:\Users\olive\Desktop\Server 2\mods}
[23:22:45] [main/INFO]: Found mod file TravelersBackpack-1.18.1-7.0.4.jar of type MOD with locator {mods folder locator at C:\Users\olive\Desktop\Server 2\mods}
[23:22:45] [main/INFO]: Found mod file waystones-forge-1.18.1-9.0.4.jar of type MOD with locator {mods folder locator at C:\Users\olive\Desktop\Server 2\mods}
[23:22:45] [main/INFO]: Found mod file fmlcore-1.18.1-39.1.0.jar of type LIBRARY with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@2756c0a7
[23:22:45] [main/INFO]: Found mod file javafmllanguage-1.18.1-39.1.0.jar of type LANGPROVIDER with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@2756c0a7
[23:22:45] [main/INFO]: Found mod file mclanguage-1.18.1-39.1.0.jar of type LANGPROVIDER with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@2756c0a7
[23:22:45] [main/INFO]: Found mod file server-1.18.1-20211210.034407-srg.jar of type MOD with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@2756c0a7
[23:22:45] [main/INFO]: Found mod file forge-1.18.1-39.1.0-universal.jar of type MOD with locator net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator@2756c0a7
[23:22:46] [main/ERROR]: Missing language javafml version [40,) wanted by GemCrabs+Gobber+v.1.0.2.jar, found 39
[23:22:46] [main/ERROR]: Missing language javafml version [40,) wanted by Gobber_Delight_1.0.3_Forge_1.18.2.jar, found 39
[23:22:46] [main/ERROR]: Missing language javafml version [40.0,) wanted by ironchest-1.18.2-13.2.11.jar, found 39
[23:22:46] [main/ERROR]: Missing mandatory dependencies: forge, feature_nbt_deadlock_be_gone, selene
[23:22:47] [main/INFO]: Compatibility level set to JAVA_17
[23:22:47] [main/INFO]: Successfully loaded Mixin Connector [de.maxhenkel.camera.MixinConnector]
[23:22:47] [main/INFO]: Launching target 'forgeserver' with arguments []
[23:22:48] [main/WARN]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Unsupported class file major version 63)
[23:22:48] [main/WARN]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Unsupported class file major version 63)
[23:22:48] [main/WARN]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Unsupported class file major version 63)
[23:22:48] [main/WARN]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Unsupported class file major version 63)
[23:22:48] [main/WARN]: Error loading class: java/util/Map$Entry (java.lang.IllegalArgumentException: Unsupported class file major version 63)
[23:22:48] [main/WARN]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Unsupported class file major version 63)
[23:22:48] [main/WARN]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Unsupported class file major version 63)
[23:22:48] [main/WARN]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Unsupported class file major version 63)
[23:22:48] [main/WARN]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Unsupported class file major version 63)
[23:22:48] [main/WARN]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Unsupported class file major version 63)
[23:22:48] [main/WARN]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Unsupported class file major version 63)
[23:22:48] [main/WARN]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Unsupported class file major version 63)
[23:22:48] [main/WARN]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Unsupported class file major version 63)
[23:22:48] [main/WARN]: Error loading class: java/util/Map$Entry (java.lang.IllegalArgumentException: Unsupported class file major version 63)
[23:22:48] [main/WARN]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Unsupported class file major version 63)
[23:22:48] [main/WARN]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Unsupported class file major version 63)
[23:22:48] [main/WARN]: Error loading class: java/util/Map$Entry (java.lang.IllegalArgumentException: Unsupported class file major version 63)
[23:22:48] [main/WARN]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Unsupported class file major version 63)
[23:22:48] [main/WARN]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Unsupported class file major version 63)
[23:22:48] [main/WARN]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Unsupported class file major version 63)
[23:22:48] [main/WARN]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Unsupported class file major version 63)
[23:22:48] [main/WARN]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Unsupported class file major version 63)
[23:22:48] [main/WARN]: Error loading class: java/util/Map$Entry (java.lang.IllegalArgumentException: Unsupported class file major version 63)
[23:22:48] [main/WARN]: Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.IllegalArgumentException: Unsupported class file major version 63)
[23:22:48] [main/WARN]: Error loading class: java/util/function/Consumer (java.lang.IllegalArgumentException: Unsupported class file major version 63)
[23:22:48] [main/FATAL]: Mixin apply failed terrablender_forge.mixins.json:MixinMain -> net.minecraft.server.Main: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException Unexpecteded ClassMetadataNotFoundException whilst transforming the mixin class: [MAIN Applicator Phase -> terrablender_forge.mixins.json:MixinMain -> Apply Methods -> (Lcom/mojang/serialization/DataResult;ZLjava/util/function/Consumer;)Ljava/lang/Object;:redirect$zio000$onGetOrThrow -> Transform LVT -> var=onError -> desc=Ljava/util/function/Consumer;]
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Unexpecteded ClassMetadataNotFoundException whilst transforming the mixin class: [MAIN Applicator Phase -> terrablender_forge.mixins.json:MixinMain -> Apply Methods -> (Lcom/mojang/serialization/DataResult;ZLjava/util/function/Consumer;)Ljava/lang/Object;:redirect$zio000$onGetOrThrow -> Transform LVT -> var=onError -> desc=Ljava/util/function/Consumer;]
        at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformMethod(MixinTargetContext.java:491) ~[mixin-0.8.5.jar%2319!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyNormalMethod(MixinApplicatorStandard.java:532) ~[mixin-0.8.5.jar%2319!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMethods(MixinApplicatorStandard.java:518) ~[mixin-0.8.5.jar%2319!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:386) ~[mixin-0.8.5.jar%2319!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[mixin-0.8.5.jar%2319!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383) ~[mixin-0.8.5.jar%2319!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365) ~[mixin-0.8.5.jar%2319!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[mixin-0.8.5.jar%2319!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.5.jar%2319!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
        at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.5.jar%2319!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
        at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.5.jar%2319!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
        at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-9.1.0.jar%235!/:9.1.0+9.1.0+main.6690ee51]
        at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-9.1.0.jar%235!/:?]
        at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-9.1.0.jar%235!/:?]
        at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-9.1.0.jar%235!/:?]
        at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110) ~[securejarhandler-1.0.1.jar:?]
        at cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:213) ~[securejarhandler-1.0.1.jar:?]
        at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:223) ~[securejarhandler-1.0.1.jar:?]
        at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:213) ~[securejarhandler-1.0.1.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:633) ~[?:?]
        at java.lang.Class.forName(Class.java:584) ~[?:?]
        at java.lang.Class.forName(Class.java:559) ~[?:?]
        at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:46) ~[fmlloader-1.18.1-39.1.0.jar%2323!/:?]
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.0.jar%235!/:?]
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.0.jar%235!/:?]
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.0.jar%235!/:?]
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.0.jar%235!/:?]
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.0.jar%235!/:?]
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.0.jar%235!/:?]
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.0.jar%235!/:?]
        at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?]
Caused by: org.spongepowered.asm.mixin.throwables.ClassMetadataNotFoundException: java.util.function.Consumer
        at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformSingleDescriptor(MixinTargetContext.java:983) ~[mixin-0.8.5.jar%2319!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
        at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformSingleDescriptor(MixinTargetContext.java:943) ~[mixin-0.8.5.jar%2319!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
        at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformLVT(MixinTargetContext.java:544) ~[mixin-0.8.5.jar%2319!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
        at org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformMethod(MixinTargetContext.java:450) ~[mixin-0.8.5.jar%2319!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
        ... 30 more
Exception in thread "main" org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.0/cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.0/cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.0/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.0/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50)
        at cpw.mods.securejarhandler@1.0.1/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110)
        at cpw.mods.securejarhandler@1.0.1/cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:213)
        at cpw.mods.securejarhandler@1.0.1/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:223)
        at cpw.mods.securejarhandler@1.0.1/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:213)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:633)
        at java.base/java.lang.Class.forName(Class.java:584)
        at java.base/java.lang.Class.forName(Class.java:559)
        at MC-BOOTSTRAP/fmlloader@1.18.1-39.1.0/net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:46)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.0/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.0/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.0/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.0/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.0/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.0/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.0/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
        at cpw.mods.bootstraplauncher@1.0.0/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149)
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [terrablender_forge.mixins.json:MixinMain] from phase [DEFAULT] in config [terrablender_forge.mixins.json] FAILED during APPLY
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:636)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:588)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
        ... 23 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Unexpecteded ClassMetadataNotFoundException whilst transforming the mixin class: [MAIN Applicator Phase -> terrablender_forge.mixins.json:MixinMain -> Apply Methods -> (Lcom/mojang/serialization/DataResult;ZLjava/util/function/Consumer;)Ljava/lang/Object;:redirect$zio000$onGetOrThrow -> Transform LVT -> var=onError -> desc=Ljava/util/function/Consumer;]
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformMethod(MixinTargetContext.java:491)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyNormalMethod(MixinApplicatorStandard.java:532)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMethods(MixinApplicatorStandard.java:518)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:386)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
        ... 23 more
Caused by: org.spongepowered.asm.mixin.throwables.ClassMetadataNotFoundException: java.util.function.Consumer
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformSingleDescriptor(MixinTargetContext.java:983)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformSingleDescriptor(MixinTargetContext.java:943)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformLVT(MixinTargetContext.java:544)
        at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinTargetContext.transformMethod(MixinTargetContext.java:450)
        ... 30 more

C:\Users\olive\Desktop\Server 2>pause

**Comment by zml2008** [comment]
either 1) you're lying and you're not actually using spongeforge, in which case you're asking in the wrong place
or 2) you are using spongeforge and it's not working because it has not been updated past 1.16.5 yet
