### ISSUE TITLE
Command suggestions are unable to retrieve child node arguments

### ISSUE THREAD

**Issue by aromaa** [SpongePowered/Sponge#3814]
### Affected Product(s)

SpongeVanilla

### Version

1.16.5-8.1.0-RC1264

### Operating System

Windows 10

### Java Version

17

### Describe the bug

After typing out `/scoreboard players enable @p ` you should see the following error after every character:
```
java.lang.IllegalArgumentException: No such argument 'targets' exists on this command
	at com.mojang.brigadier.context.CommandContext.getArgument(CommandContext.java:85) ~[?:?]
	at net.minecraft.commands.arguments.ScoreHolderArgument.getNames(ScoreHolderArgument.java:59) ~[?:?]
	at net.minecraft.commands.arguments.ScoreHolderArgument.getNamesWithDefaultWildcard(ScoreHolderArgument.java:55) ~[?:?]
	at net.minecraft.server.commands.ScoreboardCommand.lambda$register$17(ScoreboardCommand.java:256) ~[?:?]
	at com.mojang.brigadier.tree.ArgumentCommandNode.listSuggestions(ArgumentCommandNode.java:71) ~[?:?]
	at org.spongepowered.common.command.brigadier.dispatcher.SpongeCommandDispatcher.getCompletionSuggestions(SpongeCommandDispatcher.java:481) ~[?:?]
	at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:579) ~[?:?]
	at org.spongepowered.common.command.brigadier.dispatcher.DelegatingCommandDispatcher.getCompletionSuggestions(DelegatingCommandDispatcher.java:100) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCustomCommandSuggestions(ServerGamePacketListenerImpl.java:483) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundCommandSuggestionPacket.handle(ServerboundCommandSuggestionPacket.java:35) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundCommandSuggestionPacket.handle(ServerboundCommandSuggestionPacket.java:14) ~[?:?]
	at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:262) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.md5b302e$lambda$tracker$redirectProcessPacket$0$0(PacketUtils.java:552) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:134) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.redirect$zca000$tracker$wrapAndPerformContextSwitch(MinecraftServer.java:4295) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:737) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:227) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:108) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:720) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:714) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:118) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:701) ~[?:?]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:654) ~[?:?]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:228) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by lolplay123** [comment]
I believe this bug occurs in all versions from 1.16.5-8.1.0-RC1264 to 1.20.4-11.0.0-RC1507. This bug destroys various scoreboards and trigger commands, making it impossible to play custom maps and similar content.
