### ISSUE TITLE
`ResourcePackList does not define or inherit an implementation of the resolved method 'abstract org.spongepowered.api.resource.pack.Pack pack(org.spongepowered.plugin.PluginContainer)' of interface org.spongepowered.api.resource.pack.PackRepository`

### ISSUE THREAD

**Issue by SettingDust** [SpongePowered/Sponge#3880]
### Is this request specific to one implementation of Sponge?

Yes, only SpongeForge

### Sponge Version

sf RC1352

### What are you requesting?

`java.lang.AbstractMethodError: Receiver class net.minecraft.resources.ResourcePackList does not define or inherit an implementation of the resolved method 'abstract org.spongepowered.api.resource.pack.Pack pack(org.spongepowered.plugin.PluginContainer)' of interface org.spongepowered.api.resource.pack.PackRepository.`

```
[078月2023 12:58:02.312] [Server thread/ERROR] [sponge/]: Could not pass StartingEngineEvent$Impl to epicbanitem
java.lang.AbstractMethodError: Receiver class net.minecraft.resources.ResourcePackList does not define or inherit an implementation of the resolved method 'abstract org.spongepowered.api.resource.pack.Pack pack(org.spongepowered.plugin.PluginContainer)' of interface org.spongepowered.api.resource.pack.PackRepository.
	at team.ebi.epicbanitem.EBITranslation.loadMessages(EBITranslation.java:109) ~[epicbanitem:?]
	at team.ebi.epicbanitem.EBITranslation.lambda$new$0(EBITranslation.java:57) ~[epicbanitem:?]
	at org.spongepowered.common.event.manager.RegisteredListener.handle(RegisteredListener.java:88) ~[spongeforge:1.16.5-36.2.5-8.1.0-RC1352]
	at org.spongepowered.common.event.manager.SpongeEventManager.post(SpongeEventManager.java:390) ~[spongeforge:1.16.5-36.2.5-8.1.0-RC1352]
	at org.spongepowered.common.event.manager.SpongeEventManager.post(SpongeEventManager.java:417) ~[spongeforge:1.16.5-36.2.5-8.1.0-RC1352]
	at org.spongepowered.forge.launch.event.ForgeEventManager.post(ForgeEventManager.java:150) ~[spongeforge:1.16.5-36.2.5-8.1.0-RC1352]
	at org.spongepowered.common.SpongeLifecycle.callStartingEngineEvent(SpongeLifecycle.java:194) ~[spongeforge:1.16.5-36.2.5-8.1.0-RC1352]
	at org.spongepowered.forge.SpongeForge.onServerAboutToStart(SpongeForge.java:114) ~[spongeforge:1.16.5-36.2.5-8.1.0-RC1352]
	at net.minecraftforge.eventbus.ASMEventHandler_2_SpongeForge_onServerAboutToStart_FMLServerAboutToStartEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?]
	at org.spongepowered.forge.launch.event.SpongeEventBus.post(SpongeEventBus.java:120) ~[spongeforge:1.16.5-36.2.5-8.1.0-RC1352]
	at org.spongepowered.forge.launch.event.ForgeEventManager.post(ForgeEventManager.java:129) ~[spongeforge:1.16.5-36.2.5-8.1.0-RC1352]
	at org.spongepowered.forge.launch.event.ForgeEventManager.post(ForgeEventManager.java:113) ~[spongeforge:1.16.5-36.2.5-8.1.0-RC1352]
	at net.minecraftforge.fml.server.ServerLifecycleHooks.handleServerAboutToStart(ServerLifecycleHooks.java:81) ~[forge:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:166) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:621) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by ImMorpheus** [comment]
Hey! You seem to be running an unsupported version (API 8) of SpongeAPI. Support for API 8 ended in October 2023.

API-8 is now end-of-life. We will not be issuing any more API updates for version 8 of our API[^1]

As part of our legacy cleanup we are closing issues relating to API8/1.16
___

If you wish to move this forward, please try to reproduce the issue on a supported version of Sponge.

[^1]: https://forums.spongepowered.org/t/sponge-status-update-17th-october-2023/42212#spongeapi-82-1
