### ISSUE TITLE
Broken ViaVersion Plugin and Datapacks

### ISSUE THREAD

**Issue by myxxmikeyxx** [SpongePowered/Sponge#3882]
### Affected Product(s)

SpongeVanilla

### Version

spongevanilla-1.20.1-11.0.0-RC1356-universal

### Operating System

Windows

### Java Version

openjdk version "17.0.5" 2022-10-18

### Plugins/Mods

```shell
Plugins:
ViaVersion
This is a plugin that is allows newer game versions to join older servers and vise versa
(ViaBackwards & ViaRewind also rely on ViaVersion and may not work but won't load without ViaVersion)
Almost all other plugins are saying ".... does not contain any plugin metadata so it is not a plugin. Skipping..."

Datapacks:
I have 40 data packs that do a variety of things. 27 of them don't work. They worked on PaperMC and spigot and craftbukkit but not on sponge. 
Zip with datapacks here (https://drive.google.com/file/d/1ugXYBjNz4IqOTAird1ErZANBHRn6LNnB/view?usp=sharing)
```

### Describe the bug

I run this on my server so when an update comes out people can still join, just might be missing new items / features.
In the debug.log it says` [Plugin Name]... does not contain any plugin metadata so it is not a plugin. Skipping...`

I also use a lot of datapacks to help the game with small tweaks to make it more fun for my younger cousins and friends. Many of them are not working only 13 are of the 40 I use. Zip [here](https://drive.google.com/file/d/1ugXYBjNz4IqOTAird1ErZANBHRn6LNnB/view?usp=sharing).

Thank you for the time. I would love to stick with sponge since you still have the tnt dupe, many of the farms I build use this for auto destroy and collection. Craftbukkit fixed it earlier on and now it is fixed in spigot and all the way to papermc. Papermc's previous config file to renable it no longer works because it was patched in craftbukkit when "fixing other bugs" and won't undo it for craftbukkit since they focus on Spigot.

Error:
```
[10:42:45] [Server thread/ERROR] [viaversion]: ViaVersion failed to get the server protocol!
java.lang.NoSuchMethodException: org.spongepowered.common.SpongeMinecraftVersion.getProtocol()
>       at java.base/java.lang.Class.getDeclaredMethod(Class.java:2675)
        at com.viaversion.viaversion.sponge.platform.SpongeViaInjector.getServerProtocolVersion(SpongeViaInjector.java:35)
        at com.viaversion.viaversion.ViaManagerImpl.loadServerProtocol(ViaManagerImpl.java:183)
        at com.viaversion.viaversion.ViaManagerImpl.onServerLoaded(ViaManagerImpl.java:121)
        at com.viaversion.viaversion.SpongePlugin.onServerStarted(SpongePlugin.java:114)
        at org.spongepowered.common.event.manager.RegisteredListener.handle(RegisteredListener.java:88)
        at org.spongepowered.common.event.manager.SpongeEventManager.post(SpongeEventManager.java:400)
        at org.spongepowered.common.event.manager.SpongeEventManager.post(SpongeEventManager.java:430)
        at org.spongepowered.common.SpongeLifecycle.callStartedEngineEvent(SpongeLifecycle.java:224)
        at net.minecraft.server.dedicated.DedicatedServer.handler$zpe000$vanilla$callStartedEngineAndLoadedGame(DedicatedServer.java:1185)
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:201)
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:646)
        at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:265)
        at java.base/java.lang.Thread.run(Thread.java:833)
[10:42:45] [Sponge-AsyncScheduler-1/INFO] [viaversion]: Finished mapping loading, shutting down loader executor!
```

### Link to logs

https://paste.gg/p/anonymous/942eb42cbaad41c8963db9a522ffe87e

**Comment by avaruus1** [comment]
1. Issues with plugins should be reported to the authors of those plugins.
2. This issue is fixed in the latest dev build of ViaVersion: https://ci.viaversion.com/

**Comment by myxxmikeyxx** [comment]
@avaruus1 
Okay thank you.
What about the datapacks?

**Comment by AlexandreArcil** [comment]
It should be fixed in the latest version (1365), I've tested some of them with success.
