### ISSUE TITLE
The commands related to the scoreboard are broken!!!

### ISSUE THREAD

**Issue by lolplay123** [SpongePowered/Sponge#3968]
### Affected Product(s)

SpongeVanilla

### Version

1.19.4-10.0.0-RC1504

### Operating System

WIndows11

### Java Version

17.0.10

### Plugins/Mods

```shell
No plugins are installed.
```

### Describe the bug

First, when trying to enter a score name after `/scoreboard enable @p`, the following error appears:
```
[Server thread/ERROR]: Error executing task on Server
java.lang.IllegalArgumentException: No such argument 'targets' exists on this command
        at com.mojang.brigadier.context.CommandContext.getArgument(CommandContext.java:85) ~[?:?]
        at net.minecraft.commands.arguments.ScoreHolderArgument.getNames(ScoreHolderArgument.java:61) ~[?:?]
        at net.minecraft.commands.arguments.ScoreHolderArgument.getNamesWithDefaultWildcard(ScoreHolderArgument.java:57) ~[?:?]
        at net.minecraft.server.commands.ScoreboardCommand.lambda$register$17(ScoreboardCommand.java:197) ~[?:?]
        at com.mojang.brigadier.tree.ArgumentCommandNode.listSuggestions(ArgumentCommandNode.java:71) ~[?:?]
        at org.spongepowered.common.command.brigadier.dispatcher.SpongeCommandDispatcher.getCompletionSuggestions(SpongeCommandDispatcher.java:582) ~[SpongeCommandDispatcher.class:1.19.4-10.0.0-RC1504]
        at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:580)
 ~[?:?]
        at org.spongepowered.common.command.brigadier.dispatcher.DelegatingCommandDispatcher.getCompletionSuggestions(DelegatingCommandDispatcher.java:100) ~[DelegatingCommandDispatcher.class:1.19.4-10.0.0-RC1504]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCustomCommandSuggestions(ServerGamePacketListenerImpl.java:533) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundCommandSuggestionPacket.handle(ServerboundCommandSuggestionPacket.java:29) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundCommandSuggestionPacket.handle(ServerboundCommandSuggestionPacket.java:7) ~[?:?]
        at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:269) ~[PacketPhaseUtil.class:1.19.4-10.0.0-RC1504]
        at net.minecraft.network.protocol.PacketUtils.md2bfdff$lambda$tracker$redirectProcessPacket$0$0(PacketUtils.java:552) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:156) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.redirect$zcp000$tracker$wrapAndPerformContextSwitch(MinecraftServer.java:4473) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:786) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:165) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:130) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:768) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:762) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:115) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:746) ~[?:?]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:679) ~[?:?]
        at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:266) ~[?:?]
        at java.lang.Thread.run(Thread.java:842) ~[?:?]
```

And when forcefully executed as follows, since no error message appears, it may seem to be working properly at first glance.
![screenshot 2024-03-11 180715](https://github.com/SpongePowered/Sponge/assets/122137944/3f549396-65d3-453c-8042-dc5e90ff42fc)

However, in reality, the object name: TEST2 does not appear in the arguments, nor has it been activated.
![screenshot 2024-03-11 181126](https://github.com/SpongePowered/Sponge/assets/122137944/ccc9eec8-2661-4038-9c6d-3b29433acb1a)
![screnshot 2024-03-11 181221](https://github.com/SpongePowered/Sponge/assets/122137944/2519af95-ef2e-46b4-979f-82b0a06f2dce)

This bug is very severe and makes it impossible to use datapacks and scoreboards for custom maps, among others. Please, I would like it to be fixed.

**Comment by aromaa** [comment]
There is no need to make another issue, this is tracked on #3814 which you already commented on too.
